### ISSUE TITLE
cmd/cue: cue export panics on empty input

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#1016]
_Originally opened by @rogpeppe in https://github.com/cuelang/cue/issues/1016_

commit aa61ee7f7c7c65900f63e9506ed42317757b627c

Running this command: 
```
cue export json: - < /dev/null
```

gives me this panic:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x70171d]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc0004efe90)
	/home/rogpeppe/other/cue/cmd/cue/cmd/root.go:221 +0x7b
panic({0xaebe80, 0x1115ff0})
	/home/rogpeppe/go/src/runtime/panic.go:1038 +0x215
cuelang.org/go/cue.(*Instance).Value(0x0)
	/home/rogpeppe/other/cue/cue/instance.go:211 +0x1d
cuelang.org/go/cmd/cue/cmd.(*instanceIterator).value(0xc000318040)
	/home/rogpeppe/other/cue/cmd/cue/cmd/common.go:216 +0x37
cuelang.org/go/cmd/cue/cmd.runExport(0xc0003267e0, {0xc000326aa0, 0x2, 0x2})
	/home/rogpeppe/other/cue/cmd/cue/cmd/export.go:116 +0x1fa
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc00033e2c0, {0xc000326aa0, 0x2, 0x2})
	/home/rogpeppe/other/cue/cmd/cue/cmd/root.go:46 +0x4d
github.com/spf13/cobra.(*Command).execute(0xc00033e2c0, {0xc000326a80, 0x2, 0x2})
	/home/rogpeppe/src/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc00015b340)
	/home/rogpeppe/src/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	/home/rogpeppe/src/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc0003267e0, {0xc00003e124, 0x3})
	/home/rogpeppe/other/cue/cmd/cue/cmd/root.go:206 +0x6b
cuelang.org/go/cmd/cue/cmd.mainErr({0xc9dc90, 0xc00003a190}, {0xc0000320d0, 0xc000068738, 0x46031b})
	/home/rogpeppe/other/cue/cmd/cue/cmd/root.go:145 +0x55
cuelang.org/go/cmd/cue/cmd.Main()
	/home/rogpeppe/other/cue/cmd/cue/cmd/root.go:127 +0x85
main.main()
	/home/rogpeppe/other/cue/cmd/cue/main.go:24 +0x19

goroutine 18 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1139600)
	/home/rogpeppe/src/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x6a
created by github.com/golang/glog.init.0
	/home/rogpeppe/src/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x1c5

```

**Comment by mvdan** [comment]
This was resolved in https://github.com/cue-lang/cue/issues/2714 - we had too many duplicates of these :)
