### ISSUE TITLE
panic in `cue get go github.com/argoproj/argo-cd/v2/...`

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#1053]
_Originally opened by @yujunz in https://github.com/cuelang/cue/issues/1053_

### What version of CUE are you using (`cue version`)?

<pre>
❯ cue version
cue version 0.4.0 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
git clone https://github.com/argoproj/argo-cd.git
cd argo-cd
cue mod init github.com/argoproj/argo-cd
cue get go github.com/argoproj/argo-cd/v2/...
```

### What did you expect to see?

Cue files generated from go.

### What did you see instead?

```
❯ cue get go github.com/argoproj/argo-cd/v2/...
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1766340]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc06baa9ec0)
	/home/runner/work/cue/cue/cmd/cue/cmd/root.go:221 +0x95
panic(0x181f6a0, 0x1e2c780)
	/opt/hostedtoolcache/go/1.15.12/x64/src/runtime/panic.go:969 +0x1b9
cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0xc083befa70, 0xc000034044, 0x2e, 0x0, 0x1e84ca0, 0x0)
	/home/runner/work/cue/cue/cmd/cue/cmd/get_go.go:453 +0x60
cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0xc083befa70, 0xc000034044, 0x2e, 0xc0048766c0, 0xc000f6f678, 0x32)
	/home/runner/work/cue/cue/cmd/cue/cmd/get_go.go:569 +0x1355
cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0xc083befa70, 0xc000034044, 0x2e, 0xc000290120, 0xc000983198, 0x27)
	/home/runner/work/cue/cue/cmd/cue/cmd/get_go.go:569 +0x1355
cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0xc083befa70, 0xc000034044, 0x2e, 0xc000313d40, 0x0, 0x0)
	/home/runner/work/cue/cue/cmd/cue/cmd/get_go.go:569 +0x1355
cuelang.org/go/cmd/cue/cmd.extract(0xc0002f67c0, 0xc00032e100, 0x1, 0x1, 0x11fce60, 0xc000289c88)
	/home/runner/work/cue/cue/cmd/cue/cmd/get_go.go:432 +0x65c
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc00031ab00, 0xc00032e100, 0x1, 0x1, 0x0, 0x0)
	/home/runner/work/cue/cue/cmd/cue/cmd/root.go:46 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc00031ab00, 0xc00032e0d0, 0x1, 0x1, 0xc00031ab00, 0xc00032e0d0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001b9080, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc0002f67c0, 0x19f5b00, 0xc0000b0008, 0x0, 0x0)
	/home/runner/work/cue/cue/cmd/cue/cmd/root.go:206 +0x65
cuelang.org/go/cmd/cue/cmd.mainErr(0x19f5b00, 0xc0000b0008, 0xc0000ae050, 0x3, 0x3, 0x192fd70, 0xc000289f48)
	/home/runner/work/cue/cue/cmd/cue/cmd/root.go:145 +0x8a
cuelang.org/go/cmd/cue/cmd.Main(0xc000096058)
	/home/runner/work/cue/cue/cmd/cue/cmd/root.go:127 +0x9c
main.main()
	/home/runner/work/cue/cue/cmd/cue/main.go:24 +0x25
```

**Comment by cueckoo** [comment]
_Original reply by @PierreR in https://github.com/cuelang/cue/issues/1053#issuecomment-858470034_

Probably related to #668 ?

**Comment by myitcv** [comment]
@yujunz thank you for raising this! Apologies for the migration-related delay (#1078) in getting round to looking at this. 

As @PierreR points out, this is a dup of #668, so I will close here.
