### ISSUE TITLE
Panic when evaluating cue-file

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#107]
_Originally opened by @Merovius in https://github.com/cuelang/cue/issues/107_

I get a panic when exporting this seemingly harmless cue-file:

```
a: 1/1+0
```

`cue export a.cue` panics, but `cue eval a.cue` works fine, printing `a: 1`, as you'd expect. This is with a version of cue built from 7fc421b924f3a79a1f5fd7268426bef20f25a767 (side-note: I though `go version -m =cue` should give me actual module versions? For some reason that doesn't seem to work…).

<details>
<summary>Panic backtrace</summary>

```
panic: interface conversion: cue.evaluated is *cue.numLit, not *cue.bottom [recovered]
	panic: interface conversion: cue.evaluated is *cue.numLit, not *cue.bottom [recovered]
	panic: interface conversion: cue.evaluated is *cue.numLit, not *cue.bottom [recovered]
	panic: interface conversion: cue.evaluated is *cue.numLit, not *cue.bottom

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc000271ec8)
	/home/mero/src/cuelang.org/go/cmd/cue/cmd/root.go:191 +0xa3
panic(0xb37ba0, 0xc00028ae10)
	/home/mero/go/src/runtime/panic.go:679 +0x1b2
encoding/json.(*encodeState).marshal.func1(0xc000271aa0)
	/home/mero/go/src/encoding/json/encode.go:305 +0x9a
panic(0xb37ba0, 0xc00028ae10)
	/home/mero/go/src/runtime/panic.go:679 +0x1b2
encoding/json.(*encodeState).marshal.func1(0xc000271638)
	/home/mero/go/src/encoding/json/encode.go:305 +0x9a
panic(0xb37ba0, 0xc00028ae10)
	/home/mero/go/src/runtime/panic.go:679 +0x1b2
cuelang.org/go/cue.Value.marshalJSON(0xc000257700, 0xc00029a690, 0xc000020000, 0xb3a600, 0xbf02c0, 0x7effa8046948, 0xc0002714d0)
	/home/mero/src/cuelang.org/go/cue/types.go:722 +0xcad
cuelang.org/go/cue.Value.MarshalJSON(0xc000257700, 0xc00029a690, 0x40bb43, 0xb3a600, 0xbf02c0, 0x53df01, 0x7effa8046948)
	/home/mero/src/cuelang.org/go/cue/types.go:688 +0x39
encoding/json.marshalerEncoder(0xc0002613b0, 0xbf02c0, 0xc00022bf60, 0x99, 0x100)
	/home/mero/go/src/encoding/json/encode.go:453 +0xc4
encoding/json.(*encodeState).reflectValue(0xc0002613b0, 0xbf02c0, 0xc00022bf60, 0x99, 0x100)
	/home/mero/go/src/encoding/json/encode.go:337 +0x82
encoding/json.(*encodeState).marshal(0xc0002613b0, 0xbf02c0, 0xc00022bf60, 0x100, 0x0, 0x0)
	/home/mero/go/src/encoding/json/encode.go:309 +0x10b
encoding/json.Marshal(0xbf02c0, 0xc00022bf60, 0xbf02c0, 0xc00022bf60, 0x8, 0x0, 0x0)
	/home/mero/go/src/encoding/json/encode.go:161 +0x52
cuelang.org/go/cue.(*structValue).marshalJSON(0xc000271820, 0xc00029a640, 0xc0002473f0, 0x101000000, 0xc0002473f0, 0xc00029a640)
	/home/mero/src/cuelang.org/go/cue/types.go:133 +0x23e
cuelang.org/go/cue.Value.marshalJSON(0xc000257700, 0xc00029a640, 0x11f36c8, 0x0, 0x0, 0x7effa8046948, 0xc000271938)
	/home/mero/src/cuelang.org/go/cue/types.go:720 +0xb72
cuelang.org/go/cue.Value.MarshalJSON(0xc000257700, 0xc00029a640, 0x40bb43, 0xb3a600, 0xbf02c0, 0x53e001, 0x7effa8046948)
	/home/mero/src/cuelang.org/go/cue/types.go:688 +0x39
encoding/json.marshalerEncoder(0xc000261340, 0xbf02c0, 0xc00022bed0, 0x99, 0x7effac280000)
	/home/mero/go/src/encoding/json/encode.go:453 +0xc4
encoding/json.(*encodeState).reflectValue(0xc000261340, 0xbf02c0, 0xc00022bed0, 0x99, 0x400000)
	/home/mero/go/src/encoding/json/encode.go:337 +0x82
encoding/json.(*encodeState).marshal(0xc000261340, 0xbf02c0, 0xc00022bed0, 0x410000, 0x0, 0x0)
	/home/mero/go/src/encoding/json/encode.go:309 +0x10b
encoding/json.(*Encoder).Encode(0xc000271b70, 0xbf02c0, 0xc00022bed0, 0xc00022bed0, 0xbf9d94)
	/home/mero/go/src/encoding/json/stream.go:202 +0x8a
cuelang.org/go/cmd/cue/cmd.outputJSON(0xc000251000, 0xd01d00, 0xc0000d4008, 0xc000257700, 0xc00029a640, 0x1, 0x1)
	/home/mero/src/cuelang.org/go/cmd/cue/cmd/export.go:125 +0x130
cuelang.org/go/cmd/cue/cmd.runExport(0xc000251000, 0xc00022bdd0, 0x1, 0x1, 0x0, 0x0)
	/home/mero/src/cuelang.org/go/cmd/cue/cmd/export.go:108 +0x287
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc00028d900, 0xc00022bdd0, 0x1, 0x1, 0x0, 0x0)
	/home/mero/src/cuelang.org/go/cmd/cue/cmd/root.go:46 +0x5f
github.com/spf13/cobra.(*Command).execute(0xc00028d900, 0xc00022bda0, 0x1, 0x1, 0xc00028d900, 0xc00022bda0)
	/home/mero/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc00028c500, 0x0, 0xc000251260, 0x0)
	/home/mero/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/home/mero/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc000251000, 0xd11580, 0xc0000c2000, 0x0, 0x0)
	/home/mero/src/cuelang.org/go/cmd/cue/cmd/root.go:176 +0x75
cuelang.org/go/cmd/cue/cmd.Main(0xd11580, 0xc0000c2000, 0xc0000bc160, 0x2, 0x2, 0x40721f, 0xc0000ae058)
	/home/mero/src/cuelang.org/go/cmd/cue/cmd/root.go:111 +0x74
main.main()
	/home/mero/src/cuelang.org/go/cmd/cue/main.go:26 +0x84
```

</details>

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/107#issuecomment-530960710_

Found the issue and the source. Silly bug, but an interesting combination of factors why it didn't show before.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/107#issuecomment-530983279_

And the version is currently only set when using a released binary. Would you know how to include the module version in the binary?

**Comment by cueckoo** [comment]
_Original reply by @Merovius in https://github.com/cuelang/cue/issues/107#issuecomment-531063808_

I don't know what I did wrong earlier today, but `go version -m` now works as intended for me - which means "it's still not really useful here". Shows the used versions of all the dependencies, but no hash or whatever of the actual module of the binary. So disregard that part :) I'll continue to use the git-hash where it makes sense :)
