### ISSUE TITLE
cmd/cue: trim panic with nil pointer dereference

### ISSUE THREAD

**Issue by yujunz** [cue-lang/cue#1087]
### What version of CUE are you using (`cue version`)?

<pre>
cue version 0.4.0 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
cue trim
```

TBD: https://github.com/cue-lang/cue/wiki/Creating-test-or-performance-reproducers

### What did you expect to see?

Trimmed

### What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1754bf7]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc00014bec0)
	/home/runner/work/cue/cue/cmd/cue/cmd/root.go:221 +0x95
panic(0x181f6a0, 0x1e2c780)
	/opt/hostedtoolcache/go/1.15.12/x64/src/runtime/panic.go:969 +0x1b9
cuelang.org/go/tools/trim.(*trimmer).addDominators(0xc000104580, 0x0, 0xc000017d40, 0xc000017d00, 0x0, 0x1000000)
	/home/runner/work/cue/cue/tools/trim/trim.go:219 +0x437
cuelang.org/go/tools/trim.(*trimmer).findSubordinates(0xc000104580, 0x0, 0xc000017d40, 0xc0003a4a00, 0x0)
	/home/runner/work/cue/cue/tools/trim/trim.go:259 +0x126
cuelang.org/go/tools/trim.(*trimmer).findSubordinates(0xc000104580, 0x0, 0xc0003a4a20, 0xc0009ad400, 0x0)
	/home/runner/work/cue/cue/tools/trim/trim.go:273 +0x1d6
cuelang.org/go/tools/trim.(*trimmer).findSubordinates(0xc000104580, 0x0, 0xc0009ad4d0, 0xc00021b500, 0x0)
	/home/runner/work/cue/cue/tools/trim/trim.go:273 +0x1d6
cuelang.org/go/tools/trim.(*trimmer).findSubordinates(0xc000104580, 0xc00015da70, 0xc00021b560, 0x0, 0x0)
	/home/runner/work/cue/cue/tools/trim/trim.go:273 +0x1d6
cuelang.org/go/tools/trim.Files(0xc00045bb80, 0x7, 0x8, 0x19ea200, 0xc000484620, 0xc00014ba17, 0x1, 0x203000)
	/home/runner/work/cue/cue/tools/trim/trim.go:87 +0x1dd
cuelang.org/go/cmd/cue/cmd.runTrim(0xc00033a240, 0x1e83498, 0x0, 0x0, 0x11fce60, 0xc0002b9c88)
	/home/runner/work/cue/cue/cmd/cue/cmd/trim.go:115 +0x346
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc000353600, 0x1e83498, 0x0, 0x0, 0x0, 0x0)
	/home/runner/work/cue/cue/cmd/cue/cmd/root.go:46 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc000353600, 0x1e83498, 0x0, 0x0, 0xc000353600, 0x1e83498)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000dd080, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc00033a240, 0x19f5b00, 0xc0000380f0, 0x0, 0x0)
	/home/runner/work/cue/cue/cmd/cue/cmd/root.go:206 +0x65
cuelang.org/go/cmd/cue/cmd.mainErr(0x19f5b00, 0xc0000380f0, 0xc00000c090, 0x1, 0x1, 0x192fd70, 0xc0002b9f48)
	/home/runner/work/cue/cue/cmd/cue/cmd/root.go:145 +0x8a
cuelang.org/go/cmd/cue/cmd.Main(0xc00007e058)
	/home/runner/work/cue/cue/cmd/cue/cmd/root.go:127 +0x9c
main.main()
	/home/runner/work/cue/cue/cmd/cue/main.go:24 +0x25
```

**Comment by PierreR** [comment]
I have also got this issue with a `cue trim -s ./src/...` while `cue vet -c -s ./src/...` works as expected without error.
I will try to give more details but so far I am not able to understand what triggers it.

**Comment by PierreR** [comment]
In the meanwhile we have removed `trim` from our workflow because it crashes too many times for no obvious reasons for too many people  ;-)

**Comment by myitcv** [comment]
@yujunz do you have any more context for the error you are seeing? What files existed in the current directory?

@PierreR 



> In the meanwhile we have removed `trim` from our workflow because it crashes for no obvious reasons too many times for no obvious reasons for too many people ;-)

We'd certainly be very grateful of any error reports you can share. They go a long way towards improving everyone's experience of CUE.

**Comment by yujunz** [comment]
> @yujunz do you have any more context for the error you are seeing? What files existed in the current directory?

The file in current directory is pretty simple

```
package argocd

application: ambassador: _
```

But the whole package is quite complex. It borrows a lot from the [kubernetes tutorial](https://github.com/cue-lang/cue/tree/master/doc/tutorial/kubernetes) and refers some packages generated from go and some from local.

Does the current error message give any hint on which part could possibly go wrong? So that I can try to simply the code to a minimum reproducible context.

**Comment by myitcv** [comment]
> Does the current error message give any hint on which part could possibly go wrong? So that I can try to simply the code to a minimum reproducible context.

Unfortunately there is a lot of context missing. If you are able to share a repro that would be great. If this is private code you want to share we can arrange that too.

**Comment by vikstrous2** [comment]
I ran into a similar loooking nil pointer:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xa42f65]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc001933e90)
        /home/viktor/go/pkg/mod/cuelang.org/go@v0.4.0/cmd/cue/cmd/root.go:221 +0x7b
panic({0xaf2f60, 0x11235c0})
        /home/viktor/.go/src/runtime/panic.go:1038 +0x215
cuelang.org/go/tools/trim.(*trimmer).addDominators(0xc005674b80, 0x0, 0xc0072c98c0, 0x0)
        /home/viktor/go/pkg/mod/cuelang.org/go@v0.4.0/tools/trim/trim.go:219 +0x4a5
cuelang.org/go/tools/trim.(*trimmer).findSubordinates(0xc005674b80, 0x0, 0xc0072c98c0, 0x0)
        /home/viktor/go/pkg/mod/cuelang.org/go@v0.4.0/tools/trim/trim.go:259 +0x125
cuelang.org/go/tools/trim.(*trimmer).findSubordinates(0xc005674b80, 0x0, 0xc0072c9710, 0x0)
        /home/viktor/go/pkg/mod/cuelang.org/go@v0.4.0/tools/trim/trim.go:273 +0x58c
cuelang.org/go/tools/trim.(*trimmer).findSubordinates(0xc005674b80, 0x0, 0xc0072c8f30, 0x0)
        /home/viktor/go/pkg/mod/cuelang.org/go@v0.4.0/tools/trim/trim.go:273 +0x58c
cuelang.org/go/tools/trim.(*trimmer).findSubordinates(0xc005674b80, 0x0, 0xc0072c8cf0, 0x0)
        /home/viktor/go/pkg/mod/cuelang.org/go@v0.4.0/tools/trim/trim.go:273 +0x58c
cuelang.org/go/tools/trim.(*trimmer).findSubordinates(0xc005674b80, 0x0, 0xc006bfefc0, 0x0)
        /home/viktor/go/pkg/mod/cuelang.org/go@v0.4.0/tools/trim/trim.go:273 +0x58c
cuelang.org/go/tools/trim.(*trimmer).findSubordinates(0xc005674b80, 0xc0077e1830, 0xc006be0630, 0x0)
        /home/viktor/go/pkg/mod/cuelang.org/go@v0.4.0/tools/trim/trim.go:273 +0x58c
cuelang.org/go/tools/trim.(*trimmer).findSubordinates(0xc005674b80, 0x0, 0xc0007ca240, 0x0)
        /home/viktor/go/pkg/mod/cuelang.org/go@v0.4.0/tools/trim/trim.go:273 +0x58c
cuelang.org/go/tools/trim.Files({0xc0015b8080, 0xf, 0xc0001a79e0}, {0xc9efb8, 0xc00120c4d0}, 0xc001933a87)
        /home/viktor/go/pkg/mod/cuelang.org/go@v0.4.0/tools/trim/trim.go:87 +0x228
cuelang.org/go/cmd/cue/cmd.runTrim(0xc000396800, {0xc000396ae0, 0x1, 0x2})
        /home/viktor/go/pkg/mod/cuelang.org/go@v0.4.0/cmd/cue/cmd/trim.go:115 +0x297
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc0003b18c0, {0xc000396ae0, 0x2, 0x2})
        /home/viktor/go/pkg/mod/cuelang.org/go@v0.4.0/cmd/cue/cmd/root.go:46 +0x4d
github.com/spf13/cobra.(*Command).execute(0xc0003b18c0, {0xc000396ac0, 0x2, 0x2})
        /home/viktor/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002c5340)
        /home/viktor/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
        /home/viktor/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc000396800, {0x3, 0xcaeb90})
        /home/viktor/go/pkg/mod/cuelang.org/go@v0.4.0/cmd/cue/cmd/root.go:206 +0x6b
cuelang.org/go/cmd/cue/cmd.mainErr({0xca7950, 0xc000036120}, {0xc0000320d0, 0xc000060738, 0x46035b})
        /home/viktor/go/pkg/mod/cuelang.org/go@v0.4.0/cmd/cue/cmd/root.go:145 +0x55
cuelang.org/go/cmd/cue/cmd.Main()
        /home/viktor/go/pkg/mod/cuelang.org/go@v0.4.0/cmd/cue/cmd/root.go:127 +0x85
main.main()
        /home/viktor/go/pkg/mod/cuelang.org/go@v0.4.0/cmd/cue/main.go:24 +0x19
make: *** [Makefile:30: format-cue] Error 2
```

**Comment by vikstrous2** [comment]
This reproduces it:

```
configs: {
	key: 123
}

shared: {
	param: string
	derived: configs[param]
}

a: shared & {
	param: "key"
}

```

**Comment by vikstrous2** [comment]
`cue eval -c` also fails on this config, which is reasonable:
```
shared.derived: invalid non-ground value string (must be concrete string)
shared.param: incomplete value string
```

**Comment by vikstrous2** [comment]
If I make `shared` into a hidden field (`_shared`), the config renders, but cue trim still panics.

**Comment by myitcv** [comment]
Thanks @vikstrous2. Confirmed with e8550b89 that `cue trim` panics:

```
exec cue trim x.cue

-- x.cue --
configs: {
	key: 123
}

shared: {
	param:   string
	derived: configs[param]
}

a: shared & {
	param: "key"
}
```

gives:

```
> exec cue trim x.cue
[stderr]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xb0fc36]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc00021fec0)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:221 +0x9c
panic(0xbd3200, 0x11a4090)
        /home/myitcv/gos/src/runtime/panic.go:965 +0x1b9
cuelang.org/go/tools/trim.(*trimmer).addDominators(0xc000359580, 0x0, 0xc0003b66c0, 0xc0003b6600, 0xc0003b6d80, 0x1)
        /home/myitcv/dev/cuelang/cue/tools/trim/trim.go:219 +0x4d6
cuelang.org/go/tools/trim.(*trimmer).findSubordinates(0xc000359580, 0x0, 0xc0003b66c0, 0xc0003b6300, 0x0)
        /home/myitcv/dev/cuelang/cue/tools/trim/trim.go:259 +0x126
cuelang.org/go/tools/trim.(*trimmer).findSubordinates(0xc000359580, 0x0, 0xc0003b63f0, 0xc0003b6000, 0x0)
        /home/myitcv/dev/cuelang/cue/tools/trim/trim.go:273 +0x1d6
cuelang.org/go/tools/trim.(*trimmer).findSubordinates(0xc000359580, 0xc0003b6ab0, 0xc0003b6090, 0x0, 0x0)
        /home/myitcv/dev/cuelang/cue/tools/trim/trim.go:273 +0x1d6
cuelang.org/go/tools/trim.Files(0xc000369500, 0x1, 0x1, 0xd98970, 0xc00038e690, 0xc00021fa2f, 0x1, 0xc00007ebae)
        /home/myitcv/dev/cuelang/cue/tools/trim/trim.go:87 +0x1dd
cuelang.org/go/cmd/cue/cmd.runTrim(0xc0003847a0, 0xc00032b820, 0x1, 0x1, 0x5eb3a0, 0xc00021fc98)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/trim.go:115 +0x336
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc0003998c0, 0xc00032b820, 0x1, 0x1, 0x0, 0x0)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:46 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc0003998c0, 0xc00032b7f0, 0x1, 0x1, 0xc0003998c0, 0xc00032b7f0)
        /home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000c1340, 0x0, 0x0, 0x0)
        /home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc0003847a0, 0xda1d30, 0xc000124030, 0x0, 0x0)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:206 +0x65
cuelang.org/go/cmd/cue/cmd.mainErr(0xda1d30, 0xc000124030, 0xc00011c070, 0x2, 0x2, 0xc00005a740, 0x469185)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:145 +0x8d
cuelang.org/go/cmd/cue/cmd.Main(0xc00010e058)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:127 +0x9b
main.main()
        /home/myitcv/dev/cuelang/cue/cmd/cue/main.go:24 +0x25
```
