### ISSUE TITLE
Panic when hitting unresolved disjunction in tool using "tool/exec" and "encoding/json"

### ISSUE THREAD

**Issue by addreas** [cue-lang/cue#1256]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version (devel) linux/amd64 
</pre>

The master branch at commit 0f53054da7243c7a312cd0ad54a1083d67c185d3

### Does this issue reproduce with the latest release?
Yes

### What did you do?

```
exec cue cmd test

-- test_tool.cue --
package test

import (
    "tool/exec"
    "encoding/json"
)

command: test: task: test: exec.Run & {
	cmd: "cat"
	stdin: json.Marshal({test: (*1 | int) & (int | *2)})
}
```

### What did you expect to see?
Something similar to what is reported when using `encoding/yaml` instead.

```
command.test.task.test.stdin: 1 errors in empty disjunction:
command.test: error in call to encoding/yaml.Marshal: yaml: unsupported node _|_ (*ast.BottomLit):
    ./test_tool.cue:10:9
    -
```

### What did you see instead?
```
panic: runtime error: invalid memory address or nil pointer dereference
	panic: freeNode: nodeContext out of sync [recovered]
	panic: freeNode: nodeContext out of sync
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x66da48]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc00053fd68)
	/home/addem/.go/src/cuelang.org/go/cmd/cue/cmd/root.go:221 +0x7b
panic({0xac26e0, 0xc8dd70})
	/usr/lib/go/src/runtime/panic.go:1038 +0x215
cuelang.org/go/internal/core/adt.(*Vertex).freeNode(0xc0000001a0, 0xc000315220)
	/home/addem/.go/src/cuelang.org/go/internal/core/adt/eval.go:931 +0x125
panic({0xaf2f60, 0x111d5c0})
	/usr/lib/go/src/runtime/panic.go:1047 +0x266
cuelang.org/go/internal/core/adt.selectErrors({0xc000126620, 0x0, 0x0})
	/home/addem/.go/src/cuelang.org/go/internal/core/adt/disjunct.go:577 +0x1c8
cuelang.org/go/internal/core/adt.(*nodeContext).disjunctError(0x0)
	/home/addem/.go/src/cuelang.org/go/internal/core/adt/disjunct.go:524 +0x3e
cuelang.org/go/internal/core/adt.(*nodeContext).makeError(0xc000119880)
	/home/addem/.go/src/cuelang.org/go/internal/core/adt/disjunct.go:412 +0x48
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0xc000119880, 0xa0, 0xc000119880, 0x0, 0x0, 0x1)
	/home/addem/.go/src/cuelang.org/go/internal/core/adt/disjunct.go:255 +0x139a
cuelang.org/go/internal/core/adt.(*OpContext).Unify(0xc0000a71e0, 0xc000138bd0, 0x5)
	/home/addem/.go/src/cuelang.org/go/internal/core/adt/eval.go:281 +0x997
cuelang.org/go/internal/core/adt.(*nodeContext).completeArcs(0xc000118000, 0x5)
	/home/addem/.go/src/cuelang.org/go/internal/core/adt/eval.go:669 +0x4b9
cuelang.org/go/internal/core/adt.(*nodeContext).postDisjunct(0xc000118000, 0x5)
	/home/addem/.go/src/cuelang.org/go/internal/core/adt/eval.go:565 +0x7b0
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0xc000118000, 0x0, 0xc000118000, 0x0, 0x0, 0x1)
	/home/addem/.go/src/cuelang.org/go/internal/core/adt/disjunct.go:151 +0x385
cuelang.org/go/internal/core/adt.(*OpContext).Unify(0xc0000a71e0, 0xc0000ef7a0, 0x5)
	/home/addem/.go/src/cuelang.org/go/internal/core/adt/eval.go:281 +0x997
cuelang.org/go/internal/core/adt.(*nodeContext).completeArcs(0xc0000edc00, 0x5)
	/home/addem/.go/src/cuelang.org/go/internal/core/adt/eval.go:669 +0x4b9
cuelang.org/go/internal/core/adt.(*nodeContext).postDisjunct(0xc0000edc00, 0x5)
	/home/addem/.go/src/cuelang.org/go/internal/core/adt/eval.go:565 +0x7b0
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0xc0000edc00, 0x37, 0xc0000edc00, 0x0, 0x0, 0x1)
	/home/addem/.go/src/cuelang.org/go/internal/core/adt/disjunct.go:151 +0x385
cuelang.org/go/internal/core/adt.(*OpContext).Unify(0xc0000a71e0, 0xc0000ef710, 0x5)
	/home/addem/.go/src/cuelang.org/go/internal/core/adt/eval.go:281 +0x997
cuelang.org/go/internal/core/adt.(*nodeContext).completeArcs(0xc0000ed880, 0x5)
	/home/addem/.go/src/cuelang.org/go/internal/core/adt/eval.go:669 +0x4b9
cuelang.org/go/internal/core/adt.(*nodeContext).postDisjunct(0xc0000ed880, 0x5)
	/home/addem/.go/src/cuelang.org/go/internal/core/adt/eval.go:565 +0x7b0
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0xc0000ed880, 0x0, 0xc0000ed880, 0x0, 0x0, 0x1)
	/home/addem/.go/src/cuelang.org/go/internal/core/adt/disjunct.go:151 +0x385
cuelang.org/go/internal/core/adt.(*OpContext).Unify(0xc0000a71e0, 0xc0000ef680, 0x5)
	/home/addem/.go/src/cuelang.org/go/internal/core/adt/eval.go:281 +0x997
cuelang.org/go/internal/core/adt.(*nodeContext).completeArcs(0xc0000ed500, 0x5)
	/home/addem/.go/src/cuelang.org/go/internal/core/adt/eval.go:669 +0x4b9
cuelang.org/go/internal/core/adt.(*nodeContext).postDisjunct(0xc0000ed500, 0x5)
	/home/addem/.go/src/cuelang.org/go/internal/core/adt/eval.go:565 +0x7b0
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0xc0000ed500, 0xc0, 0xc0000ed500, 0x0, 0x0, 0x1)
	/home/addem/.go/src/cuelang.org/go/internal/core/adt/disjunct.go:151 +0x385
cuelang.org/go/internal/core/adt.(*OpContext).Unify(0xc0000a71e0, 0xc0000ef560, 0x5)
	/home/addem/.go/src/cuelang.org/go/internal/core/adt/eval.go:281 +0x997
cuelang.org/go/internal/core/adt.(*nodeContext).completeArcs(0xc0000ed180, 0x5)
	/home/addem/.go/src/cuelang.org/go/internal/core/adt/eval.go:669 +0x4b9
cuelang.org/go/internal/core/adt.(*nodeContext).postDisjunct(0xc0000ed180, 0x5)
	/home/addem/.go/src/cuelang.org/go/internal/core/adt/eval.go:565 +0x7b0
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0xc0000ed180, 0x0, 0xc0000ed180, 0x0, 0x0, 0x1)
	/home/addem/.go/src/cuelang.org/go/internal/core/adt/disjunct.go:151 +0x385
cuelang.org/go/internal/core/adt.(*OpContext).Unify(0xc0000a71e0, 0xc0000ef170, 0x5)
	/home/addem/.go/src/cuelang.org/go/internal/core/adt/eval.go:281 +0x997
cuelang.org/go/internal/core/adt.(*Vertex).Finalize(...)
	/home/addem/.go/src/cuelang.org/go/internal/core/adt/composite.go:445
cuelang.org/go/cue.newVertexRoot(0xcada58, 0xc0000a71e0, 0x0)
	/home/addem/.go/src/cuelang.org/go/cue/types.go:615 +0x69
cuelang.org/go/cue.(*Instance).value(0xc0003ea770)
	/home/addem/.go/src/cuelang.org/go/cue/instance.go:284 +0x52
cuelang.org/go/cue.(*Instance).Lookup(0xc00003f180, {0xc00053fc40, 0x2, 0x2})
	/home/addem/.go/src/cuelang.org/go/cue/instance.go:295 +0x28
cuelang.org/go/cmd/cue/cmd.addCustom(0xc00034ec80, 0xc00024df90, {0xb9dcc9, 0x0}, {0x7ffc1d95e88d, 0x4}, 0xc0003ea770)
	/home/addem/.go/src/cuelang.org/go/cmd/cue/cmd/custom.go:69 +0xc6
cuelang.org/go/cmd/cue/cmd.New({0xc000032050, 0x1, 0xcae9d0})
	/home/addem/.go/src/cuelang.org/go/cmd/cue/cmd/root.go:275 +0x465
cuelang.org/go/cmd/cue/cmd.mainErr({0xca7790, 0xc000036160}, {0xc000032050, 0xc000068738, 0x46043b})
	/home/addem/.go/src/cuelang.org/go/cmd/cue/cmd/root.go:141 +0x31
cuelang.org/go/cmd/cue/cmd.Main()
	/home/addem/.go/src/cuelang.org/go/cmd/cue/cmd/root.go:127 +0x85
main.main()
	/home/addem/.go/src/cuelang.org/go/cmd/cue/main.go:24 +0x19
```

edit: smaller reproduction

**Comment by mpvl** [comment]
This is fixed in tip.
