### ISSUE TITLE
encoding/openapi: Segfault when outputting OpenAPI with JSON input file

### ISSUE THREAD

**Issue by rycee** [cue-lang/cue#1270]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.4.0 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, seems so.

### What did you do?

Attempt at reproducer:

```
exec cue def -o openapi:- -e '{#Output: #Test}' test.cue test.json
cmp stdout stdout.golden

-- test.cue --
#Int: int
#Test: test: #Int
-- test.json --
{ }
-- stdout.golden --
{
    "openapi": "3.0.0",
    "info": {
        "title": "Generated by cue.",
        "version": "no version"
    },
    "paths": {},
    "components": {
        "schemas": {
            "Int": {
                "type": "integer"
            },
            "Output": {
                "$ref": "#/components/schemas/Test"
            },
            "Test": {
                "type": "object",
                "required": [
                    "test"
                ],
                "properties": {
                    "test": {
                        "$ref": "#/components/schemas/Int"
                    }
                }
            }
        }
    }
}
```

### What did you expect to see?

The result in `stdout.golden`.

### What did you see instead?

A segfault:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x9bf61b]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc0000dbec0)
	cuelang.org/go/cmd/cue/cmd/root.go:221 +0x9c
panic(0xbd3200, 0x119f090)
	runtime/panic.go:965 +0x1b9
cuelang.org/go/encoding/openapi.schemas.func1(0xc0000dbac0)
	cuelang.org/go/encoding/openapi/build.go:123 +0x9c
panic(0xbd3200, 0x119f090)
	runtime/panic.go:965 +0x1b9
cuelang.org/go/encoding/openapi.extractFormat(0xc00047b9e0, 0xc00031ccf0, 0xc00047bed0, 0xc00047bed0, 0xc73ae0)
	cuelang.org/go/encoding/openapi/types.go:70 +0x15b
cuelang.org/go/encoding/openapi.(*builder).fillSchema(0xc0002146e0, 0xc00047b9e0, 0xc00031ccf0, 0xc00047bed0, 0x2)
	cuelang.org/go/encoding/openapi/build.go:256 +0x7c
cuelang.org/go/encoding/openapi.(*builder).schema(0xc000214630, 0x0, 0xc000040d28, 0x4, 0xc00047b9e0, 0xc00031ccf0, 0xc00047bed0, 0x0)
	cuelang.org/go/encoding/openapi/build.go:230 +0x16a
cuelang.org/go/encoding/openapi.(*builder).object(0xc000214630, 0xc00047b9e0, 0xc00031d200, 0x0)
	cuelang.org/go/encoding/openapi/build.go:768 +0x3c8
cuelang.org/go/encoding/openapi.(*builder).dispatch(0xc000214630, 0x0, 0xc00047b9e0, 0xc00031d200, 0x0)
	cuelang.org/go/encoding/openapi/build.go:686 +0x407
cuelang.org/go/encoding/openapi.(*builder).value(0xc000214630, 0xc00047b9e0, 0xc00031cbd0, 0x0, 0x0, 0x0)
	cuelang.org/go/encoding/openapi/build.go:424 +0x813
cuelang.org/go/encoding/openapi.(*builder).fillSchema(0xc000214630, 0xc00047b9e0, 0xc00031cbd0, 0x0, 0x7f165d772108)
	cuelang.org/go/encoding/openapi/build.go:260 +0x112
cuelang.org/go/encoding/openapi.(*builder).schema(0xc0000db600, 0x0, 0xc000040d20, 0x5, 0xc00047b9e0, 0xc00031cbd0, 0x0, 0x0)
	cuelang.org/go/encoding/openapi/build.go:230 +0x16a
cuelang.org/go/encoding/openapi.(*buildContext).build(0xc000352140, 0xc000040d20, 0x5, 0xc00047b9e0, 0xc00031cbd0, 0x0, 0x0)
	cuelang.org/go/encoding/openapi/build.go:184 +0xc9
cuelang.org/go/encoding/openapi.schemas(0xc0000610e0, 0xc00023dd50, 0x0, 0x0, 0x0)
	cuelang.org/go/encoding/openapi/build.go:169 +0x8ea
cuelang.org/go/encoding/openapi.Generate(0xc00023dd50, 0xc0000610e0, 0xc58c40, 0xc00023dd50, 0xc0005096d0)
	cuelang.org/go/encoding/openapi/openapi.go:91 +0x39
cuelang.org/go/internal/encoding.NewEncoder.func1(0xc00047b9e0, 0xc00031ce10, 0x0, 0x0, 0xc00031cab0, 0xc00047b9e0)
	cuelang.org/go/internal/encoding/encoder.go:90 +0x45
cuelang.org/go/internal/encoding.(*Encoder).Encode(0xc00034b140, 0xc00047b9e0, 0xc00031ce10, 0x0, 0x0, 0xc000398750)
	cuelang.org/go/internal/encoding/encoder.go:257 +0x59
cuelang.org/go/cmd/cue/cmd.runDef(0xc000368ba0, 0xc00012b440, 0x2, 0x6, 0x0, 0x0)
	cuelang.org/go/cmd/cue/cmd/def.go:67 +0x26a
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc000388000, 0xc00012b440, 0x2, 0x6, 0x0, 0x0)
	cuelang.org/go/cmd/cue/cmd/root.go:46 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc000388000, 0xc00012b3e0, 0x6, 0x6, 0xc000388000, 0xc00012b3e0)
	github.com/spf13/cobra@v1.0.0/command.go:842 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000239340, 0x0, 0x0, 0x0)
	github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.0.0/command.go:887
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc000368ba0, 0xda1d30, 0xc000124030, 0x0, 0x0)
	cuelang.org/go/cmd/cue/cmd/root.go:206 +0x65
cuelang.org/go/cmd/cue/cmd.mainErr(0xda1d30, 0xc000124030, 0xc00012c010, 0x7, 0x7, 0xc000084740, 0x469485)
	cuelang.org/go/cmd/cue/cmd/root.go:145 +0x8d
cuelang.org/go/cmd/cue/cmd.Main(0xc00010e058)
	cuelang.org/go/cmd/cue/cmd/root.go:127 +0x9b
main.main()
	cuelang.org/go/cmd/cue/main.go:24 +0x25
```

**Comment by myitcv** [comment]
@rycee thanks very much for the testscript reproducer. Reproduced with 59bdbb50
