### ISSUE TITLE
cue export panics with empty input

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#1363]
commit 9217c4d0

Running this command:
```
cue export json: - < /dev/null
```

produces this panic:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x71451d]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc0005fbe90)
	/home/rogpeppe/other/cue/cmd/cue/cmd/root.go:221 +0x7b
panic({0xb16460, 0x1108fd0})
	/home/rogpeppe/go/src/runtime/panic.go:838 +0x207
cuelang.org/go/cue.(*Instance).Value(0x0)
	/home/rogpeppe/other/cue/cue/instance.go:211 +0x1d
cuelang.org/go/cmd/cue/cmd.(*instanceIterator).value(0xc00067fc80)
	/home/rogpeppe/other/cue/cmd/cue/cmd/common.go:216 +0x37
cuelang.org/go/cmd/cue/cmd.runExport(0x59dcd1?, {0xc0000e1c00, 0x2, 0x2})
	/home/rogpeppe/other/cue/cmd/cue/cmd/export.go:116 +0x1ef
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc00015d8c0?, {0xc0000e1c00?, 0x2?, 0x2?})
	/home/rogpeppe/other/cue/cmd/cue/cmd/root.go:46 +0x4d
github.com/spf13/cobra.(*Command).execute(0xc00015d8c0, {0xc0000e1be0, 0x2, 0x2})
	/home/rogpeppe/src/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00015c580)
	/home/rogpeppe/src/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x39c
github.com/spf13/cobra.(*Command).Execute(...)
	/home/rogpeppe/src/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc0000e1940, {0x3?, 0xcf0a30?})
	/home/rogpeppe/other/cue/cmd/cue/cmd/root.go:206 +0x6b
cuelang.org/go/cmd/cue/cmd.mainErr({0xcee4f0, 0xc00003a1b0}, {0xc0000320d0?, 0xc00006e738?, 0x45f73b?})
	/home/rogpeppe/other/cue/cmd/cue/cmd/root.go:145 +0x55
cuelang.org/go/cmd/cue/cmd.Main()
	/home/rogpeppe/other/cue/cmd/cue/cmd/root.go:127 +0x85
main.main()
	/home/rogpeppe/other/cue/cmd/cue/main.go:24 +0x19

goroutine 10 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x0?)
	/home/rogpeppe/src/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x6a
created by github.com/golang/glog.init.0
	/home/rogpeppe/src/go/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x1bf
```

**Comment by antong** [comment]
Isn't this #1016 ?

**Comment by rogpeppe** [comment]
Indeed it is!!
