### ISSUE TITLE
cmd/cue: if comprehension relying on value alias via cmd panics

### ISSUE THREAD

**Issue by mheers** [cue-lang/cue#1405]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.0 linux/amd64
</pre>

I also tried with the newest commit `9e7d4d63acf9cfcf7fdc33731dedfe420c0e2689`

### Does this issue reproduce with the latest release?
Yes

### What did you do?

File:
```
import (
	"tool/exec"
	"text/template"
	"tool/cli"

)

command: alias: {
	rendered: template.Execute(t, instance & {
		enabled: true
	})

    echo: exec.Run & {
		cmd: ["echo", rendered]
        stdout: string
	}

	print: cli.Print & {
        text: echo.stdout
	}

}

t: """
	# {{ .name }}
	"""

#base: {
	enabled: bool | *false
	name:    string
	value?:  int
}

#combined: X=#base & {
	name: "My instance"
	if X.enabled {
		value: 123456
	}
}

instance: #combined & {
	enabled: true
}
```

run with `cue cmd alias ./alias_tool.cue`

### What did you expect to see?
The rendered message (`My instance`) on the CLI

### What did you see instead?
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x98dc47]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc000465e90)
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/cmd/cue/cmd/root.go:221 +0x7b
panic({0xaf2e80, 0x111f5c0})
	/usr/lib/go-1.17/src/runtime/panic.go:1038 +0x215
cuelang.org/go/internal/core/dep.visit.func1()
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:120 +0xb0
panic({0xaf2e80, 0x111f5c0})
	/usr/lib/go-1.17/src/runtime/panic.go:1038 +0x215
cuelang.org/go/internal/core/dep.visit.func1()
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:120 +0xb0
panic({0xaf2e80, 0x111f5c0})
	/usr/lib/go-1.17/src/runtime/panic.go:1038 +0x215
cuelang.org/go/internal/core/dep.visit.func1()
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:120 +0xb0
panic({0xaf2e80, 0x111f5c0})
	/usr/lib/go-1.17/src/runtime/panic.go:1038 +0x215
cuelang.org/go/internal/core/dep.visit.func1()
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:120 +0xb0
panic({0xaf2e80, 0x111f5c0})
	/usr/lib/go-1.17/src/runtime/panic.go:1038 +0x215
cuelang.org/go/tools/flow.(*Controller).findImpliedTask(0xc00034afc0, {0xc000415dd0, {0x7fbc84ee8e18, 0xc0003bfc40}, 0x1})
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/tools/flow/tasks.go:184 +0x127
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies.func1({0xc000415dd0, {0x7fbc84ee8e18, 0xc0003bfc40}, 0x1})
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/tools/flow/tasks.go:225 +0x51
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0xc0004648a0, 0xc00049b180, {0x7fbc84ee8e18, 0xc0003bfc40})
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:230 +0xe8
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc0004648a0, 0xc00049b180, {0xcad8d8, 0xc0003bfc40})
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:150 +0x4c7
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0xc0004648a0, 0xc00049b180, {0xca16b0, 0xc000417380})
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:254 +0x197
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc0004648a0, 0xc00049b180, {0xcad718, 0xc000417380})
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:150 +0x4c7
cuelang.org/go/internal/core/dep.(*visitor).markYielder(0x50, 0xc00049b180, {0xca1590, 0xc000458870})
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:317 +0x1d8
cuelang.org/go/internal/core/dep.(*visitor).markDecl(0xc0004648a0, 0xcad7d8, {0x7fbc84ee87d8, 0xc000458870})
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:290 +0x1ff
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc0004648a0, 0xc0004573b0, {0xcad7d8, 0xc00044c630})
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:206 +0x50f
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc0004648a0, 0xc0004573b0, {0xcad118, 0xc0004588a0})
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:154 +0x4aa
cuelang.org/go/internal/core/dep.visit(0xb142a0, 0xc0004649e8, 0xc000417400, 0x0, 0x74)
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:125 +0x1d1
cuelang.org/go/internal/core/dep.dynamic(0xc00044c990, 0xc00044c990, 0xc00044c990, 0x1d93, 0xf5)
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/mixed.go:43 +0x1b1
cuelang.org/go/internal/core/dep.VisitFields(0xb140c0, 0xb29ac0, 0xba9d1720aa9aacc)
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:91 +0xc5
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies(0xc00034afc0, 0xc00034b0a0, 0xc00044c990)
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/tools/flow/tasks.go:224 +0x8d
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies.func1({0xc00044c990, {0x7fbc84ee8be0, 0xc0003bfc60}, 0x1})
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/tools/flow/tasks.go:240 +0x16a
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0xc000464d90, 0xc0004573b0, {0x7fbc84ee8be0, 0xc0003bfc60})
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:230 +0xe8
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc000464d90, 0xc0004573b0, {0xcad458, 0xc0003bfc60})
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:150 +0x4c7
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc000464d90, 0xc0004573b0, {0xcad118, 0xc0004588d0})
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:153 +0x485
cuelang.org/go/internal/core/dep.visit(0xb142a0, 0xc000464ed8, 0xc000417440, 0x40, 0x74)
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:125 +0x1d1
cuelang.org/go/internal/core/dep.dynamic(0xc00044ca20, 0xc00044ca20, 0xc00044ca20, 0x793, 0x0)
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/mixed.go:43 +0x1b1
cuelang.org/go/internal/core/dep.VisitFields(0xb140c0, 0xb29ac0, 0xe19de1297e2fdd8f)
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:91 +0xc5
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies(0xc00034afc0, 0xc00034b0a0, 0xc00044ca20)
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/tools/flow/tasks.go:224 +0x8d
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies.func1({0xc00044ca20, {0x7fbc84ee8be0, 0xc0003bfb00}, 0x1})
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/tools/flow/tasks.go:240 +0x16a
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0xc000465320, 0xc000457450, {0x7fbc84ee8be0, 0xc0003bfb00})
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:230 +0xe8
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc000465320, 0xc000457450, {0xcad458, 0xc0003bfb00})
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:150 +0x4c7
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc000465320, 0xc000457450, {0xcad118, 0xc0004586c0})
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:153 +0x485
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc000465320, 0xc000457450, {0xcad318, 0xc000458690})
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:172 +0x611
cuelang.org/go/internal/core/dep.visit(0xb142a0, 0xc000465468, 0xc0004170a0, 0xa0, 0x70)
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:125 +0x1d1
cuelang.org/go/internal/core/dep.dynamic(0xc00044cbd0, 0xc00044cbd0, 0xc00044cbd0, 0xc23, 0x6)
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/mixed.go:43 +0x1b1
cuelang.org/go/internal/core/dep.VisitFields(0xb140c0, 0xb29ac0, 0x78ecf6f23516943a)
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:91 +0xc5
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies(0xc00034afc0, 0xc00034b0a0, 0xc00044cbd0)
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/tools/flow/tasks.go:224 +0x8d
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies.func1({0xc00044cbd0, {0x7fbc84ee8be0, 0xc0003bfb50}, 0x0})
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/tools/flow/tasks.go:240 +0x16a
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0xc000465770, 0xc0004790e0, {0x7fbc84ee8be0, 0xc0003bfb50})
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:230 +0xe8
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc000465770, 0xc0004790e0, {0xcad458, 0xc0003bfb50})
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:150 +0x4c7
cuelang.org/go/internal/core/dep.visit(0xb142a0, 0xc000465a38, 0xc0003bfb50, 0x20, 0x71)
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:125 +0x1d1
cuelang.org/go/internal/core/dep.dynamic(0xb142a0, 0xc000481320, 0xc000417120, 0xc000417180, 0x70)
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/mixed.go:43 +0x1b1
cuelang.org/go/internal/core/dep.dynamic(0xb142a0, 0xc000480a20, 0xc000417180, 0xc000417180, 0x38)
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/mixed.go:48 +0x205
cuelang.org/go/internal/core/dep.dynamic(0x0, 0xc00044cc60, 0xc00044cc60, 0xc00034b180, 0xc0)
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/mixed.go:48 +0x205
cuelang.org/go/internal/core/dep.VisitFields(0xc00034afc0, 0xc0003bfa20, 0xc00044cb40)
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/internal/core/dep/dep.go:91 +0xc5
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies(0xc00034afc0, 0xc00034b0a0, 0xc00044cb40)
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/tools/flow/tasks.go:224 +0x8d
cuelang.org/go/tools/flow.(*Controller).initTasks(0xc00034afc0)
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/tools/flow/tasks.go:50 +0xf7
cuelang.org/go/tools/flow.New(0xc000465c48, {0xc9ebd8, 0xc000421490}, 0xc000472d40)
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/tools/flow/flow.go:216 +0x197
cuelang.org/go/cmd/cue/cmd.doTasks(0xc000465cf8, {0x5b01d3, 0xc00045c800}, {0xc000410a77, 0x5}, 0x5b3ab0)
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/cmd/cue/cmd/custom.go:132 +0x125
cuelang.org/go/cmd/cue/cmd.addCustom.func1(0x592b31, {0xc00045c800, 0x5b0280, 0xc000465ce0})
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/cmd/cue/cmd/custom.go:116 +0x2d
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc000442580, {0xc000472d10, 0x1, 0x1})
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/cmd/cue/cmd/root.go:46 +0x4d
github.com/spf13/cobra.(*Command).execute(0xc000442580, {0xc000472ce0, 0x1, 0x1})
	/home/marcel/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000343340)
	/home/marcel/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	/home/marcel/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc0004167e0, {0x3, 0xcae910})
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/cmd/cue/cmd/root.go:206 +0x6b
cuelang.org/go/cmd/cue/cmd.mainErr({0xca7590, 0xc00003a0f0}, {0xc000032090, 0xc000078738, 0x4604fb})
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/cmd/cue/cmd/root.go:145 +0x55
cuelang.org/go/cmd/cue/cmd.Main()
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/cmd/cue/cmd/root.go:127 +0x85
main.main()
	/home/marcel/go/pkg/mod/cuelang.org/go@v0.4.0/cmd/cue/main.go:24 +0x19
```

**Comment by myitcv** [comment]
@mheers apologies for the delay in looking at this. Thanks for raising the issue.

Confirmed with 556f57f5 using the smaller repro:

```
exec cue cmd alias

-- alias_tool.cue --
package alias

import (
	"text/template"
	"tool/cli"
)

command: alias: {
	rendered: template.Execute("", x)

	print: cli.Print & {
		text: rendered
	}

}

x: X={
	enabled: bool
	if X.enabled {
	}
}
```

giving a similar stack trace to the above.

**Comment by mpvl** [comment]
Analysis: the `dep` package may create "dummy" `Vertex` values with a `nil`  `BaseValue`. This is not a possible result from normal evaluation, so the task handling assumed this to be non-nil.
