### ISSUE TITLE
cue: unexpected panic in BuildInstances

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#1413]
commit 94db2eb171e7934e5d773d275bfe0d7558333c56

I ran the following testscript:
```
# pull in go.sum
go mod tidy
go run .
-- config/config.cue --
x: true
-- main.go --
package main

import (
	"log"

	"cuelang.org/go/cue/cuecontext"
	"cuelang.org/go/cue/load"
)

func main() {
	ctx := cuecontext.New()
	insts := load.Instances([]string{"."}, &load.Config{
		Dir: "config",
	})
	_, err := ctx.BuildInstances(insts)
	if err != nil {
		log.Fatal(err)
	}
	log.Println("ok")
}
-- go.mod --
module example.com

go 1.18

require cuelang.org/go v0.4.1-beta.6

require (
	github.com/cockroachdb/apd/v2 v2.0.1 // indirect
	github.com/emicklei/proto v1.6.15 // indirect
	github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b // indirect
	github.com/google/uuid v1.2.0 // indirect
	github.com/mpvl/unique v0.0.0-20150818121801-cbe035fff7de // indirect
	github.com/pkg/errors v0.8.1 // indirect
	github.com/protocolbuffers/txtpbfmt v0.0.0-20201118171849-f6a6b3f636fc // indirect
	golang.org/x/net v0.0.0-20200226121028-0de0cce0169b // indirect
	golang.org/x/text v0.3.2 // indirect
	golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543 // indirect
	gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b // indirect
)
```

I see this panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x60c018]

goroutine 1 [running]:
cuelang.org/go/internal/core/adt.(*Vertex).getNodeContext(0xffffffffffffff01?, 0xc000345c68?)
	/home/rogpeppe/src/go/pkg/mod/cuelang.org/go@v0.4.1-beta.6/internal/core/adt/eval.go:911 +0x18
cuelang.org/go/internal/core/adt.(*OpContext).Unify(0xc0004bc340, 0x0, 0x5)
	/home/rogpeppe/src/go/pkg/mod/cuelang.org/go@v0.4.1-beta.6/internal/core/adt/eval.go:172 +0x4e
cuelang.org/go/internal/core/adt.(*Vertex).Finalize(...)
	/home/rogpeppe/src/go/pkg/mod/cuelang.org/go@v0.4.1-beta.6/internal/core/adt/composite.go:453
cuelang.org/go/cue.newVertexRoot(0x40c15d?, 0xc0004bc340?, 0x1823a?)
	/home/rogpeppe/src/go/pkg/mod/cuelang.org/go@v0.4.1-beta.6/cue/types.go:617 +0x69
cuelang.org/go/cue.newValueRoot(0xaada40?, 0xc00029f3c0?, {0xaad9c0?, 0x0?})
	/home/rogpeppe/src/go/pkg/mod/cuelang.org/go@v0.4.1-beta.6/cue/types.go:626 +0x4d
cuelang.org/go/cue.(*Context).make(0xc00029f3c0?, 0x0?)
	/home/rogpeppe/src/go/pkg/mod/cuelang.org/go@v0.4.1-beta.6/cue/context.go:246 +0x57
cuelang.org/go/cue.(*Context).BuildInstances(0xc000345e50?, {0xc000480558, 0x1, 0xc0001f9f70?})
	/home/rogpeppe/src/go/pkg/mod/cuelang.org/go@v0.4.1-beta.6/cue/context.go:147 +0x105
main.main()
	$WORK/main.go:15 +0xff
```

**Comment by rogpeppe** [comment]
The panic doesn't happen if `config.cue` has a package directive.

**Comment by rogpeppe** [comment]
Ah, I've worked out what's going on now. Although `load.Instances` doesn't return an error, the instances inside it can contain errors. I think that `BuildInstances` should at least check the `Err` field before proceeding rather than panicking.

**Comment by bttk** [comment]
Possible fix from #1448

```go
func (c *Context) BuildInstances(instances []*build.Instance) ([]Value, error) {
	var errs errors.Error
	var a []Value
	for _, b := range instances {
		v, err := c.runtime().Build(nil, b)
		if err != nil {
			errs = errors.Append(errs, err)
		}
		// ADD: if v != nil {  
		a = append(a, c.make(v))
		// }
	}
	return a, errs
}
```

**Comment by myitcv** [comment]
This issue also highlights a regression introduced by https://cue-review.googlesource.com/c/cue/+/9423:

```
go mod tidy
go run main.go

-- go.mod --
module mod.com

go 1.16

require cuelang.org/go v0.4.1

-- main.go --
package main

import (
	"fmt"

	"cuelang.org/go/cue"
	"cuelang.org/go/cue/load"
)

func main() {
	bps := load.Instances([]string{"."}, nil)
	is := cue.Build(bps)
	v := is[0].Value()
	fmt.Println(v)
}
-- x.cue --
package p

*
```

With 556f57f5 (tip) we get:

```
> go run main.go
[stderr]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1ff03c]

goroutine 1 [running]:
cuelang.org/go/internal/core/adt.(*Vertex).getNodeContext(0x50?, 0x524000?)
        $WORK/gopath/pkg/mod/cuelang.org/go@v0.4.1/internal/core/adt/eval.go:911 +0x1c
cuelang.org/go/internal/core/adt.(*OpContext).Unify(0x40001b9ee0, 0x0, 0x5)
        $WORK/gopath/pkg/mod/cuelang.org/go@v0.4.1/internal/core/adt/eval.go:172 +0x40
cuelang.org/go/internal/core/adt.(*Vertex).Finalize(...)
        $WORK/gopath/pkg/mod/cuelang.org/go@v0.4.1/internal/core/adt/composite.go:453
cuelang.org/go/cue.(*Instance).Value(0x4000431b90)
        $WORK/gopath/pkg/mod/cuelang.org/go@v0.4.1/cue/instance.go:212 +0x90
main.main()
        $WORK/main.go:13 +0x58
exit status 2

[exit status 1]
FAIL: /tmp/testscript2026214946/repro.txt/script.txt:2: unexpected go command failure
error running repro.txt in /tmp/testscript2026214946/repro.txt
```

whereas with `v0.4.0-alpha.1` we get:

```
_|_ // expected operand, found 'EOF'
```

To my mind we should always return `len([]Value) == len([]*BuildInstance)`, with errors attached to those `Value`'s where necessary, with the `error` returned by `BuildInstances` effectively a convenience that represents the "combined" error value from each `[]Value` element. 

But very much defer to @mpvl.

**Comment by mpvl** [comment]
Fixed by [https://review.gerrithub.io/c/cue-lang/cue/+/532990]()
