### ISSUE TITLE
Context.BuildInstances([]*.build.Instance) crashes instead of returning syntax error

### ISSUE THREAD

**Issue by bttk** [cue-lang/cue#1448]
### What version of CUE are you using (`cue version`)?

<pre>
v0.4.1-beta.6
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

```go
ctx := cuecontext.New()
cfg := load.Config{}
insts := load.Instances([]string{"file.cue"}, &cfg)
built, err := ctx.BuildInstances(insts)  // syntax error in file.cue causes segfault here:
if err != nil {
    return xerrors.Errorf("cannot parse schema: %w", err)
}
```

Possible fix:
```go
func (c *Context) BuildInstances(instances []*build.Instance) ([]Value, error) {
	var errs errors.Error
	var a []Value
	for _, b := range instances {
		v, err := c.runtime().Build(nil, b)
		if err != nil {
			errs = errors.Append(errs, err)
		}
		// ADD: if v != nil {  
		a = append(a, c.make(v))
		// }
	}
	return a, errs
}
```

### What did you expect to see?

```
cannot parse schema:
- missing ',' in struct literal
```

### What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x686938]

goroutine 8 [running]:
testing.tRunner.func1.2({0x9d17e0, 0xea7520})
        go1.18beta1/src/testing/testing.go:1360 +0x24e
testing.tRunner.func1()
        go1.18beta1/src/testing/testing.go:1363 +0x39f
panic({0x9d17e0, 0xea7520})
        go1.18beta1/src/runtime/panic.go:838 +0x207
cuelang.org/go/internal/core/adt.(*Vertex).getNodeContext(0xc000336a80?, 0x1?)
        src/cue/internal/core/adt/eval.go:911 +0x18
cuelang.org/go/internal/core/adt.(*OpContext).Unify(0xc0003501a0, 0x0, 0x5)
        src/cue/internal/core/adt/eval.go:172 +0x4e
cuelang.org/go/internal/core/adt.(*Vertex).Finalize(...)
        src/cue/internal/core/adt/composite.go:453
cuelang.org/go/cue.newVertexRoot(0x0?, 0xc0003501a0?, 0x0?)
        src/cue/cue/types.go:617 +0x69
cuelang.org/go/cue.newValueRoot(0xb4d838?, 0xc0002bbb80?, {0xb4d7b8?, 0x0?})
        src/cue/cue/types.go:626 +0x4d
cuelang.org/go/cue.(*Context).make(0xc0002bbb80?, 0x0?)
        src/cue/cue/context.go:246 +0x57
cuelang.org/go/cue.(*Context).BuildInstances(0xb48640?, {0xc000329560, 0x1, 0x4?})
        src/cue/cue/context.go:147 +0x105
bttk.dev/finance/tools/cuesv.loadSchema(0xc0000c7d70)
        example.go:142 +0x227
```

**Comment by bttk** [comment]
This is a duplicate of #1413
