### ISSUE TITLE
Segfault during BuildInstances

### ISSUE THREAD

**Issue by n0izn0iz** [cue-lang/cue#1486]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.4.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

- [monolith.cue](https://gist.github.com/n0izn0iz/44eafc0125d634ae9f5adb42a066f27a)
- main.go
```golang
package main

import (
	"cuelang.org/go/cue/cuecontext"
	"cuelang.org/go/cue/load"
)

func main() {
	cctx := cuecontext.New()
	loadedInstances := load.Instances([]string{"monolith.cue"}, nil)
	cctx.BuildInstances(loadedInstances)
}
```

### What did you expect to see?

no crash

### What did you see instead?

```
❯ go run main.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1204818]

goroutine 1 [running]:
cuelang.org/go/internal/core/adt.(*Vertex).getNodeContext(0x6, 0x5)
	/Users/norman/go/pkg/mod/cuelang.org/go@v0.4.1/internal/core/adt/eval.go:911 +0x18
cuelang.org/go/internal/core/adt.(*OpContext).Unify(0xc0002af860, 0x0, 0x5)
	/Users/norman/go/pkg/mod/cuelang.org/go@v0.4.1/internal/core/adt/eval.go:172 +0x4e
cuelang.org/go/internal/core/adt.(*Vertex).Finalize(...)
	/Users/norman/go/pkg/mod/cuelang.org/go@v0.4.1/internal/core/adt/composite.go:453
cuelang.org/go/cue.newVertexRoot(0x1c00a68, 0xc0002af860, 0x19d42e0)
	/Users/norman/go/pkg/mod/cuelang.org/go@v0.4.1/cue/types.go:617 +0x69
cuelang.org/go/cue.newValueRoot(0x165b058, 0xc0002db9c0, {0x165afd8, 0x0})
	/Users/norman/go/pkg/mod/cuelang.org/go@v0.4.1/cue/types.go:626 +0x4d
cuelang.org/go/cue.(*Context).make(0xc0002db9c0, 0x0)
	/Users/norman/go/pkg/mod/cuelang.org/go@v0.4.1/cue/context.go:246 +0x57
cuelang.org/go/cue.(*Context).BuildInstances(0xc000297f60, {0xc000462678, 0x1, 0x0})
	/Users/norman/go/pkg/mod/cuelang.org/go@v0.4.1/cue/context.go:147 +0x105
main.main()
	/Users/norman/Code/cue-tests/main.go:11 +0xb8
exit status 2
```

**Comment by n0izn0iz** [comment]
Sorry meant to open it in cuelang/go

**Comment by n0izn0iz** [comment]
Actually seems to be the good repo, if I need to move it, tell me

**Comment by a-palchikov** [comment]
Looks like BuildInstances is missing `continue` [here](https://github.com/cue-lang/cue/blob/f29b460e31ea6b68369028fc0e015d6032586d4e/cue/context.go#L145):
```go
func (c *Context) BuildInstances(instances []*build.Instance) ([]Value, error) {
	var errs errors.Error
	var a []Value
	for _, b := range instances {
		v, err := c.runtime().Build(nil, b)
		if err != nil {
			errs = errors.Append(errs, err)
			continue // <= here
		}
		a = append(a, c.make(v))
	}
	return a, errs
}
```

**Comment by myitcv** [comment]
Thanks - this is a dup of #1413.
