### ISSUE TITLE
evaluator: index out of range panic

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1686]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +c942d0af linux/arm64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

Not attempted to reduce this yet:

```
exec cue eval x.cue

-- x.cue --
#Command: {
	args: {
		restore: _
	}

	valid: bool

	if valid {
		args: valid: _
	}

	argsList
}

args: restore: _

if true {
	args: "-ok": _
}

argsList: [ for k, _ in args {k}]
```

### What did you expect to see?

No panic.

### What did you see instead?

```
> exec cue eval x.cue
[stderr]
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0x4000595e70)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:229 +0x98
panic({0x729ee0, 0x40001585a0})
        /home/myitcv/gos/src/runtime/panic.go:838 +0x20c
cuelang.org/go/internal/core/adt.(*nodeContext).injectComprehensions(0x400070e380, 0x400070e5b0)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/comprehension.go:44 +0x414
cuelang.org/go/internal/core/adt.(*nodeContext).expandOne(0x400070e380)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/eval.go:1917 +0x6c
cuelang.org/go/internal/core/adt.(*nodeContext).postDisjunct(0x400070e380, 0x5)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/eval.go:447 +0x108
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0x400070e380, 0x40?, 0x400070e380, 0x0, 0x0, 0x1)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/disjunct.go:151 +0x2f8
cuelang.org/go/internal/core/adt.(*OpContext).Unify(0x40000a5ba0, 0x4000426510, 0x5)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/eval.go:298 +0x7e4
cuelang.org/go/internal/core/adt.(*nodeContext).completeArcs(0x4000599c00, 0x5)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/eval.go:674 +0x380
cuelang.org/go/internal/core/adt.(*nodeContext).postDisjunct(0x4000599c00, 0x5)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/eval.go:582 +0x728
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0x4000599c00, 0x78?, 0x4000599c00, 0x0, 0x0, 0x1)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/disjunct.go:151 +0x2f8
cuelang.org/go/internal/core/adt.(*OpContext).Unify(0x40000a5ba0, 0x4000420240, 0x5)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/eval.go:298 +0x7e4
cuelang.org/go/internal/core/adt.(*Vertex).Finalize(...)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/composite.go:454
cuelang.org/go/cue.newVertexRoot(0xffff80642968?, 0x40000a5ba0?, 0xb0?)
        /home/myitcv/dev/cuelang/cue/cue/types.go:624 +0x7c
cuelang.org/go/cue.newValueRoot(0x8a2ca8?, 0x4000350f90?, {0x8a2c28?, 0x4000420240?})
        /home/myitcv/dev/cuelang/cue/cue/types.go:633 +0x44
cuelang.org/go/cue.(*Context).make(0x4000350f90?, 0x0?)
        /home/myitcv/dev/cuelang/cue/cue/context.go:248 +0x64
cuelang.org/go/cue.(*Context).BuildInstances(0x4000595748?, {0x4000595900, 0x1, 0x1e0?})
        /home/myitcv/dev/cuelang/cue/cue/context.go:148 +0x1a4
cuelang.org/go/cmd/cue/cmd.buildInstances(0x40003a6ea0, {0x4000595900, 0x1, 0x1a7750?}, 0x1)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/common.go:733 +0x38
cuelang.org/go/cmd/cue/cmd.parseArgs(0x40003a6ea0, {0x40003514d0, 0x1, 0x1}, 0x40003b6870)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/common.go:629 +0xe70
cuelang.org/go/cmd/cue/cmd.runEval(0x40003a6ea0, {0x40003514d0, 0x1, 0x1})
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/eval.go:88 +0x6c
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0x40003b8c80?, {0x40003514d0?, 0x1?, 0x1?})
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:48 +0x70
github.com/spf13/cobra.(*Command).execute(0x40003b8c80, {0x40003514a0, 0x1, 0x1})
        /home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x4dc
github.com/spf13/cobra.(*Command).ExecuteC(0x40003b8500)
        /home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x360
github.com/spf13/cobra.(*Command).Execute(...)
        /home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0x40003a6ea0, {0x2?, 0x2?})
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:214 +0x60
cuelang.org/go/cmd/cue/cmd.mainErr({0x8a1248, 0x400003a0a0}, {0x40000320a0?, 0x40000021a0?, 0x4000075f28?})
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:151 +0x5c
cuelang.org/go/cmd/cue/cmd.Main()
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:133 +0x8c
main.main()
        /home/myitcv/dev/cuelang/cue/cmd/cue/main.go:24 +0x20
[exit status 2]
FAIL: /tmp/testscript768271708/repro.txt/script.txt:1: unexpected command failure
```

**Comment by benmoss** [comment]
Smaller repro:
```
#Command: {
    valid: bool

    if valid {
    ▏   args: valid: _
    }

    []
}
```

**Comment by benmoss** [comment]
Fixed by https://review.gerrithub.io/c/cue-lang/cue/+/537831/1

**Comment by myitcv** [comment]
Thanks @benmoss - this actually appears to be fixed by a change earlier in the stack: https://review.gerrithub.io/c/cue-lang/cue/+/529524

**Comment by myitcv** [comment]
Fixed in https://github.com/cue-lang/cue/commit/748a68589747fed6273d6338eb7e275a4fb116c6
