### ISSUE TITLE
0.0.14 segfault on definition with "ending" aliasing

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#172]
_Originally opened by @jjo in https://github.com/cuelang/cue/issues/172_

While exploring CUE patterns ab-using aliasing, found below incorrect snippet:
```
// testenv.cue
package testenv
env_:: [NAME=_]: [VALUE=_]
env_:: foo: "bar"
```
... to segfault cue-v0.0.14 (e.g. on `eval` or `export`)
```
$ cue eval testenv.cue
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x7733b9]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc00025beb0)
	/Users/mpvl/dev/release/cue/cmd/cue/cmd/root.go:211 +0xa3
panic(0xb43660, 0x11dbe10)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
cuelang.org/go/cue.rewrite(0xc000252b00, 0x0, 0x0, 0xc461d8, 0x0, 0x203000)
	/Users/mpvl/dev/release/cue/cue/rewrite.go:30 +0x59
cuelang.org/go/cue.(*context).copy(...)
	/Users/mpvl/dev/release/cue/cue/copy.go:19
cuelang.org/go/cue.rewriteCopy(0xc000252b00, 0xd2e0c0, 0xc0002750a0, 0x0, 0x0, 0xc00025ac00)
	/Users/mpvl/dev/release/cue/cue/copy.go:52 +0x8fe
cuelang.org/go/cue.rewrite(0xc000252b00, 0xd2e0c0, 0xc0002750a0, 0xc461d8, 0xc000133980, 0x2)
	/Users/mpvl/dev/release/cue/cue/rewrite.go:26 +0x48
cuelang.org/go/cue.(*list).rewrite(0xc000276f40, 0xc000252b00, 0xc461d8, 0xd2dd00, 0xc000276f40)
	/Users/mpvl/dev/release/cue/cue/rewrite.go:130 +0x53
cuelang.org/go/cue.rewrite(0xc000252b00, 0xd2dd00, 0xc000276f40, 0xc461d8, 0xc000252b00, 0xc000251e20)
	/Users/mpvl/dev/release/cue/cue/rewrite.go:30 +0x77
cuelang.org/go/cue.(*context).copy(...)
	/Users/mpvl/dev/release/cue/cue/copy.go:19
cuelang.org/go/cue.rewriteCopy(0xc000252b00, 0xd2dca0, 0xc00028f230, 0x0, 0x0, 0x0)
	/Users/mpvl/dev/release/cue/cue/copy.go:71 +0x429
cuelang.org/go/cue.rewrite(0xc000252b00, 0xd2dca0, 0xc00028f230, 0xc461d8, 0xc00028f230, 0x0)
	/Users/mpvl/dev/release/cue/cue/rewrite.go:26 +0x48
cuelang.org/go/cue.(*context).copy(...)
	/Users/mpvl/dev/release/cue/cue/copy.go:19
cuelang.org/go/cue.(*structLit).rewriteOpt.func1(0xd2dca0, 0xc00028f230, 0x1, 0xc000251e60)
	/Users/mpvl/dev/release/cue/cue/binop.go:736 +0x69
cuelang.org/go/cue.(*optionals).rewrite(0xc00028f260, 0xc00025af50, 0x8, 0x4, 0x0)
	/Users/mpvl/dev/release/cue/cue/value.go:890 +0x16e
cuelang.org/go/cue.(*structLit).rewriteOpt(0xc000275030, 0xc000252b00, 0xc000277180, 0x4, 0x4)
	/Users/mpvl/dev/release/cue/cue/binop.go:738 +0x69
cuelang.org/go/cue.unifyOptionals(0xc000252b00, 0xd26ac0, 0xc0002770c0, 0x1, 0xc000275030, 0xc000275110, 0xc00003a0c4, 0x34, 0x203000)
	/Users/mpvl/dev/release/cue/cue/binop.go:749 +0x47
cuelang.org/go/cue.(*structLit).binOp(0xc000275030, 0xc000252b00, 0xd26ac0, 0xc0002770c0, 0xc000270001, 0xd30b60, 0xc000275110, 0x0, 0x0)
	/Users/mpvl/dev/release/cue/cue/binop.go:639 +0x524
cuelang.org/go/cue.binOp(0xc000252b00, 0xd26ac0, 0xc0002770c0, 0xc000270001, 0xd30b60, 0xc000275030, 0xd30b60, 0xc000275110, 0xa0, 0xa0)
	/Users/mpvl/dev/release/cue/cue/binop.go:123 +0x484
cuelang.org/go/cue.(*binaryExpr).evalPartial(0xc0002770c0, 0xc000252b00, 0x0, 0x0)
	/Users/mpvl/dev/release/cue/cue/eval.go:467 +0x378
cuelang.org/go/cue.(*structLit).at(0xc000274fc0, 0xc000252b00, 0x0, 0xc0002770c0, 0x0)
	/Users/mpvl/dev/release/cue/cue/value.go:1028 +0x328
cuelang.org/go/cue.newChildValue(0xc00025b928, 0x0, 0xc000274fc0, 0xc00025b890)
	/Users/mpvl/dev/release/cue/cue/types.go:610 +0x9d
cuelang.org/go/cue.(*structValue).At(0xc00025b928, 0x0, 0xc000252b00, 0x10000000000, 0xc000252b00, 0xc00028d4f0)
	/Users/mpvl/dev/release/cue/cue/types.go:152 +0x8e
cuelang.org/go/cue.(*validator).walk(0xc00025b9d8, 0xc000133880, 0xc00028d4f0, 0x10000000000)
	/Users/mpvl/dev/release/cue/cue/types.go:1620 +0x31c
cuelang.org/go/cue.Value.Validate(0xc000133880, 0xc00028d4f0, 0x0, 0x0, 0x0, 0x1, 0x68)
	/Users/mpvl/dev/release/cue/cue/types.go:1571 +0xb9
cuelang.org/go/cmd/cue/cmd.buildInstances(0xc000251880, 0xc0000ad8f0, 0x1, 0x1, 0xc0000ad8f0, 0x1, 0x1)
	/Users/mpvl/dev/release/cue/cmd/cue/cmd/common.go:135 +0x152
cuelang.org/go/cmd/cue/cmd.buildFromArgs(0xc000251880, 0xc00023bcf0, 0x1, 0x1, 0xc00025bba8, 0x7f0f8b, 0xb2ed00)
	/Users/mpvl/dev/release/cue/cmd/cue/cmd/common.go:105 +0x8b
cuelang.org/go/cmd/cue/cmd.runEval(0xc000251880, 0xc00023bcf0, 0x1, 0x1, 0x0, 0x0)
	/Users/mpvl/dev/release/cue/cmd/cue/cmd/eval.go:82 +0x6a
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc000292a00, 0xc00023bcf0, 0x1, 0x1, 0x0, 0x0)
	/Users/mpvl/dev/release/cue/cmd/cue/cmd/root.go:46 +0x5f
github.com/spf13/cobra.(*Command).execute(0xc000292a00, 0xc00023bcc0, 0x1, 0x1, 0xc000292a00, 0xc00023bcc0)
	/Users/mpvl/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000292500, 0x0, 0xc000251b20, 0x0)
	/Users/mpvl/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/mpvl/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc000251880, 0xd26940, 0xc0000ea020, 0x0, 0x0)
	/Users/mpvl/dev/release/cue/cmd/cue/cmd/root.go:196 +0x75
cuelang.org/go/cmd/cue/cmd.mainErr(0xd26940, 0xc0000ea020, 0xc0000be010, 0x2, 0x2, 0x1189240, 0xc00005a750)
	/Users/mpvl/dev/release/cue/cmd/cue/cmd/root.go:131 +0x74
cuelang.org/go/cmd/cue/cmd.Main(0xc0000a6058)
	/Users/mpvl/dev/release/cue/cmd/cue/cmd/root.go:116 +0x84
main.main()
	/Users/mpvl/dev/release/cue/cmd/cue/main.go:24 +0x22
```
Fwiw / for completeness, below works ok (although it doesn't read naturally):
```
package testenv

env_:: [NAME=_]: [VALUE=_]: { name: NAME, value: VALUE }
env_:: foo: bar: {}
env: [v for _, v in env_]
```

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/172#issuecomment-553426511_

I was not able to reproduce this on my machine. Are there other files belonging to the package that are necessary to reproduce the issue?

**Comment by cueckoo** [comment]
_Original reply by @jjo in https://github.com/cuelang/cue/issues/172#issuecomment-553517812_

intresting, I'm able to repro from a fresh folder:
```
$ mkdir /tmp/new
$ cd /tmp/new
$ echo $'package testenv\nenv_:: [NAME=_]: [VALUE=_]\nenv_:: foo: "bar"\n' > /tmp/new/foo.cue
$ cue eval foo.cue
<segfault...>
$ cue version
cue version 0.0.14 linux/amd64
$ uname -a
Linux jjo-x270 4.18.0-24-generic #25~18.04.1-Ubuntu SMP Thu Jun 20 11:13:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
```

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/172#issuecomment-554661874_

Thanks. Not sure what was different before, but that reproduces it.

**Comment by cueckoo** [comment]
_Original reply by @xinau in https://github.com/cuelang/cue/issues/172#issuecomment-556969484_

On my machine I yield the following results.
The cue file from the issue discription works for both v0.0.14 and master
```
package testenv

env_:: [NAME=_]: [VALUE=_]: { name: NAME, value: VALUE }
env_:: foo: bar: {}
env: [v for _, v in env_]
```

the cue file generated by @jjo 's comand yields the following errors
```
package testenv
env_:: [NAME=_]: [VALUE=_]
env_:: foo: "bar"
```
on master
```
env_.*: alias not allowed in list:
    ./foo.cue:2:18
```
on v0.0.14
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x7733b9]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc000229eb0)
	/Users/mpvl/dev/release/cue/cmd/cue/cmd/root.go:211 +0xa3
panic(0xb43660, 0x11dbe10)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
cuelang.org/go/cue.rewrite(0xc000212dc0, 0x0, 0x0, 0xc461d8, 0x0, 0x203000)
	/Users/mpvl/dev/release/cue/cue/rewrite.go:30 +0x59
cuelang.org/go/cue.(*context).copy(...)
	/Users/mpvl/dev/release/cue/cue/copy.go:19
cuelang.org/go/cue.rewriteCopy(0xc000212dc0, 0xd2e0c0, 0xc0002430a0, 0x0, 0x0, 0xc000228c00)
	/Users/mpvl/dev/release/cue/cue/copy.go:52 +0x8fe
cuelang.org/go/cue.rewrite(0xc000212dc0, 0xd2e0c0, 0xc0002430a0, 0xc461d8, 0xc000107980, 0x2)
	/Users/mpvl/dev/release/cue/cue/rewrite.go:26 +0x48
cuelang.org/go/cue.(*list).rewrite(0xc000244fc0, 0xc000212dc0, 0xc461d8, 0xd2dd00, 0xc000244fc0)
	/Users/mpvl/dev/release/cue/cue/rewrite.go:130 +0x53
cuelang.org/go/cue.rewrite(0xc000212dc0, 0xd2dd00, 0xc000244fc0, 0xc461d8, 0xc000212dc0, 0xc000219e60)
	/Users/mpvl/dev/release/cue/cue/rewrite.go:30 +0x77
cuelang.org/go/cue.(*context).copy(...)
	/Users/mpvl/dev/release/cue/cue/copy.go:19
cuelang.org/go/cue.rewriteCopy(0xc000212dc0, 0xd2dca0, 0xc00025d200, 0x0, 0x0, 0x0)
	/Users/mpvl/dev/release/cue/cue/copy.go:71 +0x429
cuelang.org/go/cue.rewrite(0xc000212dc0, 0xd2dca0, 0xc00025d200, 0xc461d8, 0xc00025d200, 0x0)
	/Users/mpvl/dev/release/cue/cue/rewrite.go:26 +0x48
cuelang.org/go/cue.(*context).copy(...)
	/Users/mpvl/dev/release/cue/cue/copy.go:19
cuelang.org/go/cue.(*structLit).rewriteOpt.func1(0xd2dca0, 0xc00025d200, 0x1, 0xc000219ea0)
	/Users/mpvl/dev/release/cue/cue/binop.go:736 +0x69
cuelang.org/go/cue.(*optionals).rewrite(0xc00025d230, 0xc000228f50, 0x8, 0x4, 0x0)
	/Users/mpvl/dev/release/cue/cue/value.go:890 +0x16e
cuelang.org/go/cue.(*structLit).rewriteOpt(0xc000243030, 0xc000212dc0, 0xc000245200, 0x4, 0x4)
	/Users/mpvl/dev/release/cue/cue/binop.go:738 +0x69
cuelang.org/go/cue.unifyOptionals(0xc000212dc0, 0xd26ac0, 0xc000245140, 0x1, 0xc000243030, 0xc000243110, 0xc000036004, 0x23, 0x203000)
	/Users/mpvl/dev/release/cue/cue/binop.go:749 +0x47
cuelang.org/go/cue.(*structLit).binOp(0xc000243030, 0xc000212dc0, 0xd26ac0, 0xc000245140, 0xc000240001, 0xd30b60, 0xc000243110, 0x0, 0x0)
	/Users/mpvl/dev/release/cue/cue/binop.go:639 +0x524
cuelang.org/go/cue.binOp(0xc000212dc0, 0xd26ac0, 0xc000245140, 0xc000240001, 0xd30b60, 0xc000243030, 0xd30b60, 0xc000243110, 0xa0, 0xa0)
	/Users/mpvl/dev/release/cue/cue/binop.go:123 +0x484
cuelang.org/go/cue.(*binaryExpr).evalPartial(0xc000245140, 0xc000212dc0, 0x0, 0x0)
	/Users/mpvl/dev/release/cue/cue/eval.go:467 +0x378
cuelang.org/go/cue.(*structLit).at(0xc000242fc0, 0xc000212dc0, 0x0, 0xc000245140, 0x0)
	/Users/mpvl/dev/release/cue/cue/value.go:1028 +0x328
cuelang.org/go/cue.newChildValue(0xc000229928, 0x0, 0xc000242fc0, 0xc000229890)
	/Users/mpvl/dev/release/cue/cue/types.go:610 +0x9d
cuelang.org/go/cue.(*structValue).At(0xc000229928, 0x0, 0xc000212dc0, 0x10000000000, 0xc000212dc0, 0xc00025b4f0)
	/Users/mpvl/dev/release/cue/cue/types.go:152 +0x8e
cuelang.org/go/cue.(*validator).walk(0xc0002299d8, 0xc000107880, 0xc00025b4f0, 0x10000000000)
	/Users/mpvl/dev/release/cue/cue/types.go:1620 +0x31c
cuelang.org/go/cue.Value.Validate(0xc000107880, 0xc00025b4f0, 0x0, 0x0, 0x0, 0x1, 0x68)
	/Users/mpvl/dev/release/cue/cue/types.go:1571 +0xb9
cuelang.org/go/cmd/cue/cmd.buildInstances(0xc000219920, 0xc00000f8e8, 0x1, 0x1, 0xc00000f8e8, 0x1, 0x1)
	/Users/mpvl/dev/release/cue/cmd/cue/cmd/common.go:135 +0x152
cuelang.org/go/cmd/cue/cmd.buildFromArgs(0xc000219920, 0xc0001f1e80, 0x1, 0x1, 0xc000229ba8, 0x7f0f8b, 0xb2ed00)
	/Users/mpvl/dev/release/cue/cmd/cue/cmd/common.go:105 +0x8b
cuelang.org/go/cmd/cue/cmd.runEval(0xc000219920, 0xc0001f1e80, 0x1, 0x1, 0x0, 0x0)
	/Users/mpvl/dev/release/cue/cmd/cue/cmd/eval.go:82 +0x6a
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc000260a00, 0xc0001f1e80, 0x1, 0x1, 0x0, 0x0)
	/Users/mpvl/dev/release/cue/cmd/cue/cmd/root.go:46 +0x5f
github.com/spf13/cobra.(*Command).execute(0xc000260a00, 0xc0001f1e50, 0x1, 0x1, 0xc000260a00, 0xc0001f1e50)
	/Users/mpvl/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000260500, 0x0, 0xc000219bc0, 0x0)
	/Users/mpvl/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/mpvl/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc000219920, 0xd26940, 0xc000038048, 0x0, 0x0)
	/Users/mpvl/dev/release/cue/cmd/cue/cmd/root.go:196 +0x75
cuelang.org/go/cmd/cue/cmd.mainErr(0xd26940, 0xc000038048, 0xc0000300a0, 0x2, 0x2, 0x1189240, 0xc000060750)
	/Users/mpvl/dev/release/cue/cmd/cue/cmd/root.go:131 +0x74
cuelang.org/go/cmd/cue/cmd.Main(0xc00009e058)
	/Users/mpvl/dev/release/cue/cmd/cue/cmd/root.go:116 +0x84
main.main()
	/Users/mpvl/dev/release/cue/cmd/cue/main.go:24 +0x22
```


```
$ uname -a
Linux 1105fd1eae9d 5.2.0-3-amd64 #1 SMP Debian 5.2.17-1 (2019-09-26) x86_64 GNU/Linux
```

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/172#issuecomment-558427085_

I see that I fixed it and forgot to reference this Issue. Sorry about that. Closing
