### ISSUE TITLE
Crash when using byte strings in an import statement

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#174]
_Originally opened by @refi64 in https://github.com/cuelang/cue/issues/174_

I basically did this by accident but turns out it crashes Cue.

Example file:

```cue
import 'xyz'
```

Results:

```
2019/11/14 17:00:48 /home/ryan/code/q8s/demo.cue: parser returned invalid quoted string: <'xyz'>
panic: /home/ryan/code/q8s/demo.cue: parser returned invalid quoted string: <'xyz'> [recovered]
	panic: /home/ryan/code/q8s/demo.cue: parser returned invalid quoted string: <'xyz'>

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc000239eb0)
	/home/ryan/go/src/cuelang.org/go/cmd/cue/cmd/root.go:211 +0xa3
panic(0xb28780, 0xc000209f90)
	/usr/lib/golang/src/runtime/panic.go:679 +0x1b2
log.Panicf(0xc51c01, 0x2f, 0xc000238d08, 0x2, 0x2)
	/usr/lib/golang/src/log/log.go:345 +0xc0
cuelang.org/go/cue/load.(*fileProcessor).add(0xc0002391c0, 0x0, 0x0, 0xc000038244, 0x13, 0x7fffdba2db8d, 0x8, 0x4, 0x0)
	/home/ryan/go/src/cuelang.org/go/cue/load/import.go:399 +0x90e
cuelang.org/go/cue/load.(*loader).cueFilesPackage(0xc000231c60, 0xc000209e70, 0x1, 0x1, 0xc0001d0f28)
	/home/ryan/go/src/cuelang.org/go/cue/load/loader.go:134 +0x44d
cuelang.org/go/cue/load.Instances(0xc000209e70, 0x1, 0x1, 0x1232dc0, 0x6, 0x90000c000239ad8, 0x4db7e9)
	/home/ryan/go/src/cuelang.org/go/cue/load/loader.go:55 +0x42f
cuelang.org/go/cmd/cue/cmd.loadFromArgs(...)
	/home/ryan/go/src/cuelang.org/go/cmd/cue/cmd/common.go:109
cuelang.org/go/cmd/cue/cmd.buildFromArgs(0xc0002318c0, 0xc000209e70, 0x1, 0x1, 0xc000239ba0, 0x7f8e6b, 0xb50640)
	/home/ryan/go/src/cuelang.org/go/cmd/cue/cmd/common.go:101 +0x4f
cuelang.org/go/cmd/cue/cmd.runEval(0xc0002318c0, 0xc000209e70, 0x1, 0x1, 0x0, 0x0)
	/home/ryan/go/src/cuelang.org/go/cmd/cue/cmd/eval.go:82 +0x6a
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc000270a00, 0xc000209e70, 0x1, 0x1, 0x0, 0x0)
	/home/ryan/go/src/cuelang.org/go/cmd/cue/cmd/root.go:46 +0x5f
github.com/spf13/cobra.(*Command).execute(0xc000270a00, 0xc000209e40, 0x1, 0x1, 0xc000270a00, 0xc000209e40)
	/home/ryan/go/src/github.com/spf13/cobra/command.go:829 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000270500, 0x0, 0xc000231b60, 0x0)
	/home/ryan/go/src/github.com/spf13/cobra/command.go:917 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/ryan/go/src/github.com/spf13/cobra/command.go:867
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc0002318c0, 0xd50a00, 0xc00003c0e8, 0x0, 0x0)
	/home/ryan/go/src/cuelang.org/go/cmd/cue/cmd/root.go:196 +0x75
cuelang.org/go/cmd/cue/cmd.mainErr(0xd50a00, 0xc00003c0e8, 0xc0000320a0, 0x2, 0x2, 0x11ca420, 0xc000000180)
	/home/ryan/go/src/cuelang.org/go/cmd/cue/cmd/root.go:131 +0x74
cuelang.org/go/cmd/cue/cmd.Main(0xc0000480b8)
	/home/ryan/go/src/cuelang.org/go/cmd/cue/cmd/root.go:116 +0x84
main.main()
	/home/ryan/go/src/cuelang.org/go/cmd/cue/main.go:24 +0x22
```

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/174#issuecomment-670923675_

See https://github.com/cuelang/cue/blob/master/cmd/cue/cmd/testdata/script/issue174.txt
