### ISSUE TITLE
evaluator: nil pointer in *core/adt.Environment.evalCached / Let issue

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1828]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
v0.4.4-0.20220729051708-0a46a1624353
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
exec cue eval x.cue

-- x.cue --
volumes: L3

//cue:path: l3
let L3 = [ for v2 in [ for v1 in L2 {
	v1
}] {
	v2
}]

//cue:path: l2
let L2 = L1

//cue:path: l1
let L1 = [ for v in PARAMETER.pvc {}]

//cue:path: parameter
let PARAMETER = _
```

### What did you expect to see?

Passing test.

### What did you see instead?

```
> exec cue eval x.cue
[stderr]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x25c4b8]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0x40002b9e70)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:221 +0x98
panic({0x6bf4e0, 0xcc9640})
        /home/myitcv/gos/src/runtime/panic.go:838 +0x20c
cuelang.org/go/internal/core/adt.(*Environment).evalCached(0x0, 0x40000aa270, {0x89e750, 0x400007a2e0})
        /home/myitcv/dev/cuelang/cue/internal/core/adt/composite.go:136 +0x58
cuelang.org/go/internal/core/adt.(*LetReference).evaluate(0x40002b56f8?, 0x89e710?)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/expr.go:865 +0x48
cuelang.org/go/internal/core/adt.(*OpContext).evalState(0x40000aa270, {0x89e710, 0x400007a340}, 0x2)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/context.go:608 +0x224
cuelang.org/go/internal/core/adt.(*Environment).evalCached(0x40000bc730, 0x40000aa270, {0x89e710, 0x400007a340})
        /home/myitcv/dev/cuelang/cue/internal/core/adt/composite.go:143 +0x174
cuelang.org/go/internal/core/adt.(*LetReference).evaluate(0x0?, 0x89e710?)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/expr.go:865 +0x48
cuelang.org/go/internal/core/adt.(*OpContext).unifyNode(0x40000aa270, {0x89e710, 0x400007a360}, 0x3)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/context.go:680 +0x270
cuelang.org/go/internal/core/adt.(*OpContext).node(0x40000aa270, {0x899310?, 0x4000032900}, {0x89e710?, 0x400007a360?}, 0x1, 0x0?)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/context.go:873 +0x50
cuelang.org/go/internal/core/adt.(*ForClause).yield(0x4000032900, 0x40000aa270, 0x40000021a0?)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/expr.go:1614 +0x58
cuelang.org/go/internal/core/adt.(*OpContext).Yield(0x40000aa270, 0x40000bc7d0, {0x89b8a8, 0x4000032900}, 0x0?)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/context.go:434 +0x12c
cuelang.org/go/internal/core/adt.(*nodeContext).addLists(0x40000cca80)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/eval.go:2056 +0x16fc
cuelang.org/go/internal/core/adt.(*nodeContext).postDisjunct(0x40000cca80, 0x5)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/eval.go:433 +0xfc
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0x40000cca80, 0xac?, 0x40000cca80, 0x0, 0x0, 0x1)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/disjunct.go:151 +0x2f0
cuelang.org/go/internal/core/adt.(*OpContext).Unify(0x40000aa270, 0x40000b4630, 0x5)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/eval.go:281 +0x878
cuelang.org/go/internal/core/adt.(*ListLit).evaluate(0x400007a2c0, 0x40000aa270)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/expr.go:296 +0xfc
cuelang.org/go/internal/core/adt.(*OpContext).unifyNode(0x40000aa270, {0x89e750, 0x400007a2c0}, 0x3)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/context.go:680 +0x270
cuelang.org/go/internal/core/adt.(*OpContext).node(0x40000aa270, {0x899310?, 0x4000032930}, {0x89e750?, 0x400007a2c0?}, 0x1, 0x75?)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/context.go:873 +0x50
cuelang.org/go/internal/core/adt.(*ForClause).yield(0x4000032930, 0x40000aa270, 0x40000021a0?)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/expr.go:1614 +0x58
cuelang.org/go/internal/core/adt.(*OpContext).Yield(0x40000aa270, 0x40000bc780, {0x89b8a8, 0x4000032930}, 0x0?)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/context.go:434 +0x12c
cuelang.org/go/internal/core/adt.(*nodeContext).addLists(0x40000cc700)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/eval.go:2056 +0x16fc
cuelang.org/go/internal/core/adt.(*nodeContext).postDisjunct(0x40000cc700, 0x3)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/eval.go:433 +0xfc
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0x40000cc700, 0xb0?, 0x40000cc700, 0x0, 0x0, 0x1)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/disjunct.go:151 +0x2f0
cuelang.org/go/internal/core/adt.(*OpContext).Unify(0x40000aa270, 0x40000b45a0, 0x3)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/eval.go:281 +0x878
cuelang.org/go/internal/core/adt.(*nodeContext).addVertexConjuncts(0x40000cc380, 0x40000bc730, {0x0?, 0x0?, 0xa4?}, {0x89e710?, 0x400007a400?}, 0x40000b45a0, 0x0)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/eval.go:1387 +0x398
cuelang.org/go/internal/core/adt.(*nodeContext).evalExpr(0x40000cc380, {0x40000bc730, {0x8992c0, 0x400007a420}, {0x0, 0x0, 0x0}})
        /home/myitcv/dev/cuelang/cue/internal/core/adt/eval.go:1246 +0x490
cuelang.org/go/internal/core/adt.(*nodeContext).addExprConjunct(0x40000cc380, {0x40000bc730, {0x8992c0, 0x400007a420}, {0x0, 0x0, 0x0}})
        /home/myitcv/dev/cuelang/cue/internal/core/adt/eval.go:1206 +0x558
cuelang.org/go/internal/core/adt.(*nodeContext).insertConjuncts(0x40000cc380)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/eval.go:367 +0xc0
cuelang.org/go/internal/core/adt.(*OpContext).Unify(0x40000aa270, 0x40000b4480, 0x5)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/eval.go:227 +0x2a0
cuelang.org/go/internal/core/adt.(*nodeContext).completeArcs(0x40000cc000, 0x5)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/eval.go:669 +0x48c
cuelang.org/go/internal/core/adt.(*nodeContext).postDisjunct(0x40000cc000, 0x5)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/eval.go:565 +0x730
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0x40000cc000, 0x24?, 0x40000cc000, 0x0, 0x0, 0x1)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/disjunct.go:151 +0x2f0
cuelang.org/go/internal/core/adt.(*OpContext).Unify(0x40000aa270, 0x40000b4120, 0x5)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/eval.go:281 +0x878
cuelang.org/go/internal/core/adt.(*Vertex).Finalize(...)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/composite.go:445
cuelang.org/go/cue.(*Instance).Value(0x40000a6540)
        /home/myitcv/dev/cuelang/cue/cue/instance.go:212 +0x90
cuelang.org/go/cmd/cue/cmd.buildInstances(0x75bdc0?, {0x40002b9920?, 0x40000a8000?, 0x400036b050?})
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/common.go:737 +0xe4
cuelang.org/go/cmd/cue/cmd.parseArgs(0x1000?, {0x400039c110, 0x1, 0x1}, 0x400036ea50)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/common.go:623 +0xe44
cuelang.org/go/cmd/cue/cmd.runEval(0x400035ace0, {0x400039c110, 0x1, 0x1})
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/eval.go:88 +0x6c
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0x400022db80?, {0x400039c110?, 0x1?, 0x1?})
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:46 +0x70
github.com/spf13/cobra.(*Command).execute(0x400022db80, {0x400039c0e0, 0x1, 0x1})
        /home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x4dc
github.com/spf13/cobra.(*Command).ExecuteC(0x400022d340)
        /home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x358
github.com/spf13/cobra.(*Command).Execute(...)
        /home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0x400035ace0, {0x2?, 0x2?})
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:206 +0x60
cuelang.org/go/cmd/cue/cmd.mainErr({0x89d4d8, 0x4000138020}, {0x400011c070?, 0x40000021a0?, 0x4000075f28?})
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:145 +0x5c
cuelang.org/go/cmd/cue/cmd.Main()
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:127 +0x8c
main.main()
        /home/myitcv/dev/cuelang/cue/cmd/cue/main.go:24 +0x20
[exit status 2]
FAIL: /tmp/testscript3359003523/repro.txt/script.txt:1: unexpected command failure
error running repro.txt in /tmp/testscript3359003523/repro.txt
```

Bisected to 91476ab2151490e11c044fa48a95c713cf019b0b

**Comment by myitcv** [comment]
This input CUE was distilled from https://github.com/cue-lang/cue/issues/1815#issuecomment-1201081845. Specifically, the following program:

```
go mod tidy
go run .
cmp stdout stdout.golden

-- go.mod --
module mod.com

go 1.18

require cuelang.org/go v0.4.4-0.20220729051708-0a46a1624353

require (
	github.com/cockroachdb/apd/v2 v2.0.1 // indirect
	github.com/google/uuid v1.2.0 // indirect
	github.com/mpvl/unique v0.0.0-20150818121801-cbe035fff7de // indirect
	github.com/pkg/errors v0.8.1 // indirect
	golang.org/x/net v0.0.0-20220425223048-2871e0cb64e4 // indirect
	golang.org/x/text v0.3.7 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
)
-- main.go --
package main

import (
	"fmt"
	"log"

	"cuelang.org/go/cue"
	"cuelang.org/go/cue/ast"
	"cuelang.org/go/cue/cuecontext"
	"cuelang.org/go/cue/format"
)

var storage = `
parameter: _

l1: [ for v in parameter.pvc {} ]

l2: l1
l3: [
	for v2 in [ for v1 in l2 { v1 } ] {
		v2
	},
]

patch: volumes: l3

`

func main() {
	ctx := cuecontext.New()
	v := ctx.CompileString(storage)
	if err := v.Err(); err != nil {
		log.Fatal(err)
	}

	subv := v.LookupPath(cue.ParsePath("patch"))
	if err := subv.Err(); err != nil {
		log.Fatal(err)
	}
	node := subv.Syntax()
	b, err := format.Node(&ast.File{Decls: node.(*ast.StructLit).Elts})
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%s", b)
}
-- stdout.golden --
volumes: L3

//cue:path: l3
let L3 = [ for v2 in [ for v1 in L2 {
	v1
}] {
	v2
}]

//cue:path: l2
let L2 = L1

//cue:path: l1
let L1 = [ for v in PARAMETER.pvc {}]

//cue:path: parameter
let PARAMETER = _
```

i.e. the `stdout.golden` file contents in this comment's `txtar` are identical to the `x.cue` in the issue description `txtar`.

**Comment by myitcv** [comment]
FYI @mpvl is investigating here.
