### ISSUE TITLE
encoding/openapi: error report when generate openapi

### ISSUE THREAD

**Issue by FogDong** [cue-lang/cue#1836]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
v0.4.4-0.20220801114602-5a08d2f7a9a7
</pre>

### Does this issue reproduce with the latest release?

yes

### What did you do?

```
-- go.mod --
module test-cue/openapi-resolve

go 1.17

require cuelang.org/go v0.4.4-0.20220801114602-5a08d2f7a9a7

require (
	github.com/cockroachdb/apd/v2 v2.0.1 // indirect
	github.com/emicklei/proto v1.10.0 // indirect
	github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b // indirect
	github.com/google/uuid v1.2.0 // indirect
	github.com/mitchellh/go-wordwrap v1.0.1 // indirect
	github.com/mpvl/unique v0.0.0-20150818121801-cbe035fff7de // indirect
	github.com/pkg/errors v0.8.1 // indirect
	github.com/protocolbuffers/txtpbfmt v0.0.0-20220428173112-74888fd59c2b // indirect
	golang.org/x/net v0.0.0-20220425223048-2871e0cb64e4 // indirect
	golang.org/x/text v0.3.7 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
)
-- main.go --
package main

import (
	"fmt"

	"cuelang.org/go/cue"
	"cuelang.org/go/cue/format"
	"cuelang.org/go/encoding/openapi"
)

var test = `
#Params: {
	image: string
}

#parameter: #Params | {
	containers: [...#Params]
}
`

func main() {
	var r cue.Runtime
	cueInst, err := r.Compile("-", test)
	if err != nil {
		panic(err)
	}
	v := cueInst.LookupDef("#parameter")
	// s, err := format.Node(v.Syntax(cue.ResolveReferences(true)))
	// s, err := format.Node(v.Syntax(cue.Final()))
	s, err := format.Node(v.Syntax())
	if err != nil {
		panic(err)
	}
	cueInst, err = r.Compile("-", fmt.Sprintf("#parameter: %s", string(s)))
	if err != nil {
		panic(err)
	}

	defaultConfig := &openapi.Config{ExpandReferences: true}
	b, err := openapi.Gen(cueInst, defaultConfig)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(b))
}
-- repro.txt --
-- stderr --
panic: unsupported op . for object type ({
        image: string
} | {
        containers: [...{
                image: string
        }]
})

```

If we add `cue.ResolveReferences(true)`, the error will be resolved, and the stdout is like:

```
{"openapi":"3.0.0","info":{"title":"Generated by cue.","version":"no version"},"paths":{},"components":{"schemas":{"parameter":{"type":"object","properties":{"image":{"type":"string"},"containers":{"type":"array","items":{"type":"object","required":["image"],"properties":{"image":{"type":"string"}}}}},"oneOf":[{"required":["image"]},{"required":["containers"]}]}}}}
```

But resolve reference is deprecated. Instead, if we use `cue.Final`, the result is different like:

```
{"openapi":"3.0.0","info":{"title":"Generated by cue.","version":"no version"},"paths":{},"components":{"schemas":{"parameter":{"type":"object","properties":{"image":{"type":"string"},"containers":{"type":"array","enum":[[]]}},"oneOf":[{"required":["image"]},{"required":["containers"]}]}}}}
```

**Comment by myitcv** [comment]
@FogDong please can you provide a repro that shows something working on `v0.2.2` and then broken on tip, assuming that is what you are trying to show here?

**Comment by FogDong** [comment]
Hi @myitcv , thanks for the reply, here's the repro. Note that in v0.2.2, we have to use `ResolveReference` otherwise it will fail in build value. However, in v0.4.4, I tried to remove `ResolveReference` since `ResolveReference` is deprecated, but an error is reported when generating openapi.

```
# v0.2.2 - with resolve reference
go get cuelang.org/go@v0.2.2
go mod tidy
go run main.go --resolve
cmp stdout stdout.golden

# 0.4.4 - with resolve reference
go get cuelang.org/go@v0.4.4-0.20220801114602-5a08d2f7a9a7
go mod tidy
go run main.go --resolve
cmp stdout stdout.golden

# 0.4.4 - without resolve
go get cuelang.org/go@v0.4.4-0.20220801114602-5a08d2f7a9a7
go mod tidy
go run main.go
-- go.mod --
module test-cue/openapi-resolve

go 1.17

require cuelang.org/go v0.2.2

require (
	github.com/cockroachdb/apd/v2 v2.0.1 // indirect
	github.com/emicklei/proto v1.10.0 // indirect
	github.com/google/go-cmp v0.5.7 // indirect
	github.com/mpvl/unique v0.0.0-20150818121801-cbe035fff7de // indirect
	github.com/pkg/errors v0.8.1 // indirect
	golang.org/x/net v0.0.0-20220425223048-2871e0cb64e4 // indirect
	golang.org/x/text v0.3.7 // indirect
	golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
)
-- main.go --
package main

import (
	"flag"
	"fmt"

	"cuelang.org/go/cue"
	"cuelang.org/go/cue/format"
	"cuelang.org/go/encoding/openapi"
)

var test = `
#Params: {
	image: string
}

#parameter: #Params | {
	containers: [...#Params]
}
`

func main() {
	var resolve bool
	var final bool
	flag.BoolVar(&resolve, "resolve", false, "resolve")
	flag.BoolVar(&final, "final", false, "final")
	flag.Parse()

	var r cue.Runtime
	cueInst, err := r.Compile("-", test)
	if err != nil {
		panic(err)
	}
	v := cueInst.LookupDef("#parameter")
	opts := make([]cue.Option, 0)
	if resolve {
		opts = append(opts, cue.ResolveReferences(true))
	}
	if final {
		opts = append(opts, cue.Final())
	}
	s, err := format.Node(v.Syntax(opts...))
	if err != nil {
		panic(err)
	}
	cueInst, err = r.Compile("-", fmt.Sprintf("#parameter: %s", string(s)))
	if err != nil {
		panic(err)
	}

	defaultConfig := &openapi.Config{ExpandReferences: true}
	b, err := openapi.Gen(cueInst, defaultConfig)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(b))
}
-- repro.txt --
-- stdout.golden --
{"openapi":"3.0.0","info":{"title":"Generated by cue.","version":"no version"},"paths":{},"components":{"schemas":{"parameter":{"type":"object","properties":{"image":{"type":"string"},"containers":{"type":"array","items":{"type":"object","required":["image"],"properties":{"image":{"type":"string"}}}}},"oneOf":[{"required":["image"]},{"required":["containers"]}]}}}}

```

The current behaviour is:
```
# v0.2.2 - with resolve reference (14.773s)
# 0.4.4 - with resolve reference (9.347s)
# 0.4.4 - without resolve (1.452s)
> go get cuelang.org/go@v0.4.4-0.20220801114602-5a08d2f7a9a7
> go mod tidy
> go run main.go
[stderr]
panic: unsupported op . for object type ({
        image: string
} | {
        containers: [...{
                image: string
        }]
})

goroutine 1 [running]:
main.main()
        $WORK/main.go:54 +0x558
exit status 2

[exit status 1]
FAIL: /var/folders/2n/0vszm3355n114dk2r_ln8vrh0000gp/T/testscript3975170995/repro.txt/script.txt:16: unexpected go command failure
error running repro.txt in /var/folders/2n/0vszm3355n114dk2r_ln8vrh0000gp/T/testscript3975170995/repro.txt
```

I tried to use `cue.Final` because of the deprecated of `cue.ResolveReference`, but the result is as follows:

```
# 0.4.4 - with final
go get cuelang.org/go@v0.4.4-0.20220801114602-5a08d2f7a9a7
go mod tidy
go run main.go --final
cmp stdout stdout.golden
```

```
# 0.4.4 - with final (12.089s)
> go get cuelang.org/go@v0.4.4-0.20220801114602-5a08d2f7a9a7
[stderr]
go: downloading cuelang.org/go v0.4.4-0.20220801114602-5a08d2f7a9a7
go get: upgraded cuelang.org/go v0.2.2 => v0.4.4-0.20220801114602-5a08d2f7a9a7
go get: upgraded golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543 => v0.0.0-20200804184101-5ec99f83aff1

> go mod tidy
[stderr]
go: downloading github.com/mpvl/unique v0.0.0-20150818121801-cbe035fff7de
go: downloading github.com/stretchr/testify v1.2.2
go: downloading github.com/cockroachdb/apd/v2 v2.0.1
go: downloading github.com/google/go-cmp v0.5.7
go: downloading github.com/kylelemons/godebug v1.1.0
go: downloading golang.org/x/tools v0.1.10
go: downloading golang.org/x/text v0.3.7
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading golang.org/x/net v0.0.0-20220425223048-2871e0cb64e4
go: downloading github.com/google/uuid v1.2.0
go: downloading golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
go: downloading github.com/emicklei/proto v1.10.0
protocol error: received DATA after END_STREAM
go: downloading github.com/protocolbuffers/txtpbfmt v0.0.0-20220428173112-74888fd59c2b
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/cockroachdb/apd v1.1.0
go: downloading github.com/lib/pq v1.0.0
go: downloading github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b
go: downloading github.com/mitchellh/go-wordwrap v1.0.1

> go run main.go --final
[stdout]
{"openapi":"3.0.0","info":{"title":"Generated by cue.","version":"no version"},"paths":{},"components":{"schemas":{"parameter":{"type":"object","properties":{"image":{"type":"string"},"containers":{"type":"array","enum":[[]]}},"oneOf":[{"required":["image"]},{"required":["containers"]}]}}}}

> cmp stdout stdout.golden
--- stdout
+++ stdout.golden
@@ -1,1 +0,0 @@
-{"openapi":"3.0.0","info":{"title":"Generated by cue.","version":"no version"},"paths":{},"components":{"schemas":{"parameter":{"type":"object","properties":{"image":{"type":"string"},"containers":{"type":"array","enum":[[]]}},"oneOf":[{"required":["image"]},{"required":["containers"]}]}}}}
@@ -0,0 +1,1 @@
+{"openapi":"3.0.0","info":{"title":"Generated by cue.","version":"no version"},"paths":{},"components":{"schemas":{"parameter":{"type":"object","properties":{"image":{"type":"string"},"containers":{"type":"array","items":{"type":"object","required":["image"],"properties":{"image":{"type":"string"}}}}},"oneOf":[{"required":["image"]},{"required":["containers"]}]}}}}

FAIL: /var/folders/2n/0vszm3355n114dk2r_ln8vrh0000gp/T/testscript320694015/repro.txt/script.txt:5: stdout and stdout.golden differ
error running repro.txt in /var/folders/2n/0vszm3355n114dk2r_ln8vrh0000gp/T/testscript320694015/repro.txt

```

**Comment by FogDong** [comment]
Re-check this issue with the fixed `InstanceOrValue` API but get another error, probably related to the let issue.

Here's the repro:

```
# master
go get cuelang.org/go@v0.4.4-0.20220912105017-e5f21dbb163c
go mod tidy
go run main.go

-- go.mod --
module test-cue/openapi-resolve

go 1.17

require cuelang.org/go v0.4.4-0.20220912105017-e5f21dbb163c

require (
	github.com/cockroachdb/apd/v2 v2.0.2 // indirect
	github.com/google/uuid v1.2.0 // indirect
	github.com/mpvl/unique v0.0.0-20150818121801-cbe035fff7de // indirect
	github.com/pkg/errors v0.8.1 // indirect
	golang.org/x/net v0.0.0-20220722155237-a158d28d115b // indirect
	golang.org/x/text v0.3.7 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
)
-- main.go --
package main

import (
	"fmt"

	"cuelang.org/go/cue"
	"cuelang.org/go/cue/cuecontext"
	"cuelang.org/go/encoding/openapi"
)

var test = `
#Params: {
	image: string
}

#parameter: #Params | {
	containers: [...#Params]
}
`

func main() {
	cueV := cuecontext.New().CompileString(test)
	v := cueV.LookupPath(cue.ParsePath("#parameter"))

	defaultConfig := &openapi.Config{ExpandReferences: true}
	b, err := openapi.Gen(v, defaultConfig)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(b))
}
-- repro.txt --
-- stdout.golden --
{"openapi":"3.0.0","info":{"title":"Generated by cue.","version":"no version"},"paths":{},"components":{"schemas":{"parameter":{"type":"object","properties":{"image":{"type":"string"},"containers":{"type":"array","items":{"type":"object","required":["image"],"properties":{"image":{"type":"string"}}}}},"oneOf":[{"required":["image"]},{"required":["containers"]}]}}}}

```

The result is:
```
> go run main.go
[stderr]
panic: #parameter: non-concrete value struct

goroutine 1 [running]:
main.main()
        $WORK/main.go:28 +0x33c
exit status 2

[exit status 1]
FAIL: /var/folders/2n/0vszm3355n114dk2r_ln8vrh0000gp/T/testscript2962469817/repro.txt/script.txt:4: unexpected go command failure
error running repro.txt in /var/folders/2n/0vszm3355n114dk2r_ln8vrh0000gp/T/testscript2962469817/repro.txt
```

**Comment by myitcv** [comment]
@FogDong - I think what you are after is:

```
# tip
go get cuelang.org/go@v0.4.4-0.20221001181137-79d80efc2882
go mod tidy
go run main.go

-- go.mod --
module test-cue/openapi-resolve

go 1.17

require cuelang.org/go v0.4.4-0.20220912105017-e5f21dbb163c

require (
	github.com/cockroachdb/apd/v2 v2.0.2 // indirect
	github.com/google/uuid v1.2.0 // indirect
	github.com/mpvl/unique v0.0.0-20150818121801-cbe035fff7de // indirect
	github.com/pkg/errors v0.8.1 // indirect
	golang.org/x/net v0.0.0-20220722155237-a158d28d115b // indirect
	golang.org/x/text v0.3.7 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
)
-- main.go --
package main

import (
	"fmt"

	"cuelang.org/go/cue/cuecontext"
	"cuelang.org/go/encoding/openapi"
)

var test = `
#Params: {
	image: string
}

#parameter: #Params | {
	containers: [...#Params]
}
`

func main() {
	v := cuecontext.New().CompileString(test)

	defaultConfig := &openapi.Config{ExpandReferences: true}
	b, err := openapi.Gen(v, defaultConfig)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(b))
}
-- repro.txt --
-- stdout.golden --
{"openapi":"3.0.0","info":{"title":"Generated by cue.","version":"no version"},"paths":{},"components":{"schemas":{"parameter":{"type":"object","properties":{"image":{"type":"string"},"containers":{"type":"array","items":{"type":"object","required":["image"],"properties":{"image":{"type":"string"}}}}},"oneOf":[{"required":["image"]},{"required":["containers"]}]}}}}
```

Note the diff with the original:

```diff
--- -   2022-10-06 08:22:11.063629066 +0100
+++ repro.txtar 2022-10-06 08:21:05.220350164 +0100
@@ -1,5 +1,5 @@
-# master
-go get cuelang.org/go@v0.4.4-0.20220912105017-e5f21dbb163c
+# tip
+go get cuelang.org/go@v0.4.4-0.20221001181137-79d80efc2882
 go mod tidy
 go run main.go

@@ -25,7 +25,6 @@
 import (
        "fmt"

-       "cuelang.org/go/cue"
        "cuelang.org/go/cue/cuecontext"
        "cuelang.org/go/encoding/openapi"
 )
@@ -41,8 +40,7 @@
 `

 func main() {
-       cueV := cuecontext.New().CompileString(test)
-       v := cueV.LookupPath(cue.ParsePath("#parameter"))
+       v := cuecontext.New().CompileString(test)

        defaultConfig := &openapi.Config{ExpandReferences: true}
        b, err := openapi.Gen(v, defaultConfig)
```

(the diff in the version of CUE is just me using the current tip version)

If you lookup `#parameter`, the value you pass to `openapi.Gen()` is the struct value on the right hand side of `#parameter` declaration. This struct is not concrete, because it is the RHS of a definition. 

Instead, simply passing the compiled result in my example, you pass a struct that contains the declaration of `#parameter`. `openapi.Gen()` is then correctly able to identify the definitions vs values. 

I don't think there is an issue here so will close this issue, but please reply if I'm missing something.

**Comment by FogDong** [comment]
Hi @myitcv 

In our situation, we only want to generate the openapi for `#parameter`, and the whole cue string is more than that, so we need to lookup `#parameter` first and re-build the cue value.

So here's the new repro:

```
# tip
go mod tidy
go run main.go

-- go.mod --
module test-cue/openapi-resolve

go 1.17

require cuelang.org/go v0.4.4-0.20221001181137-79d80efc2882

require (
	github.com/cockroachdb/apd/v2 v2.0.2 // indirect
	github.com/google/uuid v1.2.0 // indirect
	github.com/mpvl/unique v0.0.0-20150818121801-cbe035fff7de // indirect
	github.com/pkg/errors v0.8.1 // indirect
	golang.org/x/net v0.0.0-20220722155237-a158d28d115b // indirect
	golang.org/x/text v0.3.7 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
)
-- main.go --
package main

import (
	"fmt"

	"cuelang.org/go/cue"
	"cuelang.org/go/cue/cuecontext"
	"cuelang.org/go/cue/format"
	"cuelang.org/go/encoding/openapi"
)

var test = `
useless: string

#Params: {
	image: string
}

#parameter: #Params | {
	containers: [...#Params]
}
`

func main() {
	cueV := cuecontext.New().CompileString(test)
	v := cueV.LookupPath(cue.ParsePath("#parameter"))
	b, err := format.Node(v.Syntax())
	if err != nil {
		panic(err)
	}
	paramValue := cuecontext.New().CompileString(fmt.Sprintf("#parameter: %s", string(b)))

	defaultConfig := &openapi.Config{ExpandReferences: true}
	b, err = openapi.Gen(paramValue, defaultConfig)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(b))
}
-- repro.txt --
-- stdout.golden --
{"openapi":"3.0.0","info":{"title":"Generated by cue.","version":"no version"},"paths":{},"components":{"schemas":{"parameter":{"type":"object","properties":{"image":{"type":"string"},"containers":{"type":"array","items":{"type":"object","required":["image"],"properties":{"image":{"type":"string"}}}}},"oneOf":[{"required":["image"]},{"required":["containers"]}]}}}}
```

The error is:

```
[stderr]
panic: unsupported op . for object type ({
        image: string
} | {
        containers: [...{
                image: string
        }]
})
```

**Comment by myitcv** [comment]
@FogDong that's because the CUE you are trying to parse (the output from the lookup of `#parameter`) is invalid. 

Instead try something like this:

```
# tip
go mod tidy
go run main.go

-- go.mod --
module test-cue/openapi-resolve

go 1.17

require cuelang.org/go v0.4.4-0.20221001181137-79d80efc2882

require (
	github.com/cockroachdb/apd/v2 v2.0.2 // indirect
	github.com/google/uuid v1.2.0 // indirect
	github.com/mpvl/unique v0.0.0-20150818121801-cbe035fff7de // indirect
	github.com/pkg/errors v0.8.1 // indirect
	golang.org/x/net v0.0.0-20220722155237-a158d28d115b // indirect
	golang.org/x/text v0.3.7 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
)
-- main.go --
package main

import (
	"fmt"

	"cuelang.org/go/cue"
	"cuelang.org/go/cue/cuecontext"
	"cuelang.org/go/encoding/openapi"
)

var test = `
useless: string

#Params: {
	image: string
}

#parameter: #Params | {
	containers: [...#Params]
}
`

func main() {
	ctx := cuecontext.New()
	test := ctx.CompileString(test)
	parameterPath := cue.MakePath(cue.Def("parameter"))
	parameter := test.LookupPath(parameterPath)
	v := ctx.CompileString("{}")
	v = v.FillPath(parameterPath, parameter)
	defaultConfig := &openapi.Config{ExpandReferences: true}
	b, err := openapi.Gen(v, defaultConfig)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(b))
}
-- stdout.golden --
{"openapi":"3.0.0","info":{"title":"Generated by cue.","version":"no version"},"paths":{},"components":{"schemas":{"parameter":{"type":"object","properties":{"image":{"type":"string"},"containers":{"type":"array","items":{"type":"object","required":["image"],"properties":{"image":{"type":"string"}}}}},"oneOf":[{"required":["image"]},{"required":["containers"]}]}}}}
```

Which passes as expected. The diff being:

```diff
--- -   2022-10-10 09:02:41.925216329 +0100
+++ repro.txtar 2022-10-10 09:00:06.350490851 +0100
@@ -26,7 +26,6 @@

        "cuelang.org/go/cue"
        "cuelang.org/go/cue/cuecontext"
-       "cuelang.org/go/cue/format"
        "cuelang.org/go/encoding/openapi"
 )

@@ -43,21 +42,18 @@
 `

 func main() {
-       cueV := cuecontext.New().CompileString(test)
-       v := cueV.LookupPath(cue.ParsePath("#parameter"))
-       b, err := format.Node(v.Syntax())
-       if err != nil {
-               panic(err)
-       }
-       paramValue := cuecontext.New().CompileString(fmt.Sprintf("#parameter: %s", string(b)))
-
+       ctx := cuecontext.New()
+       test := ctx.CompileString(test)
+       parameterPath := cue.MakePath(cue.Def("parameter"))
+       parameter := test.LookupPath(parameterPath)
+       v := ctx.CompileString("{}")
+       v = v.FillPath(parameterPath, parameter)
        defaultConfig := &openapi.Config{ExpandReferences: true}
-       b, err = openapi.Gen(paramValue, defaultConfig)
+       b, err := openapi.Gen(v, defaultConfig)
        if err != nil {
                panic(err)
        }
        fmt.Println(string(b))
 }
```
