### ISSUE TITLE
evaluator: panic when referencing non-concrete values in comprehensions

### ISSUE THREAD

**Issue by 4ad** [cue-lang/cue#1910]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20220905100514-9e9786e93b63

       -compiler gc
     CGO_ENABLED 1
          GOARCH amd64
            GOOS darwin
         GOAMD64 v1
             vcs git
    vcs.revision 9e9786e93b63af979d9f105a12c8519a6216e56f
        vcs.time 2022-09-05T10:05:14Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest release?
No, works with v0.4.3.

### What did you do?
Run this testscript:
```
exec cue eval issue1910.cue
cmp stdout issue1910.cue
-- issue1910.cue --
a: _
b: {
    for k, v in [0] {
        "\(a)": v
    }
}
```

### What did you expect to see?
```
PASS
```

### What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x129cd58]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc000573e90)
	/Users/aram/src/cue/cmd/cue/cmd/root.go:232 +0x7b
panic({0x178c5e0, 0x1ddd050})
	/Users/aram/go/src/runtime/panic.go:884 +0x212
cuelang.org/go/internal/core/adt.(*Vertex).getNodeContext(0x17c1020?, 0x17e2480?, 0x183f8ee?)
	/Users/aram/src/cue/internal/core/adt/eval.go:1019 +0x18
cuelang.org/go/internal/core/adt.(*OpContext).Unify(0xc0002401e0, 0x0, 0x2)
	/Users/aram/src/cue/internal/core/adt/eval.go:162 +0xf6
cuelang.org/go/internal/core/adt.(*OpContext).relNode(0x1985ab0?, 0x0?)
	/Users/aram/src/cue/internal/core/adt/context.go:312 +0x37
cuelang.org/go/internal/core/adt.(*FieldReference).resolve(0xc0004e3e00, 0x1982c20?, 0x0?)
	/Users/aram/src/cue/internal/core/adt/expr.go:713 +0x2f
cuelang.org/go/internal/core/adt.(*OpContext).evalState(0xc0002401e0, {0x1982c20, 0xc0004e3e00}, 0x2)
	/Users/aram/src/cue/internal/core/adt/context.go:680 +0x211
cuelang.org/go/internal/core/adt.(*OpContext).value(0xc0002401e0?, {0x1982c20?, 0xc0004e3e00?})
	/Users/aram/src/cue/internal/core/adt/context.go:627 +0x2d
cuelang.org/go/internal/core/adt.(*Interpolation).evaluate(0xc0004adb60, 0xc0002401e0)
	/Users/aram/src/cue/internal/core/adt/expr.go:1071 +0x3a7
cuelang.org/go/internal/core/adt.(*OpContext).evalState(0xc0002401e0, {0x1982ce0, 0xc0004adb60}, 0x2)
	/Users/aram/src/cue/internal/core/adt/context.go:676 +0x2f6
cuelang.org/go/internal/core/adt.(*OpContext).Evaluate(0xc0002401e0, 0xc000232a20, {0x1982ce0, 0xc0004adb60})
	/Users/aram/src/cue/internal/core/adt/context.go:579 +0x1d9
cuelang.org/go/internal/core/export.(*exporter).decl(0xc000275ef0, 0x1981c60?, {0x197f8c0?, 0xc0004adbf0?})
	/Users/aram/src/cue/internal/core/export/adt.go:467 +0x145
cuelang.org/go/internal/core/export.(*exporter).adt(0xc000275ef0, 0xc0002329a0, {0x1981c60?, 0xc00021c5a0?})
	/Users/aram/src/cue/internal/core/export/adt.go:70 +0x261a
cuelang.org/go/internal/core/export.(*conjuncts).addExpr(0xc000571000, 0xc0002329a0, 0x0, {0x1981c60?, 0xc00021c5a0?}, 0x0)
	/Users/aram/src/cue/internal/core/export/expr.go:360 +0xf53
cuelang.org/go/internal/core/export.(*exporter).mergeValues(0xc000275ef0, 0x0?, 0x0, {0xc0005712e8, 0x1, 0x197d5a8?}, {0xc00023e300, 0x1, 0x1})
	/Users/aram/src/cue/internal/core/export/expr.go:152 +0x5bd
cuelang.org/go/internal/core/export.(*exporter).expr(0x197d5a8?, 0xc00021c5a0?, {0x1981c60?, 0xc00021c5a0?})
	/Users/aram/src/cue/internal/core/export/expr.go:92 +0x2f9
cuelang.org/go/internal/core/export.(*exporter).comprehension(0xc000275ef0, 0xc0002329a0, 0xc000235b40)
	/Users/aram/src/cue/internal/core/export/adt.go:605 +0xe85
cuelang.org/go/internal/core/export.(*exporter).elem(0x2b4?, 0x197f890?, {0x1981ad8?, 0xc000235b40?})
	/Users/aram/src/cue/internal/core/export/adt.go:540 +0x151
cuelang.org/go/internal/core/export.(*exporter).decl(0xc000275ef0, 0x1981c60?, {0x197f890?, 0xc000235b40?})
	/Users/aram/src/cue/internal/core/export/adt.go:404 +0x537
cuelang.org/go/internal/core/export.(*exporter).adt(0xc000275ef0, 0xc0002326c0, {0x1981c60?, 0xc00021c510?})
	/Users/aram/src/cue/internal/core/export/adt.go:70 +0x261a
cuelang.org/go/internal/core/export.(*conjuncts).addExpr(0xc0005728f8, 0xc0002326c0, 0x0, {0x1981c60?, 0xc00021c510?}, 0x0)
	/Users/aram/src/cue/internal/core/export/expr.go:360 +0xf53
cuelang.org/go/internal/core/export.(*exporter).mergeValues(0xc000275ef0, 0x220000?, 0x0, {0xc000572be0, 0x1, 0x197d5a8?}, {0xc00023e240, 0x1, 0x1})
	/Users/aram/src/cue/internal/core/export/expr.go:152 +0x5bd
cuelang.org/go/internal/core/export.(*exporter).expr(0xc000275ef0?, 0x197d288?, {0x1981c60?, 0xc00021c510?})
	/Users/aram/src/cue/internal/core/export/expr.go:92 +0x2f9
cuelang.org/go/internal/core/export.(*exporter).vertex(0xc000275ef0, 0xc00023a100)
	/Users/aram/src/cue/internal/core/export/value.go:102 +0x9b2
cuelang.org/go/internal/core/export.(*exporter).structComposite(0xc000275ef0, 0xc00023a000, {0x0, 0x0, 0xc000573398?})
	/Users/aram/src/cue/internal/core/export/value.go:465 +0xa4e
cuelang.org/go/internal/core/export.(*exporter).vertex(0xc000275ef0, 0xc00023a000)
	/Users/aram/src/cue/internal/core/export/value.go:65 +0x5c9
cuelang.org/go/internal/core/export.(*exporter).value(0xc000275ef0, {0x1985e70?, 0xc00023a000?}, {0xc000235b80?, 0x1?, 0x1?})
	/Users/aram/src/cue/internal/core/export/value.go:182 +0x593
cuelang.org/go/internal/core/export.(*Profile).Vertex(0x8?, {0x1983160?, 0xc0003350b0?}, {0xc0004774d0?, 0xc000573a58?}, 0xc00023a000)
	/Users/aram/src/cue/internal/core/export/export.go:202 +0x93
cuelang.org/go/cue.Value.Syntax({0xc0003350b0?, 0xc00023a000?, 0x0?}, {0xc000573c38, 0x4, 0x4?})
	/Users/aram/src/cue/cue/types.go:1018 +0x24f
cuelang.org/go/cmd/cue/cmd.runEval(0xc000393170, {0x1e34310, 0x0, 0x0})
	/Users/aram/src/cue/cmd/cue/cmd/eval.go:161 +0x8fd
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc0003a2f00?, {0x1e34310?, 0x0?, 0x0?})
	/Users/aram/src/cue/cmd/cue/cmd/root.go:48 +0x4d
github.com/spf13/cobra.(*Command).execute(0xc0003a2f00, {0x1e34310, 0x0, 0x0})
	/Users/aram/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003a2780)
	/Users/aram/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/aram/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc000393170, {0x1?, 0x1?})
	/Users/aram/src/cue/cmd/cue/cmd/root.go:217 +0x6b
cuelang.org/go/cmd/cue/cmd.mainErr({0x1981870, 0xc000124008}, {0xc00012c010?, 0xc0000061a0?, 0x200000003?})
	/Users/aram/src/cue/cmd/cue/cmd/root.go:154 +0x55
cuelang.org/go/cmd/cue/cmd.Main()
	/Users/aram/src/cue/cmd/cue/cmd/root.go:136 +0x7c
main.main()
	/Users/aram/src/cue/cmd/cue/main.go:24 +0x19
```

**Comment by myitcv** [comment]
@mpvl suspect I'm also seeing this whilst running `cue def` to create a standalone repro of the Caascad unity project.

**Comment by myitcv** [comment]
Bisected to 8edd739a.

**Comment by mpvl** [comment]
Seems to be an out of whack "up count" for a dynamic reference.
