### ISSUE TITLE
evaluator: panic on valid input

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#1972]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20221001181137-79d80efc2882

       -compiler gc
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision 79d80efc288208410f77d47ae9aedd37e106d84b
        vcs.time 2022-10-01T18:11:37Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
! exec cue eval x.cue

-- x.cue --
someCondition: _
patchs: [...{}]
patchs
if someCondition {
	patchs: _
}
```

### What did you expect to see?

Passing test (notice we are not asserting the output) with no panic.

### What did you see instead?

Panic:

```
$ ts repro.txtar
> exec cue eval x.cue
[stderr]
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0x40003f1e70)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:232 +0x98
panic({0x74e8c0, 0x400003e360})
        /home/myitcv/gos/src/runtime/panic.go:838 +0x20c
cuelang.org/go/internal/core/adt.(*nodeContext).injectComprehensions(0x400048ee00, 0x400048f058)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/comprehension.go:235 +0x4ec
cuelang.org/go/internal/core/adt.(*nodeContext).expandOne(0x400048ee00)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/eval.go:1926 +0x6c
cuelang.org/go/internal/core/adt.(*nodeContext).postDisjunct(0x400048ee00, 0x5)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/eval.go:455 +0xfc
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0x400048ee00, 0x0?, 0x400048ee00, 0x0, 0x0, 0x1)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/disjunct.go:158 +0x324
cuelang.org/go/internal/core/adt.(*OpContext).Unify(0x40003cf1d0, 0x40002ab8c0, 0x5)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/eval.go:291 +0x768
cuelang.org/go/internal/core/adt.(*Vertex).Finalize(...)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/composite.go:460
cuelang.org/go/cue.newVertexRoot(0x0?, 0x40003cf1d0?, 0x2?)
        /home/myitcv/dev/cuelang/cue/cue/types.go:622 +0x7c
cuelang.org/go/cue.newValueRoot(0x8d1c80?, 0x4000339140?, {0x8d0ba0?, 0x40002ab8c0?})
        /home/myitcv/dev/cuelang/cue/cue/types.go:631 +0x44
cuelang.org/go/cue.(*Context).make(0x4000339140?, 0x0?)
        /home/myitcv/dev/cuelang/cue/cue/context.go:248 +0x64
cuelang.org/go/cue.(*Context).BuildInstances(0x40003f1748?, {0x40003f1900, 0x1, 0x1e0?})
        /home/myitcv/dev/cuelang/cue/cue/context.go:148 +0x1a4
cuelang.org/go/cmd/cue/cmd.buildInstances(0x40003976b0, {0x40003f1900, 0x1, 0x1acec0?}, 0x1)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/common.go:732 +0x38
cuelang.org/go/cmd/cue/cmd.parseArgs(0x40003976b0, {0x4000339680, 0x1, 0x1}, 0x40003a5180)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/common.go:627 +0xe70
cuelang.org/go/cmd/cue/cmd.runEval(0x40003976b0, {0x4000339680, 0x1, 0x1})
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/eval.go:88 +0x6c
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0x40003a6c80?, {0x4000339680?, 0x1?, 0x1?})
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:48 +0x70
github.com/spf13/cobra.(*Command).execute(0x40003a6c80, {0x4000339650, 0x1, 0x1})
        /home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x4dc
github.com/spf13/cobra.(*Command).ExecuteC(0x40003a6500)
        /home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x360
github.com/spf13/cobra.(*Command).Execute(...)
        /home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0x40003976b0, {0x2?, 0x2?})
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:217 +0x60
cuelang.org/go/cmd/cue/cmd.mainErr({0x8cf508, 0x4000138020}, {0x400011c070?, 0x40000021a0?, 0x4000077f28?})
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:154 +0x5c
cuelang.org/go/cmd/cue/cmd.Main()
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:136 +0x8c
main.main()
        /home/myitcv/dev/cuelang/cue/cmd/cue/main.go:24 +0x20
[exit status 2]
FAIL: /tmp/testscript3622481809/repro.txtar/script.txtar:1: unexpected command failure
```

**Comment by myitcv** [comment]
FYI @seh I discovered this bug whilst trying something in the playground. It caused the playground to crash, which renders the entire playground unusable until reloaded (https://github.com/cue-lang/cue/issues/1687).

**Comment by seh** [comment]
The symptom does sound like what I experienced with the Playground over the last couple of weeks. There was also the odd double-pasting of anything from the clipboard.

**Comment by mpvl** [comment]
Here is a slight simplification:
```
patchs: []
patchs

someCondition: _
if someCondition {
}
```
