### ISSUE TITLE
tools/flow: panic for private command configuration that works with v0.4.3

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2030]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20221022113314-dd1169c686c9

       -compiler gc
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision dd1169c686c9e45358fa87fcdb9530fe3f6a799f
        vcs.time 2022-10-22T11:33:14Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest release?

Yes

This also reproduces (actually with two panics, not one!) using https://review.gerrithub.io/c/cue-lang/cue/+/544145/4

### What did you do?

See repro at https://github.com/cue-unity-private/c7fa5d27b373080bc3041c11e2993b8c28f99125e0cb9ae59b12a11a61ddb073 (specifically commit d475cdf371d9e1f1f52e0ba159de1dd047749a4c)

For more details see https://github.com/cue-unity-private/c7fa5d27b373080bc3041c11e2993b8c28f99125e0cb9ae59b12a11a61ddb073/issues/1

### What did you expect to see?

Passing test.

### What did you see instead?

Panic:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x30b76c]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0x4000747e70)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:232 +0x98
panic({0x6e1fa0, 0xd0aa40})
        /home/myitcv/gos/src/runtime/panic.go:838 +0x20c
cuelang.org/go/internal/core/dep.visit.func1()
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:121 +0xc0
panic({0x6e1fa0, 0xd0aa40})
        /home/myitcv/gos/src/runtime/panic.go:838 +0x20c
cuelang.org/go/internal/core/dep.visit.func1()
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:121 +0xc0
panic({0x6e1fa0, 0xd0aa40})
        /home/myitcv/gos/src/runtime/panic.go:838 +0x20c
cuelang.org/go/internal/core/dep.visit.func1()
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:121 +0xc0
panic({0x6e1fa0, 0xd0aa40})
        /home/myitcv/gos/src/runtime/panic.go:838 +0x20c
cuelang.org/go/internal/core/dep.visit.func1()
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:121 +0xc0
panic({0x6e1fa0, 0xd0aa40})
        /home/myitcv/gos/src/runtime/panic.go:838 +0x20c
cuelang.org/go/cue.Selector.Type({{0x0?, 0x0?}})
        /home/myitcv/dev/cuelang/cue/cue/path.go:162 +0x2c
cuelang.org/go/cue.Path.String({{0x40e021dec0?, 0x40a44e3260?, 0x40eaba41b0?}})
        /home/myitcv/dev/cuelang/cue/cue/path.go:288 +0xa8
cuelang.org/go/tools/flow.(*Controller).getTask(0x407d019b00, 0x0, {0x40006a1600?, 0x40eaba41b0?, 0x0?})
        /home/myitcv/dev/cuelang/cue/tools/flow/tasks.go:98 +0xb8
cuelang.org/go/tools/flow.(*Controller).findImpliedTask(0x407d019b00, {0x40eaba41b0, {0x8cdaa8, 0x4000452740}, 0x0})
        /home/myitcv/dev/cuelang/cue/tools/flow/tasks.go:203 +0x1cc
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies.func1({0x40eaba41b0, {0x8cdaa8, 0x4000452740}, 0x0})
        /home/myitcv/dev/cuelang/cue/tools/flow/tasks.go:230 +0x54
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0x40007461a8, 0x40e26f6680, {0x8cdaa8?, 0x4000452740})
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:240 +0x248
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x40007461a8, 0x40e26f6680, {0xffff61fa4660?, 0x4000452740?})
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:151 +0x530
cuelang.org/go/internal/core/dep.(*visitor).markYielder(0x0?, 0x40e26f6680, {0x8cd898?, 0x40004e2690?})
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:320 +0x84
cuelang.org/go/internal/core/dep.(*visitor).markComprehension(0x4000745f98?, 0x8cf998?, 0x40003e0e80)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:313 +0x34
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x40007461a8, 0x40e26f6660, {0x8cf998?, 0x40004e2660?})
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:193 +0x690
cuelang.org/go/internal/core/dep.(*visitor).markDecl(0x40007461a8, 0x8cfa08?, {0xffff60593bf0?, 0x40004e2660?})
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:303 +0x374
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x40007461a8, 0x40cceb9e60, {0x8cfa08?, 0x4000456360?})
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:208 +0x5cc
cuelang.org/go/internal/core/dep.visit(0x715520?, 0x40007464e0?, 0x407d4b4ff0?, 0xc0?, 0x2f?)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:126 +0x1a8
cuelang.org/go/internal/core/dep.dynamic(0x715520?, 0x40eb656240, 0x407d4b4ff0?, 0x4086592fc0?, 0xb0?)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/mixed.go:43 +0xfc
cuelang.org/go/internal/core/dep.dynamic(0x715520?, 0x40e8dd42d0, 0x0?, 0x0?, 0x0?)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/mixed.go:48 +0x144
cuelang.org/go/internal/core/dep.dynamic(0x0?, 0x40b7a161b0, 0x40b7a161b0?, 0x40b7a161b0?, 0x8?)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/mixed.go:48 +0x144
cuelang.org/go/internal/core/dep.VisitFields(0x40007465d8?, 0x56e06c?, 0x11a4a0f60b457a6b?)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:91 +0x94
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies(0x407d019b00, 0x407d5b7c20, 0x40b7a161b0?)
        /home/myitcv/dev/cuelang/cue/tools/flow/tasks.go:229 +0x98
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies.func1({0x40b7a161b0, {0x8cdaa8, 0x40005072c0}, 0x1})
        /home/myitcv/dev/cuelang/cue/tools/flow/tasks.go:245 +0x218
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0x4000746998, 0x40c22fc400, {0x8cdaa8?, 0x40005072c0})
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:240 +0x248
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x4000746998, 0x40c22fc400, {0xffff61fa4660?, 0x40005072c0?})
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:151 +0x530
cuelang.org/go/internal/core/dep.visit(0x715520?, 0x4000746b50?, 0x0?, 0x0?, 0x0?)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:126 +0x1a8
cuelang.org/go/internal/core/dep.dynamic(0x7600000000000000?, 0x40c22ef5f0, 0x40c22ef5f0?, 0x40c22ef5f0?, 0x78?)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/mixed.go:43 +0xfc
cuelang.org/go/internal/core/dep.VisitFields(0x4000746c48?, 0x56e06c?, 0xbb66b6080c431399?)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:91 +0x94
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies(0x407d019b00, 0x407d5b7c20, 0x40c22ef5f0?)
        /home/myitcv/dev/cuelang/cue/tools/flow/tasks.go:229 +0x98
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies.func1({0x40c22ef5f0, {0x8cd868, 0x4000339300}, 0x1})
        /home/myitcv/dev/cuelang/cue/tools/flow/tasks.go:245 +0x218
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0x40007470d8, 0x40c22fc400, {0x8cd868?, 0x4000339300})
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:240 +0x248
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x40007470d8, 0x40c22fc400, {0xffff61fa40e8?, 0x4000339300?})
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:151 +0x530
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x40007470d8, 0x40c22fc400, {0x8cf848?, 0x4000518240?})
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:173 +0x7b8
cuelang.org/go/internal/core/dep.visit(0x715520?, 0x4000747290?, 0x0?, 0x0?, 0x0?)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:126 +0x1a8
cuelang.org/go/internal/core/dep.dynamic(0x0?, 0x40c22ef680, 0x40c22ef680?, 0x40c22ef680?, 0xb8?)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/mixed.go:43 +0xfc
cuelang.org/go/internal/core/dep.VisitFields(0x4000747388?, 0x56e06c?, 0x3f7d214d94b2800f?)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:91 +0x94
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies(0x407d019b00, 0x407d5b7c20, 0x40c22ef680?)
        /home/myitcv/dev/cuelang/cue/tools/flow/tasks.go:229 +0x98
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies.func1({0x40c22ef680, {0x8cdaa8, 0x4000507440}, 0x0})
        /home/myitcv/dev/cuelang/cue/tools/flow/tasks.go:245 +0x218
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0x4000747748, 0x404498caa0, {0x8cdaa8?, 0x4000507440})
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:240 +0x248
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x4000747748, 0x404498caa0, {0xffff61fa4660?, 0x4000507440?})
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:151 +0x530
cuelang.org/go/internal/core/dep.visit(0x715520?, 0x40007479c0?, 0x407d4b4ff0?, 0xe8?, 0xba?)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:126 +0x1a8
cuelang.org/go/internal/core/dep.dynamic(0x715520?, 0x406f5b2990, 0x405f5ead20?, 0x0?, 0x38?)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/mixed.go:43 +0xfc
cuelang.org/go/internal/core/dep.dynamic(0x7600000000000000?, 0x40b8e0b5f0, 0x40b8e0b5f0?, 0x0?, 0x28?)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/mixed.go:48 +0x144
cuelang.org/go/internal/core/dep.VisitFields(0x40b88589c0?, 0x407dcf2ea0?, 0x40006a1600?)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:91 +0x94
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies(0x407d019b00, 0x407d5b7c20, 0x407dcf2ea0?)
        /home/myitcv/dev/cuelang/cue/tools/flow/tasks.go:229 +0x98
cuelang.org/go/tools/flow.(*Controller).initTasks(0x407d019b00)
        /home/myitcv/dev/cuelang/cue/tools/flow/tasks.go:50 +0xf4
cuelang.org/go/tools/flow.New(0x4000747bf0, {0x8caeb8?, 0x40004541c0?}, 0x40a5721880)
        /home/myitcv/dev/cuelang/cue/tools/flow/flow.go:243 +0x1e4
cuelang.org/go/cmd/cue/cmd.doTasks(0x4000747ca8?, {0x1c61ac?, 0x407d4aeb00?}, {0xffffcbbdf2dd, 0xd}, 0x1c5dd4?)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/custom.go:132 +0x110
cuelang.org/go/cmd/cue/cmd.addCustom.func1(0x4000747ca8?, {0x1c606c?, 0x407d4aeb00?, 0x1c6b00?})
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/custom.go:116 +0x34
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0x40aa7b0a00?, {0xd622c8?, 0x0?, 0x0?})
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:48 +0x70
github.com/spf13/cobra.(*Command).execute(0x40aa7b0a00, {0xd622c8, 0x0, 0x0})
        /home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x4dc
github.com/spf13/cobra.(*Command).ExecuteC(0x40003a8500)
        /home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x360
github.com/spf13/cobra.(*Command).Execute(...)
        /home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0x4000399530, {0x3?, 0x3?})
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:217 +0x60
cuelang.org/go/cmd/cue/cmd.mainErr({0x8cf618, 0x4000138020}, {0x4000126010?, 0x40000021a0?, 0x400007df28?})
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:154 +0x5c
cuelang.org/go/cmd/cue/cmd.Main()
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:136 +0x8c
main.main()
        /home/myitcv/dev/cuelang/cue/cmd/cue/main.go:24 +0x20
```

**Comment by myitcv** [comment]
FYI the panic is fixed in 1d8663e67324a7c9623b8c1562936db9a0598172, but this reveals an error which is not present in v0.4.3.

Furthermore, 4eb2280f2dca883b2db7a7cde2937fed8cd1caa6 appears to introduce a significant performance issue in actually reaching that error message. 

It might be that if the error is invalid (i.e. there is a bug compared to v0.4.3) then the performance issue is no longer hit. So will investigate in that order, in two separate issues.
