### ISSUE TITLE
tools/flow: panic on cue script

### ISSUE THREAD

**Issue by kghenderson** [cue-lang/cue#2060]
cause unknown and not yet isolated

```sh

go version go1.19.2 linux/amd64

cue version v0.5.0-alpha.1

       -compiler gc
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v1

```
 
**reproduction** 

created a dedicated branch here: 
https://github.com/kghenderson/keyzen-cue/tree/errors/sublime_tangle_050a1

```sh
cd scripts/cuetools/tangle_sublime
cue cmd tangle_sublime

```
note that this occurred during development, so this model has errors and is in a rough development shape.
just saying that it may not actually run correctly (as is), but wanted to capture the panic condition

**error**

```sh
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x736f08]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc0003f5e90)
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/cmd/cue/cmd/root.go:232 +0x7b
panic({0xb8e380, 0x11e4d20})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.19.2/libexec/src/runtime/panic.go:884 +0x212
cuelang.org/go/internal/core/dep.visit.func1()
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/internal/core/dep/dep.go:121 +0xb0
panic({0xb8e380, 0x11e4d20})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.19.2/libexec/src/runtime/panic.go:884 +0x212
cuelang.org/go/internal/core/dep.visit.func1()
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/internal/core/dep/dep.go:121 +0xb0
panic({0xb8e380, 0x11e4d20})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.19.2/libexec/src/runtime/panic.go:884 +0x212
cuelang.org/go/internal/core/dep.visit.func1()
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/internal/core/dep/dep.go:121 +0xb0
panic({0xb8e380, 0x11e4d20})
        /home/linuxbrew/.linuxbrew/Cellar/go/1.19.2/libexec/src/runtime/panic.go:884 +0x212
cuelang.org/go/cue.Selector.Type({{0x0?, 0x0?}})
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/cue/path.go:162 +0x28
cuelang.org/go/cue.Path.String({{0xc003840100?, 0xc00327e1b0?, 0xc00228b320?}})
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/cue/path.go:288 +0xfc
cuelang.org/go/tools/flow.(*Controller).getTask(0xc0031dd680, 0x0, {0xc00021a0f0?, 0xc00228b320?, 0x0?})
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/tools/flow/tasks.go:98 +0xd2
cuelang.org/go/tools/flow.(*Controller).findImpliedTask(0xc0031dd680, {0xc00228b320, {0xd81530, 0xc0001736e0}, 0x0})
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/tools/flow/tasks.go:203 +0x1fa
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies.func1({0xc00228b320, {0xd81530, 0xc0001736e0}, 0x0})
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/tools/flow/tasks.go:230 +0x6b
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0xc0003f45e8, 0xc0022a9ac0, {0xd81530?, 0xc0001736e0})
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/internal/core/dep/dep.go:240 +0x307
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc0003f45e8, 0xc0022a9ac0, {0x7f461061bf18?, 0xc0001736e0?})
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/internal/core/dep/dep.go:151 +0x66e
cuelang.org/go/internal/core/dep.visit(0xbc28e0?, 0xc0003f4a98?, 0xc002fcb770?, 0xc8?, 0x36?)
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/internal/core/dep/dep.go:126 +0x23b
cuelang.org/go/internal/core/dep.dynamic(0xbc28e0?, 0xc0022b93b0, 0xc002fcb770?, 0xc0037a36c8?, 0x80?)
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/internal/core/dep/mixed.go:43 +0x135
cuelang.org/go/internal/core/dep.dynamic(0xbc28e0?, 0xc0022b0bd0, 0xc002fcb770?, 0xc0037a36c8?, 0xf0?)
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/internal/core/dep/mixed.go:48 +0x187
cuelang.org/go/internal/core/dep.dynamic(0xbc28e0?, 0xc00228a480, 0xc002fcb770?, 0xc0037a36c8?, 0xb0?)
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/internal/core/dep/mixed.go:48 +0x187
cuelang.org/go/internal/core/dep.dynamic(0xbc28e0?, 0xc00227b5f0, 0x0?, 0x0?, 0x0?)
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/internal/core/dep/mixed.go:48 +0x187
cuelang.org/go/internal/core/dep.dynamic(0x69b300?, 0xc00227b3b0, 0xc00227b3b0?, 0x0?, 0x0?)
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/internal/core/dep/mixed.go:48 +0x187
cuelang.org/go/internal/core/dep.VisitFields(0xbb0560?, 0x4cf2f5e3a8d6e8b?, 0xc002fcb701?)
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/internal/core/dep/dep.go:91 +0xbd
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies(0xc0031dd680, 0xc0038797a0, 0xc00227b3b0?)
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/tools/flow/tasks.go:229 +0x8d
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies.func1({0xc00227b3b0, {0xd81470, 0xc0003227d0}, 0x0})
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/tools/flow/tasks.go:245 +0x249
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0xc0003f4fe8, 0xc00227c8a0, {0xd81470?, 0xc0003227d0})
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/internal/core/dep/dep.go:240 +0x307
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc0003f4fe8, 0xc00227c8a0, {0x7f46106da850?, 0xc0003227d0?})
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/internal/core/dep/dep.go:151 +0x66e
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc0003f4fe8, 0xc00227c8a0, {0xd83620?, 0xc000172c60?})
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/internal/core/dep/dep.go:173 +0x80c
cuelang.org/go/internal/core/dep.visit(0xbc28e0?, 0xc0003f5258?, 0xc002fcb770?, 0x68?, 0x36?)
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/internal/core/dep/dep.go:126 +0x23b
cuelang.org/go/internal/core/dep.dynamic(0xbc28e0?, 0xc00227b320, 0x0?, 0x0?, 0x0?)
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/internal/core/dep/mixed.go:43 +0x135
cuelang.org/go/internal/core/dep.dynamic(0x69b300?, 0xc00227b050, 0xc00227b050?, 0xc00085bb00?, 0xe0?)
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/internal/core/dep/mixed.go:48 +0x187
cuelang.org/go/internal/core/dep.VisitFields(0xbb0560?, 0x1d08d2722c051131?, 0xc002fcb701?)
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/internal/core/dep/dep.go:91 +0xbd
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies(0xc0031dd680, 0xc0038797a0, 0xc00227b050?)
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/tools/flow/tasks.go:229 +0x8d
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies.func1({0xc00227b050, {0xd81470, 0xc000322db0}, 0x0})
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/tools/flow/tasks.go:245 +0x249
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0xc0003f57a8, 0xc002fd2420, {0xd81470?, 0xc000322db0})
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/internal/core/dep/dep.go:240 +0x307
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc0003f57a8, 0xc002fd2420, {0x7f46106da850?, 0xc000322db0?})
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/internal/core/dep/dep.go:151 +0x66e
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc0003f57a8, 0xc002fd2420, {0xd83620?, 0xc000173b90?})
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/internal/core/dep/dep.go:173 +0x80c
cuelang.org/go/internal/core/dep.visit(0xbc28e0?, 0xc0003f5a18?, 0xc002fcb770?, 0x50?, 0x36?)
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/internal/core/dep/dep.go:126 +0x23b
cuelang.org/go/internal/core/dep.dynamic(0xbc28e0?, 0xc002fd6090, 0xc003892200?, 0xc0035acbc0?, 0x20?)
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/internal/core/dep/mixed.go:43 +0x135
cuelang.org/go/internal/core/dep.dynamic(0xc0004fd9e0?, 0xc00227b0e0, 0xc00227b0e0?, 0xc00021a0f0?, 0x0?)
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/internal/core/dep/mixed.go:48 +0x187
cuelang.org/go/internal/core/dep.VisitFields(0xc0031b0ee0?, 0xc0004fd680?, 0xc00021a0f0?)
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/internal/core/dep/dep.go:91 +0xbd
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies(0xc0031dd680, 0xc0038797a0, 0xc0004fd680?)
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/tools/flow/tasks.go:229 +0x8d
cuelang.org/go/tools/flow.(*Controller).initTasks(0xc0031dd680)
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/tools/flow/tasks.go:50 +0xfe
cuelang.org/go/tools/flow.New(0xc0003f5c30, {0xd7ea18?, 0xc00038f730?}, 0xc002753720)
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/tools/flow/flow.go:243 +0x1df
cuelang.org/go/cmd/cue/cmd.doTasks(0xc0003f5ce0?, {0x5d25e5?, 0xc0000cc100?}, {0xc000365ec0, 0xe}, 0x5d657a?)
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/cmd/cue/cmd/custom.go:132 +0x118
cuelang.org/go/cmd/cue/cmd.addCustom.func1(0x5aded1?, {0xc0000cc100?, 0x5d2680?, 0xc0003f5cc8?})
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/cmd/cue/cmd/custom.go:116 +0x2d
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc000004780?, {0x123c638?, 0x0?, 0x0?})
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/cmd/cue/cmd/root.go:48 +0x4d
github.com/spf13/cobra.(*Command).execute(0xc000004780, {0x123c638, 0x0, 0x0})
        /home/kevin/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003a8500)
        /home/kevin/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /home/kevin/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc000399620, {0x2?, 0x2?})
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/cmd/cue/cmd/root.go:217 +0x6b
cuelang.org/go/cmd/cue/cmd.mainErr({0xd833f0, 0xc0000460f0}, {0xc0000360a0?, 0xc0000061a0?, 0x200000003?})
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/cmd/cue/cmd/root.go:154 +0x55
cuelang.org/go/cmd/cue/cmd.Main()
        /home/kevin/go/pkg/mod/cuelang.org/go@v0.5.0-alpha.1/cmd/cue/cmd/root.go:136 +0x7c
```

**Comment by myitcv** [comment]
Thanks for raising this, @kghenderson.

Interesting to note that with 102b0341dae9 the panic disappears, but is replaced with:

```
$ cue cmd tangle_sublime
command.tangle_sublime.do.debugSourceFile.contents: 1 errors in empty disjunction:
command.tangle_sublime: error in call to encoding/yaml.Marshal: yaml: unsupported node import "list", "strings" (*ast.ImportDecl):
    ./tangle_sublime_tool.cue:87:83
```

So there is clearly some issue here. 

I've not done any serious analysis yet, but this is potentially related to https://github.com/cue-lang/cue/issues/2030

**Comment by mpvl** [comment]
I see that the CUE AST -> yaml converter explicitly disallows the existence of imports.  One could argue that, instead, imports should just be ignored.

**Comment by myitcv** [comment]
Noting this is a regression from v0.4.3.

**Comment by myitcv** [comment]
Further analysis: there is a panic lurking in here somewhere too, because changing the input allows me to recreate a panic (using https://github.com/cue-lang/cue/commit/102b0341dae9420a6cd125678c96b3cd8c32ed2f).

**Comment by myitcv** [comment]
I have a repro for the panic:

```
exec cue cmd tangle_sublime
cmp stdout stdout.golden

-- other.cue --
package tangle_sublime

import (
	"strings"
	"list"

)

keyzen: KeyZen: {
	Commands: {
		CommandNames: ["CursorMoveToLineForward"]
		CommandDetailsMap: {
			CursorMoveToLineForward: {
				Human:       "Cursor Down"
				Category:    "Cursor"
				Subcategory: ""
			}
		}
	}
	Editors: {
		SublimeText: {
			EditorCommandNameMap: {
				CursorMoveToLineForward: {
					command: "move"
					// delete this line to remove panic
					argsText: "test"
				}
			}
		}
	}
	Strokes: {
		ZenStrokes1: {
			Name: "ZenStrokes1"
			StrokeCmdDefsMap: {
				CursorMoveToLineForward: [["Down"], ["Hyper+K"]]
			}
			StrokesMap: {
				CursorMoveToLineForward: [{
					Bindings: {
						Linux: {
							Down: 10
						}
					}
					DefText: "Down"
				}]
			}
		}
	}

}

args: {
	editorName:   "SublimeText"
	strokesName:  "ZenStrokes1"
	platformName: "Linux"
	fileName:     "_" + strings.ToLower(editorName) + "_strokes.json5"
}

cmdNames:      keyzen.KeyZen.Commands.CommandNames
editorCmds:    keyzen.KeyZen.Editors["\(args.editorName)"].EditorCommandNameMap
strokeCmdsMap: keyzen.KeyZen.Strokes["\(args.strokesName)"].StrokesMap

buildSource: {
	EditorName:   args.editorName
	StrokesName:  args.strokesName
	PlatformName: args.platformName

	CommandBindingsCount: len(CommandBindings)

	CommandBindings: [
		for cmdIdx, cmdName in cmdNames
		if keyzen.KeyZen.Strokes[StrokesName].StrokesMap[cmdName] != _|_ &&
			editorCmds[cmdName] != _|_ {
			let cmdDetails = keyzen.KeyZen.Commands.CommandDetailsMap[cmdName]
			let strokeDefs = keyzen.KeyZen.Strokes[StrokesName].StrokesMap[cmdName]
			let editorCmd = editorCmds[cmdName]

			let editorCmdText = editorCmd.argsText
			let editorCmdTextCommand = "\"command\": \"" + editorCmd.command + "\""

			CmdName:      cmdName
			CmdHumanName: cmdDetails["Human"]

			EditorCmdText: string
			if editorCmdText == _|_ {EditorCmdText: editorCmdTextCommand}
			if editorCmdText != _|_ {EditorCmdText: editorCmdTextCommand + ", \"args\": " + editorCmd.argsText}

			BindingsCount: len(Bindings)
			if BindingsCount == 0 {{BindingsMax: 0}}
			if BindingsCount > 0 {{BindingsMax: BindingsCount - 1}}
			Bindings: [
				for _, strokeDef in strokeDefs {
					let bindingMap = strokeDef.Bindings["\(PlatformName)"]
					let bindingIds = [ for k, v in bindingMap {name: k, idx: v}]
					let bindingIdsSorted = list.Sort(bindingIds, {x: {}, y: {}, less: x.idx < y.idx})
					let bindingKeys = [ for _, kv in bindingIdsSorted {kv.name}]
					let bindingText = strings.Join(bindingKeys, "+")
					"DefText":  "\(strokeDef.DefText)"
					"BindText": bindingText
				},
			]
		},
	]
}
-- tangle_sublime_tool.cue --
package tangle_sublime

import (
	"encoding/yaml"
	"tool/cli"
)

command: tangle_sublime: {
	debugSourceFile: cli.Print & {text: yaml.Marshal(buildSource)}
}
-- stdout.golden --
EditorName: SublimeText
StrokesName: ZenStrokes1
PlatformName: Linux
CommandBindingsCount: 1
CommandBindings:
  - CmdName: CursorMoveToLineForward
    CmdHumanName: Cursor Down
    EditorCmdText: '"command": "move", "args": test'
    BindingsCount: 1
    BindingsMax: 0
    Bindings:
      - DefText: Down
        BindText: Down

```

### What did you expect to see?

A passing test. It passes with `v0.4.3`.

### What did you see instead?

```
> exec cue cmd tangle_sublime
[stderr]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x308bcc]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0x400040fe70)
	/home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:232 +0x98
panic({0x6e2260, 0xd0aa40})
	/home/myitcv/gos/src/runtime/panic.go:838 +0x20c
cuelang.org/go/internal/core/dep.visit.func1()
	/home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:121 +0xc0
panic({0x6e2260, 0xd0aa40})
	/home/myitcv/gos/src/runtime/panic.go:838 +0x20c
cuelang.org/go/internal/core/dep.visit.func1()
	/home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:121 +0xc0
panic({0x6e2260, 0xd0aa40})
	/home/myitcv/gos/src/runtime/panic.go:838 +0x20c
cuelang.org/go/internal/core/dep.visit.func1()
	/home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:121 +0xc0
panic({0x6e2260, 0xd0aa40})
	/home/myitcv/gos/src/runtime/panic.go:838 +0x20c
cuelang.org/go/cue.Selector.Type({{0x0?, 0x0?}})
	/home/myitcv/dev/cuelang/cue/cue/path.go:162 +0x2c
cuelang.org/go/cue.Path.String({{0x4000399f80?, 0x4000300450?, 0x400007f0e0?}})
	/home/myitcv/dev/cuelang/cue/cue/path.go:288 +0xa8
cuelang.org/go/tools/flow.(*Controller).getTask(0x4000000480, 0x0, {0x4000415280?, 0x400007f0e0?, 0x0?})
	/home/myitcv/dev/cuelang/cue/tools/flow/tasks.go:98 +0xb8
cuelang.org/go/tools/flow.(*Controller).findImpliedTask(0x4000000480, {0x400007f0e0, {0x8cbb08, 0x4000445680}, 0x0})
	/home/myitcv/dev/cuelang/cue/tools/flow/tasks.go:203 +0x1cc
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies.func1({0x400007f0e0, {0x8cbb08, 0x4000445680}, 0x0})
	/home/myitcv/dev/cuelang/cue/tools/flow/tasks.go:230 +0x54
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0x400040e4b8, 0x40003d0360, {0x8cbb08?, 0x4000445680})
	/home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:237 +0x248
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x400040e4b8, 0x40003d0360, {0xffff80360088?, 0x4000445680?})
	/home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:151 +0x534
cuelang.org/go/internal/core/dep.visit(0x7039e0?, 0x400040e820?, 0x400040e588?, 0x60?, 0xe5?)
	/home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:126 +0x1a8
cuelang.org/go/internal/core/dep.dynamic(0x7039e0?, 0x400007f7a0, 0x400040e658?, 0x400040e630?, 0x50?)
	/home/myitcv/dev/cuelang/cue/internal/core/dep/mixed.go:43 +0xfc
cuelang.org/go/internal/core/dep.dynamic(0x7039e0?, 0x400007f320, 0x0?, 0x1?, 0x0?)
	/home/myitcv/dev/cuelang/cue/internal/core/dep/mixed.go:51 +0x174
cuelang.org/go/internal/core/dep.dynamic(0x400007e870?, 0x400007eea0, 0x400007eea0?, 0x0?, 0x48?)
	/home/myitcv/dev/cuelang/cue/internal/core/dep/mixed.go:51 +0x174
cuelang.org/go/internal/core/dep.VisitFields(0x400040e918?, 0x56893c?, 0xe7dc1cd0adbfe2ed?)
	/home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:91 +0x94
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies(0x4000000480, 0x4000000c60, 0x400007eea0?)
	/home/myitcv/dev/cuelang/cue/tools/flow/tasks.go:229 +0x98
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies.func1({0x400007eea0, {0x8cba48, 0x4000415830}, 0x0})
	/home/myitcv/dev/cuelang/cue/tools/flow/tasks.go:245 +0x218
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0x400040ed88, 0x400038d480, {0x8cba48?, 0x4000415830})
	/home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:237 +0x248
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x400040ed88, 0x400038d480, {0xffff81e16798?, 0x4000415830?})
	/home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:151 +0x534
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x400040ed88, 0x400038d480, {0x8cda28?, 0x4000445470?})
	/home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:173 +0x588
cuelang.org/go/internal/core/dep.visit(0x7039e0?, 0x400040f1c0?, 0x400040ee58?, 0x30?, 0xee?)
	/home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:126 +0x1a8
cuelang.org/go/internal/core/dep.dynamic(0x7039e0?, 0x400007ee10, 0x400040ef28?, 0x400040ef00?, 0x50?)
	/home/myitcv/dev/cuelang/cue/internal/core/dep/mixed.go:43 +0xfc
cuelang.org/go/internal/core/dep.dynamic(0x7039e0?, 0x400007e870, 0x400040eff8?, 0x400040efd0?, 0x50?)
	/home/myitcv/dev/cuelang/cue/internal/core/dep/mixed.go:51 +0x174
cuelang.org/go/internal/core/dep.dynamic(0x7039e0?, 0x400007e630, 0x0?, 0x1?, 0x0?)
	/home/myitcv/dev/cuelang/cue/internal/core/dep/mixed.go:51 +0x174
cuelang.org/go/internal/core/dep.dynamic(0x4000279950?, 0x400027f320, 0x400027f320?, 0x0?, 0xe8?)
	/home/myitcv/dev/cuelang/cue/internal/core/dep/mixed.go:51 +0x174
cuelang.org/go/internal/core/dep.VisitFields(0x400040f2b8?, 0x56893c?, 0xde1047d97111c23a?)
	/home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:91 +0x94
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies(0x4000000480, 0x4000000c60, 0x400027f320?)
	/home/myitcv/dev/cuelang/cue/tools/flow/tasks.go:229 +0x98
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies.func1({0x400027f320, {0x8cba48, 0x400046ef50}, 0x0})
	/home/myitcv/dev/cuelang/cue/tools/flow/tasks.go:245 +0x218
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0x400040f728, 0x4000543460, {0x8cba48?, 0x400046ef50})
	/home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:237 +0x248
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x400040f728, 0x4000543460, {0xffff81e16798?, 0x400046ef50?})
	/home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:151 +0x534
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x400040f728, 0x4000543460, {0x8cda28?, 0x4000488cc0?})
	/home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:173 +0x588
cuelang.org/go/internal/core/dep.visit(0x7039e0?, 0x400040f9c0?, 0x400040f7f8?, 0xd0?, 0xf7?)
	/home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:126 +0x1a8
cuelang.org/go/internal/core/dep.dynamic(0x7039e0?, 0x40000cbb00, 0x0?, 0x1?, 0x50?)
	/home/myitcv/dev/cuelang/cue/internal/core/dep/mixed.go:43 +0xfc
cuelang.org/go/internal/core/dep.dynamic(0x7600004000192c30?, 0x40000cb050, 0x40000cb050?, 0x0?, 0x28?)
	/home/myitcv/dev/cuelang/cue/internal/core/dep/mixed.go:51 +0x174
cuelang.org/go/internal/core/dep.VisitFields(0x4000711dc0?, 0x40000cafc0?, 0x4000415280?)
	/home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:91 +0x94
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies(0x4000000480, 0x4000000c60, 0x40000cafc0?)
	/home/myitcv/dev/cuelang/cue/tools/flow/tasks.go:229 +0x98
cuelang.org/go/tools/flow.(*Controller).initTasks(0x4000000480)
	/home/myitcv/dev/cuelang/cue/tools/flow/tasks.go:50 +0xf4
cuelang.org/go/tools/flow.New(0x400040fbf0, {0x8c9098?, 0x400030dc00?}, 0x40004b63f0)
	/home/myitcv/dev/cuelang/cue/tools/flow/flow.go:243 +0x1e4
cuelang.org/go/cmd/cue/cmd.doTasks(0x400040fca8?, {0x1c61ac?, 0x40000cd600?}, {0x400049b0f0, 0xe}, 0x1c5dd4?)
	/home/myitcv/dev/cuelang/cue/cmd/cue/cmd/custom.go:132 +0x110
cuelang.org/go/cmd/cue/cmd.addCustom.func1(0x400040fca8?, {0x1c606c?, 0x40000cd600?, 0x1c6b00?})
	/home/myitcv/dev/cuelang/cue/cmd/cue/cmd/custom.go:116 +0x34
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0x40000bcc80?, {0xd622a8?, 0x0?, 0x0?})
	/home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:48 +0x70
github.com/spf13/cobra.(*Command).execute(0x40000bcc80, {0xd622a8, 0x0, 0x0})
	/home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x4dc
github.com/spf13/cobra.(*Command).ExecuteC(0x40003b8500)
	/home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x360
github.com/spf13/cobra.(*Command).Execute(...)
	/home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0x40003a96b0, {0x2?, 0x2?})
	/home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:217 +0x60
cuelang.org/go/cmd/cue/cmd.mainErr({0x8cd7f8, 0x400003a0a0}, {0x40000320a0?, 0x40000021a0?, 0x4000077f28?})
	/home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:154 +0x5c
cuelang.org/go/cmd/cue/cmd.Main()
	/home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:136 +0x8c
main.main()
	/home/myitcv/dev/cuelang/cue/cmd/cue/main.go:24 +0x20
[exit status 2]
FAIL: /tmp/testscript1664132178/repro.txtar/script.txtar:1: unexpected command failure
```

**Comment by mpvl** [comment]
A simpler reproducer:
```
exec cue cmd ts
cmp stdout stdout.golden

-- ts_tool.cue --
package ts

import "tool/cli"

let X = {c: d: 0}

a: b: X.c

command: ts: cli.Print & {text: "", x: a}
```

**Comment by rogpeppe** [comment]
ha, that's simpler than mine! i'd got to this:
```
exec cue cmd p

-- test_tool.cue --
package p

import (
	"text/template"
	"tool/file"
)

k: c: m: "a"

command: p: {
	s: {
		let v1 = k
		x: {
			let v2 = v1.c
			y: v2.m
		}
	}

	writeFile: file.Create & {
		filename: "/dev/null"
		contents: template.Execute("", s)
	}
}
```
