### ISSUE TITLE
eval: panic in alias reference to dynamic field

### ISSUE THREAD

**Issue by mpvl** [cue-lang/cue#2094]
### What version of CUE are you using (`cue version`)?

tip and 0.4.3

### Does this issue reproduce with the latest release?
Yes

### What did you do?

```
Y=(X): string
X=("foo"): "bar"
```
Ordering matters.

### What did you expect to see?

```
bar: string
foo: "bar"
```

### What did you see instead?
panic

**Comment by myitcv** [comment]
Not sure whether you intended this for v0.5.0, so marking as such just in case. We can always remove later.

**Comment by mvdan** [comment]
Still happens:

```
$ cue version
cue version v0.6.0-alpha.1.0.20230612151802-12908b32a9a7

go version devel go1.21-c3db64c0f4 Wed Jun 14 01:36:27 2023 +0000
      -buildmode exe
       -compiler gc
        -ldflags -w -s
  DefaultGODEBUG panicnil=1
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v3
$ cue eval f.cue
panic: unreachable [recovered]
	panic: unreachable

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc00037de78)
	/home/mvdan/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1.0.20230612151802-12908b32a9a7/cmd/cue/cmd/root.go:275 +0x76
panic({0xc33660?, 0xe9b830?})
	/home/mvdan/tip/src/runtime/panic.go:914 +0x21f
cuelang.org/go/internal/core/compile.(*compiler).resolve(0xc0003061c0, 0xc000320a50)
	/home/mvdan/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1.0.20230612151802-12908b32a9a7/internal/core/compile/compile.go:498 +0xdcd
cuelang.org/go/internal/core/compile.(*compiler).expr(0xc00037cf00?, {0xeabe10?, 0xc000320a50?})
	/home/mvdan/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1.0.20230612151802-12908b32a9a7/internal/core/compile/compile.go:841 +0x4d
[...]
```

**Comment by mvdan** [comment]
Still panics as of v0.9.0-alpha.1.

**Comment by mvdan** [comment]
Still happens as of a03ed2e9a14b9a4b0340a49c89803f4e712f4323, which makes sense, as the panic is in the compiler.

**Comment by jpluscplusm** [comment]
This still panics under CUE v0.14.1.
