### ISSUE TITLE
tools/flow: top-level task causes task function to be called with spurious value

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#2185]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.5.0-beta.2

       -compiler gc
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
go mod tidy
exec go run .

-- go.mod --
module test

go 1.19

require cuelang.org/go v0.5.0-beta.2

-- main.go --
package main

import (
	"context"
	"fmt"
	"log"

	"cuelang.org/go/cue"
	"cuelang.org/go/cue/cuecontext"
	"cuelang.org/go/tools/flow"
)

func main() {
	ctx := cuecontext.New()
	top := ctx.CompileString("_")
	taskDef := ctx.CompileString(`
#task: {
	task: true
	fn: #func
}
#func: _
`)
	if err := taskDef.Err(); err != nil {
		log.Fatalf("cannot build instances: %v", err)
	}
	task := taskDef.LookupPath(cue.MakePath(cue.Def("#task")))
	if err := task.Err(); err != nil {
		panic(fmt.Errorf("cannot find #call in funcsig package: %v", err))
	}
	ctl := flow.New(&flow.Config{
		InferTasks: true,
	}, task, func(v cue.Value) (flow.Runner, error) {
		if !isTask(v) {
			return nil, nil
		}
		return flow.RunnerFunc(func(t *flow.Task) error {
			v := t.Value()
			if !isTask(v) {
				panic(fmt.Errorf("runner called on non-task:\n%#v", v))
			}
			if err := t.Fill(top); err != nil {
				panic(fmt.Errorf("cannot fill task: %v", err))
			}
			return nil
		}), nil
	})
	ctl.Run(context.Background())
}

func isTask(v cue.Value) bool {
	return v.LookupPath(cue.MakePath(cue.Str("task"))).Err() == nil
}
```

### What did you expect to see?

A passing test.

### What did you see instead?

```
> go mod tidy
> exec go run .
[stderr]
panic: runner called on non-task:
#task: {
	task: true
	fn:   #func
}
#func: _

goroutine 35 [running]:
main.main.func1.1(0xc0003c8b40)
	$WORK/main.go:39 +0x197
cuelang.org/go/tools/flow.RunnerFunc.Run(0x0?, 0x0?, {0x0?, 0x0?})
	/home/rogpeppe/src/go/pkg/mod/cuelang.org/go@v0.5.0-beta.2/tools/flow/flow.go:121 +0x1f
cuelang.org/go/tools/flow.(*Controller).runLoop.func1(0xc0003c8b40)
	/home/rogpeppe/src/go/pkg/mod/cuelang.org/go@v0.5.0-beta.2/tools/flow/run.go:70 +0x35
created by cuelang.org/go/tools/flow.(*Controller).runLoop
	/home/rogpeppe/src/go/pkg/mod/cuelang.org/go@v0.5.0-beta.2/tools/flow/run.go:69 +0x6f8
exit status 2
[exit status 1]
FAIL: /tmp/testscript3187012830/x.txtar/script.txtar:2: unexpected command failure
```

The value passed to the Runner isn't the task that the task function returned the Runner for.

**Comment by myitcv** [comment]
@rogpeppe are you intentionally using `InferTasks`?

From the comment of that feature:

```
	// InferTasks allows tasks to be defined outside of the Root. Such tasks
	// will only be included in the workflow if any of its fields is referenced
	// by any of the tasks defined within Root.
	//
	// CAVEAT EMPTOR: this features is mostly provided for backwards
	// compatibility with v0.2. A problem with this approach is that it will
	// look for task structs within arbitrary data. So if not careful, there may
	// be spurious matches.
```

**Comment by rogpeppe** [comment]
@myitcv Yes, I'm intentionally using `InferTasks` - it's not a problem for the use case here because I am being "careful" - i.e. using private fields to indicate that a task is present.
