### ISSUE TITLE
pkg/encoding/yaml: panic in Marshal

### ISSUE THREAD

**Issue by verdverm** [cue-lang/cue#2230]
### What version of CUE are you using (`cue version`)?

```
cue version v0.5.0-beta.2

       -compiler gc
        -ldflags -s -w
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
```

### What did you do?

```go
exec go run repro.go

-- repro.go --
package main

import (
	"fmt"

	"cuelang.org/go/cue"
	cueyaml "cuelang.org/go/pkg/encoding/yaml"
)

var input = `
foo:
  b: "B"
  a: "A"
`

func main() {
	x, err := cueyaml.Unmarshal([]byte(input))
	if err != nil {
		fmt.Println("error:", err)
		return
	}	

	var c cue.Context
	v := c.BuildExpr(x)

	s, err := cueyaml.Marshal(v)
	if err != nil {
		fmt.Println("error:", err)
		return
	}

	fmt.Println(s)	
}

```

### What did you expect to see?

formatted yaml

### What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x64199a]

goroutine 1 [running]:
cuelang.org/go/internal/core/runtime.(*Runtime).GetInstanceFromNode(0xc00030bd60?, 0x40d807?)
        /home/tony/go/pkg/mod/cuelang.org/go@v0.5.0-beta.2/internal/core/runtime/imports.go:119 +0x3a
cuelang.org/go/cue.getImportFromNode(0x0?, 0xc00030bd60?)
        /home/tony/go/pkg/mod/cuelang.org/go@v0.5.0-beta.2/cue/instance.go:110 +0x25
cuelang.org/go/cue.Value.instance(...)
        /home/tony/go/pkg/mod/cuelang.org/go@v0.5.0-beta.2/cue/types.go:1942
cuelang.org/go/cue.Value.Syntax({0xc00030f2d0?, 0xc000336750?, 0x0?}, {0xc00030bec0, 0x2, 0x7e25f2970000?})
        /home/tony/go/pkg/mod/cuelang.org/go@v0.5.0-beta.2/cue/types.go:989 +0x1a8
cuelang.org/go/pkg/encoding/yaml.Marshal({0xc00030f2d0?, 0xc000336750?, 0x0?})
        /home/tony/go/pkg/mod/cuelang.org/go@v0.5.0-beta.2/pkg/encoding/yaml/manual.go:34 +0x118
main.main()
        /home/tony/hof/hof/formatters/test/repro.go:26 +0xea
exit status 2
```

**Comment by mvdan** [comment]
I can reproduce with f23e3d565c49 as well as v0.4.3, so at least this is not a recent regression.

**Comment by myitcv** [comment]
This appears to be a bug in the repro: `cue.Context` is not initialised and the zero value cannot be used. We should "fix" this on our side, by panicing/similar more loudly in case a `cue.Context` is used in this way, rather than via `cuecontext.New()`.
