### ISSUE TITLE
evaluator: nil dereference panic regression in v0.5.0-beta.3

### ISSUE THREAD

**Issue by mvdan** [cue-lang/cue#2235]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.5.0-beta.3

      -buildmode exe
       -compiler gc
        -ldflags -w -s
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v3
</pre>

### Does this issue reproduce with the latest release?

* v0.4.2 works
* v0.4.3 gives error `cannot add field "...": was already used`
* v0.5.0-beta.1 works
* v0.5.0-beta.2 gives error `cannot add field "...": was already used`
* v0.5.0-beta.3 panics per the output below

### What did you do?

```
exec cue export root.cue

-- root.cue --
package kubecluster

import (
	"strings"
	"net"
)

shorewallParams: close({
	[=~"^[A-Z0-9_]+$"]: [...net.IP]
})

#Cluster: {
	clusterName:     string
	shorewallPrefix: "KUBERNETES_\(strings.ToUpper(clusterName))"
}

clusters: [CLUSTER=string]: #Cluster & {
	clusterName: CLUSTER
}

#Cluster: {
	globalIngressControllers: [string]: #GlobalIngressController
	globalIngressControllers: admin:    #GlobalIngressController & {
		class: "admin"
	}
	for _, c in globalIngressControllers {
		objects: c.objects
	}
}

for clusterName, cluster in clusters {
	for class, controller in cluster.globalIngressControllers {
		let svc = controller.objects.namespaced.ingress.Service["\(class)-nginx-ingress-controller"]

		shorewallParams: "\(cluster.shorewallPrefix)_INGRESS_\(strings.ToUpper(class))": svc.spec.externalIPs
	}
}

#GlobalIngressController: {
	class: string

	objects: namespaced: ingress: {
		Service: "\(class)-nginx-ingress-controller": {
			spec: {
				externalIPs: ["127.0.0.1"]
			}
		}
	}

	for kind, objs in objects.namespaced.ingress {
		for name, obj in objs {
			objects: namespaced: ingress: "\(kind)": "\(name)": metadata: labels: {
				"ingress-class": class
				stack:           "ingress"
				...
			}
		}
	}
}

clusters: foo: {}
```

### What did you expect to see?

Presumably, the same output as v0.5.0-beta.1, or at least no panic if the error reported by v0.5.0-beta.2 was intentional and correct.

### What did you see instead?

```
> exec cue export root.cue
[stderr]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x68537a]

goroutine 1 [running]:
panic({0xb5dd20?, 0x11c4650?})
	/home/mvdan/tip/src/runtime/panic.go:1015 +0x41b fp=0xc0004bcc80 sp=0xc0004bcbb8 pc=0x4360fb
cuelang.org/go/cmd/cue/cmd.recoverError(0xc0004c3e90)
	/home/mvdan/go/pkg/mod/cuelang.org/go@v0.5.0-beta.3/cmd/cue/cmd/root.go:261 +0x71 fp=0xc0004bcca0 sp=0xc0004bcc80 pc=0xabdb11
cuelang.org/go/cmd/cue/cmd.(*Command).Run.func1()
	/home/mvdan/go/pkg/mod/cuelang.org/go@v0.5.0-beta.3/cmd/cue/cmd/root.go:244 +0x25 fp=0xc0004bccb8 sp=0xc0004bcca0 pc=0xabda65
runtime.deferCallSave(0xc0004bcd90, 0xc0004c3ea0?)
	/home/mvdan/tip/src/runtime/panic.go:796 +0x82 fp=0xc0004bccc8 sp=0xc0004bccb8 pc=0x435c42
runtime.runOpenDeferFrame(0xc000278730)
	/home/mvdan/tip/src/runtime/panic.go:769 +0x1a5 fp=0xc0004bcd10 sp=0xc0004bccc8 pc=0x435a85
panic({0xb5dd20?, 0x11c4650?})
	/home/mvdan/tip/src/runtime/panic.go:912 +0x265 fp=0xc0004bcdd8 sp=0xc0004bcd10 pc=0x435f45
runtime.panicmem(...)
	/home/mvdan/tip/src/runtime/panic.go:260
runtime.sigpanic()
	/home/mvdan/tip/src/runtime/signal_unix.go:837 +0x376 fp=0xc0004bce38 sp=0xc0004bcdd8 pc=0x44be36
cuelang.org/go/internal/core/adt.(*nodeContext).addConjunctDynamic(0x0, {0xc0002d78c0, {0xd3daf0, 0xc000495f80}, {0xc0002d7460, 0x0, 0x0, {0x0, 0x0, 0xc000626450}}})
	/home/mvdan/go/pkg/mod/cuelang.org/go@v0.5.0-beta.3/internal/core/adt/composite.go:826 +0x1a fp=0xc0004bce98 sp=0xc0004bce38 pc=0x68537a
cuelang.org/go/internal/core/adt.(*nodeContext).notifyConjunct(0xc000601800?, {0xc0002d78c0, {0xd3daf0, 0xc000495f80}, {0xc0002d7460, 0x0, 0x0, {0x0, 0x0, 0xc000626450}}})
	/home/mvdan/go/pkg/mod/cuelang.org/go@v0.5.0-beta.3/internal/core/adt/composite.go:835 +0x132 fp=0xc0004bcf90 sp=0xc0004bce98 pc=0x685612
cuelang.org/go/internal/core/adt.(*nodeContext).addConjunctDynamic(0xc000601800, {0xc0002d78c0, {0xd3daf0, 0xc000495f80}, {0xc0002d7460, 0x0, 0x0, {0x0, 0x0, 0xc000626450}}})
	/home/mvdan/go/pkg/mod/cuelang.org/go@v0.5.0-beta.3/internal/core/adt/composite.go:828 +0x15c fp=0xc0004bcff0 sp=0xc0004bcf90 pc=0x6854bc
cuelang.org/go/internal/core/adt.(*nodeContext).insertField(0xc000500400, 0x751, {0xc0002d78c0, {0xd3daf0, 0xc000495f80}, {0xc0002d7460, 0x0, 0x0, {0x0, 0x0, ...}}})
	/home/mvdan/go/pkg/mod/cuelang.org/go@v0.5.0-beta.3/internal/core/adt/eval.go:2013 +0x3e5 fp=0xc0004bd100 sp=0xc0004bcff0 pc=0x6a2c85
[many more lines]
```

**Comment by mvdan** [comment]
Smaller repro:

```
exec cue export root.cue

-- root.cue --
params: [string]: _

root: {
	objects: obj1: obj2: {}

	for name1, obj in objects {
		for name2, _ in obj {
			objects: (name1): (name2): {}
		}
	}
}

params: root.objects.obj1
```

**Comment by mpvl** [comment]
This is another one. Different path that triggers it:

```
out: X.undefined

let X = m.x

m: x: {}

for v in m {
	if true {
		m: x:  {}
	}
}
```

**Comment by mpvl** [comment]
Simplification of first smaller repro:
```
params: x.y

x: y: {}

for _ in x {
	if true {
		x: y: a: {}
	}
}
```
Note the similarity to the example using let.
