### ISSUE TITLE
BUG: panic when using alias

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#229]
_Originally opened by @rudolph9 in https://github.com/cuelang/cue/issues/229_

Cue: v0.0.15
The following evaluates as expected when `fooNestedShape` is a field:
```
Foo :: {
	{...}
	[string]: float
}

Bar :: {
	foo: {
		a: Foo
		b: Foo
	}
	fooNestedShape: {
		{...}
		{for k, v in (and([ {for k, v in p {"\(k)": _}} for p in [foo.a, foo.b] ])) {"\(k)": _}}
	}
	fooShape: {
		{...}
		for k, v in foo {"\(k)": fooNestedShape}
	}
	for n, _ in fooNestedShape {
		foo: {
			a: "\(n)": b + 1
			b: "\(n)": a - 1
		}
	}
}
```

```
:!cue eval /tmp/bug.cue --all
Foo :: {
    [string]: float
}
Bar :: {
    foo: {
        a: {
            [string]: float
        }
        b: {
            [string]: float
        }
    }
    fooNestedShape: {
        [string]: _
    }
    fooShape: {
        [string]: _
        a: {
            [string]: _
        }
        b: {
            [string]: _
        }
    }
}
```

But results in a panic if `fooNestedShape` is declared as an alias:
```
Foo :: {
	{...}
	[string]: float
}

Bar :: {
	foo: {
		a: Foo
		b: Foo
	}
	fooNestedShape = {
		{...}
		{for k, v in (and([ {for k, v in p {"\(k)": _}} for p in [foo.a, foo.b] ])) {"\(k)": _}}
	}
	fooShape: {
		{...}
		for k, v in foo {"\(k)": fooNestedShape}
	}
	for n, _ in fooNestedShape {
		foo: {
			a: "\(n)": b + 1
			b: "\(n)": a - 1
		}
	}
}
```

```
:!cue eval /tmp/bug.cue --all
panic: already defined [recovered]
        panic: already defined

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc0002c5ee8)
        /home/username/.golang/src/cuelang.org/go/cmd/cue/cmd/root.go:211 +0xa3
panic(0xb1b0a0, 0xd14af0)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
cuelang.org/go/cue.(*astState).setScope(...)
        /home/username/.golang/src/cuelang.org/go/cue/ast.go:100
cuelang.org/go/cue.wrapClauses(0xc0002b4a00, 0xd3e2c0, 0xc0002aa920, 0xc0002a60a0, 0x1, 0x1, 0xc0002b0900, 0x18)
        /home/username/.golang/src/cuelang.org/go/cue/ast.go:747 +0xca8
cuelang.org/go/cue.(*astVisitor).walk(0xc0002b4a00, 0xd395e0, 0xc0002638c0, 0x0, 0x0)
        /home/username/.golang/src/cuelang.org/go/cue/ast.go:328 +0x7bf
cuelang.org/go/cue.(*astVisitor).walk(0xc0002b4840, 0xd39ca0, 0xc0002a5f90, 0xd3cb20, 0xc0002b2540)
        /home/username/.golang/src/cuelang.org/go/cue/ast.go:277 +0x6930
cuelang.org/go/cue.(*astVisitor).walk(0xc0002b4000, 0xd39ca0, 0xc0002ac000, 0xd3c100, 0xc0002b49c0)
        /home/username/.golang/src/cuelang.org/go/cue/ast.go:258 +0x69b8
cuelang.org/go/cue.(*astVisitor).walk(0xc0002b4000, 0xd39820, 0xc0002ad090, 0x0, 0x0)
        /home/username/.golang/src/cuelang.org/go/cue/ast.go:531 +0x2a7f
cuelang.org/go/cue.wrapClauses(0xc0002b4000, 0xd3e2c0, 0xc0002aa880, 0xc0002a6130, 0x1, 0x1, 0x0, 0x0)
        /home/username/.golang/src/cuelang.org/go/cue/ast.go:766 +0x52d
cuelang.org/go/cue.(*astVisitor).walk(0xc0002b4000, 0xd395e0, 0xc000263c80, 0x0, 0x0)
        /home/username/.golang/src/cuelang.org/go/cue/ast.go:328 +0x7bf
cuelang.org/go/cue.(*astVisitor).walk(0xc000263dc0, 0xd39ca0, 0xc0002ae460, 0xd3cb20, 0xc0002b2150)
        /home/username/.golang/src/cuelang.org/go/cue/ast.go:277 +0x6930
cuelang.org/go/cue.(*astVisitor).walk(0xc000263dc0, 0xd39700, 0xc00025d880, 0x0, 0x0)
        /home/username/.golang/src/cuelang.org/go/cue/ast.go:445 +0x1774
cuelang.org/go/cue.(*astVisitor).walk(0xc000263d40, 0xd39760, 0xc0002a82a0, 0x0, 0x0)
        /home/username/.golang/src/cuelang.org/go/cue/ast.go:211 +0x59a3
cuelang.org/go/cue.(*Instance).insertFile(0xc0001c5900, 0xc0002a82a0, 0x0, 0x0)
        /home/username/.golang/src/cuelang.org/go/cue/ast.go:47 +0x225
cuelang.org/go/cue.(*index).loadInstance(0xc0001c5880, 0xc0000dc800, 0x0)
        /home/username/.golang/src/cuelang.org/go/cue/build.go:328 +0x12b
cuelang.org/go/cue.(*Runtime).build(0xc000249a38, 0xc0000bbca8, 0x1, 0x1, 0xc000237d00, 0xa, 0x8, 0x203000, 0x203000)
        /home/username/.golang/src/cuelang.org/go/cue/build.go:181 +0x13a
cuelang.org/go/cue.Build(0xc0000bbca8, 0x1, 0x1, 0xc00025d570, 0x70, 0x68)
        /home/username/.golang/src/cuelang.org/go/cue/build.go:166 +0x5a
cuelang.org/go/cmd/cue/cmd.buildInstances(0xc000237900, 0xc0000bbca8, 0x1, 0x1, 0xc0000bbca8, 0x1, 0x1)
        /home/username/.golang/src/cuelang.org/go/cmd/cue/cmd/common.go:120 +0x4c
cuelang.org/go/cmd/cue/cmd.buildFromArgs(0xc000237900, 0xc000237cc0, 0x1, 0x2, 0x7ee1db, 0xb42ec0, 0xc00028a390)
        /home/username/.golang/src/cuelang.org/go/cmd/cue/cmd/common.go:105 +0x8c
cuelang.org/go/cmd/cue/cmd.runEval(0xc000237900, 0xc000237cc0, 0x1, 0x2, 0x0, 0x0)
        /home/username/.golang/src/cuelang.org/go/cmd/cue/cmd/eval.go:82 +0x6a
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc000290a00, 0xc000237cc0, 0x1, 0x2, 0x0, 0x0)
        /home/username/.golang/src/cuelang.org/go/cmd/cue/cmd/root.go:46 +0x5f
github.com/spf13/cobra.(*Command).execute(0xc000290a00, 0xc000237ca0, 0x2, 0x2, 0xc000290a00, 0xc000237ca0)
        /home/username/.golang/src/github.com/spf13/cobra/command.go:829 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc000290500, 0xc50518, 0xc000249ee8, 0x0)
        /home/username/.golang/src/github.com/spf13/cobra/command.go:917 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /home/username/.golang/src/github.com/spf13/cobra/command.go:867
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc000237900, 0xd34d40, 0xc0000b6030, 0x0, 0x0)
        /home/username/.golang/src/cuelang.org/go/cmd/cue/cmd/root.go:196 +0x66
cuelang.org/go/cmd/cue/cmd.mainErr(0xd34d40, 0xc0000b6030, 0xc0000be050, 0x3, 0x3, 0xa8e68b, 0x126a200)
        /home/username/.golang/src/cuelang.org/go/cmd/cue/cmd/root.go:131 +0x74
cuelang.org/go/cmd/cue/cmd.Main(0xc00009e058)
        /home/username/.golang/src/cuelang.org/go/cmd/cue/cmd/root.go:116 +0x84
main.main()
        /home/username/.golang/src/cuelang.org/go/cmd/cue/main.go:24 +0x22

shell returned 2
```

**Comment by cueckoo** [comment]
_Original reply by @rudolph9 in https://github.com/cuelang/cue/issues/229#issuecomment-565844119_

closing, doesn't seem to be an issue in 27b9ca3b6a3591addac7e51d238a77fa85281ca3
