### ISSUE TITLE
evaluator: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kajogo777** [cue-lang/cue#2339]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.5.0

go version go1.19.8
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
</pre>

### Does this issue reproduce with the latest stable release?
The problem does not happen with v0.4.3

### What did you do?
Run `cue eval` in this directory https://github.com/devopzilla/guku-devx-catalog/tree/v2.0.0-alpha.58/v1/transformers/terraform/aws

### What did you expect to see?
Normal CUE definitions in the file

### What did you see instead?
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x69c958]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc00080fe90)
        cuelang.org/go@v0.5.0/cmd/cue/cmd/root.go:261 +0x7b
panic({0xb88300, 0x11cc990})
        runtime/panic.go:884 +0x212
cuelang.org/go/internal/core/adt.(*Vertex).getNodeContext(0x0?, 0xc0007ac5c0?, 0xc3ac2f?)
        cuelang.org/go@v0.5.0/internal/core/adt/eval.go:1100 +0x18
cuelang.org/go/internal/core/adt.(*OpContext).Unify(0xc000309000, 0x0, 0x2)
        cuelang.org/go@v0.5.0/internal/core/adt/eval.go:164 +0xf6
cuelang.org/go/internal/core/adt.(*OpContext).relNode(0x203000?, 0x5dc850?)
        cuelang.org/go@v0.5.0/internal/core/adt/context.go:323 +0x37
cuelang.org/go/internal/core/adt.(*FieldReference).resolve(0xc000392ba0, 0xd7ce40?, 0xa0?)
        cuelang.org/go@v0.5.0/internal/core/adt/expr.go:740 +0x2f
cuelang.org/go/internal/core/adt.(*OpContext).unifyNode(0xc000309000, {0xd7ce40, 0xc000392ba0}, 0x2)
        cuelang.org/go@v0.5.0/internal/core/adt/context.go:773 +0x1ec
cuelang.org/go/internal/core/adt.(*OpContext).node(0xc000309000, {0xd77750?, 0xc0005302c0}, {0xd7ce40?, 0xc000392ba0?}, 0x1, 0x1f?)
        cuelang.org/go@v0.5.0/internal/core/adt/context.go:962 +0x7c
cuelang.org/go/internal/core/adt.(*SelectorExpr).resolve(0xc0005302c0, 0xc000309000, 0xc0?)
        cuelang.org/go@v0.5.0/internal/core/adt/expr.go:1004 +0x65
cuelang.org/go/internal/core/adt.(*OpContext).evalState(0xc000309000, {0xd7d0c0, 0xc0005302c0}, 0x2)
        cuelang.org/go@v0.5.0/internal/core/adt/context.go:690 +0x21c
cuelang.org/go/internal/core/adt.(*OpContext).value(0xc00080c120?, {0xd7d0c0?, 0xc0005302c0?}, 0x3e?)
        cuelang.org/go@v0.5.0/internal/core/adt/context.go:637 +0x28
cuelang.org/go/internal/core/adt.(*Interpolation).evaluate(0xc000453cb0, 0xc000309000, 0xb0?)
        cuelang.org/go@v0.5.0/internal/core/adt/expr.go:1172 +0x3ac
cuelang.org/go/internal/core/adt.(*OpContext).evalState(0xc000309000, {0xd7cf00, 0xc000453cb0}, 0x2)
        cuelang.org/go@v0.5.0/internal/core/adt/context.go:686 +0x4ac
cuelang.org/go/internal/core/adt.(*OpContext).Evaluate(0xc000309000, 0xc0005daf80, {0xd7cf00, 0xc000453cb0})
        cuelang.org/go@v0.5.0/internal/core/adt/context.go:589 +0x1c9
cuelang.org/go/internal/core/export.(*exporter).decl(0xc0001542c0, 0xd7be80?, {0xd79a48?, 0xc000453d40?})
        cuelang.org/go@v0.5.0/internal/core/export/adt.go:484 +0x145
cuelang.org/go/internal/core/export.(*exporter).adt(0xc0001542c0, 0xc00058ca20, {0xd7be80?, 0xc000454360?})
        cuelang.org/go@v0.5.0/internal/core/export/adt.go:73 +0x271a
cuelang.org/go/internal/core/export.(*exporter).adt(0xc0001542c0, 0xc00058ca20, {0xd7bcf8?, 0xc0000f7bd0?})
        cuelang.org/go@v0.5.0/internal/core/export/adt.go:280 +0x1c28
cuelang.org/go/internal/core/export.(*exporter).expr(0xc0001542c0?, 0xd77390?, {0xd7bcf8?, 0xc0000f7bd0?})
        cuelang.org/go@v0.5.0/internal/core/export/expr.go:98 +0x37a
cuelang.org/go/internal/core/export.(*exporter).vertex(0xc0001542c0, 0xc0006305a0)
        cuelang.org/go@v0.5.0/internal/core/export/value.go:102 +0x9b2
cuelang.org/go/internal/core/export.(*exporter).structComposite(0xc0001542c0, 0xc000630240, {0x0, 0x0, 0x4?})
        cuelang.org/go@v0.5.0/internal/core/export/value.go:467 +0xa4e
cuelang.org/go/internal/core/export.(*exporter).vertex(0xc0001542c0, 0xc000630240)
        cuelang.org/go@v0.5.0/internal/core/export/value.go:65 +0x5c9
cuelang.org/go/internal/core/export.(*exporter).structComposite(0xc0001542c0, 0xc000630120, {0x0, 0x0, 0x3?})
        cuelang.org/go@v0.5.0/internal/core/export/value.go:467 +0xa4e
cuelang.org/go/internal/core/export.(*exporter).vertex(0xc0001542c0, 0xc000630120)
        cuelang.org/go@v0.5.0/internal/core/export/value.go:65 +0x5c9
cuelang.org/go/internal/core/export.(*exporter).structComposite(0xc0001542c0, 0xc00044b950, {0x0, 0x0, 0xc00080e5c0?})
        cuelang.org/go@v0.5.0/internal/core/export/value.go:467 +0xa4e
cuelang.org/go/internal/core/export.(*exporter).vertex(0xc0001542c0, 0xc00044b950)
        cuelang.org/go@v0.5.0/internal/core/export/value.go:65 +0x5c9
cuelang.org/go/internal/core/export.(*exporter).structComposite(0xc0001542c0, 0xc00056fd40, {0x0, 0x0, 0x16030023cc40?})
        cuelang.org/go@v0.5.0/internal/core/export/value.go:467 +0xa4e
cuelang.org/go/internal/core/export.(*exporter).vertex(0xc0001542c0, 0xc00056fd40)
        cuelang.org/go@v0.5.0/internal/core/export/value.go:65 +0x5c9
cuelang.org/go/internal/core/export.(*exporter).structComposite(0xc0001542c0, 0xc00042e870, {0x0, 0x0, 0xc0003ebcd0?})
        cuelang.org/go@v0.5.0/internal/core/export/value.go:467 +0xa4e
cuelang.org/go/internal/core/export.(*exporter).vertex(0xc0001542c0, 0xc00042e870)
        cuelang.org/go@v0.5.0/internal/core/export/value.go:65 +0x5c9
cuelang.org/go/internal/core/export.(*exporter).value(0xc0001542c0, {0xd80030?, 0xc00042e870?}, {0xc000356a80?, 0xb?, 0x10?})
        cuelang.org/go@v0.5.0/internal/core/export/value.go:182 +0x593
cuelang.org/go/internal/core/export.(*Profile).Vertex(0x8?, {0xd7e9a8?, 0xc0002d1180?}, {0xc000146120?, 0xc00023d980?}, 0xc00042e870)
        cuelang.org/go@v0.5.0/internal/core/export/export.go:202 +0x93
cuelang.org/go/cue.Value.Syntax({0xc0002d1180?, 0xc00042e870?, 0x0?}, {0xc00023db68, 0x5, 0xc00011faa8?})
        cuelang.org/go@v0.5.0/cue/types.go:1018 +0x24f
cuelang.org/go/cmd/cue/cmd.runEval(0xc0003335f0, {0x12245a8, 0x0, 0x0})
        cuelang.org/go@v0.5.0/cmd/cue/cmd/eval.go:165 +0x96f
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc000342c80?, {0x12245a8, 0x0, 0x0})
        cuelang.org/go@v0.5.0/cmd/cue/cmd/root.go:72 +0xb3
github.com/spf13/cobra.(*Command).execute(0xc000342c80, {0x12245a8, 0x0, 0x0})
        github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000342500)
        github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.4.0/command.go:902
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc0003335f0, {0x1?, 0x1?})
        cuelang.org/go@v0.5.0/cmd/cue/cmd/root.go:246 +0x6b
cuelang.org/go/cmd/cue/cmd.mainErr({0xd7ba90, 0xc00003a130}, {0xc000034050?, 0x60?, 0x11f1680?})
        cuelang.org/go@v0.5.0/cmd/cue/cmd/root.go:183 +0x55
cuelang.org/go/cmd/cue/cmd.Main()
        cuelang.org/go@v0.5.0/cmd/cue/cmd/root.go:165 +0x7c
main.main()
        cuelang.org/go@v0.5.0/cmd/cue/main.go:24 +0x19
```

**Comment by kajogo777** [comment]
it seems this file specifically triggers the bug https://github.com/devopzilla/guku-devx-catalog/blob/v2.0.0-alpha.58/v1/transformers/terraform/aws/ecs.cue

**Comment by kajogo777** [comment]
I narrowed it down further to this simplified example

```
package main

#ECS: ecs: {
	x: string
	y: bool | *true
}

#AddECS: {
	#ECS
	ecs: _
	test: {
		if ecs.y {
			a: b: "\(ecs.x)": "anything"
		}
	}
}
```

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x69c958]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc00038fe90)
        cuelang.org/go@v0.5.0/cmd/cue/cmd/root.go:261 +0x7b
panic({0xb88300, 0x11cc990})
        runtime/panic.go:884 +0x212
cuelang.org/go/internal/core/adt.(*Vertex).getNodeContext(0x2?, 0x2?, 0xc3ac2f?)
        cuelang.org/go@v0.5.0/internal/core/adt/eval.go:1100 +0x18
cuelang.org/go/internal/core/adt.(*OpContext).Unify(0xc0001a7a00, 0x0, 0x2)
        cuelang.org/go@v0.5.0/internal/core/adt/eval.go:164 +0xf6
cuelang.org/go/internal/core/adt.(*OpContext).relNode(0x8?, 0xc31427f8?)
        cuelang.org/go@v0.5.0/internal/core/adt/context.go:323 +0x37
cuelang.org/go/internal/core/adt.(*FieldReference).resolve(0xc00007d890, 0xd7ce40?, 0x90?)
        cuelang.org/go@v0.5.0/internal/core/adt/expr.go:740 +0x2f
cuelang.org/go/internal/core/adt.(*OpContext).unifyNode(0xc0001a7a00, {0xd7ce40, 0xc00007d890}, 0x2)
        cuelang.org/go@v0.5.0/internal/core/adt/context.go:773 +0x1ec
cuelang.org/go/internal/core/adt.(*OpContext).node(0xc0001a7a00, {0xd77750?, 0xc00048a240}, {0xd7ce40?, 0xc00007d890?}, 0x1, 0x1f?)
        cuelang.org/go@v0.5.0/internal/core/adt/context.go:962 +0x7c
cuelang.org/go/internal/core/adt.(*SelectorExpr).resolve(0xc00048a240, 0xc0001a7a00, 0x40?)
        cuelang.org/go@v0.5.0/internal/core/adt/expr.go:1004 +0x65
cuelang.org/go/internal/core/adt.(*OpContext).evalState(0xc0001a7a00, {0xd7d0c0, 0xc00048a240}, 0x2)
        cuelang.org/go@v0.5.0/internal/core/adt/context.go:690 +0x21c
cuelang.org/go/internal/core/adt.(*OpContext).value(0xc0001a7a00?, {0xd7d0c0?, 0xc00048a240?}, 0x3e?)
        cuelang.org/go@v0.5.0/internal/core/adt/context.go:637 +0x28
cuelang.org/go/internal/core/adt.(*Interpolation).evaluate(0xc0003632f0, 0xc0001a7a00, 0xf0?)
        cuelang.org/go@v0.5.0/internal/core/adt/expr.go:1172 +0x3ac
cuelang.org/go/internal/core/adt.(*OpContext).evalState(0xc0001a7a00, {0xd7cf00, 0xc0003632f0}, 0x2)
        cuelang.org/go@v0.5.0/internal/core/adt/context.go:686 +0x4ac
cuelang.org/go/internal/core/adt.(*OpContext).Evaluate(0xc0001a7a00, 0xc0001899a0, {0xd7cf00, 0xc0003632f0})
        cuelang.org/go@v0.5.0/internal/core/adt/context.go:589 +0x1c9
cuelang.org/go/internal/core/export.(*exporter).decl(0xc000157600, 0xd7be80?, {0xd79a48?, 0xc000363380?})
        cuelang.org/go@v0.5.0/internal/core/export/adt.go:484 +0x145
cuelang.org/go/internal/core/export.(*exporter).adt(0xc000157600, 0xc0007f0540, {0xd7be80?, 0xc000476e10?})
        cuelang.org/go@v0.5.0/internal/core/export/adt.go:73 +0x271a
cuelang.org/go/internal/core/export.(*exporter).adt(0xc000157600, 0xc0007f0540, {0xd7bcf8?, 0xc0002fb9f0?})
        cuelang.org/go@v0.5.0/internal/core/export/adt.go:280 +0x1c28
cuelang.org/go/internal/core/export.(*exporter).expr(0xc000157600?, 0xd77390?, {0xd7bcf8?, 0xc0002fb9f0?})
        cuelang.org/go@v0.5.0/internal/core/export/expr.go:98 +0x37a
cuelang.org/go/internal/core/export.(*exporter).vertex(0xc000157600, 0xc0007ed830)
        cuelang.org/go@v0.5.0/internal/core/export/value.go:102 +0x9b2
cuelang.org/go/internal/core/export.(*exporter).structComposite(0xc000157600, 0xc0007ed7a0, {0x0, 0x0, 0x1?})
        cuelang.org/go@v0.5.0/internal/core/export/value.go:467 +0xa4e
cuelang.org/go/internal/core/export.(*exporter).vertex(0xc000157600, 0xc0007ed7a0)
        cuelang.org/go@v0.5.0/internal/core/export/value.go:65 +0x5c9
cuelang.org/go/internal/core/export.(*exporter).structComposite(0xc000157600, 0xc0007ed4d0, {0x0, 0x0, 0x10?})
        cuelang.org/go@v0.5.0/internal/core/export/value.go:467 +0xa4e
cuelang.org/go/internal/core/export.(*exporter).vertex(0xc000157600, 0xc0007ed4d0)
        cuelang.org/go@v0.5.0/internal/core/export/value.go:65 +0x5c9
cuelang.org/go/internal/core/export.(*exporter).structComposite(0xc000157600, 0xc0007ecf30, {0x0, 0x0, 0xc00038ec58?})
        cuelang.org/go@v0.5.0/internal/core/export/value.go:467 +0xa4e
cuelang.org/go/internal/core/export.(*exporter).vertex(0xc000157600, 0xc0007ecf30)
        cuelang.org/go@v0.5.0/internal/core/export/value.go:65 +0x5c9
cuelang.org/go/internal/core/export.(*exporter).structComposite(0xc000157600, 0xc0004721b0, {0x0, 0x0, 0xc0001dc43c?})
        cuelang.org/go@v0.5.0/internal/core/export/value.go:467 +0xa4e
cuelang.org/go/internal/core/export.(*exporter).vertex(0xc000157600, 0xc0004721b0)
        cuelang.org/go@v0.5.0/internal/core/export/value.go:65 +0x5c9
cuelang.org/go/internal/core/export.(*exporter).value(0xc000157600, {0xd80030?, 0xc0004721b0?}, {0xc000393340?, 0x2?, 0x2?})
        cuelang.org/go@v0.5.0/internal/core/export/value.go:182 +0x593
cuelang.org/go/internal/core/export.(*Profile).Vertex(0xc0002be3c0?, {0xd7e9a8?, 0xc0002d3130?}, {0xc00020ae8c?, 0xc00038f980?}, 0xc0004721b0)
        cuelang.org/go@v0.5.0/internal/core/export/export.go:202 +0x93
cuelang.org/go/cue.Value.Syntax({0xc0002d3130?, 0xc0004721b0?, 0x0?}, {0xc00038fb68, 0x5, 0xc00011faa8?})
        cuelang.org/go@v0.5.0/cue/types.go:1018 +0x24f
cuelang.org/go/cmd/cue/cmd.runEval(0xc000333440, {0xc000330ea0, 0x2, 0x2})
        cuelang.org/go@v0.5.0/cmd/cue/cmd/eval.go:165 +0x96f
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc000342c80?, {0xc000330ea0, 0x2, 0x2})
        cuelang.org/go@v0.5.0/cmd/cue/cmd/root.go:72 +0xb3
github.com/spf13/cobra.(*Command).execute(0xc000342c80, {0xc000330e40, 0x2, 0x2})
        github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000342500)
        github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.4.0/command.go:902
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc000333440, {0x3?, 0x3?})
        cuelang.org/go@v0.5.0/cmd/cue/cmd/root.go:246 +0x6b
cuelang.org/go/cmd/cue/cmd.mainErr({0xd7ba90, 0xc00003a130}, {0xc0000340d0?, 0x60?, 0x11f1680?})
        cuelang.org/go@v0.5.0/cmd/cue/cmd/root.go:183 +0x55
cuelang.org/go/cmd/cue/cmd.Main()
        cuelang.org/go@v0.5.0/cmd/cue/cmd/root.go:165 +0x7c
main.main()
        cuelang.org/go@v0.5.0/cmd/cue/main.go:24 +0x19
```

**Comment by mvdan** [comment]
Minified, and as a testscript:

```
exec cue eval f.cue

-- f.cue --
s: string
if true {
	out: "\(s)"
}
```

One would expect the command to succeed and not panic, but it does panic like the original bit of code.

**Comment by mvdan** [comment]
Bisected via `git bisect start master v0.4.3 && git bisect run go run ./cmd/cue eval /tmp/f.cue` to https://review.gerrithub.io/c/cue-lang/cue/+/552252.

**Comment by mvdan** [comment]
Slight correction; the minimized reproducer above does reproduce one crash, but if I fix it by adding a nil check, the original reproducer still crashes somewhere else. This slightly bigger reproducer does find both crashes, by keeping `"\(s)"` as a field:

```
exec cue eval f.cue

-- f.cue --
s: string
if true {
	out: "\(s)": 3
}
```

**Comment by mvdan** [comment]
This second (and original) crash bisects to https://review.gerrithub.io/c/cue-lang/cue/+/541463; it makes sense, because that adds the call to `e.ctx.Evaluate(env, x)`, and `env.Up.Vertex` being nil then trips up the adt package.
