### ISSUE TITLE
cuelang.org: playground: nil dereference panic on some inputs

### ISSUE THREAD

**Issue by nicuveo** [cue-lang/cue#2359]
### What version of CUE are you using (`cue version`)?

The one in the playground.

### What did you do?

```cue
a: {
  r: b.z
}
b: {
  for f in a.u {z: 0}
}
```

### What did you expect to see?

I expect the evaluation to fail: selecting a field that doesn't exist usually just yields the unevaluated expression back. In this case, since the embedded element of `b` can't be evaluated due to `a.u` not existing, neither `b` nor `a.r` can be evaluated. The output should therefore be identical to the input.

### What did you see instead?

The playground crashes (or goes on an infinite loop?), and corrupts the input buffer: any attempt to modify it mangles the input text.

**Comment by nicuveo** [comment]
FWIW, this almost identical example works as expected:

```cue
// input
a: {
  r: b.z
}
b: {
  for f in a.u {e: 0}
}

// output
a: {
	r: b.z
}
b: {
	for f in a.u {
		e: 0
	}
}
```

**Comment by nicuveo** [comment]
I found a smaller example:
```cue
a: number
for x in [a] {a: x}
```

**Comment by mvdan** [comment]
The first one appears to be a bug which only happens in the playground; the console shows a nil dereference panic:

```
panic: runtime error: invalid memory address or nil pointer dereference wasm_exec.js:1:297
[signal 0xb code=0x0 addr=0x0 pc=0x0] wasm_exec.js:1:297
<empty string> wasm_exec.js:1:297
goroutine 1 [running]: wasm_exec.js:1:297
cuelang.org/go/cue/ast.(*Field).End(0xc93200) wasm_exec.js:1:297
	/home/runner/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1.0.20230418084629-59080b65a5ba/cue/ast/ast.go:337 +0xe wasm_exec.js:1:297
cuelang.org/go/cue/ast.(*StructLit).End(0xd970e0) wasm_exec.js:1:297
	/home/runner/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1.0.20230418084629-59080b65a5ba/cue/ast/ast.go:811 +0x9 wasm_exec.js:1:297
cuelang.org/go/cue/format.(*formatter).onOneLine(0xeab790, {0x1d8dc8, 0xd970e0}) wasm_exec.js:1:297
	/home/runner/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1.0.20230418084629-59080b65a5ba/cue/format/format.go:274 +0x7 wasm_exec.js:1:297
cuelang.org/go/cue/format.(*formatter).before(0xeab790, {0x1d8dc8, 0xd970e0}) wasm_exec.js:1:297
	/home/runner/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1.0.20230418084629-59080b65a5ba/cue/format/format.go:289 +0x1c wasm_exec.js:1:297
cuelang.org/go/cue/format.(*formatter).expr1(0xeab790, {0x1daae8, 0xd970e0}, 0x0, 0x1) wasm_exec.js:1:297
	/home/runner/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1.0.20230418084629-59080b65a5ba/cue/format/node.go:523 +0x3 wasm_exec.js:1:297
cuelang.org/go/cue/format.(*formatter).expr(0xeab790, {0x1daae8, 0xd970e0}) wasm_exec.js:1:297
	/home/runner/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1.0.20230418084629-59080b65a5ba/cue/format/node.go:515 +0x2 wasm_exec.js:1:297
cuelang.org/go/cue/format.(*formatter).decl(0xeab790, {0x1d9b48, 0xc93180}) wasm_exec.js:1:297
	/home/runner/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1.0.20230418084629-59080b65a5ba/cue/format/node.go:317 +0x1cc wasm_exec.js:1:297
cuelang.org/go/cue/format.(*formatter).walkDeclList(0xeab790, {0xefb500, 0x2, 0x2}) wasm_exec.js:1:297
	/home/runner/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1.0.20230418084629-59080b65a5ba/cue/format/node.go:135 +0x3c wasm_exec.js:1:297
cuelang.org/go/cue/format.(*formatter).file(0xeab790, 0xc3cc60) wasm_exec.js:1:297
	/home/runner/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1.0.20230418084629-59080b65a5ba/cue/format/node.go:230 +0x5 wasm_exec.js:1:297
cuelang.org/go/cue/format.printNode({0xe3900, 0xc3cc60}, 0xf52280) wasm_exec.js:1:297
	/home/runner/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1.0.20230418084629-59080b65a5ba/cue/format/node.go:40 +0x18 wasm_exec.js:1:297
cuelang.org/go/cue/format.(*config).fprint(0xd122e0, {0xe3900, 0xc3cc60}) wasm_exec.js:1:297
	/home/runner/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1.0.20230418084629-59080b65a5ba/cue/format/format.go:145 +0xd wasm_exec.js:1:297
cuelang.org/go/cue/format.Node({0x1d8990, 0xc3cc60}, {0x86f028, 0x0, 0x0}) wasm_exec.js:1:297
	/home/runner/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1.0.20230418084629-59080b65a5ba/cue/format/format.go:92 +0x11 wasm_exec.js:1:297
github.com/cue-sh/playground/internal/cuelang_org_go_internal/encoding.NewEncoder.func3({0x0, 0x0}, {0x1d8990, 0xc3cc60}) wasm_exec.js:1:297
	/home/runner/work/cuelang.org/cuelang.org/play/internal/cuelang_org_go_internal/encoding/encoder.go:152 +0x1e wasm_exec.js:1:297
github.com/cue-sh/playground/internal/cuelang_org_go_internal/encoding.NewEncoder.func5(0xc3cc60) wasm_exec.js:1:297
	/home/runner/work/cuelang.org/cuelang.org/play/internal/cuelang_org_go_internal/encoding/encoder.go:162 +0x6 wasm_exec.js:1:297
github.com/cue-sh/playground/internal/cuelang_org_go_internal/encoding.(*Encoder).encodeFile(0xe8c580, 0xc3cc60, 0x0) wasm_exec.js:1:297
	/home/runner/work/cuelang.org/cuelang.org/play/internal/cuelang_org_go_internal/encoding/encoder.go:275 +0x1b wasm_exec.js:1:297
github.com/cue-sh/playground/internal/cuelang_org_go_internal/encoding.(*Encoder).EncodeFile(...) wasm_exec.js:1:297
	/home/runner/work/cuelang.org/cuelang.org/play/internal/cuelang_org_go_internal/encoding/encoder.go:243 wasm_exec.js:1:297
main.handleCUECompile({0xe0d1cb, 0x3}, {0xe0d1d6, 0x6}, {0xe0d1e0, 0x3}, {0xd19770, 0x2c}) wasm_exec.js:1:297
	/home/runner/work/cuelang.org/cuelang.org/play/impl.go:136 +0xb9 wasm_exec.js:1:297
main.cueCompile({{}, 0x7ff800010000000f, 0xe0d198}, {0xe48cc0, 0x4, 0x4}) wasm_exec.js:1:297
	/home/runner/work/cuelang.org/cuelang.org/play/main.go:56 +0xc wasm_exec.js:1:297
syscall/js.handleEvent() wasm_exec.js:1:297
	/opt/hostedtoolcache/go/1.20.2/x64/src/syscall/js/func.go:94 +0x26 wasm_exec.js:1:297
syscall/js.Value.Call({{}, 0x7ff800010000000f, 0xe0d178}, {0x11c111, 0xc}, {0x0, 0x0, 0x0}) wasm_exec.js:1:297
	/opt/hostedtoolcache/go/1.20.2/x64/src/syscall/js/js.go:379 +0x3 wasm_exec.js:1:297
main.main() wasm_exec.js:1:297
	/home/runner/work/cuelang.org/cuelang.org/play/main.go:33 +0x5 wasm_exec.js:1:297
```

The last snippet you shared causes an infinite recursion and a panic even with `cue export`, so I'll split that into a separate issue, as the two seem to have unrelated causes.

**Comment by mvdan** [comment]
Second issue split into https://github.com/cue-lang/cue/issues/2367.

**Comment by myitcv** [comment]
Will dig into this to investigate more, and also look at alongside https://github.com/cue-lang/cue/issues/1687.

**Comment by myitcv** [comment]
See also https://github.com/cue-lang/cue/issues/2537

**Comment by mvdan** [comment]
I believe one of the playground panic fixes that happened since Paul's comments above fixed this; the original example no longer panics for me: https://cuelang.org/play/?id=xu__iaC8sDx#w=function&i=cue&f=export&o=cue
