### ISSUE TITLE
cmd/cue: get go panics because of a nil pointer dereference (net/http)

### ISSUE THREAD

**Issue by addreas** [cue-lang/cue#2361]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.5.0

go version go1.20.3
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
</pre>

### Does this issue reproduce with the latest stable release?

Yes

### What did you do?
At first I ran into this with
```
$ go get "github.com/grafana/agent/pkg/operator/apis/monitoring/v1alpha1"
$ cue get go "github.com/grafana/agent/pkg/operator/apis/monitoring/v1alpha1"
```
After running again with `--verbose` it seemed to stop after `net/http`, so I also tried that directly and got a slightly shorter stack trace, with fewer recursive calls to `cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg`

### What did you expect to see?

No output, as as usual from `cue get go`

### What did you see instead?
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xaff439]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc00caf9e90)
        cuelang.org/go/cmd/cue/cmd/root.go:261 +0x7b
panic({0xbaeea0, 0x1205b30})
        runtime/panic.go:884 +0x213
cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0xc012de85a0, {0xc000040064, 0x18}, 0x0)
        cuelang.org/go/cmd/cue/cmd/get_go.go:438 +0x79
cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0xc012de85a0, {0xc000040064, 0x18}, 0xc00001bc80)
        cuelang.org/go/cmd/cue/cmd/get_go.go:554 +0xb1a
cuelang.org/go/cmd/cue/cmd.extract(0xc0002dcea0, {0xc00024ffa0, 0x1, 0x1})
        cuelang.org/go/cmd/cue/cmd/get_go.go:417 +0x3e5
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc000302000?, {0xc00024ffa0, 0x1, 0x1})
        cuelang.org/go/cmd/cue/cmd/root.go:72 +0xb3
github.com/spf13/cobra.(*Command).execute(0xc000302000, {0xc00024ff70, 0x1, 0x1})
        github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002ea780)
        github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.4.0/command.go:902
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc0002dcea0, {0x4?, 0x4?})
        cuelang.org/go/cmd/cue/cmd/root.go:246 +0x6b
cuelang.org/go/cmd/cue/cmd.mainErr({0xd959a8, 0xc00003a0d8}, {0xc0000360b0?, 0xc0000061a0?, 0x200000003?})
        cuelang.org/go/cmd/cue/cmd/root.go:183 +0x55
cuelang.org/go/cmd/cue/cmd.Main()
        cuelang.org/go/cmd/cue/cmd/root.go:165 +0x7c
main.main()
        cuelang.org/go/cmd/cue/main.go:24 +0x19
```

**Comment by seh** [comment]
Is this a duplicate of #2046?

**Comment by addreas** [comment]
Definitely looks like it, not sure how I managed to miss that in my search for existing issues. Apologies.
