### ISSUE TITLE
val.Expr() panics invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kajogo777** [cue-lang/cue#2411]
### What version of CUE are you using (`cue version`)?

Using the SDK `v0.6.0-alpha.1`

### Does this issue reproduce with the latest stable release?

I don't know, I stopped using the latest stable release because of another panic error

### What did you do?

Call `Expr()` on a value to inspect expression operator to determine if it's a reference, this is the exact [line of code the produces this error](https://github.com/devopzilla/guku-devx/blob/main/pkg/stack/stack.go#L281)

this is the value that triggers the bug `*"external-secrets" | string`

### What did you expect to see?

To execute without panicing and get the operator and values

### What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x846dbc]

goroutine 1 [running]:
cuelang.org/go/internal/core/adt.(*Environment).up(...)
        /home/george/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1/internal/core/adt/composite.go:106
cuelang.org/go/internal/core/adt.(*OpContext).relNode(0x0?, 0x0?)
        /home/george/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1/internal/core/adt/context.go:322 +0x1c
cuelang.org/go/internal/core/adt.(*FieldReference).resolve(0xc000a07f60, 0xe928f8?, 0x60?)
        /home/george/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1/internal/core/adt/expr.go:699 +0x2f
cuelang.org/go/internal/core/adt.(*OpContext).resolveState(0xc004ea9b00, {0xc004a6a9a0, {0xe928f8, 0xc000a07f60}, {0x0, 0x0, 0x0, {0x0, 0x0, 0x0}}}, ...)
        /home/george/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1/internal/core/adt/context.go:476 +0xe2
cuelang.org/go/internal/core/adt.(*nodeContext).evalExpr(0xc004eb3000, {0xc004a6a9a0, {0xe928f8, 0xc000a07f60}, {0x0, 0x0, 0x0, {0x0, 0x0, 0x0}}}, ...)
        /home/george/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1/internal/core/adt/eval.go:1497 +0x411
cuelang.org/go/internal/core/adt.(*nodeContext).addExprConjunct(0xc004eb3000, {0xc004a6a9a0, {0xe928f8, 0xc000a07f60}, {0x0, 0x0, 0x0, {0x0, 0x0, 0x0}}}, ...)
        /home/george/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1/internal/core/adt/eval.go:1475 +0x856
cuelang.org/go/internal/core/adt.(*nodeContext).insertConjuncts(0xc004eb3000, 0x1?)
        /home/george/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1/internal/core/adt/eval.go:383 +0x116
cuelang.org/go/internal/core/adt.(*OpContext).unify(0xc004ea9b00, 0xc004ebb710, 0x5)
        /home/george/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1/internal/core/adt/eval.go:231 +0xcdb
cuelang.org/go/internal/core/adt.(*Vertex).Finalize(...)
        /home/george/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1/internal/core/adt/composite.go:629
cuelang.org/go/cue.manifest(0xc004ea9b00?, 0xc000960090?)
        /home/george/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1/cue/context.go:473 +0x65
cuelang.org/go/cue.remakeValue({0xc000960090?, 0xc004a73170?, 0x0?}, 0x80?, {0xe98498?, 0xc000a07f60?})
        /home/george/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1/cue/types.go:697 +0x1da
cuelang.org/go/cue.Value.Expr({0xc000960090?, 0xc004a73170?, 0x0?})
        /home/george/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1/cue/types.go:2440 +0xe65
github.com/devopzilla/guku-devx/pkg/stack.GetRef.func1({0xc000960090?, 0xc004a73170?, 0x0?})
        /home/george/Projects/devopzilla/guku-devx/pkg/stack/stack.go:282 +0x173
cuelang.org/go/cue.Value.Walk({0xc000960090?, 0xc004a73170?, 0x0?}, 0xc004146f08, 0x0)
        /home/george/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1/cue/types.go:2271 +0x2e6
cuelang.org/go/cue.Value.Walk({0xc000960090?, 0xc004a73050?, 0x0?}, 0xc004146f08, 0x0)
        /home/george/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1/cue/types.go:2259 +0x389
cuelang.org/go/cue.Value.Walk({0xc000960090?, 0xc004a72fc0?, 0x0?}, 0xc004146f08, 0x0)
        /home/george/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1/cue/types.go:2259 +0x389
cuelang.org/go/cue.Value.Walk({0xc000960090?, 0xc004a72e10?, 0x0?}, 0xc004146f08, 0x0)
        /home/george/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1/cue/types.go:2259 +0x389
cuelang.org/go/cue.Value.Walk({0xc000960090?, 0xc004a72cf0?, 0x0?}, 0xc004146f08, 0x0)
        /home/george/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1/cue/types.go:2259 +0x389
cuelang.org/go/cue.Value.Walk({0xc000960090?, 0xc004a72c60?, 0x0?}, 0xc004146f08, 0x0)
        /home/george/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1/cue/types.go:2259 +0x389
cuelang.org/go/cue.Value.Walk({0xc000960090?, 0xc004a72b40?, 0x0?}, 0xc004146f08, 0x0)
        /home/george/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1/cue/types.go:2259 +0x389
cuelang.org/go/cue.Value.Walk({0xc000960090?, 0xc004a72a20?, 0x0?}, 0xc004146f08, 0x0)
        /home/george/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1/cue/types.go:2259 +0x389
cuelang.org/go/cue.Value.Walk({0xc000960090?, 0xc004a72990?, 0x0?}, 0xc004146f08, 0x0)
        /home/george/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1/cue/types.go:2259 +0x389
github.com/devopzilla/guku-devx/pkg/stack.GetRef({0xc000960090?, 0xc004a72990?, 0x0?})
        /home/george/Projects/devopzilla/guku-devx/pkg/stack/stack.go:277 +0x5d
github.com/devopzilla/guku-devx/pkg/stack.GetRef.func1({0xc000960090?, 0xc003f88510?, 0x0?})
        /home/george/Projects/devopzilla/guku-devx/pkg/stack/stack.go:287 +0x73e
cuelang.org/go/cue.Value.Walk({0xc000960090?, 0xc003f88510?, 0x0?}, 0xc004147498, 0x0)
        /home/george/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1/cue/types.go:2245 +0x1dc
cuelang.org/go/cue.Value.Walk({0xc000960090?, 0xc003f88360?, 0x0?}, 0xc004147498, 0x0)
        /home/george/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1/cue/types.go:2259 +0x389
github.com/devopzilla/guku-devx/pkg/stack.GetRef({0xc000960090?, 0xc003f88360?, 0x0?})
        /home/george/Projects/devopzilla/guku-devx/pkg/stack/stack.go:277 +0x5d
github.com/devopzilla/guku-devx/pkg/stack.GetRef.func1({0xc000960090?, 0xc0035adb00?, 0x0?})
        /home/george/Projects/devopzilla/guku-devx/pkg/stack/stack.go:287 +0x73e
cuelang.org/go/cue.Value.Walk({0xc000960090?, 0xc0035adb00?, 0x0?}, 0xc004147820, 0x0)
        /home/george/go/pkg/mod/cuelang.org/go@v0.6.0-alpha.1/cue/types.go:2245 +0x1dc
github.com/devopzilla/guku-devx/pkg/stack.GetRef({0xc000960090?, 0xc0035adb00?, 0x0?})
        /home/george/Projects/devopzilla/guku-devx/pkg/stack/stack.go:277 +0x5d
github.com/devopzilla/guku-devx/pkg/stack.(*Stack).GetReferences(0x40ee65?)
        /home/george/Projects/devopzilla/guku-devx/pkg/stack/stack.go:265 +0x6a
github.com/devopzilla/guku-devx/pkg/stack.(*Stack).SendBuild(0xc000c467e0, {0xd439c9, 0x1}, {0x1, {0x0, 0x0}, {0xd57a58, 0x17}}, {0x7ffc7bdf4b16, 0x4})
        /home/george/Projects/devopzilla/guku-devx/pkg/stack/stack.go:235 +0xa5
github.com/devopzilla/guku-devx/pkg/client.Run({0x7ffc7bdf4b16, 0x4}, {0xd439c9, 0x1}, {0xd45bb1, 0x5}, {0xd48f7b, 0x8}, 0x0, 0x0, ...)
        /home/george/Projects/devopzilla/guku-devx/pkg/client/client.go:48 +0xa25
main.glob..func4(0x13ef200?, {0xc000374d60?, 0x2?, 0x2?})
        /home/george/Projects/devopzilla/guku-devx/cmd/devx/build.go:17 +0xbd
github.com/spf13/cobra.(*Command).execute(0x13ef200, {0xc000374d40, 0x2, 0x2})
        /home/george/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x13ef7c0)
        /home/george/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /home/george/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
        /home/george/Projects/devopzilla/guku-devx/cmd/devx/main.go:153 +0x25
```

**Comment by kajogo777** [comment]
it seems this also triggers the bug `"external-secrets"`

**Comment by mpvl** [comment]
Do you happen to have the CUE code that is responsible for this crash? Without a reproducer it is hard to debug this.

**Comment by mpvl** [comment]
Moving to 0.6.x for now, as it is not reproducible without further input.

**Comment by mvdan** [comment]
Spoke to @kajogo777 yesterday, and we agreed that he'd circle back to this and come up with a short reproducer. It will take a bit of work, since he has to recall the details from a few months back.

FYI George, when it comes to Go reproducers, you can share an entire Go main program and module via the Go playground, like https://go.dev/play/p/BWJ4dcUqVfT. That might still time out due to https://github.com/golang/go/issues/56977, but at least it will be a full reproducer we can run via testscript or txtar, akin to what you can see described in our contribution guide.

**Comment by mvdan** [comment]
I believe we now have a reproducer at https://github.com/cue-lang/cue/issues/2911#issuecomment-2003361065, and I believe these panics have the same root cause, so for now I'm going to close this one as a duplicate to make sure all details and discussion happens in a single place. Once we have a fix, if it turns out I was wrong and the fix didn't fix your panic, @kajogo777, I'm of course always happy to reopen this issue. Thanks!
