### ISSUE TITLE
internal/core/dep: nil pointer dereference

### ISSUE THREAD

**Issue by myitcv** [cue-lang/cue#2490]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20230712153226-c10d7cbc34a8

go version go1.20.4
      -buildmode exe
       -compiler gc
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision c10d7cbc34a84f42b50881a66f8b7c7c8d162cdd
        vcs.time 2023-07-12T15:32:26Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
exec cue cmd gen_terraform

-- generate_tool.cue --
package p

import (
	"tool/file"
	"encoding/json"
)

input: {
	[name=string]: {
		out: {#convert & {#in: name}}.#out
	}
}
#convert: {
	#in: _
	#out: #in
}
command: {
	gen_terraform: {
		file.Create & {
			filename: "foo"
			contents: json.Marshal(input)
		}
	}
}
```

### What did you expect to see?

Passing test.

### What did you see instead?

```
> exec cue cmd gen_terraform
[stderr]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x597080]

goroutine 1 [running]:
panic({0x7df5e0, 0xefd390})
        /home/myitcv/gos/src/runtime/panic.go:987 +0x3ac fp=0x400037a090 sp=0x4000379fd0 pc=0x4578c
cuelang.org/go/cmd/cue/cmd.recoverError(0x400037bea0)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:315 +0x90 fp=0x400037a0b0 sp=0x400037a090 pc=0x721cf0
cuelang.org/go/cmd/cue/cmd.(*Command).Run.func1()
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:298 +0x28 fp=0x400037a0d0 sp=0x400037a0b0 pc=0x721c28
runtime.deferCallSave(0x400037a1b0, 0x400037beb0?)
        /home/myitcv/gos/src/runtime/panic.go:796 +0x88 fp=0x400037a0e0 sp=0x400037a0d0 pc=0x45388
runtime.runOpenDeferFrame(0x4000290730)
        /home/myitcv/gos/src/runtime/panic.go:769 +0x1b0 fp=0x400037a130 sp=0x400037a0e0 pc=0x451c0
panic({0x7df5e0, 0xefd390})
        /home/myitcv/gos/src/runtime/panic.go:884 +0x1f4 fp=0x400037a1f0 sp=0x400037a130 pc=0x455d4
cuelang.org/go/internal/core/dep.(*visitor).visit.func1()
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:218 +0xdc fp=0x400037a240 sp=0x400037a1f0 pc=0x2bebcc
runtime.deferCallSave(0x400037a320, 0x400037b510?)
        /home/myitcv/gos/src/runtime/panic.go:796 +0x88 fp=0x400037a250 sp=0x400037a240 pc=0x45388
runtime.runOpenDeferFrame(0x40002906e0)
        /home/myitcv/gos/src/runtime/panic.go:769 +0x1b0 fp=0x400037a2a0 sp=0x400037a250 pc=0x451c0
panic({0x7df5e0, 0xefd390})
        /home/myitcv/gos/src/runtime/panic.go:884 +0x1f4 fp=0x400037a360 sp=0x400037a2a0 pc=0x455d4
cuelang.org/go/internal/core/dep.(*visitor).visit.func1()
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:218 +0xdc fp=0x400037a3b0 sp=0x400037a360 pc=0x2bebcc
runtime.deferCallSave(0x400037a490, 0x400037aff0?)
        /home/myitcv/gos/src/runtime/panic.go:796 +0x88 fp=0x400037a3c0 sp=0x400037a3b0 pc=0x45388
runtime.runOpenDeferFrame(0x40002906e0)
        /home/myitcv/gos/src/runtime/panic.go:769 +0x1b0 fp=0x400037a410 sp=0x400037a3c0 pc=0x451c0
panic({0x7df5e0, 0xefd390})
        /home/myitcv/gos/src/runtime/panic.go:884 +0x1f4 fp=0x400037a4d0 sp=0x400037a410 pc=0x455d4
runtime.panicmem()
        /home/myitcv/gos/src/runtime/panic.go:260 +0x48 fp=0x400037a4f0 sp=0x400037a4d0 pc=0x44108
runtime.sigpanic()
        /home/myitcv/gos/src/runtime/signal_unix.go:837 +0x214 fp=0x400037a530 sp=0x400037a4f0 pc=0x5bc74
cuelang.org/go/tools/flow.(*Controller).findImpliedTask(0x4000356ea0, {0x40001a4fc0, {0xa01470, 0x4000146b00}, 0x0, 0x0, 0x40001ae310})
        /home/myitcv/dev/cuelang/cue/tools/flow/tasks.go:194 +0x100 fp=0x400037a5a0 sp=0x400037a540 pc=0x597080
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies.func1({0x40001a4fc0, {0xa01470, 0x4000146b00}, 0x0, 0x0, 0x40001ae310})
        /home/myitcv/dev/cuelang/cue/tools/flow/tasks.go:237 +0x68 fp=0x400037a640 sp=0x400037a5a0 pc=0x597308
cuelang.org/go/internal/core/dep.(*visitor).reportDependency(0x40001ae310, 0x400019ee20?, {0xa01260?, 0x40003a3730?}, 0x40001a4fc0?)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:453 +0x404 fp=0x400037a760 sp=0x400037a640 pc=0x2bf9e4
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0x40001ae310, 0xffff75611050?, {0xa01260?, 0x40003a3730})
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:350 +0x210 fp=0x400037a850 sp=0x400037a760 pc=0x2bf5a0
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x40001ae310, 0x400019ee20, {0xffff75611050?, 0x40003a3730?})
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:264 +0x470 fp=0x400037a920 sp=0x400037a850 pc=0x2bf050
cuelang.org/go/internal/core/dep.(*visitor).markConjuncts(0x400037aa08?, 0x28c718?)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:473 +0x94 fp=0x400037a9b0 sp=0x400037a920 pc=0x2bfc84
cuelang.org/go/internal/core/dep.(*visitor).markInternalResolvers(0x40001ae310, 0x400018e500?, {0xa01470?, 0x4000146b00?}, 0x0?)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:486 +0x5c fp=0x400037aa10 sp=0x400037a9b0 pc=0x2bfd2c
cuelang.org/go/internal/core/dep.(*visitor).reportDependency(0x40001ae310, 0x400019ed80?, {0xa01470?, 0x4000146b00?}, 0x40001a5050)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:398 +0x178 fp=0x400037ab30 sp=0x400037aa10 pc=0x2bf758
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0x40001ae310, 0xffff756116b8?, {0xa01470?, 0x4000146b00})
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:350 +0x210 fp=0x400037ac20 sp=0x400037ab30 pc=0x2bf5a0
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x40001ae310, 0x400019ed80, {0xffff756116b8?, 0x4000146b00?})
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:264 +0x470 fp=0x400037acf0 sp=0x400037ac20 pc=0x2bf050
cuelang.org/go/internal/core/dep.(*visitor).markSubExpr(...)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:537
cuelang.org/go/internal/core/dep.(*visitor).markDecl(0x40001ae310, 0xa03c50?, {0xa01200?, 0x4000146b20?})
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:545 +0x80 fp=0x400037ad70 sp=0x400037acf0 pc=0x2c0220
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x40001ae310, 0x400019ed60, {0xa03c50?, 0x4000158480?})
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:329 +0x4b4 fp=0x400037ae40 sp=0x400037ad70 pc=0x2bf094
cuelang.org/go/internal/core/dep.(*visitor).markSubExpr(...)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:537
cuelang.org/go/internal/core/dep.(*visitor).markDecl(0x40001ae310, 0xa03c50?, {0xa01110?, 0x400016e0f0?})
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:551 +0x118 fp=0x400037aec0 sp=0x400037ae40 pc=0x2c02b8
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x40001ae310, 0x4000146d00, {0xa03c50?, 0x40001583f0?})
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:329 +0x4b4 fp=0x400037af90 sp=0x400037aec0 pc=0x2bf094
cuelang.org/go/internal/core/dep.(*visitor).visit(0x40001ae310, 0x400016f470?, 0x70?)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:223 +0xfc fp=0x400037b060 sp=0x400037af90 pc=0x2bea6c
cuelang.org/go/internal/core/dep.(*Dependency).Recurse(...)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:130
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies.func1({0x4000158870, {0xa01260, 0x40003a3770}, 0x0, 0x0, 0x40001ae310})
        /home/myitcv/dev/cuelang/cue/tools/flow/tasks.go:255 +0x23c fp=0x400037b100 sp=0x400037b060 pc=0x5974dc
cuelang.org/go/internal/core/dep.(*visitor).reportDependency(0x40001ae310, 0x40001479e0?, {0xa01260?, 0x40003a3770?}, 0x0?)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:453 +0x404 fp=0x400037b220 sp=0x400037b100 pc=0x2bf9e4
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0x40001ae310, 0xffff75611050?, {0xa01260?, 0x40003a3770})
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:350 +0x210 fp=0x400037b310 sp=0x400037b220 pc=0x2bf5a0
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x40001ae310, 0x40001479e0, {0xffff75611050?, 0x40003a3770?})
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:264 +0x470 fp=0x400037b3e0 sp=0x400037b310 pc=0x2bf050
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x40001ae310, 0x40001479e0, {0xa03a90?, 0x400016e150?})
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:294 +0x66c fp=0x400037b4b0 sp=0x400037b3e0 pc=0x2bf24c
cuelang.org/go/internal/core/dep.(*visitor).visit(0x40001ae310, 0x40001aa2a0?, 0x80?)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:223 +0xfc fp=0x400037b580 sp=0x400037b4b0 pc=0x2bea6c
cuelang.org/go/internal/core/dep.(*visitor).dynamic(0x40001ae310, 0x40001875f0, 0x0?)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/mixed.go:43 +0xd0 fp=0x400037b620 sp=0x400037b580 pc=0x2c0a10
cuelang.org/go/internal/core/dep.(*visitor).dynamic(0x40001ae310, 0x4000158bd0, 0xd0?)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/mixed.go:51 +0x164 fp=0x400037b6c0 sp=0x400037b620 pc=0x2c0aa4
cuelang.org/go/internal/core/dep.Visit(0x0?, 0x400018e500, 0x40003a0000?, 0x400043be00)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:194 +0x13c fp=0x400037b770 sp=0x400037b6c0 pc=0x2be8fc
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies(0x4000356ea0, 0x4000356fc0, 0x4000158bd0?)
        /home/myitcv/dev/cuelang/cue/tools/flow/tasks.go:236 +0x9c fp=0x400037b7c0 sp=0x400037b770 pc=0x59726c
cuelang.org/go/tools/flow.(*Controller).initTasks(0x4000356ea0)
        /home/myitcv/dev/cuelang/cue/tools/flow/tasks.go:50 +0xec fp=0x400037b830 sp=0x400037b7c0 pc=0x59653c
cuelang.org/go/tools/flow.New(0x400037b8f0, {0x9fe610?, 0x400007db90?}, 0x40003a3e80)
        /home/myitcv/dev/cuelang/cue/tools/flow/flow.go:248 +0x1bc fp=0x400037b890 sp=0x400037b830 pc=0x5947fc
cuelang.org/go/cmd/cue/cmd.doTasks(0x1?, {0x0?, 0x0?}, {0xffffc2a4197c, 0xd}, 0x0?)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/custom.go:150 +0x108 fp=0x400037b920 sp=0x400037b890 pc=0x70f978
cuelang.org/go/cmd/cue/cmd.customCommand.func1(0x400030e630?, {0x727265745f6e6567?, 0x206d726f6661?, 0x4000090420?})
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/custom.go:135 +0x30 fp=0x400037b960 sp=0x400037b920 pc=0x70f830
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0x400030e630?, {0x400030cb90, 0x0, 0x0})
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:87 +0x8c fp=0x400037ba90 sp=0x400037b960 pc=0x72117c
cuelang.org/go/cmd/cue/cmd.newCmdCmd.func1(0x400030e630, {0x400030cb90, 0x0?, 0x0?})
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/cmd.go:175 +0x338 fp=0x400037bb50 sp=0x400037ba90 pc=0x7244a8
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0x40002d1200?, {0x400030cb90, 0x1, 0x1})
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:87 +0x8c fp=0x400037bc80 sp=0x400037bb50 pc=0x72117c
github.com/spf13/cobra.(*Command).execute(0x40002d1200, {0x400030cb50, 0x1, 0x1})
        /home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x5c4 fp=0x400037bdc0 sp=0x400037bc80 pc=0x1d43b4
github.com/spf13/cobra.(*Command).ExecuteC(0x40002d0f00)
        /home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x340 fp=0x400037be80 sp=0x400037bdc0 pc=0x1d4af0
github.com/spf13/cobra.(*Command).Execute(...)
        /home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0x400030e630, {0x2?, 0x2?})
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:300 +0x5c fp=0x400037bed0 sp=0x400037be80 pc=0x721b1c
cuelang.org/go/cmd/cue/cmd.Main()
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:228 +0x78 fp=0x400037bf50 sp=0x400037bed0 pc=0x721848
main.main()
        /home/myitcv/dev/cuelang/cue/cmd/cue/main.go:24 +0x1c fp=0x400037bf70 sp=0x400037bf50 pc=0x737e9c
runtime.main()
        /home/myitcv/gos/src/runtime/proc.go:250 +0x200 fp=0x400037bfd0 sp=0x400037bf70 pc=0x48160
runtime.goexit()
        /home/myitcv/gos/src/runtime/asm_arm64.s:1172 +0x4 fp=0x400037bfd0 sp=0x400037bfd0 pc=0x76534

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/myitcv/gos/src/runtime/proc.go:381 +0xe0 fp=0x4000062fa0 sp=0x4000062f80 pc=0x48570
runtime.goparkunlock(...)
        /home/myitcv/gos/src/runtime/proc.go:387
runtime.forcegchelper()
        /home/myitcv/gos/src/runtime/proc.go:305 +0xb0 fp=0x4000062fd0 sp=0x4000062fa0 pc=0x483c0
runtime.goexit()
        /home/myitcv/gos/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000062fd0 sp=0x4000062fd0 pc=0x76534
created by runtime.init.6
        /home/myitcv/gos/src/runtime/proc.go:293 +0x24

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/myitcv/gos/src/runtime/proc.go:381 +0xe0 fp=0x4000063760 sp=0x4000063740 pc=0x48570
runtime.goparkunlock(...)
        /home/myitcv/gos/src/runtime/proc.go:387
runtime.bgsweep(0x0?)
        /home/myitcv/gos/src/runtime/mgcsweep.go:319 +0x100 fp=0x40000637b0 sp=0x4000063760 pc=0x34520
runtime.gcenable.func1()
        /home/myitcv/gos/src/runtime/mgc.go:178 +0x28 fp=0x40000637d0 sp=0x40000637b0 pc=0x29578
runtime.goexit()
        /home/myitcv/gos/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40000637d0 sp=0x40000637d0 pc=0x76534
created by runtime.gcenable
        /home/myitcv/gos/src/runtime/mgc.go:178 +0x6c

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x400007c000?, 0x9f52b0?, 0x0?, 0x0?, 0x0?)
        /home/myitcv/gos/src/runtime/proc.go:381 +0xe0 fp=0x4000063f50 sp=0x4000063f30 pc=0x48570
runtime.goparkunlock(...)
        /home/myitcv/gos/src/runtime/proc.go:387
runtime.(*scavengerState).park(0xf25680)
        /home/myitcv/gos/src/runtime/mgcscavenge.go:400 +0x5c fp=0x4000063f80 sp=0x4000063f50 pc=0x3244c
runtime.bgscavenge(0x0?)
        /home/myitcv/gos/src/runtime/mgcscavenge.go:633 +0xa8 fp=0x4000063fb0 sp=0x4000063f80 pc=0x329e8
runtime.gcenable.func2()
        /home/myitcv/gos/src/runtime/mgc.go:179 +0x28 fp=0x4000063fd0 sp=0x4000063fb0 pc=0x29518
runtime.goexit()
        /home/myitcv/gos/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000063fd0 sp=0x4000063fd0 pc=0x76534
created by runtime.gcenable
        /home/myitcv/gos/src/runtime/mgc.go:179 +0xac

goroutine 18 [finalizer wait]:
runtime.gopark(0x1a0?, 0xf262a0?, 0x40?, 0x23?, 0x0?)
        /home/myitcv/gos/src/runtime/proc.go:381 +0xe0 fp=0x4000062580 sp=0x4000062560 pc=0x48570
runtime.runfinq()
        /home/myitcv/gos/src/runtime/mfinal.go:193 +0x100 fp=0x40000627d0 sp=0x4000062580 pc=0x28640
runtime.goexit()
        /home/myitcv/gos/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40000627d0 sp=0x40000627d0 pc=0x76534
created by runtime.createfing
        /home/myitcv/gos/src/runtime/mfinal.go:163 +0x80

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/myitcv/gos/src/runtime/proc.go:381 +0xe0 fp=0x400005e740 sp=0x400005e720 pc=0x48570
runtime.gcBgMarkWorker()
        /home/myitcv/gos/src/runtime/mgc.go:1275 +0xe4 fp=0x400005e7d0 sp=0x400005e740 pc=0x2b354
runtime.goexit()
        /home/myitcv/gos/src/runtime/asm_arm64.s:1172 +0x4 fp=0x400005e7d0 sp=0x400005e7d0 pc=0x76534
created by runtime.gcBgMarkStartWorkers
        /home/myitcv/gos/src/runtime/mgc.go:1199 +0x28

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/myitcv/gos/src/runtime/proc.go:381 +0xe0 fp=0x4000506740 sp=0x4000506720 pc=0x48570
runtime.gcBgMarkWorker()
        /home/myitcv/gos/src/runtime/mgc.go:1275 +0xe4 fp=0x40005067d0 sp=0x4000506740 pc=0x2b354
runtime.goexit()
        /home/myitcv/gos/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40005067d0 sp=0x40005067d0 pc=0x76534
created by runtime.gcBgMarkStartWorkers
        /home/myitcv/gos/src/runtime/mgc.go:1199 +0x28

goroutine 35 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/myitcv/gos/src/runtime/proc.go:381 +0xe0 fp=0x4000506f40 sp=0x4000506f20 pc=0x48570
runtime.gcBgMarkWorker()
        /home/myitcv/gos/src/runtime/mgc.go:1275 +0xe4 fp=0x4000506fd0 sp=0x4000506f40 pc=0x2b354
runtime.goexit()
        /home/myitcv/gos/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000506fd0 sp=0x4000506fd0 pc=0x76534
created by runtime.gcBgMarkStartWorkers
        /home/myitcv/gos/src/runtime/mgc.go:1199 +0x28

goroutine 5 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/myitcv/gos/src/runtime/proc.go:381 +0xe0 fp=0x4000064740 sp=0x4000064720 pc=0x48570
runtime.gcBgMarkWorker()
        /home/myitcv/gos/src/runtime/mgc.go:1275 +0xe4 fp=0x40000647d0 sp=0x4000064740 pc=0x2b354
runtime.goexit()
        /home/myitcv/gos/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40000647d0 sp=0x40000647d0 pc=0x76534
created by runtime.gcBgMarkStartWorkers
        /home/myitcv/gos/src/runtime/mgc.go:1199 +0x28

goroutine 6 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/myitcv/gos/src/runtime/proc.go:381 +0xe0 fp=0x4000064f40 sp=0x4000064f20 pc=0x48570
runtime.gcBgMarkWorker()
        /home/myitcv/gos/src/runtime/mgc.go:1275 +0xe4 fp=0x4000064fd0 sp=0x4000064f40 pc=0x2b354
runtime.goexit()
        /home/myitcv/gos/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000064fd0 sp=0x4000064fd0 pc=0x76534
created by runtime.gcBgMarkStartWorkers
        /home/myitcv/gos/src/runtime/mgc.go:1199 +0x28

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x157286780790?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/myitcv/gos/src/runtime/proc.go:381 +0xe0 fp=0x400005ef40 sp=0x400005ef20 pc=0x48570
runtime.gcBgMarkWorker()
        /home/myitcv/gos/src/runtime/mgc.go:1275 +0xe4 fp=0x400005efd0 sp=0x400005ef40 pc=0x2b354
runtime.goexit()
        /home/myitcv/gos/src/runtime/asm_arm64.s:1172 +0x4 fp=0x400005efd0 sp=0x400005efd0 pc=0x76534
created by runtime.gcBgMarkStartWorkers
        /home/myitcv/gos/src/runtime/mgc.go:1199 +0x28

goroutine 7 [GC worker (idle)]:
runtime.gopark(0x157286771cdd?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/myitcv/gos/src/runtime/proc.go:381 +0xe0 fp=0x4000065740 sp=0x4000065720 pc=0x48570
runtime.gcBgMarkWorker()
        /home/myitcv/gos/src/runtime/mgc.go:1275 +0xe4 fp=0x40000657d0 sp=0x4000065740 pc=0x2b354
runtime.goexit()
        /home/myitcv/gos/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40000657d0 sp=0x40000657d0 pc=0x76534
created by runtime.gcBgMarkStartWorkers
        /home/myitcv/gos/src/runtime/mgc.go:1199 +0x28

goroutine 36 [GC worker (idle)]:
runtime.gopark(0xf5e6a0?, 0x3?, 0x5b?, 0x59?, 0x0?)
        /home/myitcv/gos/src/runtime/proc.go:381 +0xe0 fp=0x4000507740 sp=0x4000507720 pc=0x48570
runtime.gcBgMarkWorker()
        /home/myitcv/gos/src/runtime/mgc.go:1275 +0xe4 fp=0x40005077d0 sp=0x4000507740 pc=0x2b354
runtime.goexit()
        /home/myitcv/gos/src/runtime/asm_arm64.s:1172 +0x4 fp=0x40005077d0 sp=0x40005077d0 pc=0x76534
created by runtime.gcBgMarkStartWorkers
        /home/myitcv/gos/src/runtime/mgc.go:1199 +0x28

goroutine 37 [GC worker (idle)]:
runtime.gopark(0x15728677bf22?, 0x1?, 0xc?, 0x5d?, 0x0?)
        /home/myitcv/gos/src/runtime/proc.go:381 +0xe0 fp=0x4000507f40 sp=0x4000507f20 pc=0x48570
runtime.gcBgMarkWorker()
        /home/myitcv/gos/src/runtime/mgc.go:1275 +0xe4 fp=0x4000507fd0 sp=0x4000507f40 pc=0x2b354
runtime.goexit()
        /home/myitcv/gos/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000507fd0 sp=0x4000507fd0 pc=0x76534
created by runtime.gcBgMarkStartWorkers
        /home/myitcv/gos/src/runtime/mgc.go:1199 +0x28

goroutine 8 [GC worker (idle)]:
runtime.gopark(0x1572867703a2?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/myitcv/gos/src/runtime/proc.go:381 +0xe0 fp=0x4000065f40 sp=0x4000065f20 pc=0x48570
runtime.gcBgMarkWorker()
        /home/myitcv/gos/src/runtime/mgc.go:1275 +0xe4 fp=0x4000065fd0 sp=0x4000065f40 pc=0x2b354
runtime.goexit()
        /home/myitcv/gos/src/runtime/asm_arm64.s:1172 +0x4 fp=0x4000065fd0 sp=0x4000065fd0 pc=0x76534
created by runtime.gcBgMarkStartWorkers
        /home/myitcv/gos/src/runtime/mgc.go:1199 +0x28
[exit status 2]
FAIL: /tmp/testscript3311982415/repro.txtar/script.txtar:1: unexpected command failure
error running repro.txtar in /tmp/testscript3311982415/repro.txtar
```

This is a regression, bisected to https://cuelang.org/cl/556460. 

~Will try to minimise another time if required.~

Edit: repro and minimised by @mvdan.

**Comment by myitcv** [comment]
Updated the description with a much-reduced repro (the edit history captures the original version)

**Comment by mvdan** [comment]
Here is a minified testscript that still reproduces the panic:

```
exec cue cmd gen_terraform

-- generate_tool.cue --
package p

import (
	"tool/file"
	"encoding/json"
)

input: {
	[name=string]: {
		out: {#convert & {#in: name}}.#out
	}
}
#convert: {
	#in: _
	#out: #in
}
command: {
	gen_terraform: {
		file.Create & {
			filename: "foo"
			contents: json.Marshal(input)
		}
	}
}
```

**Comment by myitcv** [comment]
> Here is a minified testscript that still reproduces the panic:


~Thanks - how does that behave with a previous commit?~

Edit: confirmed it behaves as the original repro does, i.e. no failure with a prior commit. I've updated the repro in the original description with the cut-down version.

**Comment by mvdan** [comment]
Here's an even smaller reproducer, which passes on v0.5.0:

```
exec cue cmd foo
cmp stdout stdout.golden

-- stdout.golden --
{}
-- foo_tool.cue --
package p

import (
	"tool/cli"
	"encoding/json"
)

input: [name=string]: {
	{#in: name, #out: #in}.#out
}
command: foo: {
	cli.Print & {text: json.Marshal(input)}
}
```

The problem seems to be related to the pattern constraint and `json.Marshal`.

**Comment by mvdan** [comment]
Fix at https://review.gerrithub.io/c/cue-lang/cue/+/556948 :) Although an assertion in the test is failing, so I'm checking with Marcel to see how I can make that pass.
