### ISSUE TITLE
cmd/cue: "Environment.up encountered a nil vertex" regression with v0.6 when using "cue cmd"

### ISSUE THREAD

**Issue by slewiskelly** [cue-lang/cue#2512]
### What version of CUE are you using (`cue version`)?

```console
$ cue version
cue version v0.0.0-20230801133340-43b4674898df

go version go1.20.6
      -buildmode exe
       -compiler gc
     CGO_ENABLED 1
          GOARCH arm64
            GOOS darwin
             vcs git
    vcs.revision 43b4674898df7e2e8758ccb6154041a98e321e40
        vcs.time 2023-08-01T13:33:40Z
    vcs.modified true
```

### Does this issue reproduce with the latest stable release?

No, confirmed working with the most stable release:

```console
$ cue version
cue version v0.5.0

go version go1.20.3
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 1
          GOARCH arm64
            GOOS darwin
```

### What did you do?

I'm still working on a smaller reproducer. This seems to work in simple cases, but is failing with more complicated, currently in-use, configurations.

### What did you expect to see?

A list of objects, presented in YAML format.

### What did you see instead?

Originally I had found this error via a custom command which marshals a list of objects:

```console
$ cue dump .
command.dump.text: error in call to encoding/yaml.MarshalStream: assertion failed: Environment.up encountered a nil vertex:
    ./dump_tool.cue:32:9
```

However, I found that this panics with a simple `cue export --out yaml`:

```console
$ cue export . --out yaml
panic: assertion failed: Environment.up encountered a nil vertex [recovered]
	panic: assertion failed: Environment.up encountered a nil vertex [recovered]
	panic: assertion failed: Environment.up encountered a nil vertex [recovered]
	panic: assertion failed: Environment.up encountered a nil vertex [recovered]
	panic: assertion failed: Environment.up encountered a nil vertex [recovered]
	panic: assertion failed: Environment.up encountered a nil vertex [recovered]
	panic: assertion failed: Environment.up encountered a nil vertex [recovered]
	panic: assertion failed: Environment.up encountered a nil vertex [recovered]
	panic: assertion failed: Environment.up encountered a nil vertex
```

<details>

<summary>Stack trace</summary>

```
goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0x14001105ea0)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/cmd/cue/cmd/root.go:315 +0x94
panic({0x102be1340, 0x14004a988d0})
	/opt/homebrew/Cellar/go/1.20.6/libexec/src/runtime/panic.go:884 +0x204
cuelang.org/go/internal/core/dep.visit.func1()
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:189 +0xb4
panic({0x102be1340, 0x14004a988d0})
	/opt/homebrew/Cellar/go/1.20.6/libexec/src/runtime/panic.go:884 +0x204
cuelang.org/go/internal/core/dep.visit.func1()
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:189 +0xb4
panic({0x102be1340, 0x14004a988d0})
	/opt/homebrew/Cellar/go/1.20.6/libexec/src/runtime/panic.go:884 +0x204
cuelang.org/go/internal/core/dep.visit.func1()
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:189 +0xb4
panic({0x102be1340, 0x14004a988d0})
	/opt/homebrew/Cellar/go/1.20.6/libexec/src/runtime/panic.go:884 +0x204
cuelang.org/go/internal/core/dep.visit.func1()
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:189 +0xb4
panic({0x102be1340, 0x14004a988d0})
	/opt/homebrew/Cellar/go/1.20.6/libexec/src/runtime/panic.go:884 +0x204
cuelang.org/go/internal/core/dep.visit.func1()
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:189 +0xb4
panic({0x102be1340, 0x14004a988d0})
	/opt/homebrew/Cellar/go/1.20.6/libexec/src/runtime/panic.go:884 +0x204
cuelang.org/go/internal/core/dep.visit.func1()
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:189 +0xb4
panic({0x102be1340, 0x14004a988d0})
	/opt/homebrew/Cellar/go/1.20.6/libexec/src/runtime/panic.go:884 +0x204
cuelang.org/go/internal/core/dep.visit.func1()
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:189 +0xb4
panic({0x102be1340, 0x14004a988d0})
	/opt/homebrew/Cellar/go/1.20.6/libexec/src/runtime/panic.go:884 +0x204
cuelang.org/go/internal/core/adt.(*OpContext).Assertf(0x14001102158?, {0x14000458150?, 0x14001102178?}, 0xb0?, {0x102a4cb47?, 0x0?}, {0x0, 0x0, 0x0})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/adt/context.go:104 +0xa0
cuelang.org/go/internal/core/adt.(*Environment).up(0x140011021c8?, 0x14006be0900, 0x51d7f80?)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/adt/composite.go:107 +0x54
cuelang.org/go/internal/core/adt.(*OpContext).relNode(0x14006be0900, 0x88c0?)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/adt/context.go:322 +0x30
cuelang.org/go/internal/core/adt.(*FieldReference).resolve(0x14000fa2d30, 0x102cfc2e0?, 0x30?)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/adt/expr.go:699 +0x34
cuelang.org/go/internal/core/adt.(*OpContext).unifyNode(0x14006be0900, {0x102cfc2e0, 0x14000fa2d30}, 0x2)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/adt/context.go:773 +0x180
cuelang.org/go/internal/core/adt.(*OpContext).node(0x14006be0900, {0x102cf6168?, 0x14000e0d620}, {0x102cfc2e0?, 0x14000fa2d30?}, 0x1, 0x0?)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/adt/context.go:971 +0x50
cuelang.org/go/internal/core/adt.(*IndexExpr).resolve(0x14000e0d620, 0x14006be0900, 0x68?)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/adt/expr.go:1002 +0x4c
cuelang.org/go/internal/core/adt.(*OpContext).resolveState(0x14006be0900, {0x14006355580, {0x102cf6168, 0x14000e0d620}, {0x0, 0x0, 0x0, {0x0, 0x0, 0x0}}}, ...)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/adt/context.go:476 +0xd8
cuelang.org/go/internal/core/adt.(*OpContext).Resolve(...)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/adt/context.go:470
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0x14001102cc0?, 0x12ad11280?, {0x102cf89a0?, 0x14000e0d620?})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:311 +0x108
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x14001102cc0, 0x14006355580, {0x12ad11280?, 0x14000e0d620?})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:233 +0x47c
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x14001102cc0, 0x14006355580, {0x102cfb118?, 0x14000e0d590?})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:252 +0x6e0
cuelang.org/go/internal/core/dep.(*visitor).markConjuncts(0x10500001891?, 0x1?)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:439 +0x94
cuelang.org/go/internal/core/dep.(*visitor).markInternalResolvers(0x14001102cc0, 0x0?, {0x102cf8af0?, 0x14000a11aa0?}, 0x14006346b20?)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:452 +0x5c
cuelang.org/go/internal/core/dep.(*visitor).reportDependency(0x14001102cc0, 0x14000d02f20?, {0x102cf8af0?, 0x14000a11aa0?}, 0x14003cdd9e0)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:367 +0x178
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0x14001102cc0, 0x12a8e16b8?, {0x102cf8af0?, 0x14000a11aa0})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:319 +0x210
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x14001102cc0, 0x14000d02f20, {0x12a8e16b8?, 0x14000a11aa0?})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:233 +0x47c
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x14001102cc0, 0x14000d02f20, {0x102cfb0a8?, 0x14000d181b0?})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:269 +0x620
cuelang.org/go/internal/core/dep.visit(0x14004b33801?, 0x0?, 0x14003ce1af0?, 0x14003ce1b78?, 0xf0?, 0x1a?)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:194 +0x11c
cuelang.org/go/internal/core/dep.VisitAll(...)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:144
cuelang.org/go/internal/core/export.(*pivotter).markDeps(0x14003ca74a0, 0x14006171290?, 0x14000c55dd0?)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/export/self.go:156 +0x8c
cuelang.org/go/internal/core/export.(*pivotter).markDeps.func1({0x14000c55dd0, {0x102cf8af0, 0x14000a11b20}, 0x0, 0x0})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/export/self.go:205 +0x384
cuelang.org/go/internal/core/dep.(*visitor).reportDependency(0x14001103330, 0x14006355160?, {0x102cf8af0?, 0x14000a11b20?}, 0x0?)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:419 +0x3a8
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0x14001103330, 0x12a8e16b8?, {0x102cf8af0?, 0x14000a11b20})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:319 +0x210
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x14001103330, 0x14006355160, {0x12a8e16b8?, 0x14000a11b20?})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:233 +0x47c
cuelang.org/go/internal/core/dep.(*visitor).markSubExpr(...)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:503
cuelang.org/go/internal/core/dep.(*visitor).markDecl(0x14001103330, 0x102cfb1f8?, {0x102cf8880?, 0x14000a11b40?})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:511 +0x80
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x14001103330, 0x14000d02f20, {0x102cfb1f8?, 0x140007e83f0?})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:298 +0x4c0
cuelang.org/go/internal/core/dep.visit(0x14004b33848?, 0x0?, 0x14003ce1a26?, 0x14003ce1ad8?, 0x20?, 0x1a?)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:194 +0x11c
cuelang.org/go/internal/core/dep.VisitAll(...)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:144
cuelang.org/go/internal/core/export.(*pivotter).markDeps(0x14003ca74a0, 0x14006171290?, 0x14000c55e60?)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/export/self.go:156 +0x8c
cuelang.org/go/internal/core/export.(*pivotter).markDeps.func1({0x14000c55e60, {0x102cf8af0, 0x14000e34020}, 0x0, 0x1})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/export/self.go:205 +0x384
cuelang.org/go/internal/core/dep.(*visitor).reportDependency(0x14001103920, 0x14001a65060?, {0x102cf8af0?, 0x14000e34020?}, 0x0?)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:419 +0x3a8
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0x14001103920, 0x12a8e16b8?, {0x102cf8af0?, 0x14000e34020})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:319 +0x210
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x14001103920, 0x14001a65060, {0x12a8e16b8?, 0x14000e34020?})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:233 +0x47c
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x14001103920, 0x14001a65060, {0x102cfaf58?, 0x14000ae8090?})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:244 +0x100
cuelang.org/go/internal/core/dep.visit(0x14004b33830?, 0x0?, 0x14003ce1884?, 0x14003ce1928?, 0x80?, 0x18?)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:194 +0x11c
cuelang.org/go/internal/core/dep.VisitAll(...)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:144
cuelang.org/go/internal/core/export.(*pivotter).markDeps(0x14003ca74a0, 0x14006171290?, 0x14000aadd40?)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/export/self.go:156 +0x8c
cuelang.org/go/internal/core/export.(*pivotter).markDeps.func1({0x14000aadd40, {0x102cf8af0, 0x14000ac2980}, 0x0, 0x0})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/export/self.go:205 +0x384
cuelang.org/go/internal/core/dep.(*visitor).reportDependency(0x14001104280, 0x140063544e0?, {0x102cf8af0?, 0x14000ac2980?}, 0x0?)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:419 +0x3a8
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0x14001104280, 0x12a8e16b8?, {0x102cf8af0?, 0x14000ac2980})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:319 +0x210
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x14001104280, 0x140063544e0, {0x12a8e16b8?, 0x14000ac2980?})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:233 +0x47c
cuelang.org/go/internal/core/dep.(*visitor).markSubExpr(...)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:503
cuelang.org/go/internal/core/dep.(*visitor).markDecl(0x14001104280, 0x102cfb1f8?, {0x102cf8880?, 0x14000ac2a00?})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:511 +0x80
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x14001104280, 0x140063544c0, {0x102cfb1f8?, 0x14000a5a120?})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:298 +0x4c0
cuelang.org/go/internal/core/dep.(*visitor).markSubExpr(...)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:503
cuelang.org/go/internal/core/dep.(*visitor).markDecl(0x14001104280, 0x102cfb1f8?, {0x102cf8880?, 0x14000ac2b00?})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:511 +0x80
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x14001104280, 0x14001a65140, {0x102cfb1f8?, 0x14000a5a090?})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:298 +0x4c0
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x14001104280, 0x14001a65140, {0x102cfaf58?, 0x14000a552c0?})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:245 +0x130
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x14001104280, 0x14001a65140, {0x102cfaf58?, 0x14000a552f0?})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:244 +0x100
cuelang.org/go/internal/core/dep.visit(0x14004b32701?, 0x0?, 0x140007771e2?, 0x14000777278?, 0xe0?, 0x71?)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:194 +0x11c
cuelang.org/go/internal/core/dep.VisitAll(...)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:144
cuelang.org/go/internal/core/export.(*pivotter).markDeps(0x14003ca74a0, 0x14006171290?, 0x14000bec2d0?)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/export/self.go:156 +0x8c
cuelang.org/go/internal/core/export.(*pivotter).markDeps.func1({0x14000bec2d0, {0x102cf8af0, 0x14000e34280}, 0x0, 0x1})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/export/self.go:205 +0x384
cuelang.org/go/internal/core/dep.(*visitor).reportDependency(0x140011047a0, 0x14000fa0f60?, {0x102cf8af0?, 0x14000e34280?}, 0x0?)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:419 +0x3a8
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0x140011047a0, 0x12a8e16b8?, {0x102cf8af0?, 0x14000e34280})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:319 +0x210
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x140011047a0, 0x14000fa0f60, {0x12a8e16b8?, 0x14000e34280?})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:233 +0x47c
cuelang.org/go/internal/core/dep.visit(0x14004b32701?, 0x0?, 0x140007771e1?, 0x14000777270?, 0xe0?, 0x71?)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:194 +0x11c
cuelang.org/go/internal/core/dep.VisitAll(...)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:144
cuelang.org/go/internal/core/export.(*pivotter).markDeps(0x14003ca74a0, 0x14006171290?, 0x14000cfbb00?)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/export/self.go:156 +0x8c
cuelang.org/go/internal/core/export.(*pivotter).markDeps.func1({0x14000cfbb00, {0x102cf8af0, 0x14000930000}, 0x0, 0x1})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/export/self.go:205 +0x384
cuelang.org/go/internal/core/dep.(*visitor).reportDependency(0x14001104f20, 0x14000fa0ea0?, {0x102cf8af0?, 0x14000930000?}, 0x0?)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:419 +0x3a8
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0x14001104f20, 0x12a8e16b8?, {0x102cf8af0?, 0x14000930000})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:319 +0x210
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x14001104f20, 0x14000fa0ea0, {0x12a8e16b8?, 0x14000930000?})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:233 +0x47c
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x14001104f20, 0x14000fa0ea0, {0x102cfaf58?, 0x14000a398f0?})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:244 +0x100
cuelang.org/go/internal/core/dep.(*visitor).markClauses(0x140000021a0?, 0x14001104f50?, {0x140004806d0?, 0x1, 0x14001104d98?})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:578 +0x250
cuelang.org/go/internal/core/dep.(*visitor).markComprehension(0x102c17a60?, 0x102cfb070?, 0x14000cf98c0)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:539 +0x34
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x14001104f20, 0x14000fa0ea0, {0x102cfb070?, 0x14000cf98c0?})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:302 +0x464
cuelang.org/go/internal/core/dep.visit(0x14004b32701?, 0x0?, 0x140007771e0?, 0x14000777268?, 0xe0?, 0x71?)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:194 +0x11c
cuelang.org/go/internal/core/dep.VisitAll(...)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:144
cuelang.org/go/internal/core/export.(*pivotter).markDeps(0x14003ca74a0, 0x14006171290?, 0x14000cfba70?)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/export/self.go:156 +0x8c
cuelang.org/go/internal/core/export.(*pivotter).markDeps.func1({0x14000cfba70, {0x102cf88e0, 0x14000480510}, 0x0, 0x0})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/export/self.go:205 +0x384
cuelang.org/go/internal/core/dep.(*visitor).reportDependency(0x14001105550, 0x14006346b60?, {0x102cf88e0?, 0x14000480510?}, 0x0?)
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:419 +0x3a8
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0x14001105550, 0x12a8df7e8?, {0x102cf88e0?, 0x14000480510})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:319 +0x210
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0x14001105550, 0x14006346b60, {0x12a8df7e8?, 0x14000480510?})
	/Users/slewiskelly/go/src/github.com/cue-lang/cue/internal/core/dep/dep.go:233 +0x47c
```

</details>

Note, I can export this fine with a format of CUE or JSON.

**Comment by slewiskelly** [comment]
Git bisect narrowed it down to being introduced by https://review.gerrithub.io/c/cue-lang/cue/+/556368.

```console
$ git bisect bad
f51365488e8a346fe7f321ef62b75b3ab7be1559 is the first bad commit
commit f51365488e8a346fe7f321ef62b75b3ab7be1559
...
```

**Comment by mvdan** [comment]
@vterdunov on Slack you mentioned you ran into this issue as well - do you have a reproducer that we could use to replicate this bug?

**Comment by mvdan** [comment]
Adding this to the v0.6.0 milestone for now, as an assertion panic is worrying enough that we're holding up the release for now. We might have to push back a proper fix until v0.6.1 or v0.7 if we can't get a reproducer, though.

**Comment by mvdan** [comment]
Courtesy of @slewiskelly, below is a reproducer, which I reduced a bit further to just ten lines of CUE:

```
exec cue export . --out json
exec cue export . --out yaml
exec cue export . --out cue

exec cue export . -e out --out json
exec cue export . -e out --out yaml # fails on v0.6.0-rc.1
exec cue export . -e out --out cue  # fails on v0.6.0-rc.1
-- in.cue --
package k8s

_env: "prod"
_envIf: {
	env: string
	if true {
		env: _env
	}
}

out: (_envIf & {}).env
```

I could not reproduce it any further - not even by removing the `package` line or seemingly redundant bits like `if true` or `& {}`. Also note that the way this reproduces with cmd/cue requires that:

* the `-e` flag is being used
* a particular output format is being used

**Comment by mvdan** [comment]
Also confirming that this still bisects to f51365488e8a346fe7f321ef62b75b3ab7be1559.

**Comment by mvdan** [comment]
Slightly simpler reproducer, per Marcel:

```
exec cue export . -e out --out yaml # fails on v0.6.0-rc.1
-- in.cue --
package k8s

env2: "prod"
envIf: {
	env: string
	if true {
		env: env2
	}
}

out: (envIf & {}).env
```

**Comment by vterdunov** [comment]
@mvdan 
```
git bisect bad
6db2253ab586721682e96e86bfe1fb281fe8c46d is the first bad commit
commit 6db2253ab586721682e96e86bfe1fb281fe8c46d
Author: Daniel Martí <mvdan@mvdan.cc>
Date:   Fri Jun 23 16:44:13 2023 +0100
```

Error:
```
cue cmd dump
command.dump.generate."test-manifests-repository".contents: error in call to encoding/yaml.Marshal: assertion failed: Environment.up encountered a nil vertex:
    ./k8s_tool.cue:28:19
```

Btw for previous commit `c724eef0ca75447ba2dd99bfea849f1cea1b680b` another error
```
cue cmd dump
command.dump.generate."test-manifests-repository".contents: error in call to encoding/yaml.Marshal: runtime error: invalid memory address or nil pointer dereference:
    ./k8s_tool.cue:28:19
```

Also cue rc1 fixed the `Environment.up encountered a nil vertex` in my case.

**Comment by mvdan** [comment]
@vterdunov we have just fixed the crash we were able to reproduce with @slewiskelly's report. Could you confirm whether or not you are still able to reproduce your crash with the latest master, 99e8578ac45e5e7e6ebf25794303bc916744c0d3? We're otherwise ready to tag v0.6.0 after fixes like this one, so I just want to double check that you aren't running into a different way to trigger this crash.

**Comment by vterdunov** [comment]
@mvdan thanks. 99e8578ac45e5e7e6ebf25794303bc916744c0d3 is ok. no errors
