### ISSUE TITLE
evaluator: unreachable error when using self-alias in key

### ISSUE THREAD

**Issue by CJKay** [cue-lang/cue#2527]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.6.0-rc.1

go version go1.18.1
       -compiler gc
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
</pre>

### Does this issue reproduce with the latest stable release?

Yes.

### What did you do?

Write the following into a file `crash.cue`:

```cue
this = "\(this)": _|_
```

Attempt to evaluate the file:

```sh
cue eval crash.cue
```

### What did you expect to see?

An error message indicating that the code is invalid, for any reason.

### What did you see instead?

An unreachable code crash dump:

```
panic: unreachable [recovered]
        panic: unreachable

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0x4000587ea0)
        /home/vscode/go/pkg/mod/cuelang.org/go@v0.6.0-rc.1/cmd/cue/cmd/root.go:315 +0x98
panic({0x79e020, 0x9fd728})
        /usr/lib/go-1.18/src/runtime/panic.go:838 +0x20c
cuelang.org/go/internal/core/compile.(*compiler).resolve(0x40003a0460, 0x40000911d0)
        /home/vscode/go/pkg/mod/cuelang.org/go@v0.6.0-rc.1/internal/core/compile/compile.go:506 +0xd34
cuelang.org/go/internal/core/compile.(*compiler).expr(0x40003a0460, {0xa0bae0?, 0x40000911d0?})
        /home/vscode/go/pkg/mod/cuelang.org/go@v0.6.0-rc.1/internal/core/compile/compile.go:849 +0x3a0
cuelang.org/go/internal/core/compile.(*compiler).expr(0x40003a0460, {0xa0bc98?, 0x400011cea0?})
        /home/vscode/go/pkg/mod/cuelang.org/go@v0.6.0-rc.1/internal/core/compile/compile.go:897 +0x26c
cuelang.org/go/internal/core/compile.(*compiler).expr(0x40003a0460, {0xa0bb90?, 0x400011ced0?})
        /home/vscode/go/pkg/mod/cuelang.org/go@v0.6.0-rc.1/internal/core/compile/compile.go:968 +0x15d8
cuelang.org/go/internal/core/compile.(*compiler).addLetDecl(0x40003a0460, {0xa0ab88?, 0x40000f6100?})
        /home/vscode/go/pkg/mod/cuelang.org/go@v0.6.0-rc.1/internal/core/compile/compile.go:723 +0x110
cuelang.org/go/internal/core/compile.(*compiler).addDecls(0x85a220?, 0x4000497950, {0x40002091e0, 0x1, 0x4000401570?})
        /home/vscode/go/pkg/mod/cuelang.org/go@v0.6.0-rc.1/internal/core/compile/compile.go:537 +0x178
cuelang.org/go/internal/core/compile.(*compiler).compileFiles(0x40003a0460, {0x400020a1a8, 0x1, 0x0?})
        /home/vscode/go/pkg/mod/cuelang.org/go@v0.6.0-rc.1/internal/core/compile/compile.go:307 +0x380
cuelang.org/go/internal/core/compile.Files(0x0, {0xa09c98?, 0x40003f8ee8}, {0x9fd148, 0x1}, {0x400020a1a8, 0x1, 0x1})
        /home/vscode/go/pkg/mod/cuelang.org/go@v0.6.0-rc.1/internal/core/compile/compile.go:63 +0x144
cuelang.org/go/internal/core/runtime.(*Runtime).Build(0x40003f8ee8, 0x0, 0x40002d05a0)
        /home/vscode/go/pkg/mod/cuelang.org/go@v0.6.0-rc.1/internal/core/runtime/build.go:80 +0x218
cuelang.org/go/cue.(*Context).BuildInstances(0x40003f8ee8, {0x40005877b8, 0x1, 0x1e0?})
        /home/vscode/go/pkg/mod/cuelang.org/go@v0.6.0-rc.1/cue/context.go:147 +0xb0
cuelang.org/go/cmd/cue/cmd.buildInstances(0x4000425b60, {0x40005877b8, 0x1, 0x8aaae1?}, 0x1)
        /home/vscode/go/pkg/mod/cuelang.org/go@v0.6.0-rc.1/cmd/cue/cmd/common.go:724 +0x38
cuelang.org/go/cmd/cue/cmd.parseArgs(0x4000425b60, {0x4000458410, 0x1, 0x1}, 0x4000411590)
        /home/vscode/go/pkg/mod/cuelang.org/go@v0.6.0-rc.1/cmd/cue/cmd/common.go:616 +0xc1c
cuelang.org/go/cmd/cue/cmd.runEval(0x4000425b60, {0x4000458410, 0x1, 0x1})
        /home/vscode/go/pkg/mod/cuelang.org/go@v0.6.0-rc.1/cmd/cue/cmd/eval.go:88 +0x6c
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0x400032d800?, {0x4000458410, 0x1, 0x1})
        /home/vscode/go/pkg/mod/cuelang.org/go@v0.6.0-rc.1/cmd/cue/cmd/root.go:87 +0x94
github.com/spf13/cobra.(*Command).execute(0x400032d800, {0x40004583d0, 0x1, 0x1})
        /home/vscode/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x60c
github.com/spf13/cobra.(*Command).ExecuteC(0x400032cf00)
        /home/vscode/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x368
github.com/spf13/cobra.(*Command).Execute(...)
        /home/vscode/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0x4000425b60, {0x2?, 0x2?})
        /home/vscode/go/pkg/mod/cuelang.org/go@v0.6.0-rc.1/cmd/cue/cmd/root.go:300 +0x60
cuelang.org/go/cmd/cue/cmd.Main()
        /home/vscode/go/pkg/mod/cuelang.org/go@v0.6.0-rc.1/cmd/cue/cmd/root.go:228 +0x8c
main.main()
        /home/vscode/go/pkg/mod/cuelang.org/go@v0.6.0-rc.1/cmd/cue/main.go:24 +0x20
```

**Comment by mvdan** [comment]
Slightly smaller repro, which also doesn't involve the bottom literal `_|_`:

```
exec cue export in.cue

-- in.cue --
x = (x): 3
```

**Comment by mvdan** [comment]
Still seems to happen as of v0.13.0-alpha.4.

**Comment by jpluscplusm** [comment]
This still panics under CUE v0.14.1.
