### ISSUE TITLE
encoding/openapi: panic: unreachable HiddenLabel + IndexLabel

### ISSUE THREAD

**Issue by mvdan** [cue-lang/cue#2530]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20230802143915-da3ee7dc7b27

go version devel go1.22-088f953fd0 Mon Aug 7 06:58:18 2023 +0000
      -buildmode exe
       -compiler gc
  DefaultGODEBUG panicnil=1
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v3
             vcs git
    vcs.revision da3ee7dc7b27de85bbfb0a4104dfb22bcb18ef68
        vcs.time 2023-08-02T14:39:15Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest stable release?

Yes, verified with v0.5.0.

### What did you do?

```
go mod tidy
go run .
-- main.go --
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"log"

	"cuelang.org/go/cue"
	"cuelang.org/go/cue/cuecontext"
	"cuelang.org/go/cue/load"
	"cuelang.org/go/encoding/openapi"
)

func genOpenAPI(inst cue.InstanceOrValue) ([]byte, error) {
    b, err := openapi.Gen(inst, nil)
    if err != nil {
        return nil, err
    }

    var out bytes.Buffer
    err = json.Indent(&out, b, "", "   ")
    if err != nil {
        return nil, err
    }
    
    return out.Bytes(), nil
}

func main() {
	inst := load.Instances([]string{"."}, &load.Config{Dir: "mod"})[0]
	if err := inst.Err; err != nil {
		log.Fatal(err)
	}
	val := cuecontext.New().BuildInstance(inst)
	if err := val.Err(); err != nil {
		log.Fatal(err)
	}

    b, err := genOpenAPI(val)
    if err != nil {
		log.Fatal(err)
    }
	fmt.Println(string(b))
}

-- mod/cue.mod/module.cue --
module: "mod.test"
-- mod/x.cue --
package x

#Def: {
	_Another
	barRadius: float64
}

_Another: {
	barRadius: < 2.5
}

-- go.mod --
module test

go 1.20

replace cuelang.org/go => /home/mvdan/src/cue/cue

require cuelang.org/go v0.0.0-00010101000000-000000000000
-- go.sum --
```

### What did you expect to see?

No panic.

### What did you see instead?

```
> go run .
[stderr]
panic: unreachable HiddenLabel [recovered]
	panic: unreachable HiddenLabel

goroutine 1 [running]:
panic({0x96fce0?, 0xc0002c0c70?})
	/home/mvdan/tip/src/runtime/panic.go:621 +0x158 fp=0xc0002ef218 sp=0xc0002ef160 pc=0x439b78
cuelang.org/go/encoding/openapi.schemas.func2()
	/home/mvdan/src/cue/cue/encoding/openapi/build.go:161 +0x76 fp=0xc0002ef240 sp=0xc0002ef218 pc=0x8d8b96
panic({0x96fce0?, 0xc0002c0c70?})
	/home/mvdan/tip/src/runtime/panic.go:612 +0x132 fp=0xc0002ef2f8 sp=0xc0002ef240 pc=0x439b52
cuelang.org/go/encoding/openapi.selectorLabel({{0xb076f0?, 0xc000444e40?}})
	/home/mvdan/src/cue/cue/encoding/openapi/build.go:1375 +0x114 fp=0xc0002ef350 sp=0xc0002ef2f8 pc=0x8e0c14
cuelang.org/go/encoding/openapi.(*buildContext).makeRef(0xc0002c08f0?, {0xc0002c08f0?, 0xc0004f47e0?, 0x0?}, {{0xc0002c0c30?, 0xc0004f4b40?, 0x0?}})
	/home/mvdan/src/cue/cue/encoding/openapi/build.go:1323 +0x1d4 fp=0xc0002ef410 sp=0xc0002ef350 pc=0x8e0514
cuelang.org/go/encoding/openapi.(*builder).value(0xc0000b6dc0, {0xc0002c08f0?, 0xc0004f4b40?, 0x0?}, 0xc0000b6dc0?)
	/home/mvdan/src/cue/cue/encoding/openapi/build.go:383 +0x3a7 fp=0xc0002ef790 sp=0xc0002ef410 pc=0x8da167
cuelang.org/go/encoding/openapi.(*builder).fillSchema(0xc0000b6dc0, {0xc0002c08f0?, 0xc0004f4b40?, 0x0?})
	/home/mvdan/src/cue/cue/encoding/openapi/build.go:297 +0xc9 fp=0xc0002ef7f8 sp=0xc0002ef790 pc=0x8d9a49
cuelang.org/go/encoding/openapi.(*builder).schema(0xc0002ef940?, 0x0, {{0xb076b0?, 0xc0002c0a90?}}, {0xc0002c08f0?, 0xc0004f4b40?, 0x0?})
	/home/mvdan/src/cue/cue/encoding/openapi/build.go:267 +0x311 fp=0xc0002ef8e0 sp=0xc0002ef7f8 pc=0x8d95f1
cuelang.org/go/encoding/openapi.(*buildContext).build(0xb076b0?, {{0xb076b0?, 0xc0002c0a90?}}, {0xc0002c08f0?, 0xc0004f4b40?, 0x0?})
	/home/mvdan/src/cue/cue/encoding/openapi/build.go:220 +0xb2 fp=0xc0002efa00 sp=0xc0002ef8e0 pc=0x8d8e92
cuelang.org/go/encoding/openapi.schemas(0xea6160, {0xb04368, 0xc00000e6d8})
	/home/mvdan/src/cue/cue/encoding/openapi/build.go:184 +0xb7a fp=0xc0002efcc0 sp=0xc0002efa00 pc=0x8d84ba
cuelang.org/go/encoding/openapi.(*Config).All(0xc00000e6d8?, {0xb04368, 0xc00000e6d8})
	/home/mvdan/src/cue/cue/encoding/openapi/openapi.go:122 +0x25 fp=0xc0002efcf8 sp=0xc0002efcc0 pc=0x8e3bc5
cuelang.org/go/encoding/openapi.Gen({0xb04368?, 0xc00000e6d8?}, 0x4185dc?)
	/home/mvdan/src/cue/cue/encoding/openapi/openapi.go:94 +0x38 fp=0xc0002efd20 sp=0xc0002efcf8 pc=0x8e3b38
```

**Comment by mvdan** [comment]
Using the same testscript and cue version, the input CUE

```
package x

#Schemas: [
    {
        #AsRef: {}
    }
]
```

produces `panic: unreachable IndexLabel` in the same func body.

**Comment by eadlam** [comment]
@mvdan Have you found any good workarounds for this?

**Comment by mvdan** [comment]
We haven't looked into this panic yet, I'm afraid. It's up for grabs if anyone else wants to try to debug what's going on.

**Comment by eadlam** [comment]
I found a workaround for my problem. This produces the same `unreachable HiddenLabel` panic:

```cue
package x

#Def: {
    params: barRadius: float64
    _params: params
    inner: params: _params
}
```

This workaround avoids the panic:

```cue
package x

#Def: {
    params: barRadius: float64
    inner: "params": params
}
```

**Comment by rogpeppe** [comment]
The panic reported here (`unreachable HiddenLabel` / `unreachable IndexLabel`) is fixed by the new whole-document OpenAPI implementation, which converts schemas via `encoding/jsonschema.Generate` and no longer goes through the old reference-building code that panicked. All the variants from the issue and the follow-up comments now generate valid OpenAPI.

This fix requires the new implementation, which is enabled with `CUE_EXPERIMENT=openapiv2` (a preview introduced in v0.18.0). Closing as fixed.
