### ISSUE TITLE
internal/core/export: nil pointer dereference during eval since v0.6.0

### ISSUE THREAD

**Issue by mvdan** [cue-lang/cue#2584]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.6.1-0.20230919100910-692361740f70

go version devel go1.22-ace1494d92 Thu Sep 21 02:36:06 2023 +0000
      -buildmode exe
       -compiler gc
        -ldflags -w -s
  DefaultGODEBUG httplaxcontentlength=1,panicnil=1
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v3
</pre>

### Does this issue reproduce with the latest stable release?

Yes, with v0.6.0.

### What did you do?

```
exec cue eval in.cue

-- in.cue --
F1: sub1: sub2: L
F2: {
	(string): _
	L
}
D: {}
let L = D
```

### What did you expect to see?

A testscript PASS; it shouldn't panic, and it should produce some CUE syntax.

### What did you see instead?

```
> exec cue eval in.cue
[stderr]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1b pc=0x6e43e9]

goroutine 1 [running]:
panic({0xc8f700?, 0x1405550?})
	/home/mvdan/tip/src/runtime/panic.go:774 +0x158 fp=0xc00035a200 sp=0xc00035a150 pc=0x43ad18
cuelang.org/go/cmd/cue/cmd.recoverError(0xc00035de88)
	/home/mvdan/go/pkg/mod/cuelang.org/go@v0.6.1-0.20230919100910-692361740f70/cmd/cue/cmd/root.go:318 +0x76 fp=0xc00035a220 sp=0xc00035a200 pc=0xbd87b6
cuelang.org/go/cmd/cue/cmd.(*Command).Run.deferwrap1()
	/home/mvdan/go/pkg/mod/cuelang.org/go@v0.6.1-0.20230919100910-692361740f70/cmd/cue/cmd/root.go:301 +0x25 fp=0xc00035a238 sp=0xc00035a220 pc=0xbd8705
panic({0xc8f700?, 0x1405550?})
	/home/mvdan/tip/src/runtime/panic.go:765 +0x132 fp=0xc00035a2e8 sp=0xc00035a238 pc=0x43acf2
runtime.panicmem(...)
	/home/mvdan/tip/src/runtime/panic.go:261
runtime.sigpanic()
	/home/mvdan/tip/src/runtime/signal_unix.go:866 +0x378 fp=0xc00035a348 sp=0xc00035a2e8 pc=0x451c18
cuelang.org/go/internal/core/export.(*exporter).resolve(0xc0000de420, 0xc0002029a0, {0xec87b0?, 0xc0002bc7a0?})
	/home/mvdan/go/pkg/mod/cuelang.org/go@v0.6.1-0.20230919100910-692361740f70/internal/core/export/adt.go:332 +0xb09 fp=0xc00035a510 sp=0xc00035a348 pc=0x6e43e9
cuelang.org/go/internal/core/export.(*exporter).adt(0xc0000de420, 0xc0002029a0, {0x7fa5f5dc8310?, 0xc0002bc7a0?})
	/home/mvdan/go/pkg/mod/cuelang.org/go@v0.6.1-0.20230919100910-692361740f70/internal/core/export/adt.go:137 +0xa35 fp=0xc00035a9c0 sp=0xc00035a510 pc=0x6e1bf5
cuelang.org/go/internal/core/export.(*exporter).expr(0xc0000de420?, 0xc0001d5710?, {0x7fa5f5dc8310?, 0xc0002bc7a0?})
	/home/mvdan/go/pkg/mod/cuelang.org/go@v0.6.1-0.20230919100910-692361740f70/internal/core/export/expr.go:99 +0x2df fp=0xc00035ac18 sp=0xc00035a9c0 pc=0x6eba7f
cuelang.org/go/internal/core/export.(*exporter).resolveLet(0xc0000de420, 0x0?, 0xc000398080)
	/home/mvdan/go/pkg/mod/cuelang.org/go@v0.6.1-0.20230919100910-692361740f70/internal/core/export/export.go:580 +0xf2 fp=0xc00035ac78 sp=0xc00035ac18 pc=0x6ea7d2
[...]
```

This panic does not happen with v0.5.0; I have not bisected yet.

**Comment by rudifa** [comment]
Out of curiosity, I performed the bisect between commits `d573e0c2f041 tag: v0.5.0-beta.3` and `99e8578ac45e tag: v0.6.0`. Here is the result:

```
cue % git bisect start                                                           [topic-2 L|✔]
status: waiting for both good and bad commits
cue % git bisect good d573e0c2f041                          [topic-2|BISECT 0; -inf steps L|✔]
status: waiting for bad commit, 1 good commit known
cue % git bisect bad 99e8578ac45e                           [topic-2|BISECT 0; -inf steps L|✔]
Bisecting: 141 revisions left to test after this (roughly 7 steps)
[0c840f6652709b9d142f2023fac744773b375bd9] internal/core/adt: change addList signature
cue % git bisect good                                       [:0c840f6|BISECT 283; 8 steps L|✔]
Bisecting: 70 revisions left to test after this (roughly 6 steps)
[e46324ef052b90aaf605aebea608fa147b2bf8dd] spec: various fixes
cue % git bisect bad                                        [:e46324e|BISECT 141; 7 steps L|✔]
Bisecting: 35 revisions left to test after this (roughly 5 steps)
[bad36b2d8a19dd566a27e304407038abbe617968] all: move pkg/gen and internal/cmd/qgo to build-ignored files
cue % git bisect bad                                                         [:bad36b2|BISECT 70; 6 steps L|✔]
Bisecting: 17 revisions left to test after this (roughly 4 steps)
[e7d7c6a7aa9ba8e2024a874431558c8e5ec4e8d5] cue: fail on required field in various cases
cue % git bisect good                                                        [:e7d7c6a|BISECT 34; 5 steps L|✔]
Bisecting: 8 revisions left to test after this (roughly 3 steps)
[1932295afe5dc1753a99bf8cf616c2afc12eb653] cue/build: remove context.Context field
cue % git bisect bad                                                         [:1932295|BISECT 17; 4 steps L|✔]
Bisecting: 4 revisions left to test after this (roughly 2 steps)
[1c9a3b26939456a729de38c7e31a20f4f5693bb7] internal/core/export: avoid introducing shadowing
cue % git bisect bad                                                          [:1c9a3b2|BISECT 8; 3 steps L|✔]
Bisecting: 1 revision left to test after this (roughly 1 step)
[0e1608456fd9df41b27d05bba7f97d25881bce63] cue: more support for required fields for selectors
cue % git bisect good                                                         [:0e16084|BISECT 3; 1 steps L|✔]
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[102150dedd937090ffee149b1675ff1b0bef89cc] internal/tdtest: new table-driven test package
cue % git bisect good                                                         [:102150d|BISECT 2; 1 steps L|✔]
1c9a3b26939456a729de38c7e31a20f4f5693bb7 is the first bad commit
commit 1c9a3b26939456a729de38c7e31a20f4f5693bb7
Author: Marcel van Lohuizen <mpvl@gmail.com>
Date:   Wed Apr 5 11:13:04 2023 +0200

    internal/core/export: avoid introducing shadowing
    
    The solution is to unconditionally link Ident.Node fields with
    their resolution, allowing the sanitizer to unshadow.
    The exporter is becoming quite a mess and is due for an
    overhaul. The implementation should be notably easier with the
    upcoming evaluator overhaul, so it seems a waste to do that now.
    
    Fixes #2311
    
    Signed-off-by: Marcel van Lohuizen <mpvl@gmail.com>
    Change-Id: I38d2c010814e5d97424d72890da002bb1c6ef2cb
    Reviewed-on: https://review.gerrithub.io/c/cue-lang/cue/+/552252
    Reviewed-by: Roger Peppe <rogpeppe@gmail.com>
    Unity-Result: CUEcueckoo <cueckoo@cuelang.org>
    TryBot-Result: CUEcueckoo <cueckoo@cuelang.org>

 internal/core/export/adt.go                     |  43 +++-
 internal/core/export/export.go                  |  54 ++++-
 internal/core/export/expr.go                    |   2 +
 internal/core/export/testdata/main/shadow.txtar | 308 +++++++++++++++++-------
 4 files changed, 323 insertions(+), 84 deletions(-)
```

**Comment by rudifa** [comment]
@mvdan I identified the panic point in the code. On my branch 
[fix-issue-2584](https://github.com/cue-lang/cue/compare/master...rudifa:cue:fix-issue-2584) I added a fix and a txtar script that checks it.

Would this be good enough for a pull request?

**Comment by mvdan** [comment]
We looked at this fix together; I can't say for sure if it's the best one, but like Marcel said in the commit message that you bisected the panic to, the exporter is due for an overhaul and it's a bit messy. And it's his added fix that introduced this panic. Plus, I verified that your fix doesn't break any other tests.

For all the reasons above, I'm inclined to merge your nil check fix with the test. Can you send a PR or CL per https://github.com/cue-lang/cue/blob/master/CONTRIBUTING.md?

Please add the test via `internal/core/export/testdata`, since that's a better place for export tests than `cmd/cue/cmd`. You can find a recent example where a fix added a test in 24f3fb310302afea643e19087876e7836afd2e5c.

**Comment by mvdan** [comment]
Also, you can use `cd internal/core/export; CUE_UPDATE=1 go test` to update the output in the testdata file once you've added the CUE input source and fixed the bug.

**Comment by gotwarlost** [comment]
Came here to raise a nil pointer deref issue, found this bug and it looks like the PR fixes my problems too.

```
exec cue eval in.cue

-- in.cue --
_ref: { name: string }

let genName= "\(_ref.name)-suffix"
let innerObj = {
	gen:   genName
}
name: genName
inner: innerObj
```
