### ISSUE TITLE
Can't build *adt.Vertex from same *build.Instance in multiple goroutines

### ISSUE THREAD

**Issue by bozaro** [cue-lang/cue#2596]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version

cue version v0.0.0-20230912145313-0e9584387f3f

go version go1.21.1
      -buildmode exe
       -compiler gc
  DefaultGODEBUG panicnil=1
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
             vcs git
    vcs.revision 0e9584387f3fa0fa6b0a5c509d75c0088481df96
        vcs.time 2023-09-12T14:53:13Z
    vcs.modified true
</pre>

### Does this issue reproduce with the latest stable release?

Yes.

### What did you do?

I execute code like from multiple goroutines:
```go
		func(instance *build.Instance) {
			_, err := runtime.New().Build(nil, instance)
			if err != nil {
				t.Fatal(err)
			}
		}
```

Runnable testcase:
 - https://github.com/cue-lang/cue/pull/2597

### What did you expect to see?

No panics.

### What did you see instead?

```
=== RUN   TestX
panic: runtime error: index out of range [2] with length 2

goroutine 131 [running]:
cuelang.org/go/internal/core/runtime.resolveFile(0xc000782070, 0xc000133f80, 0xc0002c4b40, 0x4?)
	/home/bozaro/joom/cue/internal/core/runtime/resolve.go:157 +0xf85
cuelang.org/go/internal/core/runtime.(*Runtime).ResolveFiles(0xd469d8?, 0xc0002c4b40)
	/home/bozaro/joom/cue/internal/core/runtime/resolve.go:52 +0x1b7
cuelang.org/go/internal/core/runtime.(*Runtime).Build(0xc000780018, 0x0, 0xc0002c4b40)
	/home/bozaro/joom/cue/internal/core/runtime/build.go:69 +0x19c
cuelang.org/go/internal/core/runtime.(*Runtime).buildSpec(0xc000780018, 0x41ae6b?, 0xc0002c4960, 0xc00040c870)
	/home/bozaro/joom/cue/internal/core/runtime/build.go:150 +0x2cc
cuelang.org/go/internal/core/runtime.(*Runtime).Build.func1(0x0?)
	/home/bozaro/joom/cue/internal/core/runtime/build.go:64 +0x8a
cuelang.org/go/cue/ast.(*File).VisitImports(0xc000784150?, 0xc0000d9f10)
	/home/bozaro/joom/cue/cue/ast/ast.go:996 +0x87
cuelang.org/go/internal/core/runtime.(*Runtime).Build(0xc000780018, 0x0, 0xc0002c4960)
	/home/bozaro/joom/cue/internal/core/runtime/build.go:62 +0x16c
cuelang.org/go/internal/core/adt_test.TestX.func1(0xd44128?)
	/home/bozaro/joom/cue/internal/core/adt/eval_test.go:177 +0x1dd
created by cuelang.org/go/internal/core/adt_test.TestX in goroutine 19
	/home/bozaro/joom/cue/internal/core/adt/eval_test.go:173 +0x198
```

**Comment by bozaro** [comment]
`runtime.New()` contains builtins index and inject builtins definitions by mutatiting `*build.Instance` instance on first `Build` execution. 

This also means that, strictly speaking, `*build.Instance` cannot be reused with different `runtime.New()` object even in single goroutine mode.

**Comment by mvdan** [comment]
These APIs are currently not safe for concurrent use - for example, see https://github.com/cue-lang/cue/issues/460 and https://github.com/cue-lang/cue/issues/1746. This is something we want to improve for sure, and in fact @rogpeppe has sent a few changes already, although right now we are prioritizing issues relating to correctness and evaluator performance.

This issue _might_ be a duplicate of 1746, but I think it's worth keeping it open for the sake of ensuring that your reproducer is fixed as well.

**Comment by mvdan** [comment]
Actually, I'll add your reproducer to https://github.com/cue-lang/cue/issues/1746, for the sake of not tracking this in multiple issues.
