### ISSUE TITLE
cue/ast: cuecontext.Context.BuildExpr panics when building expressions with built-in AST functions

### ISSUE THREAD

**Issue by brandoshmando** [cue-lang/cue#2628]
### What version of CUE are you using (Go SDK)?

<pre>
cuelang.org/go v0.6.0
</pre>

### Does this issue reproduce with the latest stable release?
Yes

### What did you do?
I'm currently using the `cue/ast` package to parse cue from config based syntax. When building values using `cuecontxt.Context.BuildExpr()`, the method call is panicking.

Go version: go1.21.0
SDK Version: v0.6.0

repro:
```
cd $(mktemp -d)
(
set -e
go mod init buildexpr
cat <<EOD > main.go
package main

import (
	"fmt"

	"cuelang.org/go/cue/ast"
	"cuelang.org/go/cue/cuecontext"
	"cuelang.org/go/cue/token"
)

func main() {
	ctx := cuecontext.New()
	x := ast.NewIdent("bool")
	y := ast.NewBool(true)
	bin := ast.NewBinExpr(
		token.AND,
		x, y,
	)
	b := ctx.BuildExpr(bin)
	fmt.Println(b)
}
EOD

go mod tidy
go run main.go
)
```

### What did you expect to see?
```
bool & true
```

### What did you see instead?
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x1a pc=0x1025c5edc]

goroutine 1 [running]:
cuelang.org/go/internal/core/adt.(*BinaryExpr).evaluate(0x1400023fbf0, 0x140001b2400, 0xf0?)
	/Users/bcraft/.gvm/pkgsets/go1.21.0/global/pkg/mod/cuelang.org/go@v0.6.0/internal/core/adt/expr.go:1243 +0x14c
cuelang.org/go/internal/core/adt.(*OpContext).evalState(0x140001b2400, {0x1029b4968, 0x1400023fbf0}, 0x2)
	/Users/bcraft/.gvm/pkgsets/go1.21.0/global/pkg/mod/cuelang.org/go@v0.6.0/internal/core/adt/context.go:678 +0x348
cuelang.org/go/internal/core/adt.(*OpContext).Evaluate(0x140001b2400, 0x14000244900, {0x1029b4968, 0x1400023fbf0})
	/Users/bcraft/.gvm/pkgsets/go1.21.0/global/pkg/mod/cuelang.org/go@v0.6.0/internal/core/adt/context.go:581 +0x144
cuelang.org/go/internal/core/adt.Resolve(0x140001b2400, {0x14000244900, {0x1029b2228, 0x1400023fbf0}, {0x0, 0x0, 0x0, {0x0, 0x0, 0x0}}})
	/Users/bcraft/.gvm/pkgsets/go1.21.0/global/pkg/mod/cuelang.org/go@v0.6.0/internal/core/adt/adt.go:52 +0x28c
cuelang.org/go/cue.(*Context).BuildExpr(0x140001247b0, {0x1029b8800?, 0x140001632c0}, {0x0, 0x0, 0x1023b0cf8?})
	/Users/bcraft/.gvm/pkgsets/go1.21.0/global/pkg/mod/cuelang.org/go@v0.6.0/cue/context.go:197 +0x23c
main.main()
	/var/folders/ts/mcj116j50qz85wwk2z4fm5br0000gn/T/tmp.p8n5A7qG/main.go:19 +0x1b8
exit status 2
```

### Findiings
The panic is occurring due to IsDynamic field access on a nil Vertex.

https://github.com/cue-lang/cue/blob/a43792cc30bd3d9bff2b2f4c73469b8faa2f8c48/internal/core/adt/expr.go#L1243C3-L1243C3

I was able to fix the issue by simply adjusting the if statement to first check if the Vertex was nil before accessing the IsDynamic field.

**Comment by mvdan** [comment]
Thanks for reporting this and apologies that it flew under our radar! I've just sent a fix here: https://cue.gerrithub.io/c/cue-lang/cue/+/1228536
