### ISSUE TITLE
tools/flow: panic: unexpected label type 3

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#2633]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.0.0-20231004170206-6c71b2c90d63

go version devel go1.21-af8f94e3c5 Tue Jul 11 21:30:51 2023 +0000
      -buildmode exe
       -compiler gc
  DefaultGODEBUG panicnil=1
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
             vcs git
    vcs.revision 6c71b2c90d63846f2983deb07102253298a568c0
        vcs.time 2023-10-04T17:02:06Z
    vcs.modified false
</pre>

### Does this issue reproduce with the latest stable release?

Yes, it reproduces with v0.6.0, but not with v0.5.0 or v0.4.3.

### What did you do?

```
exec cue cmd test
cmp stdout want-stdout
-- want-stdout --
finish
-- cue.mod/module.cue --
module: "example.com"

-- foo_tool.cue --
package foo

import (
	"tool/cli"
	"tool/file"
	"tool/exec"
)

command: test: {
	start: file.Read & {
		filename: "/dev/null"
	}
	subtasks: a: #sleep & {
		$after: start
	}
	cleanup: cli.Print & {
		$after: [
			for task in subtasks {
				task
			}
		]
		text: "finish"
	}
}


#sleep: exec.Run & {
	$after: _
	cmd: "sleep 0.1"
}
```

### What did you expect to see?

Passing test.

### What did you see instead?

```
> exec cue cmd test
[stderr]
panic: unexpected label type 3 [recovered]
	panic: unexpected label type 3

goroutine 1 [running]:
panic({0xc8ef60?, 0xc0004c7040?})
	/home/rogpeppe/go/src/runtime/panic.go:1017 +0x3ac fp=0xc0005212f8 sp=0xc000521248 pc=0x43b28c
cuelang.org/go/cmd/cue/cmd.recoverError(0xc000521e78)
	/home/rogpeppe/src/cuelabs/cue/cmd/cue/cmd/root.go:323 +0x76 fp=0xc000521318 sp=0xc0005212f8 pc=0xbe9c96
cuelang.org/go/cmd/cue/cmd.(*Command).Run.func1()
	/home/rogpeppe/src/cuelabs/cue/cmd/cue/cmd/root.go:306 +0x25 fp=0xc000521330 sp=0xc000521318 pc=0xbe9be5
runtime.deferCallSave(0xc0005213e8, 0xc000521e88?)
	/home/rogpeppe/go/src/runtime/panic.go:798 +0x84 fp=0xc000521340 sp=0xc000521330 pc=0x43ae44
runtime.runOpenDeferFrame(0xc00039ceb0)
	/home/rogpeppe/go/src/runtime/panic.go:771 +0x1b8 fp=0xc000521380 sp=0xc000521340 pc=0x43ac78
panic({0xc8ef60?, 0xc0004c7040?})
	/home/rogpeppe/go/src/runtime/panic.go:914 +0x21f fp=0xc000521430 sp=0xc000521380 pc=0x43b0ff
cuelang.org/go/tools/flow.(*Controller).updateTaskResults(0xc0000c8120, 0xc00021a900)
	/home/rogpeppe/src/cuelabs/cue/tools/flow/run.go:231 +0x6d3 fp=0xc0005215c8 sp=0xc000521430 pc=0xa1c0f3
cuelang.org/go/tools/flow.(*Controller).runLoop(0xc0000c8120)
	/home/rogpeppe/src/cuelabs/cue/tools/flow/run.go:108 +0x5a5 fp=0xc000521830 sp=0xc0005215c8 pc=0xa1b005
cuelang.org/go/tools/flow.(*Controller).Run(0xc0000c8120, {0xee33d0?, 0x1487bc0?})
	/home/rogpeppe/src/cuelabs/cue/tools/flow/flow.go:258 +0x94 fp=0xc000521890 sp=0xc000521830 pc=0xa1a074
cuelang.org/go/cmd/cue/cmd.doTasks(0xc00049aea0, {0x7ffe3fcd3c15?, 0x0?}, {0x7ffe3fcd3c15, 0x4}, 0xc000249ce0?)
	/home/rogpeppe/src/cuelabs/cue/cmd/cue/cmd/custom.go:156 +0x165 fp=0xc000521910 sp=0xc000521890 pc=0xbd22c5
cuelang.org/go/cmd/cue/cmd.customCommand.func1(0xc00049aea0?, {0xc000404990?, 0x0?, 0x0?})
	/home/rogpeppe/src/cuelabs/cue/cmd/cue/cmd/custom.go:139 +0x27 fp=0xc000521950 sp=0xc000521910 pc=0xbd2127
cuelang.org/go/cmd/cue/cmd.customCommand.mkRunE.func2(0xc00049aea0?, {0xc0004c6200, 0x0, 0x0})
	/home/rogpeppe/src/cuelabs/cue/cmd/cue/cmd/root.go:92 +0xb6 fp=0xc000521a80 sp=0xc000521950 pc=0xbd1e96
cuelang.org/go/cmd/cue/cmd.newCmdCmd.func1(0xc00049aea0, {0xc0004c6200, 0x0?, 0x0?})
	/home/rogpeppe/src/cuelabs/cue/cmd/cue/cmd/cmd.go:178 +0x1d0 fp=0xc000521b48 sp=0xc000521a80 pc=0xbec730
cuelang.org/go/cmd/cue/cmd.newCmdCmd.mkRunE.func2(0xc000499800?, {0xc0004c6200, 0x1, 0x1})
	/home/rogpeppe/src/cuelabs/cue/cmd/cue/cmd/root.go:92 +0xb6 fp=0xc000521c78 sp=0xc000521b48 pc=0xbcb6f6
github.com/spf13/cobra.(*Command).execute(0xc0003e3b00, {0xc0004c61c0, 0x1, 0x1})
	/home/rogpeppe/src/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x87c fp=0xc000521db0 sp=0xc000521c78 pc=0x5dc1bc
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003e3800)
	/home/rogpeppe/src/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5 fp=0xc000521e68 sp=0xc000521db0 pc=0x5dc9e5
github.com/spf13/cobra.(*Command).Execute(...)
	/home/rogpeppe/src/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc00049aea0, {0x2?, 0x2?})
	/home/rogpeppe/src/cuelabs/cue/cmd/cue/cmd/root.go:308 +0x65 fp=0xc000521eb0 sp=0xc000521e68 pc=0xbe9ae5
cuelang.org/go/cmd/cue/cmd.Main()
	/home/rogpeppe/src/cuelabs/cue/cmd/cue/cmd/root.go:236 +0x72 fp=0xc000521f28 sp=0xc000521eb0 pc=0xbe97d2
main.main()
	/home/rogpeppe/src/cuelabs/cue/cmd/cue/main.go:24 +0x13 fp=0xc000521f40 sp=0xc000521f28 pc=0xc014f3
runtime.main()
	/home/rogpeppe/go/src/runtime/proc.go:267 +0x2bb fp=0xc000521fe0 sp=0xc000521f40 pc=0x43e13b
runtime.goexit()
	/home/rogpeppe/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000521fe8 sp=0xc000521fe0 pc=0x46d601
[exit status 2]
FAIL: /tmp/testscript2529429847/y.txtar/script.txtar:1: unexpected command failure
```

**Comment by mvdan** [comment]
Still seems to happen as of v0.14.0.

**Comment by yujunz** [comment]
Any plan to fix or workaround?

**Comment by mvdan** [comment]
https://cue.gerrithub.io/c/cue-lang/cue/+/1224695
