### ISSUE TITLE
cmd/cue: get go does not import constants from nested dependencies

### ISSUE THREAD

**Issue by aakarim** [cue-lang/cue#2670]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.6.0

go version go1.20.7
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 1
          GOARCH arm64
            GOOS darwin

</pre>

### Does this issue reproduce with the latest stable release?
Yes.

### What did you do? 
I’m using the defs here: https://github.com/redpanda-data/redpanda/blob/dev/src/go/k8s/api/cluster.redpanda.com/v1alpha1/topic_types.go which I can download with no problem by doing this:
```
go get github.com/redpanda-data/redpanda/src/go/k8s
cue get go github.com/redpanda-data/redpanda/src/go/k8s/api/cluster.redpanda.com/v1alpha1
```

And then I tried to import the CUE package to use the k8s definitions:
```
import (
	redpanda_1alpha1 "github.com/redpanda-data/redpanda/src/go/k8s/api/cluster.redpanda.com/v1alpha1"
)
```

### What did you expect to see?
No errors.

### What did you see instead?
```
#SASLMechanismPlain: reference "unknown" not found:
    ./cue.mod/gen/github.com/redpanda-data/redpanda/src/go/k8s/api/cluster.redpanda.com/v1alpha1/topic_types_go_gen.cue:99:56
#SASLMechanismScramSHA256: reference "unknown" not found:
    ./cue.mod/gen/github.com/redpanda-data/redpanda/src/go/k8s/api/cluster.redpanda.com/v1alpha1/topic_types_go_gen.cue:100:56
#SASLMechanismScramSHA512: reference "unknown" not found:
    ./cue.mod/gen/github.com/redpanda-data/redpanda/src/go/k8s/api/cluster.redpanda.com/v1alpha1/topic_types_go_gen.cue:101:56
#SASLMechanismGSSAPI: reference "unknown" not found:
    ./cue.mod/gen/github.com/redpanda-data/redpanda/src/go/k8s/api/cluster.redpanda.com/v1alpha1/topic_types_go_gen.cue:102:56
#SASLMechanismOAuthBearer: reference "unknown" not found:
    ./cue.mod/gen/github.com/redpanda-data/redpanda/src/go/k8s/api/cluster.redpanda.com/v1alpha1/topic_types_go_gen.cue:103:56
#SASLMechanismAWSManagedStreamingIAM: reference "unknown" not found:
    ./cue.mod/gen/github.com/redpanda-data/redpanda/src/go/k8s/api/cluster.redpanda.com/v1alpha1/topic_types_go_gen.cue:104:56
make: *** [topics] Error 1
```

It looks like it’s missing the import `github.com/redpanda-data/console/backend/pkg/config` but if I then run cue get go `github.com/redpanda-data/console/backend/pkg/config` I get a nil pointer dereference:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x1014ff0ec]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0x1400f719ea0)
        cuelang.org/go/cmd/cue/cmd/root.go:318 +0x94
panic({0x10171bc60, 0x101cd9420})
        runtime/panic.go:884 +0x204
cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0x1400ba41950, {0x1400003e104, 0x2e}, 0x0)
        cuelang.org/go/cmd/cue/cmd/get_go.go:437 +0x5c
cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0x1400ba41950, {0x1400003e104, 0x2e}, 0x14000431080)
        cuelang.org/go/cmd/cue/cmd/get_go.go:553 +0x8f0
cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0x1400ba41950, {0x1400003e104, 0x2e}, 0x140006af980)
        cuelang.org/go/cmd/cue/cmd/get_go.go:553 +0x8f0
cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0x1400ba41950, {0x1400003e104, 0x2e}, 0x140006c6480)
        cuelang.org/go/cmd/cue/cmd/get_go.go:553 +0x8f0
cuelang.org/go/cmd/cue/cmd.extract(0x140003b7d10, {0x140003f0590, 0x1, 0x1})
        cuelang.org/go/cmd/cue/cmd/get_go.go:416 +0x300
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0x140003faf00?, {0x140003f0590, 0x1, 0x1})
        cuelang.org/go/cmd/cue/cmd/root.go:87 +0x90
github.com/spf13/cobra.(*Command).execute(0x140003faf00, {0x140003f0550, 0x1, 0x1})
        github.com/spf13/cobra@v1.7.0/command.go:940 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x14000119200)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0x140003b7d10, {0x3?, 0x3?})
        cuelang.org/go/cmd/cue/cmd/root.go:303 +0x5c
cuelang.org/go/cmd/cue/cmd.Main()
        cuelang.org/go/cmd/cue/cmd/root.go:231 +0x74
main.main()
        cuelang.org/go/cmd/cue/main.go:24 +0x1c
```

# Workaround

If I manually replace 'unknown' and enter the constants it works without errors:
```
#SASLMechanismPlain:                  #SASLMechanism & "PLAIN"
#SASLMechanismScramSHA256:            #SASLMechanism & "SCRAM-SHA-256"
#SASLMechanismScramSHA512:            #SASLMechanism & "SCRAM-SHA-512"
#SASLMechanismGSSAPI:                 #SASLMechanism & "GSSAPI"
#SASLMechanismOAuthBearer:            #SASLMechanism & "OAUTHBEARER"
#SASLMechanismAWSManagedStreamingIAM: #SASLMechanism & "AWS_MSK_IAM"
```

Then in your root dir set up the k8s_defs.

```
package kube 

import (
	redpanda_1alpha1 "github.com/redpanda-data/redpanda/src/go/k8s/api/cluster.redpanda.com/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

redpandaTopic: [string]: {
	metav1.#TypeMeta
	metadata?: metav1.#ObjectMeta @go(ObjectMeta) @protobuf(1,bytes,opt)
	redpanda_1alpha1.#Topic
}
```

Then your defaults in kube.cue:

```
package kube

import "app"

redpandaTopic: [ID=_]: {
	apiVersion: "cluster.redpanda.com/v1alpha1"
	kind:       "Topic"
	metadata: name:      ID
	metadata: namespace: #Namespace
    spec: kafkaApiSpec: brokers: app.rp.brokers
}

redpandaTopics: [ for v in redpandaTopic {v} ]
```

Now you can define all your topics without having to specify default config and it will all be validated:
```
package kube

#Namespace: "redpanda"

redpandaTopic: "test-topic": {
  spec: partitions: 28
}

redpandaTopic: "test-topic-2": {
  spec: partitions: 14
}
```

**Comment by mvdan** [comment]
Both problems reported here are fixed as of v0.15.0.

The `reference "unknown" not found` errors came from `cue get go` ignoring type errors when loading Go packages. Running `go get` on the k8s module alone leaves `go.sum` without entries for the packages imported by its API package, such as `github.com/redpanda-data/console/backend/pkg/config`, so the constants defined via that import could not be evaluated and were generated as `unknown`. Since b311ec41747a (https://cuelang.org/cl/1221580, v0.15.0), such loading errors are fatal and are printed much like `go build` would print them:

```
.../api/cluster.redpanda.com/v1alpha1/topic_types.go:17:2: missing go.sum entry for module providing package github.com/redpanda-data/console/backend/pkg/config (imported by github.com/redpanda-data/redpanda/src/go/k8s/api/cluster.redpanda.com/v1alpha1); to add:
	go get github.com/redpanda-data/redpanda/src/go/k8s/api/cluster.redpanda.com/v1alpha1@v0.0.0-20231017154429-d192ba922309
```

After running the suggested `go get` command, `cue get go` generates the constants correctly, such as `#SASLMechanismPlain: #SASLMechanism & "PLAIN"`.

The nil pointer dereference when running `cue get go github.com/redpanda-data/console/backend/pkg/config` was fixed by b648cf45d5ad (https://cuelang.org/cl/1173100, v0.9.0), which also fixed #1607 and #2046.
