### ISSUE TITLE
cmd/cue: mod tidy broken "local" package

### ISSUE THREAD

**Issue by richardpeng** [cue-lang/cue#2790]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version

cue version v0.7.1-0.20240130164206-ec7ca0af55c7

go version go1.21.4
      -buildmode exe
       -compiler gc
  DefaultGODEBUG panicnil=1
     CGO_ENABLED 1
          GOARCH arm64
            GOOS darwin

</pre>

### What did you do?

```
$ history
 3933  cue get go k8s.io/api/apps/v1
 3935  cue get go k8s.io/api/autoscaling/v2
 3936  cue mod tidy
```

### What did you see instead?
```
panic: broken invariant: failed to split version in "local" [recovered]
        panic: broken invariant: failed to split version in "local"

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0x1400061fe60)
        /Users/richard/pkg/mod/cuelang.org/go@v0.7.1-0.20240130164206-ec7ca0af55c7/cmd/cue/cmd/root.go:324 +0x94
panic({0x1054c6300?, 0x140000cc540?})
        /Users/richard/.asdf/installs/golang/1.21.4/go/src/runtime/panic.go:914 +0x218
cuelang.org/go/internal/mod/module.Version.BasePath({{0x1052a5c3e?, 0x14000409050?}, {0x0?, 0x14?}})
        /Users/richard/pkg/mod/cuelang.org/go@v0.7.1-0.20240130164206-ec7ca0af55c7/internal/mod/module/module.go:124 +0x84
cuelang.org/go/internal/mod/modrequirements.(*Requirements).initDefaultMajorVersions(0x140000a3b00, 0x14000033c80)
        /Users/richard/pkg/mod/cuelang.org/go@v0.7.1-0.20240130164206-ec7ca0af55c7/internal/mod/modrequirements/requirements.go:150 +0x240
cuelang.org/go/internal/mod/modrequirements.NewRequirements({0x140002eb7a1, 0x17}, {0x12cc10698?, 0x1400048ec60}, {0x140001718a0?, 0x1, 0x1}, 0x14000033c80?)
        /Users/richard/pkg/mod/cuelang.org/go@v0.7.1-0.20240130164206-ec7ca0af55c7/internal/mod/modrequirements/requirements.go:108 +0x360
cuelang.org/go/internal/mod/modload.(*loader).tidyRoots(0x140004d2ff0, {0x1055db168, 0x105bed660}, 0x140000a3680, 0x14000148420)
        /Users/richard/pkg/mod/cuelang.org/go@v0.7.1-0.20240130164206-ec7ca0af55c7/internal/mod/modload/load.go:522 +0x438
cuelang.org/go/internal/mod/modload.Tidy({0x1055db168, 0x105bed660}, {0x1055d2b18?, 0x1400044dd40}, {0x105410778, 0x1}, {0x1055d9f40?, 0x1400048ec60}, {0x0, 0x0})
        /Users/richard/pkg/mod/cuelang.org/go@v0.7.1-0.20240130164206-ec7ca0af55c7/internal/mod/modload/load.go:80 +0x44c
cuelang.org/go/cmd/cue/cmd.runModTidy(0x1400047b590?, {0x0?, 0x0?, 0x0?})
        /Users/richard/pkg/mod/cuelang.org/go@v0.7.1-0.20240130164206-ec7ca0af55c7/cmd/cue/cmd/modtidy.go:61 +0x80
cuelang.org/go/cmd/cue/cmd.newModCmd.newModTidyCmd.mkRunE.func5(0x140004a7000?, {0x105bed660, 0x0, 0x0})
        /Users/richard/pkg/mod/cuelang.org/go@v0.7.1-0.20240130164206-ec7ca0af55c7/cmd/cue/cmd/root.go:92 +0x90
github.com/spf13/cobra.(*Command).execute(0x140004ac600, {0x105bed660, 0x0, 0x0})
        /Users/richard/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0x82c
github.com/spf13/cobra.(*Command).ExecuteC(0x140003c3800)
        /Users/richard/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/richard/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0x1400047b590, {0x2?, 0x2?})
        /Users/richard/pkg/mod/cuelang.org/go@v0.7.1-0.20240130164206-ec7ca0af55c7/cmd/cue/cmd/root.go:309 +0x5c
cuelang.org/go/cmd/cue/cmd.Main()
        /Users/richard/pkg/mod/cuelang.org/go@v0.7.1-0.20240130164206-ec7ca0af55c7/cmd/cue/cmd/root.go:237 +0x74
main.main()
        /Users/richard/pkg/mod/cuelang.org/go@v0.7.1-0.20240130164206-ec7ca0af55c7/cmd/cue/main.go:24 +0x1c
```

**Comment by mvdan** [comment]
cc @rogpeppe
