### ISSUE TITLE
cuelang.org: preprocessor: panic: "bad state with respect to validate"

### ISSUE THREAD

**Issue by rogpeppe** [cue-lang/cue#2792]
I'm developing content for cuelang.org, currently at commit 65d80fa6ca822d154b31463d01866940dde550c1 (alpha tip).

I added these files:

```
-- content/docs/tutorial/test-tutorial/test.md --
---
title: Test tutorial
authors:
- myitcv
---

{{{with step}}}

{{{with code "en" "something"}}}
#norun
something
{{{end}}}
{{{end}}}

-- content/docs/tutorial/test-tutorial/page.cue --
package site

content: docs: tutorial: "test-tutorial": {}
```

I ran `_scripts/runPreprocessor execute` and I see this panic:

```
% ./_scripts/runPreprocessor.bash execute
panic: ** 0: bad state with respect to validate(): found not set, but unsupported number of files (%!d(MISSING)) for a default


goroutine 134 [running]:
github.com/cue-lang/cuelang.org/internal/cmd/preprocessor/cmd.(*errorContextBuffer).fatalf(0xc000444800, {0xdae3c1?, 0x502a6a?}, {0xc001672fb0, 0x1, 0x1})
	github.com/cue-lang/cuelang.org/internal/cmd/preprocessor/cmd/buffered_error_context.go:70 +0xf8
github.com/cue-lang/cuelang.org/internal/cmd/preprocessor/cmd.(*codeNode).writeTransformTo(0xc00161d280, 0xc001ee9980)
	github.com/cue-lang/cuelang.org/internal/cmd/preprocessor/cmd/code_node.go:345 +0x2cf
github.com/cue-lang/cuelang.org/internal/cmd/preprocessor/cmd.transformNodes(0xc001ee9980, {0xc000da22c0?, 0xd8c411?, 0x1c?})
	github.com/cue-lang/cuelang.org/internal/cmd/preprocessor/cmd/rootfile.go:782 +0x6f
github.com/cue-lang/cuelang.org/internal/cmd/preprocessor/cmd.(*stepNode).writeTransformTo(0xc001413b30, 0xc001ee9980)
	github.com/cue-lang/cuelang.org/internal/cmd/preprocessor/cmd/step_node.go:51 +0x88
github.com/cue-lang/cuelang.org/internal/cmd/preprocessor/cmd.transformNodes(0xc001ee9980, {0xc000da2340?, 0x4?, 0xc000da2301?})
	github.com/cue-lang/cuelang.org/internal/cmd/preprocessor/cmd/rootfile.go:782 +0x6f
github.com/cue-lang/cuelang.org/internal/cmd/preprocessor/cmd.(*rootFile).writeTarget(0xc0002a9e00, 0xc001ee9980)
	github.com/cue-lang/cuelang.org/internal/cmd/preprocessor/cmd/rootfile.go:774 +0x89
github.com/cue-lang/cuelang.org/internal/cmd/preprocessor/cmd.(*rootFile).transform(0xc0002a9e00, {0xc001826d20, 0x5c})
	github.com/cue-lang/cuelang.org/internal/cmd/preprocessor/cmd/rootfile.go:196 +0x45a
github.com/cue-lang/cuelang.org/internal/cmd/preprocessor/cmd.(*page).process(0xc0002cab40)
	github.com/cue-lang/cuelang.org/internal/cmd/preprocessor/cmd/page.go:196 +0xad2
github.com/cue-lang/cuelang.org/internal/cmd/preprocessor/cmd.(*executeContext).execute.func1()
	github.com/cue-lang/cuelang.org/internal/cmd/preprocessor/cmd/execute_context.go:130 +0x25
created by github.com/cue-lang/cuelang.org/internal/cmd/preprocessor/cmd.(*executeContext).execute in goroutine 1
	github.com/cue-lang/cuelang.org/internal/cmd/preprocessor/cmd/execute_context.go:129 +0x8e5
```

**Comment by mvdan** [comment]
I tried reproducing with cuelang.org at master (https://github.com/cue-lang/cuelang.org/commit/133db6a4fee6d659f9f32693a256309053f25a54) with the files you provided, and the preprocessor finished without a problem, so it seems like this got fixed at some point.
