### ISSUE TITLE
cmd/cue: mod tidy panic with local registry

### ISSUE THREAD

**Issue by richardpeng** [cue-lang/cue#2793]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.7.1-0.20240201160647-2a56875bdecf

go version go1.21.4
      -buildmode exe
       -compiler gc
  DefaultGODEBUG panicnil=1
     CGO_ENABLED 1
          GOARCH arm64
            GOOS darwin
</pre>

### What did you do?

1. Created an OCI image with my CUE module:

`Containerfile`:
```
FROM scratch

COPY . /
```

Build and push image to local registry:
```
podman build --tag host.containers.internal:5000/example.com/config:v0.0.1 .
podman push host.containers.internal:5000/example.com/config:v0.0.1 --tls-verify=false
```

`test.cue`:
```
package app

import "example.com/config@v0"
```

2. Run `cue mod tidy`

### What did you see instead?
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x60 pc=0x1052a9a60]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0x1400061fe60)
	/Users/richard/pkg/mod/cuelang.org/go@v0.7.1-0.20240201160647-2a56875bdecf/cmd/cue/cmd/root.go:324 +0x94
panic({0x1057dda00?, 0x105e8abd0?})
	/Users/richard/.asdf/installs/golang/1.21.4/go/src/runtime/panic.go:914 +0x218
cuelang.org/go/internal/mod/modpkgload.(*Packages).All(...)
	/Users/richard/pkg/mod/cuelang.org/go@v0.7.1-0.20240201160647-2a56875bdecf/internal/mod/modpkgload/pkgload.go:219
cuelang.org/go/internal/mod/modload.Tidy({0x1058db348, 0x105eed680}, {0x1058d2cd8?, 0x140004c5dc0}, {0x105711b08, 0x1}, {0x1058da120?, 0x14000506c60}, {0x1400047f884, 0x6})
	/Users/richard/pkg/mod/cuelang.org/go@v0.7.1-0.20240201160647-2a56875bdecf/internal/mod/modload/load.go:74 +0x360
cuelang.org/go/cmd/cue/cmd.runModTidy(0x140004f3590?, {0x0?, 0x0?, 0x0?})
	/Users/richard/pkg/mod/cuelang.org/go@v0.7.1-0.20240201160647-2a56875bdecf/cmd/cue/cmd/modtidy.go:72 +0xc4
cuelang.org/go/cmd/cue/cmd.newModCmd.newModTidyCmd.mkRunE.func5(0x14000521000?, {0x105eed680, 0x0, 0x0})
	/Users/richard/pkg/mod/cuelang.org/go@v0.7.1-0.20240201160647-2a56875bdecf/cmd/cue/cmd/root.go:92 +0x90
github.com/spf13/cobra.(*Command).execute(0x14000526600, {0x105eed680, 0x0, 0x0})
	/Users/richard/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0x82c
github.com/spf13/cobra.(*Command).ExecuteC(0x1400043b800)
	/Users/richard/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/richard/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0x140004f3590, {0x2?, 0x2?})
	/Users/richard/pkg/mod/cuelang.org/go@v0.7.1-0.20240201160647-2a56875bdecf/cmd/cue/cmd/root.go:309 +0x5c
cuelang.org/go/cmd/cue/cmd.Main()
	/Users/richard/pkg/mod/cuelang.org/go@v0.7.1-0.20240201160647-2a56875bdecf/cmd/cue/cmd/root.go:237 +0x74
main.main()
	/Users/richard/pkg/mod/cuelang.org/go@v0.7.1-0.20240201160647-2a56875bdecf/cmd/cue/main.go:24 +0x1c
```

**Comment by rogpeppe** [comment]
Thanks for the report! The underlying issue here is that CUE module images aren't like other images - they need to be created by the `cue` command itself (via `cue mod publish`). The panic you're seeing is because there's a missing error check in the code. You _should_ be seeing something like this error instead:
```
cannot resolve dependencies: example.com/config@v0.0.1: example.com/config@v0.0.1 does not resolve to a manifest (media type is "application/vnd.oci.image.manifest.v1+json")
```
Will fix the panic tomorrow!
