### ISSUE TITLE
cmd/cue: get go panics when built with Go 1.21 and used with cmd/go 1.22

### ISSUE THREAD

**Issue by ikawaha** [cue-lang/cue#2802]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.7.0

go version go1.21.5
      -buildmode exe
       -compiler gc
       -trimpath true
  DefaultGODEBUG panicnil=1
     CGO_ENABLED 1
          GOARCH arm64
            GOOS darwin
</pre>

### Does this issue reproduce with the latest stable release?

Yes, it reproduces with the latest stable release.

### What did you do?

I've discovered an issue where executing cue get go results in a panic when it targets a Go module at version 1.22.0. 

I've prepared two repositories, one with a go.mod file set to Go version 1.22.0 and another set to Go version 1.21.0. Each repository only defines a single constant. I run cue get go results in a panic when it targets a Go module at version 1.22.0.

|repository| go.mod | cue get go |
|:---|:---|:---|
|https://github.com/ikawaha/cuegetgosample| go 1.21.0 | OK |
|https://github.com/ikawaha/cuepanicsample| go 1.22.0 | PANIC!|

### What did you expect to see?

```
$ go get github.com/ikawaha/cuegetgosample && cue get go github.com/ikawaha/cuegetgosample

go: downloading github.com/ikawaha/cuegetgosample v0.0.0-20240209122316-7722e486d3de
go: added github.com/ikawaha/cuegetgosample v0.0.0-20240209122316-7722e486d3de

$ tree cue.mod/
cue.mod/
└── gen
    └── github.com
        └── ikawaha
            └── cuegetgosample
                └── sample_go_gen.cue
```

### What did you see instead?

```
$ go get github.com/ikawaha/cuepanicsample && cue get go github.com/ikawaha/cuepanicsample

go: downloading github.com/ikawaha/cuepanicsample v0.0.0-20240209121617-0d013f9d2ed6
go: added github.com/ikawaha/cuepanicsample v0.0.0-20240209121617-0d013f9d2ed6
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x10151d778]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0x1400061fe60)
	cuelang.org/go/cmd/cue/cmd/root.go:323 +0x94
panic({0x10174e420?, 0x101d4e7e0?})
	runtime/panic.go:914 +0x218
cuelang.org/go/cmd/cue/cmd.(*extractor).recordConsts(0x14000360900, 0x14000272180?)
	cuelang.org/go/cmd/cue/cmd/get_go.go:621 +0x108
cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0x14000360900, {0x14000036064, 0x17}, 0x14000272180)
	cuelang.org/go/cmd/cue/cmd/get_go.go:447 +0xc94
cuelang.org/go/cmd/cue/cmd.extract(0x140004f1680, {0x140005242a0, 0x1, 0x1})
	cuelang.org/go/cmd/cue/cmd/get_go.go:416 +0x2f8
cuelang.org/go/cmd/cue/cmd.newGoCmd.mkRunE.func1(0x140004fdf00?, {0x140005242a0, 0x1, 0x1})
	cuelang.org/go/cmd/cue/cmd/root.go:92 +0x90
github.com/spf13/cobra.(*Command).execute(0x1400050d500, {0x14000524260, 0x1, 0x1})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x66c
github.com/spf13/cobra.(*Command).ExecuteC(0x14000447800)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0x140004f1680, {0x3?, 0x3?})
	cuelang.org/go/cmd/cue/cmd/root.go:308 +0x5c
cuelang.org/go/cmd/cue/cmd.Main()
	cuelang.org/go/cmd/cue/cmd/root.go:236 +0x74
main.main()
	cuelang.org/go/cmd/cue/main.go:24 +0x1c
```

**Comment by myitcv** [comment]
Thanks for raising this, @ikawaha. Looking as a matter of urgency to see if we can't get this fixed in the v0.8.0-alpha.1 release.

**Comment by myitcv** [comment]
Reproduced locally:

```
exec go version
exec go env
exec go mod tidy
exec cue version
exec cue get go github.com/ikawaha/cuegetgosample
exec cue get go github.com/ikawaha/cuepanicsample

-- home/.config/go/telemetry/mode --
on 2023-10-30
-- cue.mod/module.cue --
module: "mod.com"

-- go.mod --
module mod.com

go 1.22.0

require (
	github.com/ikawaha/cuegetgosample v0.0.0-20240209122700-ef905a50931f
	github.com/ikawaha/cuepanicsample v0.0.0-20240209121617-0d013f9d2ed6
)
-- deps.go --
//go:build deps

package deps

import (
	_ "github.com/ikawaha/cuegetgosample"
	_ "github.com/ikawaha/cuepanicsample"
)
```

That test should succeed but instead gives:


```
> exec go version
[stdout]
go version go1.22.0 linux/arm64
> exec go env
[stdout]
GO111MODULE=''
GOARCH='arm64'
GOBIN=''
GOCACHE='/home/myitcv/.cache/go-build'
GOENV='/no-home/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/home/myitcv/gostuff/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/home/myitcv/gostuff'
GOPRIVATE=''
GOPROXY='https://proxy.golang.org,direct'
GOROOT='/home/myitcv/gos'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/home/myitcv/gos/pkg/tool/linux_arm64'
GOVCS=''
GOVERSION='go1.22.0'
GCCGO='gccgo'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='$WORK/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=$WORK/.tmp/go-build3935909308=/tmp/go-build -gno-record-gcc-switches'
> exec go mod tidy
> exec cue version
[stdout]
cue version v0.0.0-20240209203336-3d1c0cb3f5e0

go version go1.21.4
      -buildmode exe
       -compiler gc
     CGO_ENABLED 1
          GOARCH arm64
            GOOS linux
             vcs git
    vcs.revision 3d1c0cb3f5e0abef4e6638d6775c2672968d2863
        vcs.time 2024-02-09T20:33:36Z
    vcs.modified false
> exec cue get go github.com/ikawaha/cuegetgosample
> exec cue get go github.com/ikawaha/cuepanicsample
[stderr]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7dfcf8]

goroutine 1 [running]:
panic({0x8c6f20?, 0x10faa20?})
	/home/myitcv/gos/src/runtime/panic.go:1017 +0x3cc fp=0x400061f300 sp=0x400061f250 pc=0x4a63c
cuelang.org/go/cmd/cue/cmd.recoverError(0x400061fe60)
	/home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:324 +0x94 fp=0x400061f320 sp=0x400061f300 pc=0x7f0154
cuelang.org/go/cmd/cue/cmd.(*Command).Run.func1()
	/home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:307 +0x28 fp=0x400061f340 sp=0x400061f320 pc=0x7f0088
runtime.deferCallSave(0x400061f410, 0x400061fe70?)
	/home/myitcv/gos/src/runtime/panic.go:798 +0x90 fp=0x400061f350 sp=0x400061f340 pc=0x4a200
runtime.runOpenDeferFrame(0x40000426e0)
	/home/myitcv/gos/src/runtime/panic.go:771 +0x1b4 fp=0x400061f3a0 sp=0x400061f350 pc=0x4a034
panic({0x8c6f20?, 0x10faa20?})
	/home/myitcv/gos/src/runtime/panic.go:914 +0x218 fp=0x400061f450 sp=0x400061f3a0 pc=0x4a488
runtime.panicmem(...)
	/home/myitcv/gos/src/runtime/panic.go:261
runtime.sigpanic()
	/home/myitcv/gos/src/runtime/signal_unix.go:861 +0x30c fp=0x400061f4b0 sp=0x400061f450 pc=0x61c2c
cuelang.org/go/cmd/cue/cmd.(*extractor).recordConsts(0x40004cd320, 0x40002def00?)
	/home/myitcv/dev/cuelang/cue/cmd/cue/cmd/get_go.go:618 +0x108 fp=0x400061f570 sp=0x400061f4c0 pc=0x7dfcf8
cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0x40004cd320, {0x4000036094, 0x2b}, 0x40002def00)
	/home/myitcv/dev/cuelang/cue/cmd/cue/cmd/get_go.go:444 +0xcf0 fp=0x400061f810 sp=0x400061f570 pc=0x7df630
cuelang.org/go/cmd/cue/cmd.extract(0x400047b590, {0x400044dca0, 0x1, 0x1})
	/home/myitcv/dev/cuelang/cue/cmd/cue/cmd/get_go.go:413 +0x2f8 fp=0x400061fa80 sp=0x400061f810 pc=0x7de5a8
cuelang.org/go/cmd/cue/cmd.newGoCmd.mkRunE.func1(0x40004a6000?, {0x400044dca0, 0x1, 0x1})
	/home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:92 +0x90 fp=0x400061fbb0 sp=0x400061fa80 pc=0x7dd920
github.com/spf13/cobra.(*Command).execute(0x4000493500, {0x400044dc60, 0x1, 0x1})
	/home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0x82c fp=0x400061fd60 sp=0x400061fbb0 pc=0x1d194c
github.com/spf13/cobra.(*Command).ExecuteC(0x40003c3800)
	/home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344 fp=0x400061fe40 sp=0x400061fd60 pc=0x1d20c4
github.com/spf13/cobra.(*Command).Execute(...)
	/home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0x400047b590, {0x3?, 0x3?})
	/home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:309 +0x5c fp=0x400061fe90 sp=0x400061fe40 pc=0x7eff7c
cuelang.org/go/cmd/cue/cmd.Main()
	/home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:237 +0x74 fp=0x400061ff10 sp=0x400061fe90 pc=0x7efca4
main.main()
	/home/myitcv/dev/cuelang/cue/cmd/cue/main.go:24 +0x1c fp=0x400061ff30 sp=0x400061ff10 pc=0x809d2c
runtime.main()
	/home/myitcv/gos/src/runtime/proc.go:267 +0x2bc fp=0x400061ffd0 sp=0x400061ff30 pc=0x4d38c
runtime.goexit()
	/home/myitcv/gos/src/runtime/asm_arm64.s:1197 +0x4 fp=0x400061ffd0 sp=0x400061ffd0 pc=0x7db34

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/myitcv/gos/src/runtime/proc.go:398 +0xc8 fp=0x4000064f90 sp=0x4000064f70 pc=0x4d7b8
runtime.goparkunlock(...)
	/home/myitcv/gos/src/runtime/proc.go:404
runtime.forcegchelper()
	/home/myitcv/gos/src/runtime/proc.go:322 +0xb8 fp=0x4000064fd0 sp=0x4000064f90 pc=0x4d648
runtime.goexit()
	/home/myitcv/gos/src/runtime/asm_arm64.s:1197 +0x4 fp=0x4000064fd0 sp=0x4000064fd0 pc=0x7db34
created by runtime.init.6 in goroutine 1
	/home/myitcv/gos/src/runtime/proc.go:310 +0x24

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/myitcv/gos/src/runtime/proc.go:398 +0xc8 fp=0x4000065760 sp=0x4000065740 pc=0x4d7b8
runtime.goparkunlock(...)
	/home/myitcv/gos/src/runtime/proc.go:404
runtime.bgsweep(0x0?)
	/home/myitcv/gos/src/runtime/mgcsweep.go:321 +0x108 fp=0x40000657b0 sp=0x4000065760 pc=0x38ca8
runtime.gcenable.func1()
	/home/myitcv/gos/src/runtime/mgc.go:200 +0x28 fp=0x40000657d0 sp=0x40000657b0 pc=0x2d768
runtime.goexit()
	/home/myitcv/gos/src/runtime/asm_arm64.s:1197 +0x4 fp=0x40000657d0 sp=0x40000657d0 pc=0x7db34
created by runtime.gcenable in goroutine 1
	/home/myitcv/gos/src/runtime/mgc.go:200 +0x6c

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x400007e000?, 0xb2a460?, 0x0?, 0x0?, 0x0?)
	/home/myitcv/gos/src/runtime/proc.go:398 +0xc8 fp=0x4000065f50 sp=0x4000065f30 pc=0x4d7b8
runtime.goparkunlock(...)
	/home/myitcv/gos/src/runtime/proc.go:404
runtime.(*scavengerState).park(0x1125f80)
	/home/myitcv/gos/src/runtime/mgcscavenge.go:425 +0x5c fp=0x4000065f80 sp=0x4000065f50 pc=0x3650c
runtime.bgscavenge(0x0?)
	/home/myitcv/gos/src/runtime/mgcscavenge.go:658 +0xac fp=0x4000065fb0 sp=0x4000065f80 pc=0x36abc
runtime.gcenable.func2()
	/home/myitcv/gos/src/runtime/mgc.go:201 +0x28 fp=0x4000065fd0 sp=0x4000065fb0 pc=0x2d708
runtime.goexit()
	/home/myitcv/gos/src/runtime/asm_arm64.s:1197 +0x4 fp=0x4000065fd0 sp=0x4000065fd0 pc=0x7db34
created by runtime.gcenable in goroutine 1
	/home/myitcv/gos/src/runtime/mgc.go:201 +0xac

goroutine 18 [finalizer wait]:
runtime.gopark(0x40001024e0?, 0x32?, 0x98?, 0x1?, 0x9ad5c0?)
	/home/myitcv/gos/src/runtime/proc.go:398 +0xc8 fp=0x4000064580 sp=0x4000064560 pc=0x4d7b8
runtime.runfinq()
	/home/myitcv/gos/src/runtime/mfinal.go:193 +0x108 fp=0x40000647d0 sp=0x4000064580 pc=0x2c858
runtime.goexit()
	/home/myitcv/gos/src/runtime/asm_arm64.s:1197 +0x4 fp=0x40000647d0 sp=0x40000647d0 pc=0x7db34
created by runtime.createfing in goroutine 1
	/home/myitcv/gos/src/runtime/mfinal.go:163 +0x80

goroutine 19 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/myitcv/gos/src/runtime/proc.go:398 +0xc8 fp=0x4000060730 sp=0x4000060710 pc=0x4d7b8
runtime.gcBgMarkWorker()
	/home/myitcv/gos/src/runtime/mgc.go:1293 +0xd8 fp=0x40000607d0 sp=0x4000060730 pc=0x2f3b8
runtime.goexit()
	/home/myitcv/gos/src/runtime/asm_arm64.s:1197 +0x4 fp=0x40000607d0 sp=0x40000607d0 pc=0x7db34
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/home/myitcv/gos/src/runtime/mgc.go:1217 +0x28

goroutine 5 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/myitcv/gos/src/runtime/proc.go:398 +0xc8 fp=0x4000066730 sp=0x4000066710 pc=0x4d7b8
runtime.gcBgMarkWorker()
	/home/myitcv/gos/src/runtime/mgc.go:1293 +0xd8 fp=0x40000667d0 sp=0x4000066730 pc=0x2f3b8
runtime.goexit()
	/home/myitcv/gos/src/runtime/asm_arm64.s:1197 +0x4 fp=0x40000667d0 sp=0x40000667d0 pc=0x7db34
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/home/myitcv/gos/src/runtime/mgc.go:1217 +0x28

goroutine 34 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/myitcv/gos/src/runtime/proc.go:398 +0xc8 fp=0x4000508730 sp=0x4000508710 pc=0x4d7b8
runtime.gcBgMarkWorker()
	/home/myitcv/gos/src/runtime/mgc.go:1293 +0xd8 fp=0x40005087d0 sp=0x4000508730 pc=0x2f3b8
runtime.goexit()
	/home/myitcv/gos/src/runtime/asm_arm64.s:1197 +0x4 fp=0x40005087d0 sp=0x40005087d0 pc=0x7db34
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/home/myitcv/gos/src/runtime/mgc.go:1217 +0x28

goroutine 35 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/home/myitcv/gos/src/runtime/proc.go:398 +0xc8 fp=0x4000508f30 sp=0x4000508f10 pc=0x4d7b8
runtime.gcBgMarkWorker()
	/home/myitcv/gos/src/runtime/mgc.go:1293 +0xd8 fp=0x4000508fd0 sp=0x4000508f30 pc=0x2f3b8
runtime.goexit()
	/home/myitcv/gos/src/runtime/asm_arm64.s:1197 +0x4 fp=0x4000508fd0 sp=0x4000508fd0 pc=0x7db34
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/home/myitcv/gos/src/runtime/mgc.go:1217 +0x28

goroutine 6 [GC worker (idle)]:
runtime.gopark(0x293d2c1a8f8?, 0x3?, 0x61?, 0x5f?, 0x0?)
	/home/myitcv/gos/src/runtime/proc.go:398 +0xc8 fp=0x4000066f30 sp=0x4000066f10 pc=0x4d7b8
runtime.gcBgMarkWorker()
	/home/myitcv/gos/src/runtime/mgc.go:1293 +0xd8 fp=0x4000066fd0 sp=0x4000066f30 pc=0x2f3b8
runtime.goexit()
	/home/myitcv/gos/src/runtime/asm_arm64.s:1197 +0x4 fp=0x4000066fd0 sp=0x4000066fd0 pc=0x7db34
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/home/myitcv/gos/src/runtime/mgc.go:1217 +0x28

goroutine 36 [GC worker (idle)]:
runtime.gopark(0x115f8a0?, 0x1?, 0x98?, 0x9b?, 0x0?)
	/home/myitcv/gos/src/runtime/proc.go:398 +0xc8 fp=0x4000509730 sp=0x4000509710 pc=0x4d7b8
runtime.gcBgMarkWorker()
	/home/myitcv/gos/src/runtime/mgc.go:1293 +0xd8 fp=0x40005097d0 sp=0x4000509730 pc=0x2f3b8
runtime.goexit()
	/home/myitcv/gos/src/runtime/asm_arm64.s:1197 +0x4 fp=0x40005097d0 sp=0x40005097d0 pc=0x7db34
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/home/myitcv/gos/src/runtime/mgc.go:1217 +0x28

goroutine 37 [GC worker (idle)]:
runtime.gopark(0x293d2c1e079?, 0x1?, 0xd5?, 0xe?, 0x0?)
	/home/myitcv/gos/src/runtime/proc.go:398 +0xc8 fp=0x4000509f30 sp=0x4000509f10 pc=0x4d7b8
runtime.gcBgMarkWorker()
	/home/myitcv/gos/src/runtime/mgc.go:1293 +0xd8 fp=0x4000509fd0 sp=0x4000509f30 pc=0x2f3b8
runtime.goexit()
	/home/myitcv/gos/src/runtime/asm_arm64.s:1197 +0x4 fp=0x4000509fd0 sp=0x4000509fd0 pc=0x7db34
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/home/myitcv/gos/src/runtime/mgc.go:1217 +0x28

goroutine 20 [GC worker (idle)]:
runtime.gopark(0x115f8a0?, 0x3?, 0x21?, 0xe9?, 0x0?)
	/home/myitcv/gos/src/runtime/proc.go:398 +0xc8 fp=0x4000060f30 sp=0x4000060f10 pc=0x4d7b8
runtime.gcBgMarkWorker()
	/home/myitcv/gos/src/runtime/mgc.go:1293 +0xd8 fp=0x4000060fd0 sp=0x4000060f30 pc=0x2f3b8
runtime.goexit()
	/home/myitcv/gos/src/runtime/asm_arm64.s:1197 +0x4 fp=0x4000060fd0 sp=0x4000060fd0 pc=0x7db34
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/home/myitcv/gos/src/runtime/mgc.go:1217 +0x28

goroutine 7 [GC worker (idle)]:
runtime.gopark(0x115f8a0?, 0x3?, 0xf6?, 0x4d?, 0x0?)
	/home/myitcv/gos/src/runtime/proc.go:398 +0xc8 fp=0x4000067730 sp=0x4000067710 pc=0x4d7b8
runtime.gcBgMarkWorker()
	/home/myitcv/gos/src/runtime/mgc.go:1293 +0xd8 fp=0x40000677d0 sp=0x4000067730 pc=0x2f3b8
runtime.goexit()
	/home/myitcv/gos/src/runtime/asm_arm64.s:1197 +0x4 fp=0x40000677d0 sp=0x40000677d0 pc=0x7db34
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/home/myitcv/gos/src/runtime/mgc.go:1217 +0x28

goroutine 38 [GC worker (idle)]:
runtime.gopark(0x293d2c18c00?, 0x1?, 0x30?, 0x8d?, 0x0?)
	/home/myitcv/gos/src/runtime/proc.go:398 +0xc8 fp=0x400050a730 sp=0x400050a710 pc=0x4d7b8
runtime.gcBgMarkWorker()
	/home/myitcv/gos/src/runtime/mgc.go:1293 +0xd8 fp=0x400050a7d0 sp=0x400050a730 pc=0x2f3b8
runtime.goexit()
	/home/myitcv/gos/src/runtime/asm_arm64.s:1197 +0x4 fp=0x400050a7d0 sp=0x400050a7d0 pc=0x7db34
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/home/myitcv/gos/src/runtime/mgc.go:1217 +0x28
[exit status 2]
FAIL: /tmp/testscript4292256633/repro.txtar/script.txtar:6: unexpected command failure
```

~What I cannot explain though is that when I run this outside of `cmd/testscript` I only get the following:~

Edit: the missing stack information was a local setup vagary. 

cc @mvdan

**Comment by myitcv** [comment]
Tentatively marking as v0.8.0-alpha.1 because this panic does not appear to be triggered any new language features.

**Comment by mvdan** [comment]
This panic only happens when cmd/cue is built with Go 1.21 but then `cue get go` is run with Go 1.22. The panic goes away when cmd/cue is rebuilt with Go 1.22. FYI @ikawaha, re-building or re-installing CUE should fix this issue, assuming you'll build it with Go 1.22.

We should probably add some checks so that `cue get go` gives a good error message when it was built with an older version of Go than the one currently in use.

**Comment by mvdan** [comment]
We have released https://github.com/cue-lang/cue/releases/tag/v0.7.1 as a rebuild of v0.7.0 with Go 1.22.0, so that there are prebuilt release binaries that will work fine with Go 1.22 out of the box.

I'm going to leave this issue open to think about whether (and how) CUE v0.8 could deal with these edge cases. My instinct is that a Go tool should always be built with a version that's at least as new as the installed Go version it's being used for (i.e. in this case, your https://pkg.go.dev/runtime#Version was go1.21.5, but `go env GOVERSION` was go1.22.0). But perhaps my understanding isn't right. I've asked upstream Go to see what they think.

**Comment by DavidGamba** [comment]
It happens to me with 0.7.1 and argo-workflows (it never worked for me before with this project).

```
$ cue get go github.com/argoproj/argo-workflows/pkg/apis/...

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x103140478]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0x1403085fe60)
	/Users/DGAMBARI/go/pkg/mod/cuelang.org/go@v0.7.1/cmd/cue/cmd/root.go:323 +0x94
panic({0x103372420?, 0x10397e870?})
	/opt/homebrew/Cellar/go/1.21.5/libexec/src/runtime/panic.go:914 +0x218
cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0x14006f7a3f0, {0x14000042004, 0x50}, 0x0)
	/Users/DGAMBARI/go/pkg/mod/cuelang.org/go@v0.7.1/cmd/cue/cmd/get_go.go:437 +0x58
cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0x14006f7a3f0, {0x14000042004, 0x50}, 0x140001d7980)
	/Users/DGAMBARI/go/pkg/mod/cuelang.org/go@v0.7.1/cmd/cue/cmd/get_go.go:553 +0x8a8
cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0x14006f7a3f0, {0x14000042004, 0x50}, 0x14000518180)
	/Users/DGAMBARI/go/pkg/mod/cuelang.org/go@v0.7.1/cmd/cue/cmd/get_go.go:553 +0x8a8
cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0x14006f7a3f0, {0x14000042004, 0x50}, 0x14000532300)
	/Users/DGAMBARI/go/pkg/mod/cuelang.org/go@v0.7.1/cmd/cue/cmd/get_go.go:553 +0x8a8
cuelang.org/go/cmd/cue/cmd.extract(0x1400045b680, {0x1400048a2e0, 0x1, 0x1})
	/Users/DGAMBARI/go/pkg/mod/cuelang.org/go@v0.7.1/cmd/cue/cmd/get_go.go:416 +0x2f8
cuelang.org/go/cmd/cue/cmd.newGoCmd.mkRunE.func1(0x14000467f00?, {0x1400048a2e0, 0x1, 0x1})
	/Users/DGAMBARI/go/pkg/mod/cuelang.org/go@v0.7.1/cmd/cue/cmd/root.go:92 +0x90
github.com/spf13/cobra.(*Command).execute(0x14000477500, {0x1400048a2a0, 0x1, 0x1})
	/Users/DGAMBARI/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x66c
github.com/spf13/cobra.(*Command).ExecuteC(0x140003b1800)
	/Users/DGAMBARI/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/DGAMBARI/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0x1400045b680, {0x3?, 0x3?})
	/Users/DGAMBARI/go/pkg/mod/cuelang.org/go@v0.7.1/cmd/cue/cmd/root.go:308 +0x5c
cuelang.org/go/cmd/cue/cmd.Main()
	/Users/DGAMBARI/go/pkg/mod/cuelang.org/go@v0.7.1/cmd/cue/cmd/root.go:236 +0x74
main.main()
	/Users/DGAMBARI/go/pkg/mod/cuelang.org/go@v0.7.1/cmd/cue/main.go:24 +0x1c
```

**Comment by mvdan** [comment]
@DavidGamba to triple check, what Go version did you use to build CUE v0.7.1? You can check it via `cue version`.

**Comment by mvdan** [comment]
The panic here is in `recordConsts`, which is not related to yours - yours is https://github.com/cue-lang/cue/issues/2046, and will require a different fix.

**Comment by DavidGamba** [comment]
Sorry for the noise, updating my go version now.

```
$ cue version
cue version v0.7.1

go version go1.21.5
      -buildmode exe
       -compiler gc
  DefaultGODEBUG panicnil=1
     CGO_ENABLED 1
          GOARCH arm64
            GOOS darwin
```

**Comment by ikawaha** [comment]
@mvdan Thank you for your comment and for the release of 0.7.1. I was able to avoid this problem by rebuilding with Go 1.22.

**Comment by mvdan** [comment]
Had a brief exchange with Rob Findley on Slack - forwards compatibility for Go tools using `go/packages` (that is, `cmd/cue` built with Go 1.21 but being used where Go 1.22 is installed) is not guaranteed, but should in general work. The fact that it broke with Go 1.22 appears to be a bug, which they started tracking around the same time as this issue was opened: https://github.com/golang/go/issues/65608

They are struggling with a reproducer, so I'll share more details there about our panic in CUE. Luckily, all of our code is open source, so that should help them reproduce and debug it.

Rob also suggests that having some version skew check would be good, so at least my intuition on the matter wasn't misguided.

> I think it would be reasonable for go/packages to report an error when the go version or language version of the module is more recent than the Go version used to compile the tool. Either of those indicate that the tool may not understand the output.

For the time being, I'll provide upstream with a reproducer and leave this issue open until they can figure out the fix.

**Comment by mvdan** [comment]
They figured out a fix and the involved Go and CUE versions are fairly outdated now, so I think we can close this as resolved.
