### ISSUE TITLE
mod: panic when running `cue export` on non-relative path

### ISSUE THREAD

**Issue by NoamTD** [cue-lang/cue#2964]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.8.0

go version go1.22.1
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH arm64
            GOOS darwin
</pre>

### Does this issue reproduce with the latest stable release?
yes

### What did you do?
I initialized an empty cue module with `cue mod init`, and ran `cue export`. 

Run the following script:
```bash
#!/usr/bin/env bash

set -ex

reprodir=$(mktemp -d)
cd $reprodir

cue mod init example.com
cue export anypath
```

### What did you expect to see?
an error indicating that the package I'm trying to export (in this case `anypath`) does not exist, or some other helpful error

### What did you see instead?
a panic:
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0x1400061fe60)
	cuelang.org/go@v0.8.0/cmd/cue/cmd/root.go:328 +0x94
panic({0x104c20680?, 0x14000290ca8?})
	runtime/panic.go:770 +0x124
cuelang.org/go/cue/load.(*loader).absDirFromImportPath(0x1400012da40, {0x0?, 0x104935e96?}, {0x16bd43323, 0x7})
	cuelang.org/go@v0.8.0/cue/load/import.go:376 +0xf18
cuelang.org/go/cue/load.(*loader).newInstance(0x1400012da40, {0x0?, 0x104935e96?}, {0x16bd43323, 0x7})
	cuelang.org/go@v0.8.0/cue/load/import.go:313 +0x2c
cuelang.org/go/cue/load.(*loader).importPathsQuiet(0x1400012da40, {0x14000417f50?, 0x14000504908?, 0x14000504f88?})
	cuelang.org/go@v0.8.0/cue/load/search.go:262 +0x54c
cuelang.org/go/cue/load.(*loader).importPaths(0x1400061f6c0?, {0x14000417f50?, 0x140005945a0?, 0x14000417f50?})
	cuelang.org/go@v0.8.0/cue/load/search.go:220 +0x24
cuelang.org/go/cue/load.Instances({0x14000417f50, 0x1, 0x1}, 0x1040d5b6c?)
	cuelang.org/go@v0.8.0/cue/load/instances.go:93 +0x3c0
cuelang.org/go/cmd/cue/cmd.loadFromArgs(...)
	cuelang.org/go@v0.8.0/cmd/cue/cmd/common.go:115
cuelang.org/go/cmd/cue/cmd.parseArgs(0x14000458fc0, {0x14000417f50, 0x1, 0x1}, 0x14000492000)
	cuelang.org/go@v0.8.0/cmd/cue/cmd/common.go:541 +0x78
cuelang.org/go/cmd/cue/cmd.runExport(0x14000458fc0, {0x14000417f50, 0x1, 0x1})
	cuelang.org/go@v0.8.0/cmd/cue/cmd/export.go:113 +0x64
cuelang.org/go/cmd/cue/cmd.newExportCmd.mkRunE.func1(0x14000474200?, {0x14000417f50, 0x1, 0x1})
	cuelang.org/go@v0.8.0/cmd/cue/cmd/root.go:96 +0x98
github.com/spf13/cobra.(*Command).execute(0x1400046c608, {0x14000417f10, 0x1, 0x1})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x140002e3508)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0x14000458fc0, {0x105324800?, 0x104b8ae00?})
	cuelang.org/go@v0.8.0/cmd/cue/cmd/root.go:313 +0x5c
cuelang.org/go/cmd/cue/cmd.Main()
	cuelang.org/go@v0.8.0/cmd/cue/cmd/root.go:241 +0xac
main.main()
	cuelang.org/go@v0.8.0/cmd/cue/main.go:24 +0x1c

**Comment by myitcv** [comment]
Thanks for raising, @NoamTD!

FYI creating test repros with `testscript` is (at least in my experience) much easier:

https://github.com/cue-lang/cue/wiki/Creating-test-or-performance-reproducers

Because you can capture the positive and negative expectations. 

### What did you do?

```
env CUE_EXPERIMENT=modules
exec cue mod init example.com
! exec cue export anypath
stderr 'cannot find package "anypath"'
```

### What did you expect to see?

A passing test

### What did you see instead?

```
> env CUE_EXPERIMENT=modules
> exec cue mod init example.com
> ! exec cue export anypath
[stderr]
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0

goroutine 1 gp=0x40000021c0 m=7 mp=0x4000580008 [running]:
panic({0x9e3c00?, 0x40002fac60?})
        /home/myitcv/gos/src/runtime/panic.go:779 +0x140 fp=0x400061ec20 sp=0x400061eb70 pc=0x4cd70
cuelang.org/go/cmd/cue/cmd.recoverError(0x400061fe60)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:328 +0x94 fp=0x400061ec40 sp=0x400061ec20 pc=0x871ea4
cuelang.org/go/cmd/cue/cmd.(*Command).Run.deferwrap1()
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:311 +0x28 fp=0x400061ec60 sp=0x400061ec40 pc=0x871dd8
panic({0x9e3c00?, 0x40002fac60?})
        /home/myitcv/gos/src/runtime/panic.go:770 +0x124 fp=0x400061ed10 sp=0x400061ec60 pc=0x4cd54
runtime.goPanicIndex(0x0, 0x0)
        /home/myitcv/gos/src/runtime/panic.go:114 +0x7c fp=0x400061ed50 sp=0x400061ed10 pc=0x4b92c
cuelang.org/go/cue/load.(*loader).absDirFromImportPath(0x40001d0440, {0x0?, 0xa4693e?}, {0xffffdb8b3970, 0x7})
        /home/myitcv/dev/cuelang/cue/cue/load/import.go:376 +0xf18 fp=0x400061f190 sp=0x400061ed50 pc=0x602228
cuelang.org/go/cue/load.(*loader).newInstance(0x40001d0440, {0x0?, 0xa4693e?}, {0xffffdb8b3970, 0x7})
        /home/myitcv/dev/cuelang/cue/cue/load/import.go:313 +0x2c fp=0x400061f210 sp=0x400061f190 pc=0x60111c
cuelang.org/go/cue/load.(*loader).importPathsQuiet(0x40001d0440, {0x4000492040?, 0x4000580008?, 0x4000580610?})
        /home/myitcv/dev/cuelang/cue/cue/load/search.go:262 +0x54c fp=0x400061f2f0 sp=0x400061f210 pc=0x60a4ac
cuelang.org/go/cue/load.(*loader).importPaths(0x400061f6c0?, {0x4000492040?, 0x4000152360?, 0x4000492040?})
        /home/myitcv/dev/cuelang/cue/cue/load/search.go:220 +0x24 fp=0x400061f390 sp=0x400061f2f0 pc=0x609d94
cuelang.org/go/cue/load.Instances({0x4000492040, 0x1, 0x1}, 0x7?)
        /home/myitcv/dev/cuelang/cue/cue/load/instances.go:93 +0x3c0 fp=0x400061f730 sp=0x400061f390 pc=0x602800
cuelang.org/go/cmd/cue/cmd.loadFromArgs(...)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/common.go:115
cuelang.org/go/cmd/cue/cmd.parseArgs(0x400045d110, {0x4000492040, 0x1, 0x1}, 0x400046a050)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/common.go:541 +0x78 fp=0x400061f9d0 sp=0x400061f730 pc=0x8561c8
cuelang.org/go/cmd/cue/cmd.runExport(0x400045d110, {0x4000492040, 0x1, 0x1})
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/export.go:113 +0x64 fp=0x400061faa0 sp=0x400061f9d0 pc=0x85c7e4
cuelang.org/go/cmd/cue/cmd.newExportCmd.mkRunE.func1(0x4000476200?, {0x4000492040, 0x1, 0x1})
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:96 +0x98 fp=0x400061fbd0 sp=0x400061faa0 pc=0x85c598
github.com/spf13/cobra.(*Command).execute(0x400046e608, {0x4000492000, 0x1, 0x1})
        /home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0x840 fp=0x400061fd60 sp=0x400061fbd0 pc=0x1e0220
github.com/spf13/cobra.(*Command).ExecuteC(0x400029d508)
        /home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344 fp=0x400061fe40 sp=0x400061fd60 pc=0x1e09e4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0x400045d110, {0x1284ea0?, 0x94eaa0?})
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:313 +0x5c fp=0x400061fe90 sp=0x400061fe40 pc=0x871ccc
cuelang.org/go/cmd/cue/cmd.Main()
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:241 +0xac fp=0x400061ff20 sp=0x400061fe90 pc=0x8719fc
main.main()
        /home/myitcv/dev/cuelang/cue/cmd/cue/main.go:24 +0x1c fp=0x400061ff40 sp=0x400061ff20 pc=0x88ae8c
runtime.main()
        /home/myitcv/gos/src/runtime/proc.go:271 +0x28c fp=0x400061ffd0 sp=0x400061ff40 pc=0x501fc
runtime.goexit({})
        /home/myitcv/gos/src/runtime/asm_arm64.s:1222 +0x4 fp=0x400061ffd0 sp=0x400061ffd0 pc=0x84124

goroutine 2 gp=0x4000002c40 m=nil [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/myitcv/gos/src/runtime/proc.go:402 +0xc8 fp=0x400006cf90 sp=0x400006cf70 pc=0x50628
runtime.goparkunlock(...)
        /home/myitcv/gos/src/runtime/proc.go:408
runtime.forcegchelper()
        /home/myitcv/gos/src/runtime/proc.go:326 +0xb8 fp=0x400006cfd0 sp=0x400006cf90 pc=0x504b8
runtime.goexit({})
        /home/myitcv/gos/src/runtime/asm_arm64.s:1222 +0x4 fp=0x400006cfd0 sp=0x400006cfd0 pc=0x84124
created by runtime.init.6 in goroutine 1
        /home/myitcv/gos/src/runtime/proc.go:314 +0x24

goroutine 3 gp=0x4000003180 m=nil [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/myitcv/gos/src/runtime/proc.go:402 +0xc8 fp=0x400006d760 sp=0x400006d740 pc=0x50628
runtime.goparkunlock(...)
        /home/myitcv/gos/src/runtime/proc.go:408
runtime.bgsweep(0x400007e000)
        /home/myitcv/gos/src/runtime/mgcsweep.go:318 +0x108 fp=0x400006d7b0 sp=0x400006d760 pc=0x3b108
runtime.gcenable.gowrap1()
        /home/myitcv/gos/src/runtime/mgc.go:203 +0x28 fp=0x400006d7d0 sp=0x400006d7b0 pc=0x2f2d8
runtime.goexit({})
        /home/myitcv/gos/src/runtime/asm_arm64.s:1222 +0x4 fp=0x400006d7d0 sp=0x400006d7d0 pc=0x84124
created by runtime.gcenable in goroutine 1
        /home/myitcv/gos/src/runtime/mgc.go:203 +0x6c

goroutine 4 gp=0x4000003340 m=nil [GC scavenge wait]:
runtime.gopark(0x10000?, 0xbc8680?, 0x0?, 0x0?, 0x0?)
        /home/myitcv/gos/src/runtime/proc.go:402 +0xc8 fp=0x400006df60 sp=0x400006df40 pc=0x50628
runtime.goparkunlock(...)
        /home/myitcv/gos/src/runtime/proc.go:408
runtime.(*scavengerState).park(0x121b200)
        /home/myitcv/gos/src/runtime/mgcscavenge.go:425 +0x5c fp=0x400006df90 sp=0x400006df60 pc=0x38aac
runtime.bgscavenge(0x400007e000)
        /home/myitcv/gos/src/runtime/mgcscavenge.go:658 +0xac fp=0x400006dfb0 sp=0x400006df90 pc=0x3905c
runtime.gcenable.gowrap2()
        /home/myitcv/gos/src/runtime/mgc.go:204 +0x28 fp=0x400006dfd0 sp=0x400006dfb0 pc=0x2f278
runtime.goexit({})
        /home/myitcv/gos/src/runtime/asm_arm64.s:1222 +0x4 fp=0x400006dfd0 sp=0x400006dfd0 pc=0x84124
created by runtime.gcenable in goroutine 1
        /home/myitcv/gos/src/runtime/mgc.go:204 +0xac

goroutine 5 gp=0x4000003c00 m=nil [finalizer wait]:
runtime.gopark(0x94b860?, 0x21fcc?, 0xc0?, 0x1?, 0x33?)
        /home/myitcv/gos/src/runtime/proc.go:402 +0xc8 fp=0x400006c580 sp=0x400006c560 pc=0x50628
runtime.runfinq()
        /home/myitcv/gos/src/runtime/mfinal.go:194 +0x108 fp=0x400006c7d0 sp=0x400006c580 pc=0x2e3a8
runtime.goexit({})
        /home/myitcv/gos/src/runtime/asm_arm64.s:1222 +0x4 fp=0x400006c7d0 sp=0x400006c7d0 pc=0x84124
created by runtime.createfing in goroutine 1
        /home/myitcv/gos/src/runtime/mfinal.go:164 +0x80

goroutine 6 gp=0x40004da000 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/myitcv/gos/src/runtime/proc.go:402 +0xc8 fp=0x400006e730 sp=0x400006e710 pc=0x50628
runtime.gcBgMarkWorker()
        /home/myitcv/gos/src/runtime/mgc.go:1310 +0xd8 fp=0x400006e7d0 sp=0x400006e730 pc=0x313c8
runtime.goexit({})
        /home/myitcv/gos/src/runtime/asm_arm64.s:1222 +0x4 fp=0x400006e7d0 sp=0x400006e7d0 pc=0x84124
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /home/myitcv/gos/src/runtime/mgc.go:1234 +0x28

goroutine 18 gp=0x4000500000 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/myitcv/gos/src/runtime/proc.go:402 +0xc8 fp=0x4000068730 sp=0x4000068710 pc=0x50628
runtime.gcBgMarkWorker()
        /home/myitcv/gos/src/runtime/mgc.go:1310 +0xd8 fp=0x40000687d0 sp=0x4000068730 pc=0x313c8
runtime.goexit({})
        /home/myitcv/gos/src/runtime/asm_arm64.s:1222 +0x4 fp=0x40000687d0 sp=0x40000687d0 pc=0x84124
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /home/myitcv/gos/src/runtime/mgc.go:1234 +0x28

goroutine 19 gp=0x40005001c0 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/myitcv/gos/src/runtime/proc.go:402 +0xc8 fp=0x4000068f30 sp=0x4000068f10 pc=0x50628
runtime.gcBgMarkWorker()
        /home/myitcv/gos/src/runtime/mgc.go:1310 +0xd8 fp=0x4000068fd0 sp=0x4000068f30 pc=0x313c8
runtime.goexit({})
        /home/myitcv/gos/src/runtime/asm_arm64.s:1222 +0x4 fp=0x4000068fd0 sp=0x4000068fd0 pc=0x84124
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /home/myitcv/gos/src/runtime/mgc.go:1234 +0x28

goroutine 7 gp=0x40004da1c0 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        /home/myitcv/gos/src/runtime/proc.go:402 +0xc8 fp=0x400006ef30 sp=0x400006ef10 pc=0x50628
runtime.gcBgMarkWorker()
        /home/myitcv/gos/src/runtime/mgc.go:1310 +0xd8 fp=0x400006efd0 sp=0x400006ef30 pc=0x313c8
runtime.goexit({})
        /home/myitcv/gos/src/runtime/asm_arm64.s:1222 +0x4 fp=0x400006efd0 sp=0x400006efd0 pc=0x84124
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /home/myitcv/gos/src/runtime/mgc.go:1234 +0x28

goroutine 20 gp=0x4000500380 m=nil [GC worker (idle)]:
runtime.gopark(0x16a5471d8ad?, 0x3?, 0xbd?, 0x34?, 0x0?)
        /home/myitcv/gos/src/runtime/proc.go:402 +0xc8 fp=0x4000069730 sp=0x4000069710 pc=0x50628
runtime.gcBgMarkWorker()
        /home/myitcv/gos/src/runtime/mgc.go:1310 +0xd8 fp=0x40000697d0 sp=0x4000069730 pc=0x313c8
runtime.goexit({})
        /home/myitcv/gos/src/runtime/asm_arm64.s:1222 +0x4 fp=0x40000697d0 sp=0x40000697d0 pc=0x84124
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /home/myitcv/gos/src/runtime/mgc.go:1234 +0x28

goroutine 34 gp=0x4000102380 m=nil [GC worker (idle)]:
runtime.gopark(0x16a5472380f?, 0x400010e060?, 0x1a?, 0xa?, 0x0?)
        /home/myitcv/gos/src/runtime/proc.go:402 +0xc8 fp=0x4000114730 sp=0x4000114710 pc=0x50628
runtime.gcBgMarkWorker()
        /home/myitcv/gos/src/runtime/mgc.go:1310 +0xd8 fp=0x40001147d0 sp=0x4000114730 pc=0x313c8
runtime.goexit({})
        /home/myitcv/gos/src/runtime/asm_arm64.s:1222 +0x4 fp=0x40001147d0 sp=0x40001147d0 pc=0x84124
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /home/myitcv/gos/src/runtime/mgc.go:1234 +0x28

goroutine 35 gp=0x4000102540 m=nil [GC worker (idle)]:
runtime.gopark(0x16a54720b22?, 0x1?, 0xd4?, 0x37?, 0x0?)
        /home/myitcv/gos/src/runtime/proc.go:402 +0xc8 fp=0x4000114f30 sp=0x4000114f10 pc=0x50628
runtime.gcBgMarkWorker()
        /home/myitcv/gos/src/runtime/mgc.go:1310 +0xd8 fp=0x4000114fd0 sp=0x4000114f30 pc=0x313c8
runtime.goexit({})
        /home/myitcv/gos/src/runtime/asm_arm64.s:1222 +0x4 fp=0x4000114fd0 sp=0x4000114fd0 pc=0x84124
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /home/myitcv/gos/src/runtime/mgc.go:1234 +0x28

goroutine 36 gp=0x4000102700 m=nil [GC worker (idle)]:
runtime.gopark(0x16a5471db71?, 0x3?, 0x36?, 0x5?, 0x0?)
        /home/myitcv/gos/src/runtime/proc.go:402 +0xc8 fp=0x4000115730 sp=0x4000115710 pc=0x50628
runtime.gcBgMarkWorker()
        /home/myitcv/gos/src/runtime/mgc.go:1310 +0xd8 fp=0x40001157d0 sp=0x4000115730 pc=0x313c8
runtime.goexit({})
        /home/myitcv/gos/src/runtime/asm_arm64.s:1222 +0x4 fp=0x40001157d0 sp=0x40001157d0 pc=0x84124
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /home/myitcv/gos/src/runtime/mgc.go:1234 +0x28

goroutine 37 gp=0x40001028c0 m=nil [GC worker (idle)]:
runtime.gopark(0x16a5471dc18?, 0x3?, 0x8d?, 0x35?, 0x0?)
        /home/myitcv/gos/src/runtime/proc.go:402 +0xc8 fp=0x4000115f30 sp=0x4000115f10 pc=0x50628
runtime.gcBgMarkWorker()
        /home/myitcv/gos/src/runtime/mgc.go:1310 +0xd8 fp=0x4000115fd0 sp=0x4000115f30 pc=0x313c8
runtime.goexit({})
        /home/myitcv/gos/src/runtime/asm_arm64.s:1222 +0x4 fp=0x4000115fd0 sp=0x4000115fd0 pc=0x84124
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /home/myitcv/gos/src/runtime/mgc.go:1234 +0x28

goroutine 38 gp=0x4000102a80 m=nil [GC worker (idle)]:
runtime.gopark(0x16a54721469?, 0x1?, 0x80?, 0x8c?, 0x0?)
        /home/myitcv/gos/src/runtime/proc.go:402 +0xc8 fp=0x4000116730 sp=0x4000116710 pc=0x50628
runtime.gcBgMarkWorker()
        /home/myitcv/gos/src/runtime/mgc.go:1310 +0xd8 fp=0x40001167d0 sp=0x4000116730 pc=0x313c8
runtime.goexit({})
        /home/myitcv/gos/src/runtime/asm_arm64.s:1222 +0x4 fp=0x40001167d0 sp=0x40001167d0 pc=0x84124
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /home/myitcv/gos/src/runtime/mgc.go:1234 +0x28
[exit status 2]
> stderr 'cannot find package "anypath"'
FAIL: /tmp/testscript3337930269/repro.txtar/script.txtar:4: no match for `cannot find package "anypath"` found in stderr
error running repro.txtar in /tmp/testscript3337930269/repro.txtar
```

**Comment by noamtd-msft** [comment]
@myitcv good to know, thank you - will take this into account next time

**Comment by NoamTD** [comment]
@myitcv  good to know, thank you - will take this into account next time
