### ISSUE TITLE
Nil pointer dereference

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#300]
_Originally opened by @robsonmeemo in https://github.com/cuelang/cue/issues/300_

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version (devel) darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?
Complicated config file. If the stacktrace is not enough let me know and I'll try to have a small reproduction.

### What did you expect to see?
success

### What did you see instead?
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x151c159]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc00048fea8)
	/Users/robson/work/cue/cmd/cue/cmd/root.go:218 +0xa3
panic(0x1784d40, 0x1e5a810)
	/Users/robson/work/go-sdk/go1.13/src/runtime/panic.go:679 +0x1b2
cuelang.org/go/cue.rewrite(0xc00045a0b0, 0x0, 0x0, 0x188ec50, 0x203000, 0xc00048dbd8)
	/Users/robson/work/cue/cue/rewrite.go:30 +0x59
cuelang.org/go/cue.(*indexExpr).rewrite(0xc0003408d0, 0xc00045a0b0, 0x188ec50, 0x19809a0, 0xc0003408d0)
	/Users/robson/work/cue/cue/rewrite.go:73 +0x50
cuelang.org/go/cue.rewrite(0xc00045a0b0, 0x19809a0, 0xc0003408d0, 0x188ec50, 0x2441460, 0x1015c8a)
	/Users/robson/work/cue/cue/rewrite.go:30 +0x77
cuelang.org/go/cue.(*selectorExpr).rewrite(0xc000340900, 0xc00045a0b0, 0x188ec50, 0x1980d00, 0xc000340900)
	/Users/robson/work/cue/cue/rewrite.go:65 +0x50
cuelang.org/go/cue.rewrite(0xc00045a0b0, 0x1980d00, 0xc000340900, 0x188ec50, 0xc00048dd50, 0x2)
	/Users/robson/work/cue/cue/rewrite.go:30 +0x77
cuelang.org/go/cue.(*context).copy(...)
	/Users/robson/work/cue/cue/copy.go:19
cuelang.org/go/cue.resolveReference(0xc00045a0b0, 0x1980d00, 0xc00030fc20, 0x1983700, 0xc000515700)
	/Users/robson/work/cue/cue/eval.go:73 +0x355
cuelang.org/go/cue.(*binaryExpr).evalPartial(0xc000515780, 0xc00045a0b0, 0x0, 0x0)
	/Users/robson/work/cue/cue/eval.go:617 +0xc5
cuelang.org/go/cue.(*structLit).at(0xc00001e850, 0xc00045a0b0, 0x0, 0x0, 0xc00001e930)
	/Users/robson/work/cue/cue/value.go:1071 +0x2ec
cuelang.org/go/cue.validate(0xc00045a0b0, 0x1980e80, 0xc00001e850, 0xc00044a540)
	/Users/robson/work/cue/cue/validate.go:36 +0x255
cuelang.org/go/cue.(*disjunction).normalize(0xc000229c20, 0xc00045a0b0, 0x19791e0, 0xc000515440, 0xc0003f6be0, 0x153f901, 0x1983900)
	/Users/robson/work/cue/cue/value.go:1704 +0xcd
cuelang.org/go/cue.distribute(0xc00045a0b0, 0x19791e0, 0xc000515440, 0x1980001, 0x1983400, 0xc0003f6be0, 0x1983900, 0xc00001e540, 0xc00048e328, 0x14f4b81)
	/Users/robson/work/cue/cue/binop.go:149 +0x116
cuelang.org/go/cue.binOp(0xc00045a0b0, 0x19791e0, 0xc000515440, 0x1980001, 0x1983400, 0xc0003f6be0, 0x1983900, 0xc00001e540, 0xc0003f41c0, 0x0)
	/Users/robson/work/cue/cue/binop.go:113 +0x709
cuelang.org/go/cue.(*binaryExpr).evalPartial(0xc000515440, 0xc00045a0b0, 0x0, 0x0)
	/Users/robson/work/cue/cue/eval.go:630 +0x380
cuelang.org/go/cue.(*context).manifest(0xc00045a0b0, 0x1980460, 0xc000515440, 0x2441460, 0x0)
	/Users/robson/work/cue/cue/evaluator.go:18 +0x3f
cuelang.org/go/cue.(*evaluator).eval(0xc00048e658, 0x1980460, 0xc000515440, 0x1980600, 0x1879a50, 0x40, 0xc000447f00, 0x1, 0x1, 0x153b123, ...)
	/Users/robson/work/cue/cue/evaluator.go:83 +0x4f
cuelang.org/go/cue.(*selectorExpr).evalPartial(0xc0003401b0, 0xc00045a0b0, 0x0, 0x0)
	/Users/robson/work/cue/cue/eval.go:120 +0xfc
cuelang.org/go/cue.(*context).manifest(0xc00045a0b0, 0x1980d00, 0xc0003401b0, 0xc0002268c0, 0xc00045a0b0)
	/Users/robson/work/cue/cue/evaluator.go:18 +0x3f
cuelang.org/go/cue.(*feed).yield(0xc000340300, 0xc00045a0b0, 0xc00000f2c0, 0x0)
	/Users/robson/work/cue/cue/value.go:1893 +0x76
cuelang.org/go/cue.(*listComprehension).evalPartial(0xc00000f240, 0xc00045a0b0, 0xc000068c00, 0x2441460)
	/Users/robson/work/cue/cue/eval.go:421 +0xfd
cuelang.org/go/cue.(*evaluator).evalPartial(0xc00048ead0, 0x1980b20, 0xc00000f240, 0xc0004407fe, 0x185c35f, 0xe, 0x0, 0x0, 0x0, 0x1983280, ...)
	/Users/robson/work/cue/cue/evaluator.go:100 +0x4b
cuelang.org/go/cue.(*callExpr).evalPartial(0xc000515480, 0xc00045a0b0, 0x0, 0x0)
	/Users/robson/work/cue/cue/eval.go:335 +0x1a2
cuelang.org/go/cue.(*context).manifest(0xc00045a0b0, 0x19806a0, 0xc000515480, 0xc00001e500, 0xc0000e0b40)
	/Users/robson/work/cue/cue/evaluator.go:18 +0x3f
cuelang.org/go/cue.evalUnary(0xc00045a0b0, 0x19795e0, 0xc000340330, 0x6, 0x19806a0, 0xc000515480, 0xc000515640, 0x203000)
	/Users/robson/work/cue/cue/eval.go:643 +0x5a
cuelang.org/go/cue.(*unaryExpr).evalPartial(0xc000340330, 0xc00045a0b0, 0x0, 0x0)
	/Users/robson/work/cue/cue/eval.go:639 +0x88
cuelang.org/go/cue.(*context).manifest(0xc00045a0b0, 0x1980f40, 0xc000340330, 0x20, 0x17db8a0)
	/Users/robson/work/cue/cue/evaluator.go:18 +0x3f
cuelang.org/go/cue.(*guard).yield(0xc000340360, 0xc00045a0b0, 0xc00000f2a0, 0x100be01)
	/Users/robson/work/cue/cue/value.go:1866 +0x46
cuelang.org/go/cue.(*structComprehension).evalPartial(0xc00000f260, 0xc00045a0b0, 0x14d1169, 0xc00001e4d0)
	/Users/robson/work/cue/cue/eval.go:437 +0xd7
cuelang.org/go/cue.(*structLit).expandFields(0xc00001e4d0, 0xc00045a0b0, 0xc00001e4d0, 0x1983900)
	/Users/robson/work/cue/cue/value.go:1145 +0x215
cuelang.org/go/cue.(*structLit).at(0xc0002f5ce0, 0xc00045a0b0, 0x0, 0xc, 0xc0002f5ce0)
	/Users/robson/work/cue/cue/value.go:1093 +0x637
cuelang.org/go/cue.(*feed).yield(0xc0002aff20, 0xc00045a0b0, 0xc00000e8e0, 0x0)
	/Users/robson/work/cue/cue/value.go:1912 +0x7f0
cuelang.org/go/cue.(*structComprehension).evalPartial(0xc00044fdc0, 0xc00045a0b0, 0xc000447d20, 0xc000440002)
	/Users/robson/work/cue/cue/eval.go:437 +0xd7
cuelang.org/go/cue.(*structLit).expandFields(0xc00043a2a0, 0xc00045a0b0, 0xc00043a2a0, 0x1983900)
	/Users/robson/work/cue/cue/value.go:1145 +0x215
cuelang.org/go/cue.(*structLit).at(0xc00044bea0, 0xc00045a0b0, 0x1, 0x0, 0xc000272630)
	/Users/robson/work/cue/cue/value.go:1093 +0x637
cuelang.org/go/cue.(*structLit).iterAt(0xc00044bea0, 0xc00045a0b0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/robson/work/cue/cue/value.go:1035 +0x123
cuelang.org/go/cue.newChildValue(0xc00048f848, 0x1, 0x3, 0xe)
	/Users/robson/work/cue/cue/types.go:625 +0x257
cuelang.org/go/cue.(*structValue).At(0xc00048f848, 0x1, 0xc000464aa0, 0x10000000000, 0xc000354800, 0xc000464aa0)
	/Users/robson/work/cue/cue/types.go:155 +0x8a
cuelang.org/go/cue.(*validator).walk(0xc00048fa38, 0xc000354800, 0xc0003f73b0, 0x10000000000, 0xc000354800)
	/Users/robson/work/cue/cue/types.go:1803 +0x36a
cuelang.org/go/cue.(*validator).walk(0xc00048fa38, 0xc000354800, 0xc0003f72c0, 0x10000000000, 0xc000273a00)
	/Users/robson/work/cue/cue/types.go:1808 +0x32b
cuelang.org/go/cue.Value.Validate(0xc000354800, 0xc0003f72c0, 0x0, 0x0, 0x0, 0x1, 0x1)
	/Users/robson/work/cue/cue/types.go:1754 +0xc7
cuelang.org/go/cmd/cue/cmd.buildInstances(0xc0002bc380, 0xc0004020e0, 0x1, 0x1, 0xc0004020e0, 0x1, 0x1)
	/Users/robson/work/cue/cmd/cue/cmd/common.go:141 +0x1c8
cuelang.org/go/cmd/cue/cmd.buildFromArgs(0xc0002bc380, 0xc0002be800, 0x1, 0x1, 0x187580c, 0x32, 0x1e90f40)
	/Users/robson/work/cue/cmd/cue/cmd/common.go:108 +0x11a
cuelang.org/go/cmd/cue/cmd.runExport(0xc0002bc380, 0xc0002be800, 0x1, 0x1, 0x13a9e30, 0xc000243c58)
	/Users/robson/work/cue/cmd/cue/cmd/export.go:107 +0x67
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc0002cb180, 0xc0002be800, 0x1, 0x1, 0x0, 0x0)
	/Users/robson/work/cue/cmd/cue/cmd/root.go:47 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc0002cb180, 0xc0002be7d0, 0x1, 0x1, 0xc0002cb180, 0xc0002be7d0)
	/Users/robson/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002caa00, 0x0, 0xc0002bc720, 0x0)
	/Users/robson/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/robson/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc0002bc380, 0x1979060, 0xc0000380f0, 0x0, 0x0)
	/Users/robson/work/cue/cmd/cue/cmd/root.go:203 +0x75
cuelang.org/go/cmd/cue/cmd.mainErr(0x1979060, 0xc0000380f0, 0xc000032070, 0x2, 0x2, 0xc000243f00, 0x105d2c0)
	/Users/robson/work/cue/cmd/cue/cmd/root.go:138 +0x74
cuelang.org/go/cmd/cue/cmd.Main(0x0)
	/Users/robson/work/cue/cmd/cue/cmd/root.go:123 +0x84
main.main()
	/Users/robson/work/cue/cmd/cue/main.go:35 +0x3a
```

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/300#issuecomment-595979388_

It is hard to tell from the stack trace. I can see its related to selecting into an indexed value, but why there is a nil pointer there is hard to tell without having a reproducer. Thanks!

**Comment by cueckoo** [comment]
_Original reply by @robsonmeemo in https://github.com/cuelang/cue/issues/300#issuecomment-596026801_

I can't reproduce it anymore :(
I'll close this and if I see it again I'll reopen.
