### ISSUE TITLE
evaluator: evalv3 panics in equalTerminal

### ISSUE THREAD

**Issue by mvdan** [cue-lang/cue#3045]
### What version of CUE are you using (`cue version`)?

master, 6728bb2599dc778fea5c53dbf3248ef5da77db4b

### Does this issue reproduce with the latest stable release?

The new evaluator is... new.

### What did you do?

On https://github.com/tmm1/taxes.cue at master (c7a9fefa2fa115b5d06fb952636a475823ff14a9), ran `CUE_EXPERIMENT=evalv3 cue eval -c .:taxes`. Note how this succeeds after about 15s without the experiment.

### What did you expect to see?

Success, or at least no panic.

### What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x6ee96a]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc00711de78)
	/home/mvdan/src/c/cue/cmd/cue/cmd/root.go:358 +0x76
panic({0xcc9f60?, 0x14565b0?})
	/home/mvdan/tip/src/runtime/panic.go:759 +0x132
cuelang.org/go/internal/core/adt.runTask.func1()
	/home/mvdan/src/c/cue/internal/core/adt/sched.go:692 +0x76
panic({0xcc9f60?, 0x14565b0?})
	/home/mvdan/tip/src/runtime/panic.go:759 +0x132
cuelang.org/go/internal/core/adt.equalTerminal(0xc0006be000, {0xf0e5f0?, 0xc122732b10?}, {0xf0e5f0?, 0x0?}, 0x2)
	/home/mvdan/src/c/cue/internal/core/adt/equality.go:178 +0xea
cuelang.org/go/internal/core/adt.Equal(0x145cee0?, {0xf0e5f0?, 0xc122732b10?}, {0xf0e5f0?, 0x0?}, 0xae10?)
	/home/mvdan/src/c/cue/internal/core/adt/equality.go:37 +0x66
cuelang.org/go/internal/core/adt.isEqualBaseValue(0xc0006be000, {0xf00600?, 0xc122732b10}, {0xf00600, 0x0})
	/home/mvdan/src/c/cue/internal/core/adt/disjunct2.go:742 +0xb7
cuelang.org/go/internal/core/adt.isEqualNodeValue(0xc122761208, 0xc122761808)
	/home/mvdan/src/c/cue/internal/core/adt/disjunct2.go:701 +0x171
cuelang.org/go/internal/core/adt.equalPartialNode(0xc0006be000, 0xc12276a2d0, 0xc12276af00)
	/home/mvdan/src/c/cue/internal/core/adt/disjunct2.go:615 +0x75
cuelang.org/go/internal/core/adt.appendDisjunct(0xc0006be000, {0xc12269a8f0, 0x1, 0x1}, 0xc122761808)
	/home/mvdan/src/c/cue/internal/core/adt/disjunct2.go:531 +0x5f5
cuelang.org/go/internal/core/adt.(*nodeContext).crossProduct(0xc122760008, {0xc00711bdf8?, 0xc12275fc20?, 0xc0006be000?}, {0xc00711be90, 0x1, 0xc00711be00?}, 0xc10e5a1960, 0x2)
	/home/mvdan/src/c/cue/internal/core/adt/disjunct2.go:354 +0x397
cuelang.org/go/internal/core/adt.(*nodeContext).processDisjunctions(0xc122760008)
	/home/mvdan/src/c/cue/internal/core/adt/disjunct2.go:279 +0x176
cuelang.org/go/internal/core/adt.processDisjunctions(0xdac8b9?, 0xc122762500, 0xb5?)
	/home/mvdan/src/c/cue/internal/core/adt/tasks.go:187 +0x1c
cuelang.org/go/internal/core/adt.runTask(0xc122762500, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/sched.go:712 +0x525
cuelang.org/go/internal/core/adt.(*scheduler).process(0xc1227601c0, 0x7eff, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/sched.go:411 +0x238
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc122762280, 0xc0006be000, 0x7fff, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/unify.go:157 +0x28d
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc12270b808, 0x7fff, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/unify.go:465 +0x215
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc122704640, 0xc0006be000, 0x7fff, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/unify.go:233 +0x776
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc1225e4c08, 0x7fff, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/unify.go:465 +0x215
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc1225d1ae0, 0xc0006be000, 0x7fff, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/unify.go:233 +0x776
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc1225a0008, 0x7fff, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/unify.go:465 +0x215
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc122595220, 0xc0006be000, 0x7fff, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/unify.go:233 +0x776
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc007419208, 0x7fff, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/unify.go:465 +0x215
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc007414be0, 0xc0006be000, 0x7fff, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/unify.go:233 +0x776
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc001227808, 0x7fff, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/unify.go:465 +0x215
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc001d752c0, 0xc0006be000, 0x7fff, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/unify.go:233 +0x776
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc000020008, 0x7fff, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/unify.go:465 +0x215
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc001d740a0, 0xc0006be000, 0x7fff, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/unify.go:233 +0x776
cuelang.org/go/internal/core/adt.(*OpContext).unify(0x41942a?, 0x0?, 0xf0c6b0?)
	/home/mvdan/src/c/cue/internal/core/adt/eval.go:158 +0x386
cuelang.org/go/internal/core/adt.(*Vertex).Finalize(0x160?, 0xc0006be000)
	/home/mvdan/src/c/cue/internal/core/adt/composite.go:781 +0x59
cuelang.org/go/cue.newVertexRoot(0xc0004279e0, 0xc0006be000?, 0xc001d740a0)
	/home/mvdan/src/c/cue/cue/types.go:603 +0x25
cuelang.org/go/cue.newValueRoot(0xf0e320?, 0xc0004279e0?, {0xf0aa00?, 0xc001d740a0?})
	/home/mvdan/src/c/cue/cue/types.go:612 +0x3e
cuelang.org/go/cue.(*Context).make(0xc0004279e0, 0xc001d740a0)
	/home/mvdan/src/c/cue/cue/context.go:257 +0x65
cuelang.org/go/cue.(*Context).BuildInstances(0xc0004279e0, {0xc000d953b0, 0x1, 0xa?})
	/home/mvdan/src/c/cue/cue/context.go:152 +0x1e5
cuelang.org/go/cmd/cue/cmd.buildInstances(0xc00042ce70, {0xc000d953b0, 0x1, 0xc0018430e0?}, 0x0)
	/home/mvdan/src/c/cue/cmd/cue/cmd/common.go:742 +0x46
cuelang.org/go/cmd/cue/cmd.(*buildPlan).instances(0xc0004641a0)
	/home/mvdan/src/c/cue/cmd/cue/cmd/common.go:179 +0x48
cuelang.org/go/cmd/cue/cmd.runEval(0xc00042ce70, {0xc000427c20, 0x1, 0x2})
	/home/mvdan/src/c/cue/cmd/cue/cmd/eval.go:113 +0x3ac
cuelang.org/go/cmd/cue/cmd.newEvalCmd.mkRunE.func1(0xc00042e800?, {0xc000427c20, 0x1, 0x2})
	/home/mvdan/src/c/cue/cmd/cue/cmd/root.go:122 +0x288
github.com/spf13/cobra.(*Command).execute(0xc000440008, {0xc000427c00, 0x2, 0x2})
	/home/mvdan/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002c5508)
	/home/mvdan/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/home/mvdan/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc00042ce70, {0x14b21c0?, 0xccafe0?})
	/home/mvdan/src/c/cue/cmd/cue/cmd/root.go:343 +0x65
cuelang.org/go/cmd/cue/cmd.Main()
	/home/mvdan/src/c/cue/cmd/cue/cmd/root.go:271 +0xa5
main.main()
	/home/mvdan/src/c/cue/cmd/cue/main.go:24 +0x13
```

**Comment by mvdan** [comment]
I can no longer reproduce in master; Marcel had a suspicion that his alpha.3 fixes would resolve this panic, and it seems like it happened. For example, see https://review.gerrithub.io/c/cue-lang/cue/+/1193672 and https://review.gerrithub.io/c/cue-lang/cue/+/1193674.
