### ISSUE TITLE
evalv3: "incDependent: already closed" panic on valid CUE

### ISSUE THREAD

**Issue by gdvalle** [cue-lang/cue#3062]
### What version of CUE are you using (`cue version`)?

de5d0cfc99a7d9b9974fdecf5f87f52b8a073090 - latest tip of master at time of writing.

<pre>
cue version v0.9.0-alpha.3

go version go1.22.2
      -buildmode exe
       -compiler gc
  DefaultGODEBUG httplaxcontentlength=1,httpmuxgo121=1,tls10server=1,tlsrsakex=1,tlsunsafeekm=1
     CGO_ENABLED 1
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
</pre>

### Does this issue reproduce with the latest stable release?
No, without evalv3 this exports correctly.

### What did you do?
This can probably be reduced a little further, but this is representative of some k8s code we have.
```
#S: "a"

#A: "a"

#sA: #A

#Thing: x: #S
#Things: {
    one: x: #sA
}

#o: things: #Thing
#o2: #o & {
    things: #Things.one
}

o2: #o2
```

And ran `CUE_EXPERIMENT=evalv3 cue export test.cue`.

### What did you expect to see?
```json
{
    "o2": {
        "things": {
            "x": "a"
        }
    }
}
```

### What did you see instead?
```
panic: incDependent: already closed: 0xc0001c0a50 [recovered]
        panic: incDependent: already closed: 0xc0001c0a50 [recovered]
        panic: incDependent: already closed: 0xc0001c0a50

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc00061fe78)
        /home/greg/Projects/cue/cmd/cue/cmd/root.go:358 +0x76
panic({0xc83540?, 0xc000442610?})
        /home/greg/.local/share/mise/installs/go/1.22.2/src/runtime/panic.go:770 +0x132
cuelang.org/go/internal/core/adt.runTask.func1()
        /home/greg/Projects/cue/internal/core/adt/sched.go:692 +0x76
panic({0xc83540?, 0xc000442610?})
        /home/greg/.local/share/mise/installs/go/1.22.2/src/runtime/panic.go:770 +0x132
cuelang.org/go/internal/core/adt.(*closeContext).incDependent(0xc0001c0a50, 0xc000196780, 0xc0001c0b40?, 0x146f320?)
        /home/greg/Projects/cue/internal/core/adt/fields.go:533 +0xa9
cuelang.org/go/internal/core/adt.CloseInfo.spawnCloseContext({0x0, 0xc0001c0e10, 0x0, 0x0, 0x0, 0x0, {0x0, 0x0, 0xc0001a04e0}}, 0xc000196780, ...)
        /home/greg/Projects/cue/internal/core/adt/fields.go:471 +0xfc
cuelang.org/go/internal/core/adt.(*nodeContext).scheduleVertexConjuncts(0xc0001c2008, {0xc000194a00, {0xf06830, 0xc000442330}, {0x0, 0xc0001c0a50, 0x0, 0x0, 0x0, 0x0, ...}}, ...)
        /home/greg/Projects/cue/internal/core/adt/conjunct.go:397 +0x426
cuelang.org/go/internal/core/adt.(*nodeContext).unshare(0x14600f0?)
        /home/greg/Projects/cue/internal/core/adt/share.go:47 +0x12e
cuelang.org/go/internal/core/adt.(*nodeContext).scheduleConjunct(0xc0001c2008, {0xc0001943a0, {0xf06718, 0xc0001941c0}, {0x0, 0xc00015c4b0, 0x0, 0x0, 0x0, 0x0, ...}}, ...)
        /home/greg/Projects/cue/internal/core/adt/conjunct.go:152 +0xf45
cuelang.org/go/internal/core/adt.(*nodeContext).scheduleConjunct(0xc0001c2008, {0x0, {0xf066f0, 0xc000465a28}, {0x0, 0xc00015c3c0, 0x0, 0x0, 0x0, 0x0, ...}}, ...)
        /home/greg/Projects/cue/internal/core/adt/conjunct.go:137 +0x136c
cuelang.org/go/internal/core/adt.(*nodeContext).scheduleVertexConjuncts(0xc0001c2008, {0xc000194ac0, {0xf06830, 0xc000442310}, {0x0, 0xc0001c0c30, 0x0, 0x0, 0x0, 0x0, ...}}, ...)
        /home/greg/Projects/cue/internal/core/adt/conjunct.go:423 +0x676
cuelang.org/go/internal/core/adt.processResolver(0xc000196780, 0xc000193220, 0x10?)
        /home/greg/Projects/cue/internal/core/adt/tasks.go:120 +0x425
cuelang.org/go/internal/core/adt.runTask(0xc000193220, 0x4)
        /home/greg/Projects/cue/internal/core/adt/sched.go:712 +0x525
cuelang.org/go/internal/core/adt.(*scheduler).process(0xc0001c21d0, 0x7eff, 0x4)
        /home/greg/Projects/cue/internal/core/adt/sched.go:411 +0x23d
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc0001930e0, 0xc000196780, 0x7fff, 0x4)
        /home/greg/Projects/cue/internal/core/adt/unify.go:157 +0x28d
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc0001bb808, 0x7fff, 0x4)
        /home/greg/Projects/cue/internal/core/adt/unify.go:478 +0x215
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc000192f00, 0xc000196780, 0x7fff, 0x4)
        /home/greg/Projects/cue/internal/core/adt/unify.go:226 +0x7b6
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc0001b7208, 0x7fff, 0x4)
        /home/greg/Projects/cue/internal/core/adt/unify.go:478 +0x215
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc000192820, 0xc000196780, 0x7fff, 0x4)
        /home/greg/Projects/cue/internal/core/adt/unify.go:226 +0x7b6
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc000190608, 0x7fff, 0x4)
        /home/greg/Projects/cue/internal/core/adt/unify.go:478 +0x215
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc0001923c0, 0xc000196780, 0x7fff, 0x4)
        /home/greg/Projects/cue/internal/core/adt/unify.go:226 +0x7b6
cuelang.org/go/internal/core/adt.(*OpContext).unify(0xc000700008?, 0xc0003d19e0?, 0x0?)
        /home/greg/Projects/cue/internal/core/adt/eval.go:158 +0x386
cuelang.org/go/internal/core/adt.(*Vertex).Finalize(0x78511dd02c68?, 0xc000196780)
        /home/greg/Projects/cue/internal/core/adt/composite.go:786 +0x59
cuelang.org/go/cue.newVertexRoot(0xc0002e1640, 0x0?, 0xc0001923c0)
        /home/greg/Projects/cue/cue/types.go:603 +0x25
cuelang.org/go/cue.newValueRoot(0xf115c0?, 0xc0002e1640?, {0xf0da00?, 0xc0001923c0?})
        /home/greg/Projects/cue/cue/types.go:612 +0x3e
cuelang.org/go/cue.(*Context).make(0xc0002e1640, 0xc0001923c0)
        /home/greg/Projects/cue/cue/context.go:257 +0x65
cuelang.org/go/cue.(*Context).BuildInstances(0xc0002e1640, {0xc00061f908, 0x1, 0x0?})
        /home/greg/Projects/cue/cue/context.go:152 +0x1e5
cuelang.org/go/cmd/cue/cmd.buildInstances(0xc0002e9a40, {0xc00061f908, 0x1, 0x0?}, 0x1)
        /home/greg/Projects/cue/cmd/cue/cmd/common.go:742 +0x46
cuelang.org/go/cmd/cue/cmd.parseArgs(0xc0002e9a40, {0xc0002eb6a0, 0x1, 0x1}, 0xc00029f090)
        /home/greg/Projects/cue/cmd/cue/cmd/common.go:634 +0xc8e
cuelang.org/go/cmd/cue/cmd.runExport(0xc0002e9a40, {0xc0002eb6a0, 0x1, 0x1})
        /home/greg/Projects/cue/cmd/cue/cmd/export.go:113 +0x8a
cuelang.org/go/cmd/cue/cmd.newExportCmd.mkRunE.func1(0xc0001c4e00?, {0xc0002eb6a0, 0x1, 0x1})
        /home/greg/Projects/cue/cmd/cue/cmd/root.go:122 +0x2a5
github.com/spf13/cobra.(*Command).execute(0xc0002f5508, {0xc0002eb660, 0x1, 0x1})
        /home/greg/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002f4608)
        /home/greg/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/greg/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc0002e9a40, {0x14f5740?, 0xcc8ea0?})
        /home/greg/Projects/cue/cmd/cue/cmd/root.go:343 +0x65
cuelang.org/go/cmd/cue/cmd.Main()
        /home/greg/Projects/cue/cmd/cue/cmd/root.go:271 +0xa5
main.main()
        /home/greg/Projects/cue/cmd/cue/main.go:24 +0x13
```

**Comment by mvdan** [comment]
This still seems to reproduce as of 7d49080bb7ab8518a43bc9fe743e302f14c28712.

**Comment by mpvl** [comment]
A smaller reproducer:
```
#S: "a"
#o: x: #S
o: #o
o: X
X: x: A
A: "a"
```
All elements, including definitions and references are necessary to reproduce it.

### Analysis
Structure sharing influences the order of evaluation, causing tracking of completion to be affected in previously unforeseen ways.

This is a bad bug, so we will prioritize fixing it.

In the meantime, this crash can be prevented by turning structure sharing off:
```
CUE_DEBUG=sharing=false CUE_EXPERIMENT=evalv3 go run ./cmd/cue export test.cue
```

Note that turning sharing off can have a significantly negative impact on performance.
