### ISSUE TITLE
evalv3: nil pointer dereference panic in equalTerminal with repeated unifications

### ISSUE THREAD

**Issue by massive** [cue-lang/cue#3194]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version

cue version v0.9.0-rc.1

go version go1.21.10
      -buildmode exe
       -compiler gc
     CGO_ENABLED 1
          GOARCH arm64
            GOOS darwin
cue.lang.version v0.9.0
</pre>

### Does this issue reproduce with the latest stable release?

Yes

### What did you do?

I ran the following command: `CUE_EXPERIMENT=evalv3 cue export tests/fixtures/kafka_topics.cue`

So far, I have *not* yet created a reproducer since I just discovered the issue, and our project is several thousands of lines of Cue code. Similarly, as before, I can try to narrow the problem down and provide you with a sample reproducer upon request.

### What did you expect to see?

A bunch of JSON output. It works as intended when *not* using CUE_EXPERIMENT

### What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x1008a938c]

goroutine 1 [running]:
cuelang.org/go/internal/core/adt.runTask.func1()
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/sched.go:692 +0xa4
panic({0x100f53d00?, 0x101548f10?})
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/go/src/runtime/panic.go:914 +0x218
cuelang.org/go/internal/core/adt.runTask.func1()
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/sched.go:692 +0xa4
panic({0x100f53d00?, 0x101548f10?})
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/go/src/runtime/panic.go:914 +0x218
cuelang.org/go/internal/core/adt.runTask.func1()
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/sched.go:692 +0xa4
panic({0x100f53d00?, 0x101548f10?})
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/go/src/runtime/panic.go:914 +0x218
cuelang.org/go/internal/core/adt.equalTerminal(0x140090448e8?, {0x10103d240?, 0x0?}, {0x10103d240?, 0x140116afd70?}, 0xfd70?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/equality.go:194 +0x17c
cuelang.org/go/internal/core/adt.Equal(0x0?, {0x10103d240?, 0x0?}, {0x10103d240?, 0x140116afd70?}, 0x9080?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/equality.go:37 +0x84
cuelang.org/go/internal/core/adt.isEqualBaseValue(0x0?, {0x101030f00?, 0x0?}, {0x101030f00?, 0x140116afd70})
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/disjunct2.go:762 +0xac
cuelang.org/go/internal/core/adt.isEqualNodeValue(0x1400f826c00, 0x1400f827800)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/disjunct2.go:721 +0x114
cuelang.org/go/internal/core/adt.equalPartialNode(0x14009044f18?, 0x14011521680, 0x1401152c1e0)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/disjunct2.go:635 +0x74
cuelang.org/go/internal/core/adt.appendDisjunct(0x1400f826600?, {0x1400ab41ac0?, 0x2, 0x2}, 0x1400f827800)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/disjunct2.go:542 +0x4c8
cuelang.org/go/internal/core/adt.(*nodeContext).crossProduct(0x1400f4aec00, {0x14009044f18?, 0x14009044eb8?, 0x1008c34c0?}, {0x1400ab41a50, 0x2, 0x14012cf8d20?}, 0x140000b6e70, 0xb8?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/disjunct2.go:357 +0x38c
cuelang.org/go/internal/core/adt.(*nodeContext).processDisjunctions(0x1400f4aec00)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/disjunct2.go:279 +0x118
cuelang.org/go/internal/core/adt.processDisjunctions(0x100d561ff?, 0x14012df7400, 0x86?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/tasks.go:189 +0x24
cuelang.org/go/internal/core/adt.runTask(0x14012df7400, 0x80?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/sched.go:712 +0x430
cuelang.org/go/internal/core/adt.(*scheduler).process(0x1400f4aedd0, 0x7eff, 0x4)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/sched.go:411 +0x1dc
cuelang.org/go/internal/core/adt.(*Vertex).unify(0x14012d14b40, 0x14000359080, 0x7fff, 0x4)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/unify.go:159 +0x224
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0x1400f476000, 0x7e05?, 0x4?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/unify.go:503 +0x1e8
cuelang.org/go/internal/core/adt.(*Vertex).unify(0x14012cf8d20, 0x14000359080, 0x7fff, 0x4)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/unify.go:226 +0x758
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0x1400dfd8600, 0x7e05?, 0x4?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/unify.go:503 +0x1e8
cuelang.org/go/internal/core/adt.(*Vertex).unify(0x14011cb6640, 0x14000359080, 0x7fff, 0x4)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/unify.go:226 +0x758
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0x1400d6e6c00, 0x7e05?, 0x4?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/unify.go:503 +0x1e8
cuelang.org/go/internal/core/adt.(*Vertex).unify(0x1401171b040, 0x14000359080, 0x7fff, 0x4)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/unify.go:226 +0x758
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0x14011ced200, 0x7e05?, 0x4?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/unify.go:503 +0x1e8
cuelang.org/go/internal/core/adt.(*Vertex).unify(0x14011cd9900, 0x14000359080, 0x7fff, 0x4)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/unify.go:226 +0x758
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0x14011cea000, 0x7e05?, 0x4?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/unify.go:503 +0x1e8
cuelang.org/go/internal/core/adt.(*Vertex).unify(0x14011cd9220, 0x14000359080, 0x7fff, 0x4)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/unify.go:226 +0x758
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0x14011ce7800, 0x7e05?, 0x4?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/unify.go:503 +0x1e8
cuelang.org/go/internal/core/adt.(*Vertex).unify(0x14011cd90e0, 0x14000359080, 0x7fff, 0x4)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/unify.go:226 +0x758
cuelang.org/go/internal/core/adt.(*OpContext).unify(0xa0?, 0x101015300?, 0x9046f01?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/eval.go:158 +0x318
cuelang.org/go/internal/core/adt.(*Vertex).Finalize(0x14009047008?, 0x14000359080)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/composite.go:816 +0x58
cuelang.org/go/internal/core/adt.(*BinaryExpr).evaluate(0x1400049bb90, 0x14000359080, 0x49bb90?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/expr.go:1303 +0x170
cuelang.org/go/internal/core/adt.(*OpContext).unifyNode(0x14000359080, {0x101039588, 0x1400049bb90}, 0x410202)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/context.go:834 +0x1ec
cuelang.org/go/internal/core/adt.(*OpContext).node(0x14000359080, {0x101033918?, 0x14000123dc0}, {0x101039588?, 0x1400049bb90?}, 0x1, 0x1?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/context.go:1061 +0x50
cuelang.org/go/internal/core/adt.(*SelectorExpr).resolve(0x14000123dc0, 0x14000359080, 0x11cde780?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/expr.go:1011 +0x6c
cuelang.org/go/internal/core/adt.processResolver(0x14000359080?, 0x14011cd9040, 0x18?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/tasks.go:99 +0x64
cuelang.org/go/internal/core/adt.runTask(0x14011cd9040, 0x80?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/sched.go:712 +0x430
cuelang.org/go/internal/core/adt.(*scheduler).process(0x14011cdb9d0, 0x7eff, 0x4)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/sched.go:411 +0x1dc
cuelang.org/go/internal/core/adt.(*Vertex).unify(0x14011cd8780, 0x14000359080, 0x7fff, 0x4)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/unify.go:159 +0x224
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0x14011cdb200, 0x7e05?, 0x4?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/unify.go:503 +0x1e8
cuelang.org/go/internal/core/adt.(*Vertex).unify(0x14011cd8640, 0x14000359080, 0x7fff, 0x4)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/unify.go:226 +0x758
cuelang.org/go/internal/core/adt.(*OpContext).unify(0xa0?, 0x101015300?, 0x11c6b101?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/eval.go:158 +0x318
cuelang.org/go/internal/core/adt.(*Vertex).CompleteArcs(0x14009048158?, 0x14000359080?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/composite.go:822 +0x30
cuelang.org/go/internal/core/adt.(*BinaryExpr).evaluate(0x1400049bbc0, 0x14000359080, 0x49bbc0?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/expr.go:1305 +0x178
cuelang.org/go/internal/core/adt.(*OpContext).unifyNode(0x14000359080, {0x101039588, 0x1400049bbc0}, 0x410202)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/context.go:834 +0x1ec
cuelang.org/go/internal/core/adt.(*OpContext).node(0x14000359080, {0x101033918?, 0x14000123e40}, {0x101039588?, 0x1400049bbc0?}, 0x1, 0x1?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/context.go:1061 +0x50
cuelang.org/go/internal/core/adt.(*SelectorExpr).resolve(0x14000123e40, 0x14000359080, 0x9048448?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/expr.go:1011 +0x6c
cuelang.org/go/internal/core/adt.processResolver(0x14000359080?, 0x14011cd85a0, 0x18?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/tasks.go:99 +0x64
cuelang.org/go/internal/core/adt.runTask(0x14011cd85a0, 0x80?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/sched.go:712 +0x430
cuelang.org/go/internal/core/adt.(*scheduler).process(0x140003ba1d0, 0x7eff, 0x4)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/sched.go:411 +0x1dc
cuelang.org/go/internal/core/adt.(*Vertex).unify(0x1400033f4a0, 0x14000359080, 0x7fff, 0x4)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/unify.go:159 +0x224
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0x1400033ac00, 0x7e05?, 0x4?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/unify.go:503 +0x1e8
cuelang.org/go/internal/core/adt.(*Vertex).unify(0x1400033f2c0, 0x14000359080, 0x7fff, 0x4)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/unify.go:226 +0x758
cuelang.org/go/internal/core/adt.(*OpContext).unify(0x0?, 0x0?, 0x2b7318?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/eval.go:158 +0x318
cuelang.org/go/internal/core/adt.(*Vertex).Finalize(0x140003b5290?, 0x14000359080)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/internal/core/adt/composite.go:816 +0x58
cuelang.org/go/cue.newVertexRoot(0x140002b73b8?, 0x100613e0c?, 0x14000359080?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/cue/types.go:602 +0x2c
cuelang.org/go/cue.newValueRoot(0x0?, 0x140002b7490?, {0x101039608?, 0x1400033f2c0?})
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/cue/types.go:611 +0x40
cuelang.org/go/cue.(*Context).make(0x14000297640, 0x0?)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/cue/context.go:257 +0x8c
cuelang.org/go/cue.(*Context).BuildInstances(0x14000297640, {0x14009049740, 0x1, 0x1e0?})
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/cue/context.go:152 +0x1ac
cuelang.org/go/cmd/cue/cmd.buildInstances(0x140002e1890, {0x14009049740, 0x1, 0x100f0ff20?}, 0x1)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/cmd/cue/cmd/common.go:710 +0x38
cuelang.org/go/cmd/cue/cmd.parseArgs(0x140002e1890, {0x140002e5600, 0x1, 0x1}, 0x14000295040)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/cmd/cue/cmd/common.go:599 +0xaf8
cuelang.org/go/cmd/cue/cmd.runExport(0x140002e1890, {0x140002e5600, 0x1, 0x1})
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/cmd/cue/cmd/export.go:113 +0x64
cuelang.org/go/cmd/cue/cmd.newExportCmd.mkRunE.func1(0x140001aae00?, {0x140002e5600, 0x1, 0x1})
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/cmd/cue/cmd/root.go:125 +0x200
github.com/spf13/cobra.(*Command).execute(0x1400031d200, {0x140002e55c0, 0x1, 0x1})
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x1400031c300)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0x140002e1890, {0x1015a8440?, 0x100f54c60?})
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/cmd/cue/cmd/root.go:377 +0x28
cuelang.org/go/cmd/cue/cmd.Main()
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/cmd/cue/cmd/root.go:285 +0x9c
main.main()
	/Users/matias.kakela/.local/share/rtx/installs/go/1.21.10/packages/pkg/mod/cuelang.org/go@v0.9.0-rc.1/cmd/cue/main.go:24 +0x1c
```

**Comment by mvdan** [comment]
@massive could you share what CUE code you used to reproduce this panic, so that we may also reproduce it and investigate a fix? If this is code that you cannot share publicly, you can also share it with me privately.

**Comment by massive** [comment]
Shared privately

**Comment by mvdan** [comment]
Thanks @massive! I have been able to reduce the reproducer to 13 lines:

```
#Player: {
	level: *0 | >10
} & {
	level: *0 | >10
}

{
	out: (close({
		player: #Player
	}) & {
		player: #Player
	})
}.out
```

I am struggling to reduce it further. I will leave it to @mpvl from here.
