### ISSUE TITLE
evalv3: panic: inconsistent state: nodes differ

### ISSUE THREAD

**Issue by jpluscplusm** [cue-lang/cue#3406]
### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.10.0

go version go1.23.0
      -buildmode exe
       -compiler gc
       -trimpath true
     CGO_ENABLED 0
          GOARCH amd64
            GOOS linux
         GOAMD64 v1
cue.lang.version v0.10.0

</pre>

### Does this issue reproduce with the latest stable release?

v0.10.0 is latest.

### What did you do?

I ran `cue vet` and `cue export` on a configuration with the evalv3 experiment enabled.

The configuration is private, and is not currently enrolled in Unity. I can share more details privately if required.

### What did you expect to see?

Both `cue vet` and `cue export` should succeed as happens with the current evaluator.

### What did you see instead?

- `cue vet`:
```
panic: inconsistent state: nodes differ [recovered]
	panic: inconsistent state: nodes differ [recovered]
	panic: inconsistent state: nodes differ

goroutine 1 [running]:
cuelang.org/go/internal/core/adt.runTask.func1()
	cuelang.org/go@v0.10.0/internal/core/adt/sched.go:703 +0x76
panic({0xcf1ec0?, 0xf877f0?})
	runtime/panic.go:785 +0x132
cuelang.org/go/internal/core/adt.runTask.func1()
	cuelang.org/go@v0.10.0/internal/core/adt/sched.go:703 +0x76
panic({0xcf1ec0?, 0xf877f0?})
	runtime/panic.go:785 +0x132
cuelang.org/go/internal/core/adt.(*nodeContext).scheduleConjunct(0xc001c79208, {0xc0006fcaa0, {0xf8e490, 0x1551510}, {0x0, 0xc000c26b40, 0x0, 0x0, 0x0, 0x0, ...}}, ...)
	cuelang.org/go@v0.10.0/internal/core/adt/conjunct.go:93 +0x15e5
cuelang.org/go/internal/core/adt.(*nodeContext).processDisjunctions(0xc001c79208)
	cuelang.org/go@v0.10.0/internal/core/adt/disjunct2.go:293 +0x48d
cuelang.org/go/internal/core/adt.processDisjunctions(0xe24024?, 0xc001c5f0e0, 0x3b?)
	cuelang.org/go@v0.10.0/internal/core/adt/tasks.go:189 +0x1c
cuelang.org/go/internal/core/adt.runTask(0xc001c5f0e0, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/sched.go:723 +0x505
cuelang.org/go/internal/core/adt.(*scheduler).process(0xc001c793d8, 0x7eff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/sched.go:422 +0x226
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc001c5f040, 0xc0002ca180, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:160 +0x2c5
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc001c8f208, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:504 +0x22c
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc001c5efa0, 0xc0002ca180, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:227 +0x8a7
cuelang.org/go/internal/core/adt.(*nodeContext).doDisjunct(0xc001045208, {0xc0004db660, {0xf8e440, 0xc0003d5920}, {0x0, 0xc001c86e10, 0x0, 0x0, 0x0, 0x0, ...}}, ...)
	cuelang.org/go@v0.10.0/internal/core/adt/disjunct2.go:441 +0x58b
cuelang.org/go/internal/core/adt.(*nodeContext).crossProduct(0xc000922008, {0xc0014b6d88?, 0xc0009de090?, 0xc00090d360?}, {0xc00199b688, 0x63, 0xc00089bf80?}, 0xc000c32388, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/disjunct2.go:345 +0x3c5
cuelang.org/go/internal/core/adt.(*nodeContext).processDisjunctions(0xc000922008)
	cuelang.org/go@v0.10.0/internal/core/adt/disjunct2.go:279 +0x16b
cuelang.org/go/internal/core/adt.processDisjunctions(0xe24024?, 0xc000c24460, 0x3b?)
	cuelang.org/go@v0.10.0/internal/core/adt/tasks.go:189 +0x1c
cuelang.org/go/internal/core/adt.runTask(0xc000c24460, 0x2)
	cuelang.org/go@v0.10.0/internal/core/adt/sched.go:723 +0x505
cuelang.org/go/internal/core/adt.(*scheduler).process(0xc0009221d8, 0x24, 0x2)
	cuelang.org/go@v0.10.0/internal/core/adt/sched.go:422 +0x226
cuelang.org/go/internal/core/adt.(*nodeContext).completeNodeTasks(0xc000922008, 0x2)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:391 +0x16b
cuelang.org/go/internal/core/adt.runTask.func1()
	cuelang.org/go@v0.10.0/internal/core/adt/sched.go:689 +0x30
cuelang.org/go/internal/core/adt.runTask(0xc000c240a0, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/sched.go:745 +0x6bf
cuelang.org/go/internal/core/adt.(*scheduler).process(0xc0009221d8, 0x7eff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/sched.go:422 +0x226
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc00090d2c0, 0xc0002ca180, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:160 +0x2c5
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc00091ec08, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:504 +0x22c
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc000665040, 0xc0002ca180, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:227 +0x8a7
cuelang.org/go/internal/core/adt.(*OpContext).unify(0xd18240?, 0x438508?, 0xd18240?)
	cuelang.org/go@v0.10.0/internal/core/adt/eval.go:158 +0x339
cuelang.org/go/internal/core/adt.(*Vertex).Finalize(0xc000662608?, 0xc0002ca180)
	cuelang.org/go@v0.10.0/internal/core/adt/composite.go:822 +0x59
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc000561ea0, 0xc0002ca180, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:326 +0xcd3
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc0005e4c08, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:504 +0x22c
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc000560e60, 0xc0002ca180, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:227 +0x8a7
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc000559808, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:504 +0x22c
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc000560c80, 0xc0002ca180, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:227 +0x8a7
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc000539208, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:504 +0x22c
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc0002357c0, 0xc0002ca180, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:227 +0x8a7
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc000538008, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:504 +0x22c
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc0002354a0, 0xc0002ca180, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:227 +0x8a7
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc000226608, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:504 +0x22c
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc0002345a0, 0xc0002ca180, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:227 +0x8a7
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc000208008, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:504 +0x22c
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc000234500, 0xc0002ca180, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:227 +0x8a7
cuelang.org/go/internal/core/adt.(*OpContext).unify(0x41b236?, 0x157a360?, 0x9176a8?)
	cuelang.org/go@v0.10.0/internal/core/adt/eval.go:158 +0x339
cuelang.org/go/internal/core/adt.(*Vertex).Finalize(0x0?, 0xc0002ca180)
	cuelang.org/go@v0.10.0/internal/core/adt/composite.go:822 +0x59
cuelang.org/go/cue.newVertexRoot(0xc0000dac00, 0x0?, 0xc000234500)
	cuelang.org/go@v0.10.0/cue/types.go:602 +0x25
cuelang.org/go/cue.newValueRoot(0x0?, 0xc000917768?, {0xf960a0?, 0xc000234500?})
	cuelang.org/go@v0.10.0/cue/types.go:611 +0x3e
cuelang.org/go/cue.(*Context).make(0xc0000dac00, 0xc000234500)
	cuelang.org/go@v0.10.0/cue/context.go:252 +0x79
cuelang.org/go/cue.(*Context).BuildInstances(0xc0000dac00, {0xc00025c528, 0x1, 0x0?})
	cuelang.org/go@v0.10.0/cue/context.go:150 +0x1e5
cuelang.org/go/cmd/cue/cmd.buildInstances(0xc0000e13b0, {0xc00025c528, 0x1, 0xc0000c3930?}, 0x0)
	cuelang.org/go@v0.10.0/cmd/cue/cmd/common.go:724 +0x46
cuelang.org/go/cmd/cue/cmd.(*buildPlan).instances(0xc0000f7ba0)
	cuelang.org/go@v0.10.0/cmd/cue/cmd/common.go:138 +0x105
cuelang.org/go/cmd/cue/cmd.doVet(0xc0000e13b0, {0xc00004fab0, 0x1, 0x1})
	cuelang.org/go@v0.10.0/cmd/cue/cmd/vet.go:108 +0x98
cuelang.org/go/cmd/cue/cmd.newVetCmd.mkRunE.func1(0xc0000e3000?, {0xc00004fab0, 0x1, 0x1})
	cuelang.org/go@v0.10.0/cmd/cue/cmd/root.go:136 +0x2c2
github.com/spf13/cobra.(*Command).execute(0xc000330908, {0xc00004fa70, 0x1, 0x1})
	github.com/spf13/cobra@v1.8.1/command.go:985 +0xaaa
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000f0308)
	github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.1/command.go:1041
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc0000e13b0, {0x1578b80?, 0xd3b2a0?})
	cuelang.org/go@v0.10.0/cmd/cue/cmd/root.go:401 +0x1f
cuelang.org/go/cmd/cue/cmd.Main()
	cuelang.org/go@v0.10.0/cmd/cue/cmd/root.go:309 +0x95
main.main()
	cuelang.org/go@v0.10.0/cmd/cue/main.go:24 +0x13
```

- `cue export`:
```
panic: inconsistent state: nodes differ [recovered]
	panic: inconsistent state: nodes differ [recovered]
	panic: inconsistent state: nodes differ

goroutine 1 [running]:
cuelang.org/go/internal/core/adt.runTask.func1()
	cuelang.org/go@v0.10.0/internal/core/adt/sched.go:703 +0x76
panic({0xcf1ec0?, 0xf877f0?})
	runtime/panic.go:785 +0x132
cuelang.org/go/internal/core/adt.runTask.func1()
	cuelang.org/go@v0.10.0/internal/core/adt/sched.go:703 +0x76
panic({0xcf1ec0?, 0xf877f0?})
	runtime/panic.go:785 +0x132
cuelang.org/go/internal/core/adt.(*nodeContext).scheduleConjunct(0xc001ee7208, {0xc000777b60, {0xf8e490, 0x1551510}, {0x0, 0xc000c31a40, 0x0, 0x0, 0x0, 0x0, ...}}, ...)
	cuelang.org/go@v0.10.0/internal/core/adt/conjunct.go:93 +0x15e5
cuelang.org/go/internal/core/adt.(*nodeContext).processDisjunctions(0xc001ee7208)
	cuelang.org/go@v0.10.0/internal/core/adt/disjunct2.go:293 +0x48d
cuelang.org/go/internal/core/adt.processDisjunctions(0xe24024?, 0xc001ed4e60, 0x3b?)
	cuelang.org/go@v0.10.0/internal/core/adt/tasks.go:189 +0x1c
cuelang.org/go/internal/core/adt.runTask(0xc001ed4e60, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/sched.go:723 +0x505
cuelang.org/go/internal/core/adt.(*scheduler).process(0xc001ee73d8, 0x7eff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/sched.go:422 +0x226
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc001ed4dc0, 0xc0002ea180, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:160 +0x2c5
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc001efb208, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:504 +0x22c
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc001ed4d20, 0xc0002ea180, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:227 +0x8a7
cuelang.org/go/internal/core/adt.(*nodeContext).doDisjunct(0xc001741208, {0xc0004a0aa0, {0xf8e440, 0xc0004acdb0}, {0x0, 0xc001ef7860, 0x0, 0x0, 0x0, 0x0, ...}}, ...)
	cuelang.org/go@v0.10.0/internal/core/adt/disjunct2.go:441 +0x58b
cuelang.org/go/internal/core/adt.(*nodeContext).crossProduct(0xc00085e008, {0xc00169f688?, 0xc00078cab0?, 0xc00083b400?}, {0xc001c26008, 0x63, 0xc0007d5f80?}, 0xc000c3e388, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/disjunct2.go:345 +0x3c5
cuelang.org/go/internal/core/adt.(*nodeContext).processDisjunctions(0xc00085e008)
	cuelang.org/go@v0.10.0/internal/core/adt/disjunct2.go:279 +0x16b
cuelang.org/go/internal/core/adt.processDisjunctions(0xe24024?, 0xc000c2e500, 0x3b?)
	cuelang.org/go@v0.10.0/internal/core/adt/tasks.go:189 +0x1c
cuelang.org/go/internal/core/adt.runTask(0xc000c2e500, 0x2)
	cuelang.org/go@v0.10.0/internal/core/adt/sched.go:723 +0x505
cuelang.org/go/internal/core/adt.(*scheduler).process(0xc00085e1d8, 0x24, 0x2)
	cuelang.org/go@v0.10.0/internal/core/adt/sched.go:422 +0x226
cuelang.org/go/internal/core/adt.(*nodeContext).completeNodeTasks(0xc00085e008, 0x2)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:391 +0x16b
cuelang.org/go/internal/core/adt.runTask.func1()
	cuelang.org/go@v0.10.0/internal/core/adt/sched.go:689 +0x30
cuelang.org/go/internal/core/adt.runTask(0xc000c2e140, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/sched.go:745 +0x6bf
cuelang.org/go/internal/core/adt.(*scheduler).process(0xc00085e1d8, 0x7eff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/sched.go:422 +0x226
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc00083b360, 0xc0002ea180, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:160 +0x2c5
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc000856c08, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:504 +0x22c
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc00022f0e0, 0xc0002ea180, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:227 +0x8a7
cuelang.org/go/internal/core/adt.(*OpContext).unify(0xd18240?, 0x438508?, 0xd18240?)
	cuelang.org/go@v0.10.0/internal/core/adt/eval.go:158 +0x339
cuelang.org/go/internal/core/adt.(*Vertex).Finalize(0xc0008b6608?, 0xc0002ea180)
	cuelang.org/go@v0.10.0/internal/core/adt/composite.go:822 +0x59
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc00088dd60, 0xc0002ea180, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:326 +0xcd3
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc00089ec08, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:504 +0x22c
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc00088cd20, 0xc0002ea180, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:227 +0x8a7
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc000881808, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:504 +0x22c
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc00088cb40, 0xc0002ea180, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:227 +0x8a7
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc00078b208, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:504 +0x22c
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc0000c8c80, 0xc0002ea180, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:227 +0x8a7
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc00078a008, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:504 +0x22c
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc0000c8820, 0xc0002ea180, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:227 +0x8a7
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc00076a608, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:504 +0x22c
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc00013f540, 0xc0002ea180, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:227 +0x8a7
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc00076a008, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:504 +0x22c
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc00013f4a0, 0xc0002ea180, 0x7fff, 0x4)
	cuelang.org/go@v0.10.0/internal/core/adt/unify.go:227 +0x8a7
cuelang.org/go/internal/core/adt.(*OpContext).unify(0x41b236?, 0x157a360?, 0x5b96d8?)
	cuelang.org/go@v0.10.0/internal/core/adt/eval.go:158 +0x339
cuelang.org/go/internal/core/adt.(*Vertex).Finalize(0x0?, 0xc0002ea180)
	cuelang.org/go@v0.10.0/internal/core/adt/composite.go:822 +0x59
cuelang.org/go/cue.newVertexRoot(0xc000306400, 0x0?, 0xc00013f4a0)
	cuelang.org/go@v0.10.0/cue/types.go:602 +0x25
cuelang.org/go/cue.newValueRoot(0x0?, 0xc0005b9798?, {0xf960a0?, 0xc00013f4a0?})
	cuelang.org/go@v0.10.0/cue/types.go:611 +0x3e
cuelang.org/go/cue.(*Context).make(0xc000306400, 0xc00013f4a0)
	cuelang.org/go@v0.10.0/cue/context.go:252 +0x79
cuelang.org/go/cue.(*Context).BuildInstances(0xc000306400, {0xc0005481e0, 0x1, 0x15793c0?})
	cuelang.org/go@v0.10.0/cue/context.go:150 +0x1e5
cuelang.org/go/cmd/cue/cmd.buildInstances(0xc0002f5c20, {0xc0005481e0, 0x1, 0x414018?}, 0x0)
	cuelang.org/go@v0.10.0/cmd/cue/cmd/common.go:724 +0x46
cuelang.org/go/cmd/cue/cmd.(*buildPlan).instances(0xc00032eea0)
	cuelang.org/go@v0.10.0/cmd/cue/cmd/common.go:138 +0x105
cuelang.org/go/cmd/cue/cmd.runExport(0xc0002f5c20, {0xc0002731a0, 0x1, 0x1})
	cuelang.org/go@v0.10.0/cmd/cue/cmd/export.go:123 +0xd7
cuelang.org/go/cmd/cue/cmd.newExportCmd.mkRunE.func1(0xc000226c00?, {0xc0002731a0, 0x1, 0x1})
	cuelang.org/go@v0.10.0/cmd/cue/cmd/root.go:136 +0x2c2
github.com/spf13/cobra.(*Command).execute(0xc0002ff208, {0xc000273160, 0x1, 0x1})
	github.com/spf13/cobra@v1.8.1/command.go:985 +0xaaa
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002fe308)
	github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.1/command.go:1041
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc0002f5c20, {0x1578b80?, 0xd3b2a0?})
	cuelang.org/go@v0.10.0/cmd/cue/cmd/root.go:401 +0x1f
cuelang.org/go/cmd/cue/cmd.Main()
	cuelang.org/go@v0.10.0/cmd/cue/cmd/root.go:309 +0x95
main.main()
	cuelang.org/go@v0.10.0/cmd/cue/main.go:24 +0x13
```

**Comment by mvdan** [comment]
Reduced the private code in about thirty minutes:

```
env CUE_EXPERIMENT=
exec cue export input.cue
cmp stdout export.stdout

env CUE_EXPERIMENT=evalv3
exec cue export input.cue
cmp stdout export.stdout

-- input.cue --
out: #def1 & { #def1 }

#def1: {
	#def2
	obj?: {
		kind!: "foo"
	} | close({
		kind!: "bar"
	})
}

#def2: {
	obj?: {
		kind?: "foo" | "bar"
	}
}
-- export.stdout --
{
    "out": {}
}
```

The testscript above should succeed, but it fails:

```
> exec cue export input.cue
[stderr]
panic: inconsistent state: nodes differ [recovered]
	panic: inconsistent state: nodes differ [recovered]
	panic: inconsistent state: nodes differ

goroutine 1 gp=0xc000002380 m=7 mp=0xc000500008 [running]:
panic({0xcd7540?, 0xf6bf00?})
	/home/mvdan/tip/src/runtime/panic.go:804 +0x168 fp=0xc000379480 sp=0xc0003793d0 pc=0x472788
cuelang.org/go/internal/core/adt.runTask.func1()
	/home/mvdan/src/c/cue/internal/core/adt/sched.go:695 +0x76 fp=0xc0003794a8 sp=0xc000379480 pc=0x727db6
panic({0xcd7540?, 0xf6bf00?})
	/home/mvdan/tip/src/runtime/panic.go:785 +0x132 fp=0xc000379558 sp=0xc0003794a8 pc=0x472752
cuelang.org/go/internal/core/adt.runTask.func1()
	/home/mvdan/src/c/cue/internal/core/adt/sched.go:695 +0x76 fp=0xc000379580 sp=0xc000379558 pc=0x727db6
panic({0xcd7540?, 0xf6bf00?})
	/home/mvdan/tip/src/runtime/panic.go:785 +0x132 fp=0xc000379630 sp=0xc000379580 pc=0x472752
cuelang.org/go/internal/core/adt.(*nodeContext).scheduleConjunct(0xc000124608, {0xc0003d4c20, {0xf72c30, 0x15377d0}, {0x0, 0xc000119680, 0x0, 0x0, 0x0, 0x0, ...}}, ...)
	/home/mvdan/src/c/cue/internal/core/adt/conjunct.go:93 +0x15e5 fp=0xc000379898 sp=0xc000379630 pc=0x6e6a05
cuelang.org/go/internal/core/adt.(*nodeContext).processDisjunctions(0xc000124608)
	/home/mvdan/src/c/cue/internal/core/adt/disjunct2.go:293 +0x478 fp=0xc000379a08 sp=0xc000379898 pc=0x6fe878
cuelang.org/go/internal/core/adt.processDisjunctions(0xe09627?, 0xc000117220, 0xa5?)
	/home/mvdan/src/c/cue/internal/core/adt/tasks.go:189 +0x1c fp=0xc000379a48 sp=0xc000379a08 pc=0x72a73c
cuelang.org/go/internal/core/adt.runTask(0xc000117220, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/sched.go:715 +0x545 fp=0xc000379c60 sp=0xc000379a48 pc=0x727925
cuelang.org/go/internal/core/adt.(*scheduler).process(0xc0001247d8, 0x7eff, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/sched.go:408 +0x21f fp=0xc000379d30 sp=0xc000379c60 pc=0x726bff
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc000117180, 0xc0000e2480, 0x7fff, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/unify.go:160 +0x2bf fp=0xc000379f78 sp=0xc000379d30 pc=0x72c5ff
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc000124c08, 0x7fff, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/unify.go:504 +0x22c fp=0xc00037a020 sp=0xc000379f78 pc=0x72dd8c
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc0001170e0, 0xc0000e2480, 0x7fff, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/unify.go:227 +0x8a6 fp=0xc00037a268 sp=0xc00037a020 pc=0x72cbe6
cuelang.org/go/internal/core/adt.(*nodeContext).doDisjunct(0xc00011ac08, {0xc0003d40c0, {0xf72be0, 0xc000412600}, {0x0, 0xc0001280f0, 0x0, 0x0, 0x0, 0x0, ...}}, ...)
	/home/mvdan/src/c/cue/internal/core/adt/disjunct2.go:441 +0x585 fp=0xc00037a478 sp=0xc00037a268 pc=0x6ff605
cuelang.org/go/internal/core/adt.(*nodeContext).crossProduct(0xc000114c08, {0xc00037a780?, 0xc00001ee10?, 0xc0000e2480?}, {0xc00003f070, 0x2, 0xc00003ff80?}, 0xc0000005b0, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/disjunct2.go:345 +0x3c5 fp=0xc00037a630 sp=0xc00037a478 pc=0x6fecc5
cuelang.org/go/internal/core/adt.(*nodeContext).processDisjunctions(0xc000114c08)
	/home/mvdan/src/c/cue/internal/core/adt/disjunct2.go:279 +0x165 fp=0xc00037a7a0 sp=0xc00037a630 pc=0x6fe565
cuelang.org/go/internal/core/adt.processDisjunctions(0xe09627?, 0xc000116460, 0xa5?)
	/home/mvdan/src/c/cue/internal/core/adt/tasks.go:189 +0x1c fp=0xc00037a7e0 sp=0xc00037a7a0 pc=0x72a73c
cuelang.org/go/internal/core/adt.runTask(0xc000116460, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/sched.go:715 +0x545 fp=0xc00037a9f8 sp=0xc00037a7e0 pc=0x727925
cuelang.org/go/internal/core/adt.(*scheduler).process(0xc000114dd8, 0x7eff, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/sched.go:408 +0x21f fp=0xc00037aac8 sp=0xc00037a9f8 pc=0x726bff
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc000116140, 0xc0000e2480, 0x7fff, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/unify.go:160 +0x2bf fp=0xc00037ad10 sp=0xc00037aac8 pc=0x72c5ff
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc00001d808, 0x7fff, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/unify.go:504 +0x22c fp=0xc00037adb8 sp=0xc00037ad10 pc=0x72dd8c
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc0004f7cc0, 0xc0000e2480, 0x7fff, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/unify.go:227 +0x8a6 fp=0xc00037b000 sp=0xc00037adb8 pc=0x72cbe6
cuelang.org/go/internal/core/adt.(*nodeContext).completeAllArcs(0xc00001d208, 0x7fff, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/unify.go:504 +0x22c fp=0xc00037b0a8 sp=0xc00037b000 pc=0x72dd8c
cuelang.org/go/internal/core/adt.(*Vertex).unify(0xc0004f7c20, 0xc0000e2480, 0x7fff, 0x4)
	/home/mvdan/src/c/cue/internal/core/adt/unify.go:227 +0x8a6 fp=0xc00037b2f0 sp=0xc00037b0a8 pc=0x72cbe6
cuelang.org/go/internal/core/adt.(*OpContext).unify(0x90?, 0xf728f8?, 0x37b5f0?)
	/home/mvdan/src/c/cue/internal/core/adt/eval.go:158 +0x339 fp=0xc00037b540 sp=0xc00037b2f0 pc=0x7047d9
cuelang.org/go/internal/core/adt.(*Vertex).Finalize(0x0?, 0xc0000e2480)
	/home/mvdan/src/c/cue/internal/core/adt/composite.go:821 +0x59 fp=0xc00037b570 sp=0xc00037b540 pc=0x6df419
cuelang.org/go/cue.newVertexRoot(0xc000265400, 0x1?, 0xc0004f7c20)
	/home/mvdan/src/c/cue/cue/types.go:602 +0x25 fp=0xc00037b598 sp=0xc00037b570 pc=0x94c0c5
cuelang.org/go/cue.newValueRoot(0x0?, 0xc00037b6b0?, {0xf7aa60?, 0xc0004f7c20?})
	/home/mvdan/src/c/cue/cue/types.go:611 +0x3e fp=0xc00037b670 sp=0xc00037b598 pc=0x94c15e
cuelang.org/go/cue.(*Context).make(0xc000265400, 0xc0004f7c20)
	/home/mvdan/src/c/cue/cue/context.go:252 +0x79 fp=0xc00037b6d8 sp=0xc00037b670 pc=0x93b439
cuelang.org/go/cue.(*Context).BuildInstances(0xc000265400, {0xc00037b980, 0x1, 0x1e0?})
	/home/mvdan/src/c/cue/cue/context.go:150 +0x1e5 fp=0xc00037b788 sp=0xc00037b6d8 pc=0x93a745
[...]
```

**Comment by mvdan** [comment]
Note that it's possible it can be reduced a bit further, but I think this is small enough for now, and it's the end of the week :)

**Comment by mpvl** [comment]
The panic is non-critical. There are some known (esoteric) bugs in this code, so I'll disable it for now.

**Comment by mvdan** [comment]
That sounds fine for now, as long as we add a regression test.
