### ISSUE TITLE
cmd/cue: fmt panics on unrecognized import

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#447]
_Originally opened by @robfig in https://github.com/cuelang/cue/issues/447_

### What version of CUE are you using (`cue version`)?

This happens on 0.2 and master.

<pre>
$ cd gocode/src/cuelang.org/go/ && git log -1 --oneline
f01cfc5 (HEAD -> master, origin/master, origin/HEAD) pkg/strings: add SliceRunes
</pre>

### What did you do?

Running `cue fmt` on files with an import that can not be resolved results in a panic. We use the bazel rules, so we do not expect cue cli to resolve our imports, yet we'd still like to have a way to format our cue files. 

```
$ cue fmt gocode/src/corp/graph/mergetest/testdata/case_redo.cue
<nil>
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x11f7cba]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc000117ec0)
	/Users/robfig/alpha/gocode/src/cuelang.org/go/cmd/cue/cmd/root.go:221 +0xa3
panic(0x17b2060, 0x1ed5270)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:969 +0x166
golang.org/x/xerrors.As(0x0, 0x0, 0x1753f80, 0xc000467780, 0xc0001176d8)
	/Users/robfig/alpha/gocode/src/golang.org/x/xerrors/wrap.go:92 +0x20a
cuelang.org/go/cue/errors.Path(0x0, 0x0, 0xc000467770, 0x180b280, 0xc000473e60)
	/Users/robfig/alpha/gocode/src/cuelang.org/go/cue/errors/errors.go:130 +0xe0
cuelang.org/go/cue/errors.(*posError).Path(0xc000473e60, 0xc000473e60, 0x1753f80, 0xc000467770)
	/Users/robfig/alpha/gocode/src/cuelang.org/go/cue/errors/errors.go:179 +0x38
cuelang.org/go/cue/errors.Path(0x2659148, 0xc000473e60, 0x2059108, 0x0, 0x48)
	/Users/robfig/alpha/gocode/src/cuelang.org/go/cue/errors/errors.go:131 +0xfd
cuelang.org/go/cue/errors.(*posError).Path(0xc000473ec0, 0x17d8180, 0x180b280, 0x19bbbc0)
	/Users/robfig/alpha/gocode/src/cuelang.org/go/cue/errors/errors.go:179 +0x38
cuelang.org/go/cue/errors.writeErr(0x19a8a80, 0xc00001c330, 0x19bbbc0, 0xc000473ec0)
	/Users/robfig/alpha/gocode/src/cuelang.org/go/cue/errors/errors.go:482 +0x3b
cuelang.org/go/cue/errors.printError(0x19a8a80, 0xc00001c330, 0x2659148, 0xc000473ec0, 0xc000117ab0)
	/Users/robfig/alpha/gocode/src/cuelang.org/go/cue/errors/errors.go:556 +0x4dd
cuelang.org/go/cue/errors.Print(0x19a8a80, 0xc00001c330, 0x2659148, 0xc000473ec0, 0xc000117ab0)
	/Users/robfig/alpha/gocode/src/cuelang.org/go/cue/errors/errors.go:462 +0x129
cuelang.org/go/cmd/cue/cmd.exitOnErr(0xc000366420, 0x2659148, 0xc000473ec0, 0x1)
	/Users/robfig/alpha/gocode/src/cuelang.org/go/cmd/cue/cmd/common.go:88 +0x13b
cuelang.org/go/cmd/cue/cmd.newFmtCmd.func1(0xc000366420, 0xc000370a10, 0x1, 0x1, 0x0, 0x0)
	/Users/robfig/alpha/gocode/src/cuelang.org/go/cmd/cue/cmd/fmt.go:39 +0x105
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc000244dc0, 0xc000370a10, 0x1, 0x1, 0x0, 0x0)
	/Users/robfig/alpha/gocode/src/cuelang.org/go/cmd/cue/cmd/root.go:46 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc000244dc0, 0xc0003709e0, 0x1, 0x1, 0xc000244dc0, 0xc0003709e0)
	/Users/robfig/alpha/gocode/src/github.com/spf13/cobra/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000b58c0, 0x0, 0x0, 0x0)
	/Users/robfig/alpha/gocode/src/github.com/spf13/cobra/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/robfig/alpha/gocode/src/github.com/spf13/cobra/command.go:887
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc000366420, 0x19b96c0, 0xc00003a0a8, 0x0, 0x0)
	/Users/robfig/alpha/gocode/src/cuelang.org/go/cmd/cue/cmd/root.go:206 +0x63
cuelang.org/go/cmd/cue/cmd.mainErr(0x19b96c0, 0xc00003a0a8, 0xc0000320d0, 0x2, 0x2, 0x18bebd8, 0xc000357f48)
	/Users/robfig/alpha/gocode/src/cuelang.org/go/cmd/cue/cmd/root.go:145 +0x88
cuelang.org/go/cmd/cue/cmd.Main(0xc000040118)
	/Users/robfig/alpha/gocode/src/cuelang.org/go/cmd/cue/cmd/root.go:127 +0x9c
main.main()
	/Users/robfig/alpha/gocode/src/cuelang.org/go/cmd/cue/main.go:24 +0x22
```

Modifying the code to print out the error that caused this panic:

```
&errors.posError{pos:token.Pos{file:(*token.File)(nil), offset:0}, inputs:[]token.Pos(nil), Message:errors.Message{format:"cannot find package %!q(MISSING)", args:[]interface {}{"merge.test/lib"}}, err:error(nil)}
```

We use Bazel rules to export our CUE objects, but we have no easy way to format our cue files at the moment. Our current workaround is to modify the exports to be one term instead of two, which allows the fmt to complete successfully.

### What did you expect to see?

The file would ideally be formatted without worrying about whether an import can be resolved. At minimum, an error message should be printed instead of a panic.

### What did you see instead?

A panic

**Comment by cueckoo** [comment]
_Original reply by @robfig in https://github.com/cuelang/cue/issues/447#issuecomment-657722322_

Another detail about the current behavior:

If there's a cue.mod file in testdata/ declaring `module: "merge.test"`, AND `cue fmt` is run from that directory, it formats. But if it's run from outside the directory, it fails in the same way. I think it's surprising that the working directory matters. Perhaps this is enough to script the formatting though.

**Comment by cueckoo** [comment]
_Original reply by @robfig in https://github.com/cuelang/cue/issues/447#issuecomment-657735315_

I apologize, it does not reproduce with 0.2 downloaded binary, and I think this is because of compiling this with an older xerrors version that didn't handle some case. It does print an error instead of format the file, but I can work around that and I suppose it's working as intended. Sorry for the noise.
