### ISSUE TITLE
CUE 0.3 Alpha 1 - error generating code for tekton/pipelines

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#458]
_Originally opened by @ekarlso in https://github.com/cuelang/cue/issues/458_

Trying to **get go** for a golang based project but:

```sh
mkdir test
cd test

export GO111MODULE=on

cat >go.mod<<EOF
module test.foo/bar

go 1.14

require (
        cuelang.org/go v0.2.2 // indirect
        github.com/tektoncd/pipeline v0.14.0 // indirect
        github.com/tektoncd/triggers v0.6.1 // indirect
)

replace (
        ggithub.com/tektoncd/pipeline => ithub.com/tektoncd/pipeline v0.14.0 // indirect
        github.com/tektoncd/triggers => github.com/tektoncd/triggers v0.6.1 // indirect
        k8s.io/api => k8s.io/api v0.17.6
        k8s.io/apiextensions-apiserver => k8s.io/apiextensions-apiserver v0.17.6
        k8s.io/apimachinery => k8s.io/apimachinery v0.17.6
        k8s.io/apiserver => k8s.io/apiserver v0.17.6
        k8s.io/client-go => k8s.io/client-go v0.17.6
        k8s.io/code-generator => k8s.io/code-generator v0.17.6
        k8s.io/kube-openapi => k8s.io/kube-openapi v0.0.0-20200410145947-bcb3869e6f29

)
EOF

cue get go github.com/tektoncd/pipeline/pkg/apis/...
```

```panic: string literal not terminated [recovered]
	panic: string literal not terminated

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc005fbbec0)
	/github/workspace/cmd/cue/cmd/root.go:221 +0xa3
panic(0xbf2e20, 0xc0195d1e60)
	/usr/local/go/src/runtime/panic.go:969 +0x166
cuelang.org/go/cmd/cue/cmd.(*extractor).reportDecl(0xc0341d0fa0, 0xc034151880, 0x0, 0x0, 0x0)
	/github/workspace/cmd/cue/cmd/get_go.go:700 +0x14d7
cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0xc0341d0fa0, 0xc00003a004, 0x46, 0xc000a2fe60, 0x0, 0x0)
	/github/workspace/cmd/cue/cmd/get_go.go:450 +0x14b3
cuelang.org/go/cmd/cue/cmd.extract(0xc000444e20, 0xc0003f1d10, 0x1, 0x1, 0x5e8f60, 0xc00025dc88)
	/github/workspace/cmd/cue/cmd/get_go.go:365 +0x3f1
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc000474dc0, 0xc0003f1d10, 0x1, 0x1, 0x0, 0x0)
	/github/workspace/cmd/cue/cmd/root.go:46 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc000474dc0, 0xc0003f1ce0, 0x1, 0x1, 0xc000474dc0, 0xc0003f1ce0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000b9340, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc000444e20, 0xd9a620, 0xc000038120, 0x0, 0x0)
	/github/workspace/cmd/cue/cmd/root.go:206 +0x63
cuelang.org/go/cmd/cue/cmd.mainErr(0xd9a620, 0xc000038120, 0xc000030090, 0x3, 0x3, 0xca5480, 0xc00025df48)
	/github/workspace/cmd/cue/cmd/root.go:145 +0x88
cuelang.org/go/cmd/cue/cmd.Main(0xc0000421d8)
	/github/workspace/cmd/cue/cmd/root.go:127 +0x9c
main.main()
	/github/workspace/cmd/cue/main.go:24 +0x22
```

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cue/issues/458#issuecomment-666419308_

This should be fixed by https://cue-review.googlesource.com/c/cue/+/6781 - please can you check?

**Comment by cueckoo** [comment]
_Original reply by @ekarlso in https://github.com/cuelang/cue/issues/458#issuecomment-667295973_

```
cue vet -c -v
incomplete
```

At least a

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cue/issues/458#issuecomment-667297800_

Please can you provide full details on what you did to get this error, @ekarlso

**Comment by cueckoo** [comment]
_Original reply by @ekarlso in https://github.com/cuelang/cue/issues/458#issuecomment-667299250_

Wen't into one of my existing cue "workspaces" and ran ```cue vet -c```. The code worked on 0.2.x

**Comment by cueckoo** [comment]
_Original reply by @ekarlso in https://github.com/cuelang/cue/issues/458#issuecomment-667302374_

The code that this happens with is not public sadly and internal to company :)

**Comment by cueckoo** [comment]
_Original reply by @ekarlso in https://github.com/cuelang/cue/issues/458#issuecomment-667307436_

I will split the error out for the incomplete error. For the "cue get go" command it seems your fix is ok @myitcv
