### ISSUE TITLE
cmd/cue: panic where command cmd depends on @tag attribute

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#520]
_Originally opened by @myitcv in https://github.com/cuelang/cue/issues/520_

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +20c637a linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
cue cmd -t greeting=hello prefix

-- cue.mod/module.cue --
module: "mod.com"
-- my_tool.cue --
package tools

import (
	"tool/cli"
)

greeting: string @tag(greeting)

command: prefix: {
	gen: cli.Print & {
		text: greeting
	}
}
```

### What did you expect to see?

Success, with `hello` printed

### What did you see instead?

```
panic: unreachable [recovered]
        panic: unreachable

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc000495ec8)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:221 +0x95
panic(0xb82880, 0xd59510)
        /home/myitcv/gos/src/runtime/panic.go:969 +0x175
cuelang.org/go/internal/core/compile.(*compiler).resolve(0xc00047a3c0, 0xc000357770, 0x10, 0xc508e0)
        /home/myitcv/dev/cuelang/cue/internal/core/compile/compile.go:396 +0x1225
cuelang.org/go/internal/core/compile.(*compiler).expr(0xc00047a3c0, 0xd82a00, 0xc000357770, 0x38, 0x8)
        /home/myitcv/dev/cuelang/cue/internal/core/compile/compile.go:719 +0x68a
cuelang.org/go/internal/core/compile.(*compiler).labeledExpr(0xc00047a3c0, 0xc0001993b0, 0xd6a020, 0xc0001993b0, 0xd82a00, 0xc000357770, 0x5, 0x203000)
        /home/myitcv/dev/cuelang/cue/internal/core/compile/compile.go:708 +0xcf
cuelang.org/go/internal/core/compile.(*compiler).decl(0xc00047a3c0, 0xd81560, 0xc0001993b0, 0xc000165dc0, 0xe0)
        /home/myitcv/dev/cuelang/cue/internal/core/compile/compile.go:480 +0xf8
cuelang.org/go/internal/core/compile.(*compiler).addDecls(0xc00047a3c0, 0xc000298b10, 0xc0002f6f10, 0x1, 0x1)
        /home/myitcv/dev/cuelang/cue/internal/core/compile/compile.go:447 +0xda
cuelang.org/go/internal/core/compile.(*compiler).expr(0xc00047a3c0, 0xd82d00, 0xc000357810, 0xd7d500, 0xc00031c700)
        /home/myitcv/dev/cuelang/cue/internal/core/compile/compile.go:724 +0x16cd
cuelang.org/go/internal/core/compile.(*compiler).expr(0xc00047a3c0, 0xd82820, 0xc000357860, 0x203000, 0xd7f040)
        /home/myitcv/dev/cuelang/cue/internal/core/compile/compile.go:879 +0xcaa
cuelang.org/go/internal/core/compile.(*compiler).labeledExpr(0xc00047a3c0, 0xc000199340, 0xd6a020, 0xc000199340, 0xd82820, 0xc000357860, 0x40f1d0, 0x203000)
        /home/myitcv/dev/cuelang/cue/internal/core/compile/compile.go:708 +0xcf
cuelang.org/go/internal/core/compile.(*compiler).decl(0xc00047a3c0, 0xd81560, 0xc000199340, 0xc000494e40, 0x6fa105)
        /home/myitcv/dev/cuelang/cue/internal/core/compile/compile.go:480 +0xf8
cuelang.org/go/internal/core/compile.(*compiler).addDecls(0xc00047a3c0, 0xc000298ae0, 0xc0002f6f20, 0x1, 0x1)
        /home/myitcv/dev/cuelang/cue/internal/core/compile/compile.go:447 +0xda
cuelang.org/go/internal/core/compile.(*compiler).expr(0xc00047a3c0, 0xd82d00, 0xc000357950, 0x38, 0x8)
        /home/myitcv/dev/cuelang/cue/internal/core/compile/compile.go:724 +0x16cd
cuelang.org/go/internal/core/compile.(*compiler).labeledExpr(0xc00047a3c0, 0xc0001992d0, 0xd6a020, 0xc0001992d0, 0xd82d00, 0xc000357950, 0x0, 0x203000)
        /home/myitcv/dev/cuelang/cue/internal/core/compile/compile.go:708 +0xcf
cuelang.org/go/internal/core/compile.(*compiler).decl(0xc00047a3c0, 0xd81560, 0xc0001992d0, 0xc000198e70, 0x70)
        /home/myitcv/dev/cuelang/cue/internal/core/compile/compile.go:480 +0xf8
cuelang.org/go/internal/core/compile.(*compiler).addDecls(0xc00047a3c0, 0xc000298ab0, 0xc0002f6f00, 0x1, 0x1)
        /home/myitcv/dev/cuelang/cue/internal/core/compile/compile.go:447 +0xda
cuelang.org/go/internal/core/compile.(*compiler).expr(0xc00047a3c0, 0xd82d00, 0xc000356b90, 0x40f1d0, 0xc000079370)
        /home/myitcv/dev/cuelang/cue/internal/core/compile/compile.go:724 +0x16cd
cuelang.org/go/internal/core/compile.(*compiler).labeledExpr(0xc00047a3c0, 0xc000199260, 0xd6a020, 0xc000199260, 0xd82d00, 0xc000356b90, 0x11a0b60, 0x7f76fcb9c108)
        /home/myitcv/dev/cuelang/cue/internal/core/compile/compile.go:708 +0xcf
cuelang.org/go/internal/core/compile.(*compiler).decl(0xc00047a3c0, 0xd81560, 0xc000199260, 0x0, 0x1)
        /home/myitcv/dev/cuelang/cue/internal/core/compile/compile.go:480 +0xf8
cuelang.org/go/internal/core/compile.(*compiler).addDecls(0xc00047a3c0, 0xc000298a20, 0xc0001af5c0, 0x4, 0x4)
        /home/myitcv/dev/cuelang/cue/internal/core/compile/compile.go:447 +0xda
cuelang.org/go/internal/core/compile.(*compiler).compileFiles(0xc00047a3c0, 0xc000206610, 0x1, 0x1, 0x0)
        /home/myitcv/dev/cuelang/cue/internal/core/compile/compile.go:243 +0x52b
cuelang.org/go/internal/core/compile.Files(0xc0004957f8, 0xd7d740, 0xc00031c3e0, 0xc000206610, 0x1, 0x1, 0xc000635cb0, 0xc000000000, 0x0)
        /home/myitcv/dev/cuelang/cue/internal/core/compile/compile.go:55 +0xcb
cuelang.org/go/cue.(*Instance).Build(0xc000478800, 0xc00036e000, 0x1)
        /home/myitcv/dev/cuelang/cue/cue/instance.go:256 +0x11b
cuelang.org/go/cmd/cue/cmd.buildTools(0xc000443dc0, 0xc00041efc0, 0x1, 0x1, 0xc000468610, 0x0, 0x2, 0x2, 0xc0002b7c68, 0xb15b06)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/common.go:608 +0x52a
cuelang.org/go/cmd/cue/cmd.addSubcommands(0xc000443dc0, 0xc000495d88, 0xc0000320b0, 0x4, 0x4, 0xc000000100, 0xc0002b7cd8, 0x467785)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:333 +0x98
cuelang.org/go/cmd/cue/cmd.New(0xc0000320b0, 0x4, 0x4, 0xc000443dc0, 0x0, 0x0)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:250 +0x993
cuelang.org/go/cmd/cue/cmd.mainErr(0xd7aec0, 0xc000036138, 0xc0000320b0, 0x4, 0x4, 0xcbf600, 0xc0002b7f48)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:141 +0x45
cuelang.org/go/cmd/cue/cmd.Main(0xc00007c058)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:127 +0x9c
main.main()
        /home/myitcv/dev/cuelang/cue/cmd/cue/main.go:24 +0x25
```

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/520#issuecomment-693962537_

Fixed with https://cue-review.googlesource.com/c/cue/+/7121.
