### ISSUE TITLE
cmd/cue: panic whilst trying to run a command step that has an error

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#526]
_Originally opened by @myitcv in https://github.com/cuelang/cue/issues/526_

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version +b9b2c54 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

This is a variant on #525, discovered whilst trying to reduce that issue to a minimal repro.

https://gist.github.com/myitcv/12c7317a3d935979a581ce47a8f2adf7

### What did you expect to see?

An error telling me that `test` does not confirm to the `json.#Workflow` schema.

### What did you see instead?

```
panic: runtime error: index out of range [3] with length 1 [recovered]
        panic: runtime error: index out of range [3] with length 1

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc000711ec8)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:221 +0x95
panic(0xc290a0, 0xc000038440)
        /home/myitcv/gos/src/runtime/panic.go:969 +0x175
cuelang.org/go/internal/core/eval.(*acceptor).node(...)
        /home/myitcv/dev/cuelang/cue/internal/core/eval/closed.go:237
cuelang.org/go/internal/core/eval.(*nodeContext).addValueConjunct(0xc0008a5e40, 0xc0003ef720, 0xd82220, 0xc0003c4d58, 0xc000000003)
        /home/myitcv/dev/cuelang/cue/internal/core/eval/eval.go:1219 +0x14dd
cuelang.org/go/internal/core/eval.(*nodeContext).addExprConjunct(0xc0008a5e40, 0xc0003ef720, 0xd705a0, 0xc0003c4d58, 0x3)
        /home/myitcv/dev/cuelang/cue/internal/core/eval/eval.go:925 +0x4aa
cuelang.org/go/internal/core/eval.(*Evaluator).evalVertex(0xc0001ed980, 0xc0003ccaf0, 0xc00063e1b0, 0x70ec04, 0x0, 0x0, 0x0)
        /home/myitcv/dev/cuelang/cue/internal/core/eval/eval.go:403 +0x1f9
cuelang.org/go/internal/core/eval.(*Evaluator).UnifyAccept(0xc0001ed980, 0xc0003ccaf0, 0xc00063e1b0, 0x6d9504, 0x0, 0x0)
        /home/myitcv/dev/cuelang/cue/internal/core/eval/eval.go:265 +0x88
cuelang.org/go/internal/core/eval.(*Evaluator).Unify(0xc0001ed980, 0xc0003ccaf0, 0xc00063e1b0, 0x4)
        /home/myitcv/dev/cuelang/cue/internal/core/eval/eval.go:239 +0x50
cuelang.org/go/internal/core/eval.(*nodeContext).postDisjunct(0xc0008a5ce0)
        /home/myitcv/dev/cuelang/cue/internal/core/eval/eval.go:587 +0x1e9
cuelang.org/go/internal/core/eval.(*nodeContext).updateResult(0xc0008a5ce0, 0xc000164001)
        /home/myitcv/dev/cuelang/cue/internal/core/eval/disjunct.go:130 +0x32
cuelang.org/go/internal/core/eval.(*nodeContext).tryDisjuncts(0xc0008a5ce0, 0xc000364cd0)
        /home/myitcv/dev/cuelang/cue/internal/core/eval/disjunct.go:197 +0x16b
cuelang.org/go/internal/core/eval.(*Evaluator).evalVertex(0xc0001ed980, 0xc0003ccaf0, 0xc0001bf440, 0xc000580004, 0x0, 0x0, 0x0)
        /home/myitcv/dev/cuelang/cue/internal/core/eval/eval.go:431 +0x2d1
cuelang.org/go/internal/core/eval.(*Evaluator).UnifyAccept(0xc0001ed980, 0xc0003ccaf0, 0xc0001bf440, 0xc0001af204, 0x0, 0x0)
        /home/myitcv/dev/cuelang/cue/internal/core/eval/eval.go:265 +0x88
cuelang.org/go/internal/core/eval.(*Evaluator).Unify(0xc0001ed980, 0xc0003ccaf0, 0xc0001bf440, 0xc000164a04)
        /home/myitcv/dev/cuelang/cue/internal/core/eval/eval.go:239 +0x50
cuelang.org/go/internal/core/eval.(*nodeContext).postDisjunct(0xc00035eb00)
        /home/myitcv/dev/cuelang/cue/internal/core/eval/eval.go:587 +0x1e9
cuelang.org/go/internal/core/eval.(*nodeContext).updateResult(0xc00035eb00, 0xc000164a01)
        /home/myitcv/dev/cuelang/cue/internal/core/eval/disjunct.go:130 +0x32
cuelang.org/go/internal/core/eval.(*nodeContext).tryDisjuncts(0xc00035eb00, 0xc0003f3c00)
        /home/myitcv/dev/cuelang/cue/internal/core/eval/disjunct.go:197 +0x16b
cuelang.org/go/internal/core/eval.(*Evaluator).evalVertex(0xc0001ed980, 0xc0003ccaf0, 0xc000164bd0, 0xc000580004, 0x0, 0x0, 0x0)
        /home/myitcv/dev/cuelang/cue/internal/core/eval/eval.go:431 +0x2d1
cuelang.org/go/internal/core/eval.(*Evaluator).UnifyAccept(0xc0001ed980, 0xc0003ccaf0, 0xc000164bd0, 0x6c8404, 0x0, 0x0)
        /home/myitcv/dev/cuelang/cue/internal/core/eval/eval.go:265 +0x88
cuelang.org/go/internal/core/eval.(*Evaluator).Unify(0xc0001ed980, 0xc0003ccaf0, 0xc000164bd0, 0xc000164b04)
        /home/myitcv/dev/cuelang/cue/internal/core/eval/eval.go:239 +0x50
cuelang.org/go/internal/core/eval.(*nodeContext).postDisjunct(0xc00035e9a0)
        /home/myitcv/dev/cuelang/cue/internal/core/eval/eval.go:587 +0x1e9
cuelang.org/go/internal/core/eval.(*nodeContext).updateResult(0xc00035e9a0, 0xc000164b01)
        /home/myitcv/dev/cuelang/cue/internal/core/eval/disjunct.go:130 +0x32
cuelang.org/go/internal/core/eval.(*nodeContext).tryDisjuncts(0xc00035e9a0, 0xc0003f3b00)
        /home/myitcv/dev/cuelang/cue/internal/core/eval/disjunct.go:197 +0x16b
cuelang.org/go/internal/core/eval.(*Evaluator).evalVertex(0xc0001ed980, 0xc0003ccaf0, 0xc000132870, 0xc000020004, 0x0, 0x0, 0x0)
        /home/myitcv/dev/cuelang/cue/internal/core/eval/eval.go:431 +0x2d1
cuelang.org/go/internal/core/eval.(*Evaluator).UnifyAccept(0xc0001ed980, 0xc0003ccaf0, 0xc000132870, 0x4, 0x0, 0x0)
        /home/myitcv/dev/cuelang/cue/internal/core/eval/eval.go:265 +0x88
cuelang.org/go/internal/core/eval.(*Evaluator).Unify(0xc0001ed980, 0xc0003ccaf0, 0xc000132870, 0xc000164b04)
        /home/myitcv/dev/cuelang/cue/internal/core/eval/eval.go:239 +0x50
cuelang.org/go/internal/core/adt.(*Vertex).Finalize(0xc000132870, 0xc0003ccaf0)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/composite.go:320 +0x51
cuelang.org/go/cue.Merge(0xc0003c4dc0, 0x1, 0x1, 0x1)
        /home/myitcv/dev/cuelang/cue/cue/instance.go:236 +0x14e
cuelang.org/go/cmd/cue/cmd.buildTools(0xc000423e00, 0x11d53f8, 0x0, 0x0, 0xc0003fafd0, 0x0, 0x0, 0x2, 0xc000295c68, 0xb16446)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/common.go:608 +0x50f
cuelang.org/go/cmd/cue/cmd.addSubcommands(0xc000423e00, 0xc000711d88, 0xc0000320a0, 0x2, 0x2, 0xc000000100, 0xc000295cd8, 0x467785)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:333 +0x98
cuelang.org/go/cmd/cue/cmd.New(0xc0000320a0, 0x2, 0x2, 0xc000423e00, 0x0, 0x0)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:250 +0x993
cuelang.org/go/cmd/cue/cmd.mainErr(0xd7b1c0, 0xc000036138, 0xc0000320a0, 0x2, 0x2, 0xcbf7c0, 0xc000295f48)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:141 +0x45
cuelang.org/go/cmd/cue/cmd.Main(0xc00007e058)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:127 +0x9c
main.main()
        /home/myitcv/dev/cuelang/cue/cmd/cue/main.go:24 +0x25
```

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/526#issuecomment-694207174_

Reduced to
```
-- x.cue --
package x

test:      #Workflow
#Workflow: "check_run" | [_, ...]

-- x_tool.cue --
package x

command: gengithub: {}
```
It's finalizing cue.Merge that is the issue.
