### ISSUE TITLE
Panic: unimplemented type *cue.mergedValues

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#546]
_Originally opened by @nyarly in https://github.com/cuelang/cue/issues/546_

### What version of CUE are you using (`cue version`)?
cue version 0.2.2 linux/amd64

### Does this issue reproduce with the latest release?

Haven't tried against betas.

### What did you do?

I added `yaml.Marshal(v & {})` to a cue tool.

Whole file:
```
package kustomize

import (
  "path"
	"encoding/yaml"
	"tool/cli"
	"tool/file"
	"tool/exec"
)

kustomization: [
	for k, v in files {
		name:     k
		contents: *yaml.Marshal(v.ops) |
			(*yaml.MarshalStream(v & [...]) |
      (*yaml.Marshal(v & {}) |
        v))
	},
]

command: {
  review: {
    for k, v in kustomization {
      "print_\(v.name)": cli.Print & {
        text: "\(v.name):\n\(v.contents)\n"
      }
    }
  }

  gen: {
    target: string @tag(outdir)

    for k, v in kustomization {
      let Path = path.Clean("\(target)/\(v.name)")
      let Dir = path.Dir(Path)

      "dir_\(Dir)": exec.Run & {
        cmd: [ "mkdir", "-p", Dir ]
      }

      "emit_\(v.name)": file.Create & {
        $after: gen["dir_\(Dir)"]
        filename: Path
        contents: v.contents
      }
    }
  }
}
```

### What did you expect to see?

`cue gen ./...` should have produced `incomplete value 'target' in interpolation`
Supplying -t outdir=/tmp/something should render files into that directory

### What did you see instead
```
panic: unimplemented type *cue.mergedValues [recovered]
        panic: unimplemented type *cue.mergedValues

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc000d29ec0)
        /build/cue/cmd/cue/cmd/root.go:221 +0xa3
panic(0xb6ea00, 0xc00074a070)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.14.6/share/go/src/runtime/panic.go:969 +0x166
cuelang.org/go/cue.(*printer).str(0xc0001592c0, 0xc1cec0, 0xc000455620)
        /build/cue/cue/debug.go:538 +0x477a
cuelang.org/go/cue.(*printer).str(0xc0001592c0, 0xc27900, 0xc001027500)
        /build/cue/cue/debug.go:389 +0xcad
cuelang.org/go/cue.(*printer).str(0xc0001592c0, 0xb60500, 0xc0001592e0)
        /build/cue/cue/debug.go:370 +0x13ca
cuelang.org/go/cue.(*printer).str(0xc0001592c0, 0xc55880, 0xc000568e00)
        /build/cue/cue/debug.go:350 +0x25c
cuelang.org/go/cue.(*context).str(0xc001002840, 0xdb6600, 0xc000568e00, 0xc000ff09e4, 0x5)
        /build/cue/cue/debug.go:35 +0xa1
cuelang.org/go/cue.binOp(0xc001002840, 0xdaf140, 0xc00074a030, 0xc000740001, 0xdb7e20, 0xc0001e3100, 0xdb86a0, 0xc000568e00, 0xdb7620, 0xc000568e00)
        /build/cue/cue/binop.go:79 +0xaca
cuelang.org/go/cue.dist(0xc001002840, 0xc00025bcc0, 0x18601, 0xdb7e20, 0xc0001e3100, 0xc00039a101, 0xdb86a0, 0xc000568e00, 0x0)
        /build/cue/cue/binop.go:176 +0x51e
cuelang.org/go/cue.dist(0xc001002840, 0xc00025bcc0, 0x17e01, 0xdb7e20, 0xc0001e3100, 0x1, 0xdb81a0, 0xc000262b40, 0x78ca01)
        /build/cue/cue/binop.go:171 +0x328
cuelang.org/go/cue.dist(0xc001002840, 0xc00025bcc0, 0xc00001d400, 0xdb81a0, 0xc000230140, 0x7d8001, 0xdb81a0, 0xc000262b40, 0xbe7e01)
        /build/cue/cue/binop.go:160 +0x189
cuelang.org/go/cue.distribute(0xc001002840, 0xdaea80, 0xc000ffd440, 0xdb0001, 0xdb81a0, 0xc000230140, 0xdb81a0, 0xc000262b40, 0xc000d28cd8, 0x78c121)
        /build/cue/cue/binop.go:148 +0xe7
cuelang.org/go/cue.binOp(0xc001002840, 0xdaea80, 0xc000ffd440, 0xdb0001, 0xdb81a0, 0xc000230140, 0xdb81a0, 0xc000262b40, 0xc000216d20, 0xdb6501)
        /build/cue/cue/binop.go:113 +0x761
cuelang.org/go/cue.(*binaryExpr).evalPartial(0xc000ffd440, 0xc001002840, 0x0, 0x0)
        /build/cue/cue/eval.go:634 +0x4c4
cuelang.org/go/cue.resolveReference(0xc001002840, 0xdb5be0, 0xc000ffd440, 0xdb0001, 0xdb7f20)
        /build/cue/cue/eval.go:82 +0x91
cuelang.org/go/cue.(*binaryExpr).evalPartial(0xc000ffd540, 0xc001002840, 0x0, 0x0)
        /build/cue/cue/eval.go:620 +0xad
cuelang.org/go/cue.(*structLit).at(0xc000feeb60, 0xc001002840, 0x3, 0x0, 0xc000d291a0)
        /build/cue/cue/value.go:1074 +0x2ef
cuelang.org/go/cue.(*structLit).iterAt(0xc000feeb60, 0xc001002840, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /build/cue/cue/value.go:1038 +0x123
cuelang.org/go/cue.newChildValue(0xc000d293b0, 0x3, 0xc000197d90, 0x8)
        /build/cue/cue/types.go:631 +0x257
cuelang.org/go/cue.(*structValue).At(0xc000d293b0, 0x3, 0xc0002625f0, 0x10000000000, 0xc000000000, 0xc0002625f0)
        /build/cue/cue/types.go:154 +0x8a
cuelang.org/go/cue.(*validator).walk(0xc000d29480, 0xc0005a7300, 0xc000279bd0, 0x10000000000, 0x0)
        /build/cue/cue/types.go:2089 +0x36d
cuelang.org/go/cue.Value.Validate(0xc0005a7300, 0xc000279bd0, 0x0, 0x0, 0x0, 0xc000279bd0, 0xdb6600)
        /build/cue/cue/types.go:2037 +0xc5
cuelang.org/go/cue.Value.Unify(0xc0005a7300, 0xc000279540, 0xc0005a7300, 0xc0002799a0, 0xc0002799a0, 0xc00022c930)
        /build/cue/cue/types.go:1698 +0x27b
cuelang.org/go/cue.init.2.func1(0xc6c280, 0xc00077d700, 0xc00003d9c1, 0x10, 0xcb62b0, 0x1)
        /build/cue/cue/builtin.go:392 +0x2a3
cuelang.org/go/cmd/cue/cmd.newTask(0xc000ffcf00, 0x3, 0x4, 0xc0005a7300, 0xc000279540, 0xc000fee9a0, 0x200, 0xc72f03)
        /build/cue/cmd/cue/cmd/custom.go:454 +0x21f
cuelang.org/go/cmd/cue/cmd.(*customRunner).insert(0xc00090ed20, 0xc000ffcf00, 0x3, 0x4, 0xc0005a7300, 0xc000279540, 0xb4c)
        /build/cue/cmd/cue/cmd/custom.go:135 +0x5a
cuelang.org/go/cmd/cue/cmd.(*customRunner).getTasks(0xc00090ed20, 0xc0005a7300, 0xc000279540, 0xc000ffcf00, 0x3, 0x4)
        /build/cue/cmd/cue/cmd/custom.go:223 +0x3c7
cuelang.org/go/cmd/cue/cmd.(*customRunner).getTasks(0xc00090ed20, 0xc0005a7300, 0xc00090eeb0, 0xc000d29a28, 0x2, 0x2)
        /build/cue/cmd/cue/cmd/custom.go:232 +0x251
cuelang.org/go/cmd/cue/cmd.executeTasks(0xc0002e6460, 0xc764fe, 0x7, 0x7ffd7cca3877, 0x3, 0xc000398f30, 0x0, 0x0)
        /build/cue/cmd/cue/cmd/custom.go:252 +0x175
cuelang.org/go/cmd/cue/cmd.doTasks(0xc0002e6460, 0xc764fe, 0x7, 0x7ffd7cca3877, 0x3, 0xc000398f30, 0xc000689ca0, 0xc000689ca0)
        /build/cue/cmd/cue/cmd/custom.go:129 +0x67
cuelang.org/go/cmd/cue/cmd.addCustom.func1(0xc0002e6460, 0xc0008841c0, 0x1, 0x1, 0x5eecd0, 0xc000689c88)
        /build/cue/cmd/cue/cmd/custom.go:99 +0x58
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc0000e02c0, 0xc0008841c0, 0x1, 0x1, 0x0, 0x0)
        /build/cue/cmd/cue/cmd/root.go:46 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc0000e02c0, 0xc000884190, 0x1, 0x1, 0xc0000e02c0, 0xc000884190)
        /build/cue/vendor/github.com/spf13/cobra/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000e18c0, 0x0, 0x0, 0x0)
        /build/cue/vendor/github.com/spf13/cobra/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /build/cue/vendor/github.com/spf13/cobra/command.go:887
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc0002e6460, 0xdae900, 0xc000038270, 0x0, 0x0)
        /build/cue/cmd/cue/cmd/root.go:206 +0x63
cuelang.org/go/cmd/cue/cmd.mainErr(0xdae900, 0xc000038270, 0xc0000320a0, 0x2, 0x2, 0xcb5700, 0xc0002d9f48)
        /build/cue/cmd/cue/cmd/root.go:145 +0x88
cuelang.org/go/cmd/cue/cmd.Main(0xc000042358)
        /build/cue/cmd/cue/cmd/root.go:127 +0x9c
main.main()
        /build/cue/cmd/cue/main.go:24 +0x22
```

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/546#issuecomment-701457353_

This code base no longer exists in tip and thus is not fixable.

I cannot reproduce this with the latest release.

Even though v0.3.0 is still alpha, it is getting to a point that it is more solid than v0.2.2, short of a few bugs that prevent me from making it non-alpha/beta.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/546#issuecomment-701457957_

Leaving open until v0.3.0 is non-beta for the sake of discoverability.

**Comment by cueckoo** [comment]
_Original reply by @nyarly in https://github.com/cuelang/cue/issues/546#issuecomment-701471814_

My workaround was:

```
kustomization: [
    for k, v in files {
        name:     k
        contents: *yaml.Marshal(v.ops) |
            (*yaml.MarshalStream(v & [...]) |
      (*(v & string) | yaml.Marshal(v)))
    },
]
```

In other words, I constrained to `string` rather than `{}`.

**Comment by cueckoo** [comment]
_Original reply by @nyarly in https://github.com/cuelang/cue/issues/546#issuecomment-701471853_


Two questions related to this:
is there a better way to express "use the first concrete representation that matches" than this kind of Lisp list of preferred disjunctions?

My first approach to this list comprehension was `for ... { name: ... contents: ... } | { ... } | ....` which threw an error about "multiple list comprehensions aren't implemented yet." For the record, what I went with was better, but I was surprised a disjunction at the list item level threw an error, and that it talked about multiple list comprehensions. I'd've thought that would refer to something like `[ for (k,v), (l,w) in ... ]` which I can also see wanting.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/546#issuecomment-706500302_

That is a strange error indeed. No need to file a bug. That check will soon go away. Most code supports multiple comprehensions now. It is mostly a matter of removing the check and adding tests.

**Comment by rogpeppe** [comment]
I tried to reproduce this issue with the latest version of CUE (commit f207b0b9285ad043221ff9f3c2207d04e8c32cc0) and just got the following error, which looks legit to me:

```
kustomization: reference "files" not found:
    ./x.cue:12:14
```

Here's the testscript example I used:

```
exec cue gen .

-- x.cue --
package kustomize

import (
	"path"
	"encoding/yaml"
	"tool/cli"
	"tool/file"
	"tool/exec"
)

kustomization: [
	for k, v in files {
		name:     k
		contents: *yaml.Marshal(v.ops) |
			(*yaml.MarshalStream(v & [...]) |
			(*yaml.Marshal(v & {}) |
			v))
	},
]

command: {
	review: {
		for k, v in kustomization {
			"print_\(v.name)": cli.Print & {
				text: "\(v.name):\n\(v.contents)\n"
			}
		}
	}

	gen: {
		target: string @tag(outdir)

		for k, v in kustomization {
			let Path = path.Clean("\(target)/\(v.name)")
			let Dir = path.Dir(Path)

			"dir_\(Dir)": exec.Run & {
				cmd: [ "mkdir", "-p", Dir]
			}

			"emit_\(v.name)": file.Create & {
				$after:   gen["dir_\(Dir)"]
				filename: Path
				contents: v.contents
			}
		}
	}
}
```

Looks like this issue can be closed now.
