### ISSUE TITLE
Error when generating code for Tekton components

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#554]
_Originally opened by @ekarlso in https://github.com/cuelang/cue/issues/554_

### What version of CUE are you using (`cue version`)?

```
/cue version
cue version 0.3.0-alpha4 linux/amd64
```

### Does this issue reproduce with the latest release?

Yes and 0.2.x

### What did you do?

Create a go.mod

```
cat >>go.mod<<EOF
go 1.14

require (
	cuelang.org/go v0.2.2 // indirect
	github.com/tektoncd/pipeline v0.17.0 // indirect
	github.com/tektoncd/triggers v0.8.0 // indirect
	k8s.io/api v0.18.8
	k8s.io/apimachinery v0.19.0
	k8s.io/client-go v11.0.1-0.20190805182717-6502b5e7b1b5+incompatible
	k8s.io/code-generator v0.18.8
	k8s.io/kube-openapi v0.0.0-20200410145947-bcb3869e6f29
	knative.dev/pkg v0.0.0-20200922164940-4bf40ad82aab
)

replace (
	k8s.io/api => k8s.io/api v0.18.8
	k8s.io/apiextensions-apiserver => k8s.io/apiextensions-apiserver v0.18.8
	k8s.io/apimachinery => k8s.io/apimachinery v0.18.8
	k8s.io/apiserver => k8s.io/apiserver v0.18.8
	k8s.io/client-go => k8s.io/client-go v0.18.8
	k8s.io/code-generator => k8s.io/code-generator v0.18.8
	k8s.io/kube-openapi => k8s.io/kube-openapi v0.0.0-20200410145947-bcb3869e6f29
)
EOF

export GO1111MODULE=on
go get github.com/tektoncd/pipeline/pkg/apis/...@v0.17.0
go get github.com/tektoncd/triggers/pkg/apis/...@v0.8.0
```

### What did you expect to see?
Code generation going ok

### What did you see instead?

0.3.0-alpha4
```
panic: unimplemented embedding for type *types.Pointer [recovered]
	panic: unimplemented embedding for type *types.Pointer

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc00a60fec0)
	/github/workspace/cmd/cue/cmd/root.go:221 +0x95
panic(0xb85460, 0xc018b56410)
	/usr/local/go/src/runtime/panic.go:969 +0x175
cuelang.org/go/cmd/cue/cmd.(*extractor).addFields(0xc032c697a0, 0xc0351fccf0, 0xc018a9bcc0)
	/github/workspace/cmd/cue/cmd/get_go.go:1083 +0x2017
cuelang.org/go/cmd/cue/cmd.(*extractor).makeType(0xc032c697a0, 0xd75ae0, 0xc0351fccf0, 0xc035588138, 0xd75901)
	/github/workspace/cmd/cue/cmd/get_go.go:981 +0x111c
cuelang.org/go/cmd/cue/cmd.(*extractor).makeField(0xc032c697a0, 0xc034876a40, 0xc, 0x30, 0xd75ae0, 0xc0351fccf0, 0x0, 0x1, 0xc018a96fc0, 0xc030af9c30, ...)
	/github/workspace/cmd/cue/cmd/get_go.go:889 +0x5a
cuelang.org/go/cmd/cue/cmd.(*extractor).reportDecl(0xc032c697a0, 0xc034f84340, 0x1, 0xc018fa52b0, 0x1)
	/github/workspace/cmd/cue/cmd/get_go.go:634 +0x1178
cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0xc032c697a0, 0xc000036004, 0x4, 0xc007b6de60, 0x0, 0x0)
	/github/workspace/cmd/cue/cmd/get_go.go:450 +0x7bc
cuelang.org/go/cmd/cue/cmd.extract(0xc00047ccc0, 0xc0003f1a00, 0x1, 0x1, 0x5fb2a0, 0xc000265c90)
	/github/workspace/cmd/cue/cmd/get_go.go:366 +0x3d5
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc00049cb00, 0xc0003f1a00, 0x1, 0x1, 0x0, 0x0)
	/github/workspace/cmd/cue/cmd/root.go:46 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc00049cb00, 0xc0003f19d0, 0x1, 0x1, 0xc00049cb00, 0xc0003f19d0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000225080, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc00047ccc0, 0xd7ece0, 0xc0000a2030, 0x0, 0x0)
	/github/workspace/cmd/cue/cmd/root.go:206 +0x65
cuelang.org/go/cmd/cue/cmd.mainErr(0xd7ece0, 0xc0000a2030, 0xc0000a6050, 0x3, 0x3, 0xcc23c0, 0xc000265f48)
	/github/workspace/cmd/cue/cmd/root.go:145 +0x8a
cuelang.org/go/cmd/cue/cmd.Main(0xc0000380b8)
	/github/workspace/cmd/cue/cmd/root.go:127 +0x9c
main.main()
	/github/workspace/cmd/cue/main.go:24 +0x25
```

0.2.1 error
```
panic: unimplemented embedding for type *types.Pointer [recovered]
	panic: unimplemented embedding for type *types.Pointer

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc001f6fec0)
	/github/workspace/cmd/cue/cmd/root.go:220 +0xa3
panic(0xb61e20, 0xc02355ccb0)
	/usr/local/go/src/runtime/panic.go:969 +0x166
cuelang.org/go/cmd/cue/cmd.(*extractor).addFields(0xc0336b9360, 0xc034229110, 0xc0180071d0)
	/github/workspace/cmd/cue/cmd/get_go.go:1080 +0x1fed
cuelang.org/go/cmd/cue/cmd.(*extractor).makeType(0xc0336b9360, 0xd93980, 0xc034229110, 0xc03465cee8, 0xd93801)
	/github/workspace/cmd/cue/cmd/get_go.go:978 +0x112c
cuelang.org/go/cmd/cue/cmd.(*extractor).makeField(0xc0336b9360, 0xc033cfed20, 0xc, 0x30, 0xd93980, 0xc034229110, 0x0, 0x1, 0xc017ecda40, 0xc02f471d90, ...)
	/github/workspace/cmd/cue/cmd/get_go.go:899 +0x5a
cuelang.org/go/cmd/cue/cmd.(*extractor).reportDecl(0xc0336b9360, 0xc03400b980, 0x1, 0x1, 0xc02355cbe0)
	/github/workspace/cmd/cue/cmd/get_go.go:645 +0x111f
cuelang.org/go/cmd/cue/cmd.(*extractor).extractPkg(0xc0336b9360, 0xc000036004, 0x4, 0xc000d24480, 0x0, 0x0)
	/github/workspace/cmd/cue/cmd/get_go.go:450 +0x14b3
cuelang.org/go/cmd/cue/cmd.extract(0xc0003e43a0, 0xc0003e8920, 0x1, 0x1, 0x5e5260, 0xc0003d1c88)
	/github/workspace/cmd/cue/cmd/get_go.go:365 +0x3f1
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc0003fb080, 0xc0003e8920, 0x1, 0x1, 0x0, 0x0)
	/github/workspace/cmd/cue/cmd/root.go:46 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc0003fb080, 0xc0003e88f0, 0x1, 0x1, 0xc0003fb080, 0xc0003e88f0)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:838 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000af8c0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc0003e43a0, 0xd9cd00, 0xc000036078, 0x0, 0x0)
	/github/workspace/cmd/cue/cmd/root.go:205 +0x63
cuelang.org/go/cmd/cue/cmd.mainErr(0xd9cd00, 0xc000036078, 0xc000030050, 0x3, 0x3, 0xca54c0, 0xc0003d1f48)
	/github/workspace/cmd/cue/cmd/root.go:144 +0x88
cuelang.org/go/cmd/cue/cmd.Main(0xc0000380b8)
	/github/workspace/cmd/cue/cmd/root.go:126 +0x9c
main.main()
	/github/workspace/cmd/cue/main.go:24 +0x22
```

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/554#issuecomment-705098390_

Analysis: inlined embedded pointer types are not allowed, but should be.
