### ISSUE TITLE
cue def panic when alias are redeclared in the same scope but eval doesn't

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#590]
_Originally opened by @eonpatapon in https://github.com/cuelang/cue/issues/590_

### What version of CUE are you using (`cue version`)?

master (cd621ffa2727a9ba9b20d600cf5bf9593217ed8b)

### What did you do?

```
-- x.cue --
x: string

let X = x

y: X
-- y.cue --
x: "foo"

let X = x

y: X
```

### What did you see?

```
cue eval x.cue y.cue
x: "foo"
y: "foo"
```

```
cue def x.cue y.cue
panic: alias "X" redeclared in same scope [recovered]
	panic: alias "X" redeclared in same scope

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc00017bec0)
	/build/source/cmd/cue/cmd/root.go:221 +0x95
panic(0xc22aa0, 0xc0001a5f80)
	/nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.15.2/share/go/src/runtime/panic.go:969 +0x175
cuelang.org/go/cue.Value.Syntax(0xc0005102c0, 0xc00025a1b0, 0xc0001e0a80, 0x7, 0x8, 0xc0005102c0, 0xc00025a1b0)
```

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/590#issuecomment-731000650_

Analysis:
this is triggered by bug in `internal/core/export`.Def. It converts let expressions back from their compiled form, but uses the original name without worrying about conflicts.

Also, arguably, `Syntax` should not panic on such input. OTOH, the panic is always a result of an internal bug.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/590#issuecomment-731007014_

See `internal/core/export/adt.go` at `case *adt.LetReference`. Always somewhat reassuring if there is already a TODO indicating the bug. :)
