### ISSUE TITLE
Panic during eval

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#593]
_Originally opened by @nyarly in https://github.com/cuelang/cue/issues/593_

### What version of CUE are you using (`cue version`)?

from source, from the `v0.3.0-alpha4` tag

### What did you do?

I added this code to my (large, private) Cue structure:
```
_clobbers: [
			...{
			apiVersion: string | *"v1"
			kind:       string
			metadata: {
				name:       string
				namespace?: string
			}
		},
	] & [ for crd in [
		"cephblockpools.ceph.rook.io",
		"cephclients.ceph.rook.io",
		"cephclusters.ceph.rook.io",
		"cephfilesystems.ceph.rook.io",
		"cephnfses.ceph.rook.io",
		"cephobjectrealms.ceph.rook.io",
		"cephobjectstores.ceph.rook.io",
		"cephobjectstoreusers.ceph.rook.io",
		"cephobjectzonegroups.ceph.rook.io",
		"cephobjectzones.ceph.rook.io",
		"cephrbdmirrors.ceph.rook.io",
		"objectbucketclaims.objectbucket.io",
		"objectbuckets.objectbucket.io",
		"volumes.rook.io",
	] {
		apiVersion: "apiextensions.k8s.io/v1beta1"
		kind:       "CustomResourceDefinition"
		metadata: name: crd
	}]+[
// THIS HERE comprehension is the most recent addition
		for sa in [
			"rook-ceph-admission-controller",
			"rook-ceph-cmd-reporter",
			"rook-ceph-mgr",
			"rook-ceph-osd",
			"rook-ceph-system",
			"rook-csi-cephfs-plugin-sa",
			"rook-csi-cephfs-provisioner-sa",
			"rook-csi-rbd-plugin-sa",
			"rook-csi-rbd-provisioner-sa",
		] {
			kind: "ServiceAccount"
			metadata: {
				name:      sa
				namespace: "rook-ceph"
			}
		},
	]+[{
		apiVersion: "storage.k8s.io/v1"
		kind:       "StorageClass"
		metadata: name: "rook-ceph-bucket"
	}]

	for cfg in _clobbers {
		let pname = "\(cfg.kind)-\(cfg.name)"
		let filepath = "variants/\(vname)/plugins/clobber-\(pname).yaml"
		files: "\(filepath)": {
			apiVersion: "builtin"
			kind:       "PatchStrategicMergeTransformer"
			metadata: name: pname
			patches: yaml.Marshal(_cpatches)
			let _cpatches = cfg & {
				apiVersion: string
				kind:       string
				metadata: {
					name:       string
					namespace?: string
				}
				$patch: "delete"
			}
		}
	}
```

and run
`cue eval ./stucture/...`

### What did you expect to see?

A lengthy Cue result from the package.

### What did you see instead?

I get 25k lines of output (that looks correct...) and then
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xb05d8e]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc001affec0)
        /build/source/cmd/cue/cmd/root.go:221 +0x95
panic(0xbbbb60, 0x118abe0)
        /nix/store/eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-go-1.15.2/share/go/src/runtime/panic.go:969 +0x175
cuelang.org/go/cmd/cue/cmd.runEval(0xc0003d8cc0, 0xc00034bb60, 0x1, 0x1, 0x0, 0x0)
        /build/source/cmd/cue/cmd/eval.go:153 +0x68e
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc00020f8c0, 0xc00034bb60, 0x1, 0x1, 0x0, 0x0)
        /build/source/cmd/cue/cmd/root.go:46 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc00020f8c0, 0xc00034bb30, 0x1, 0x1, 0xc00020f8c0, 0xc00034bb30)
        /build/source/vendor/github.com/spf13/cobra/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00020f080, 0x0, 0x0, 0x0)
        /build/source/vendor/github.com/spf13/cobra/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /build/source/vendor/github.com/spf13/cobra/command.go:887
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc0003d8cc0, 0xd7fb40, 0xc000036270, 0x0, 0x0)
        /build/source/cmd/cue/cmd/root.go:206 +0x65
cuelang.org/go/cmd/cue/cmd.mainErr(0xd7fb40, 0xc000036270, 0xc0000300a0, 0x2, 0x2, 0xcc3280, 0xc000247f48)
        /build/source/cmd/cue/cmd/root.go:145 +0x8a
cuelang.org/go/cmd/cue/cmd.Main(0xc000040358)
        /build/source/cmd/cue/cmd/root.go:127 +0x9c
main.main()
        /build/source/cmd/cue/main.go:24 +0x25
```

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/593#issuecomment-731372066_

I cannot reproduce this crash with the above example, so will be nearly impossible to debug. The stack trace the point at which the real stack trace is recovered, so that's not that useful either.

Is there any change you can have a working example that can reproduce it? Happy to work with you offline if this would contain sensitive information that you don't want to share publically.

**Comment by cueckoo** [comment]
_Original reply by @nyarly in https://github.com/cuelang/cue/issues/593#issuecomment-731376847_

What I found was that there was an error in the interpolation - I'd changed the _clobber struct from `name: string` to `metadata: name: string`, which wasn't reflected in the `pname` interpolation.

I had to add some instrumentation to Cue to determine that; I wonder if there's better ways to have done that.

**Comment by cueckoo** [comment]
_Original reply by @nyarly in https://github.com/cuelang/cue/issues/593#issuecomment-731412486_

Reduced case:

```
package broken

variants: kind: {}

for vname, variant in variants {
    cfgs: [ for crd in [
        "one",
        "two",
    ] {
        metadata: name: crd
    }]

    for cfg in cfgs {
        let filepath = "\(vname)-\(cfg.name)"
        files: "\(filepath)": {
            patches: cfg
        }
    }
}
```

**Comment by cueckoo** [comment]
_Original reply by @nyarly in https://github.com/cuelang/cue/issues/593#issuecomment-731412632_

I've noticed that `cue export` reports an error, where `eval` panics.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/593#issuecomment-731562485_

Awesome, thanks!

It is indeed possible that `eval` and `export` behave differently. This means that the bug is most likely in `internal/core/export`.  `cue def` prints mostly simplified raw values and `cue export` prints evaluated values only, whereas `cue eval` does something funky in between that wasn't always thought out well and is bug prone.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/593#issuecomment-731566887_

BTW, this is the second time I ran into this crash this week, so I've added a report functionality that gives more information for these kind of errors:

https://cue-review.googlesource.com/c/cue/+/7722

Feel free to comment or add yourself as a reviewer.

Converting evaluated values to a CUE AST is actually surprisingly complex (especially doing anything else than `export`), so I suspect this reporting may come in handy in the future.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/593#issuecomment-731567962_

BTW, the error in the config that triggered this is that `cfg.name` should be `cfg.metadata.name`.  This then means that the `let` clause is "incomplete" and included in the output.  A bug in the exporter then causes a let clause with the same name to be included for each iteration, causing the error.
