### ISSUE TITLE
panic: getNodeContext: nodeContext out of sync

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#633]
_Originally opened by @binarylogic in https://github.com/cuelang/cue/issues/633_

### What version of CUE are you using (`cue version`)?

<pre>
➜ cue version
cue version 0.3.0-beta.1 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

We use Cue over at [Vector](https://github.com/timberio/vector) to maintain [project metadata](https://github.com/timberio/vector/tree/master/docs) (such as configuration) for our docs. Up until `0.3.0-beta.1` everything has worked fine.

1. `git clone git@github.com:timberio/vector.git`
2. `cd vector`
3. `cue export docs/**/*.cue`

### What did you expect to see?

The normal JSON document generated from our cue files.

### What did you see instead?

```
panic: getNodeContext: nodeContext out of sync
  panic: freeNode: nodeContext out of sync [recovered]
  panic: freeNode: nodeContext out of sync

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc00221fec0)
  /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/root.go:221 +0x95
panic(0x17996c0, 0x19760a0)
  /usr/local/go/src/runtime/panic.go:969 +0x1b9
cuelang.org/go/internal/core/adt.(*Vertex).freeNode(0xc0043726c0, 0xc004337180)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:799 +0x132
panic(0x17996c0, 0x1976080)
  /usr/local/go/src/runtime/panic.go:975 +0x47a
cuelang.org/go/internal/core/adt.(*Vertex).getNodeContext(0xc00438c2d0, 0xc000329450, 0xc00438c240)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:785 +0xd6
cuelang.org/go/internal/core/adt.(*Unifier).Unify(0xc000329468, 0xc000329450, 0xc00438c2d0, 0x180e905)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:207 +0x92
cuelang.org/go/internal/core/adt.(*nodeContext).completeArcs(0xc004337880, 0x5)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:577 +0x136
cuelang.org/go/internal/core/adt.(*nodeContext).postDisjunct(0xc004337880, 0x605)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:548 +0x4fb
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0xc004337880, 0xc0038dbe05, 0xc004337180, 0x0, 0x1)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/disjunct.go:137 +0x1008
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0xc004337180, 0xc004372603, 0xc004337180, 0x0, 0x0)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/disjunct.go:213 +0x408
cuelang.org/go/internal/core/adt.(*Unifier).Unify(0xc000329468, 0xc000329450, 0xc0043726c0, 0x12ccb03)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:315 +0x4a8
cuelang.org/go/internal/core/adt.(*Unifier).evaluate(0xc000329468, 0xc000329450, 0xc0043726c0, 0x810a303, 0xc0015a64b0, 0x1)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:139 +0x8c
cuelang.org/go/internal/core/adt.(*OpContext).evalState(0xc000329450, 0x199a300, 0xc0015a64b0, 0xc00389d603, 0x0, 0x0)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/context.go:585 +0x247
cuelang.org/go/internal/core/adt.(*OpContext).node(0xc000329450, 0x198d340, 0xc001aad4a0, 0x199a300, 0xc0015a64b0, 0x180e801, 0x1)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/context.go:725 +0x5f
cuelang.org/go/internal/core/adt.(*SelectorExpr).resolve(0xc001aad4a0, 0xc000329450, 0xc001aad4a0)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/expr.go:698 +0x65
cuelang.org/go/internal/core/adt.(*OpContext).evalState(0xc000329450, 0x199a5c0, 0xc001aad4a0, 0x1807002, 0x0, 0x0)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/context.go:577 +0x1fd
cuelang.org/go/internal/core/adt.(*OpContext).Evaluate(0xc000329450, 0xc0038db1d0, 0x199a5c0, 0xc001aad4a0, 0xc001a93280, 0x199ecc0, 0xc001a93280)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/context.go:507 +0x105
cuelang.org/go/internal/core/adt.(*OpContext).Concrete(0xc000329450, 0xc0038db1d0, 0x199a5c0, 0xc001aad4a0, 0x17cce20, 0x1d6fe78, 0x1009eff, 0xc00001e000, 0x17e5a40)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/context.go:445 +0x53
cuelang.org/go/internal/core/adt.(*BinaryExpr).evaluate(0xc0019bb3e0, 0xc000329450, 0xc0019bb3e0, 0x86731d8)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/expr.go:961 +0x285
cuelang.org/go/internal/core/adt.(*OpContext).evalState(0xc000329450, 0x1999fc0, 0xc0019bb3e0, 0x2, 0x0, 0x0)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/context.go:573 +0x38c
cuelang.org/go/internal/core/adt.(*OpContext).value(0xc000329450, 0x1999fc0, 0xc0019bb3e0, 0xc003d2d500, 0xc0019bb470)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/context.go:537 +0x48
cuelang.org/go/internal/core/adt.(*IfClause).yield(0xc0019bb410, 0xc000329450, 0xc003d2d500)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/expr.go:1417 +0x46
cuelang.org/go/internal/core/adt.(*OpContext).Yield(0xc000329450, 0xc0038db1d0, 0x19944c0, 0xc0019bb410, 0xc003d2d500, 0x19944c0)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/context.go:433 +0xf9
cuelang.org/go/internal/core/adt.(*nodeContext).injectEmbedded(0xc004328000, 0xc004328200, 0x0)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:1799 +0x14f
cuelang.org/go/internal/core/adt.(*nodeContext).expandOne(0xc004328000, 0xc004348360)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:1722 +0xc5
cuelang.org/go/internal/core/adt.(*Unifier).Unify(0xc000329468, 0xc000329450, 0xc004348360, 0x180e905)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:277 +0x3c5
cuelang.org/go/internal/core/adt.(*nodeContext).completeArcs(0xc0041d7880, 0x5)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:577 +0x136
cuelang.org/go/internal/core/adt.(*nodeContext).postDisjunct(0xc0041d7880, 0x5)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:548 +0x4fb
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0xc0041d7880, 0xc00431f805, 0xc0041d7880, 0x0, 0x0)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/disjunct.go:137 +0x1008
cuelang.org/go/internal/core/adt.(*Unifier).Unify(0xc000329468, 0xc000329450, 0xc00431f8c0, 0x180e905)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:315 +0x4a8
cuelang.org/go/internal/core/adt.(*nodeContext).completeArcs(0xc000037c00, 0x5)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:577 +0x136
cuelang.org/go/internal/core/adt.(*nodeContext).postDisjunct(0xc000037c00, 0x1829805)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:548 +0x4fb
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0xc000037c00, 0xc0014ab305, 0xc000037c00, 0x0, 0x0)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/disjunct.go:137 +0x1008
cuelang.org/go/internal/core/adt.(*Unifier).Unify(0xc000329468, 0xc000329450, 0xc0014ab320, 0x180e905)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:315 +0x4a8
cuelang.org/go/internal/core/adt.(*nodeContext).completeArcs(0xc000282a80, 0x5)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:577 +0x136
cuelang.org/go/internal/core/adt.(*nodeContext).postDisjunct(0xc000282a80, 0x5)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:548 +0x4fb
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0xc000282a80, 0xc001448605, 0xc000282a80, 0x0, 0x0)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/disjunct.go:137 +0x1008
cuelang.org/go/internal/core/adt.(*Unifier).Unify(0xc000329468, 0xc000329450, 0xc001448630, 0x180e905)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:315 +0x4a8
cuelang.org/go/internal/core/adt.(*nodeContext).completeArcs(0xc000282380, 0x5)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:577 +0x136
cuelang.org/go/internal/core/adt.(*nodeContext).postDisjunct(0xc000282380, 0xc00088bc05)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:548 +0x4fb
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0xc000282380, 0xc000fabb05, 0xc000282380, 0x0, 0x0)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/disjunct.go:137 +0x1008
cuelang.org/go/internal/core/adt.(*Unifier).Unify(0xc000329468, 0xc000329450, 0xc000fabb00, 0x180e905)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:315 +0x4a8
cuelang.org/go/internal/core/adt.(*nodeContext).completeArcs(0xc000282000, 0x5)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:577 +0x136
cuelang.org/go/internal/core/adt.(*nodeContext).postDisjunct(0xc000282000, 0x5)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:548 +0x4fb
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0xc000282000, 0xc00182e505, 0xc000282000, 0x0, 0x0)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/disjunct.go:137 +0x1008
cuelang.org/go/internal/core/adt.(*Unifier).Unify(0xc000329468, 0xc000329450, 0xc00182e510, 0xc000329405)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:315 +0x4a8
cuelang.org/go/internal/core/adt.(*Vertex).Finalize(...)
  /Users/mpvl/Documents/dev/release/cue/internal/core/adt/composite.go:401
cuelang.org/go/cue.(*Instance).Value(0xc00188a700, 0x6, 0xc00031fea0)
  /Users/mpvl/Documents/dev/release/cue/cue/instance.go:271 +0x6c
cuelang.org/go/cmd/cue/cmd.buildInstances(0xc00031fea0, 0xc0017e7898, 0x1, 0x1, 0x17c8180, 0xc000321d40, 0xc0002c3b58)
  /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/common.go:552 +0x131
cuelang.org/go/cmd/cue/cmd.(*buildPlan).instances(0xc000178180, 0x0, 0x0)
  /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/common.go:156 +0x58
cuelang.org/go/cmd/cue/cmd.runExport(0xc00031fea0, 0xc00036c600, 0x10d, 0x10d, 0x0, 0x0)
  /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/export.go:114 +0x1be
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc000344000, 0xc00036c600, 0x10d, 0x10d, 0x0, 0x0)
  /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/root.go:46 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc000344000, 0xc00036b300, 0x10d, 0x130, 0xc000344000, 0xc00036b300)
  /Users/mpvl/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000281080, 0x0, 0x0, 0x0)
  /Users/mpvl/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
  /Users/mpvl/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc00031fea0, 0x1997f00, 0xc00003a0b8, 0x0, 0x0)
  /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/root.go:206 +0x65
cuelang.org/go/cmd/cue/cmd.mainErr(0x1997f00, 0xc00003a0b8, 0xc000031310, 0x10e, 0x12f, 0x18da528, 0xc0002c3f48)
  /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/root.go:145 +0x8a
cuelang.org/go/cmd/cue/cmd.Main(0xc000100058)
  /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/root.go:127 +0x9c
main.main()
  /Users/mpvl/Documents/dev/release/cue/cmd/cue/main.go:24 +0x25
```

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/633#issuecomment-757483496_

Thanks for the feedback.

FTR: for those not having `**` enabled in their shell, the reproducing command is `cue export docs/*/*.cue docs/*/*/*.cue docs/*/*/*/*.cue  docs/*.cue`.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/633#issuecomment-757483908_

This is also a nice test case related to performance as the pre-beta v0.3 runs over 22s on my machine.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/633#issuecomment-757491019_

FTR: more reduced reproducer: 
```
go run ../../cmd/cue export \
./reference.cue \
./reference/services.cue \
./reference/components/sources.cue \
./reference/components/sources/socket.cue \
./reference/components/sources/syslog.cue \
./reference/components/sinks.cue \
./reference/components/splunk.cue \
./reference/components.cue \
./reference/urls.cue
```

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/633#issuecomment-757516094_

See below for a "minimal" example. One of the causes is the use of `close()`, which is unnecessary in this case (as of v0.3). If I remove the `close` things work as expected. This may be a possible workaround for now (while cleaning up the code).

```
sources: [Type=string]: configuration: #Schema

#Schema: [Name=string]: {
	_args: required: true
	let Args = _args

	close({"string": _args: required: true}) |
	close({"uint": {_args: required: Args.required}})
}
sources: socket: {}

sources: syslog: configuration: sources.socket.configuration & {
	type: string: {}
}
```

Removing the unnecessary calls to close makes this work:

```
sources: [Type=string]: configuration: #Schema

#Schema: [Name=string]: {
	_args: required: true
	let Args = _args

	{"string": _args: required: true} |
	{"uint": {_args: required: Args.required}}
}
sources: socket: {}

sources: syslog: configuration: sources.socket.configuration & {
	type: string: {}
}
```
Because the closed structs are defined in a definition (`#Schema`), these structs are already closed. There was a bug in v0.2 that caused such disjunctions not to be handled correctly. But v0.3 fixed that.

**Comment by cueckoo** [comment]
_Original reply by @binarylogic in https://github.com/cuelang/cue/issues/633#issuecomment-757516617_

Thanks for your help! We will remove those.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/633#issuecomment-757667811_

I see there are still some discrepancies left when removing `close`. Looking in to that shortly.

However, removing close for alpha6 will at least significantly reduce the running time for alpha6 even.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/633#issuecomment-757710492_

FTR: this is a reproducer for after removing the closes:
```
sources: socket: {}
sources: [Type=string]: #Schema

sources: syslog: sources.socket
sources: syslog: foo: type: string: {}

#Schema: [Name=string]: {
	required: bool
	type:     #Type
}

#Type: {
	_args: required: bool
	let Args = _args

	{"array": {_args: required: Args.required}} |
	#TypePrimitive
}

#TypePrimitive: {
	_args: required: bool
	let Args = _args

	{"string": {_args: required: Args.required}} |
	{"uint": {_args: required: true}}
}
```
which gives
```
sources.syslog.foo.type: 1 errors in empty disjunction:
sources.syslog.foo.type: field `string` not allowed:
```
even though `alpha6` passes (which is correct).

The issue seems to be a misalignment in the caching when evaluating disjunctions. After applying a fix for the crashes caused with the use of `close`, I'm getting the same errors. Funnily enough, the fixes for close are not related to close but also related to the same issue. So it seems that that fix is just incomplete, but that it is only one issue. Anyway, closing in on a fix.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/633#issuecomment-758684022_

Interim update. This actually uncovered a couple of bugs. Most of these are fixed, modulo a cleanup, but there is one more issue that was uncovered I will need to address.

This effort also uncovered a bug in the _old_ code that is fixed in beta: a `close` could reopen an object. For instance, in 
```
		#ExampleConfig: close({
			"configuration": {
				for k, v in configuration {
					"\( k )"?: _ | *null
				}
			}
		})
```
the close would have the effect of opening up the `configuration` struct. Removing the close would disallow additional fields in `configuration`. Of course, additional fields should be disallowed in `configuration` regardless of whether `close` is used.

This was a bug in `alpha6` and is fixed in `beta.1`.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/633#issuecomment-758684700_

BTW, note that @myitcv is working on allowing CUE users to register repos so that we can validate new releases against a large body of code so as to avoid these surprises in the future.

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/633#issuecomment-758844091_

Another update. I have some fixes that make the code work. There is one matter I need to investigate more though. There was (another) bug in the alpha code that eliminated disjuncts that were equal in terms of concrete fields, but different in terms of closeness.This is causing trouble for:
```
_ | {[string]: #Any}
```
as the first is considered open, whereas the first is not. This should probably be fixed, but then still, CUE would have to determine that #Any equals `_` to determine full equivalency of pattern constraints, which is probably not a good idea.

The solution is to simply write this as `_`, but there is a bug in `alpha6` that seems to prevent that from working. Another solution is to write `*_ | {[string]: #Any}` to break a tie. This works for both versions.

The fix in `beta1` does seem a bit too strict for comfort though. The same problem exists for `#Fields`, which could be replaced by `{...}`. But the restrictions there seem too awkward. So will have to see if I can relax it a bit in a sane way.

Anyway, closing in on the fixes. The running time with the new alpha is also about 50%!r(MISSING)educed with the `close` fix. Compared to the original it runs over 75%!f(MISSING)aster. Still too slow for my taste, but inching in on a reasonable running time (should be less than a second for your repo).

Either way, thanks for providing such an excellent test case! :)

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/633#issuecomment-758846871_

Actually, I was comparing running the original cue binary against running `go run ./cmd/cue`. Comparing apples to apples I get about an 89%!r(MISSING)eduction, running at about 1.7s. Still too slow, but a bit better still. :)

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/633#issuecomment-759299988_

I've sent a fix for this in patchset https://cue-review.googlesource.com/c/cue/+/8141/3. This is rebased directly on beta.1. For beta.2, which we will launch shortly as this is a serious bug, I'll first revert at least one of that language changes (really a bug fix) to not change too much at once. So this patchset is more representative for a next beta than rebasing this at tip. Note that I probably rebase this CL on tip before reverting some of the changes.

Before the release, though, I will need to consider what to do with deduplicating disjunctions. So that is still a blocker.

Below is patch of the changes I made to your repo to make things work with the patch set. The changes to `close` are mostly unnecessary but just a good idea. Some are critical, though, as they utilized bugs in alpha6, as discussed before. Replacing `#Fields` with `{....}` and `#Any`  with `_` is probably the nicest.

Note that the patch also adds some missing `package metadata` clauses.  beta1 requires consistent package labeling, even when used with explicit files. This may be too restrictive. Let me know if this is an issue. I think this should be relaxed.

```
diff --git a/docs/reference.cue b/docs/reference.cue
index 37e5904a0..0cc01493b 100644
--- a/docs/reference.cue
+++ b/docs/reference.cue
@@ -1,13 +1,8 @@
-// Root
-//
-// The root file defines the schema for all of Vector's reference metadata.
-// It does not include boilerplate or domain specific policies.
-
 package metadata
 
-import (
-	"strings"
-)
+import "strings"
+
+#Arch: "ARM64" | "ARMv7" | "x86_64"
 
 _values: {
 	current_timestamp: "2020-10-10T17:07:36.452332Z"
@@ -16,10 +11,7 @@ _values: {
 	instance:          "vector:9598"
 }
 
-// `#Any` allows for any value.
-#Any: _ | {[_=string]: #Any}
-
-#Arch: "ARM64" | "ARMv7" | "x86_64"
+#Any: *_ | {[_=string]: #Any}
 
 // `#CompressionAlgorithm` specified data compression algorithm.
 //
@@ -83,8 +75,8 @@ _values: {
 #Enum: [Name=_]: string
 
 #Event: {
-	close({log: #LogEvent}) |
-	close({metric: #MetricEvent})
+	{log: #LogEvent} |
+	{metric: #MetricEvent}
 }
 
 // `#EventType` represents one of Vector's supported event types.
@@ -93,15 +85,15 @@ _values: {
 // * `metric` - metric event
 #EventType: "log" | "metric"
 
-#Fields: [Name=string]: #Fields | _
+#Fields: [Name=string]: #Fields | *_
 
 #Interface: {
-	close({binary: #InterfaceBinary}) |
-	close({ffi: close({})}) |
-	close({file_system: #InterfaceFileSystem}) |
-	close({socket: #InterfaceSocket}) |
-	close({stdin: close({})}) |
-	close({stdout: close({})})
+	{binary: #InterfaceBinary} |
+	{ffi: {}} |
+	{file_system: #InterfaceFileSystem} |
+	{socket: #InterfaceSocket} |
+	{stdin: {}} |
+	{stdout: {}}
 }
 
 #InterfaceBinary: {
@@ -134,7 +126,7 @@ _values: {
 	ssl:     "disabled" | "required" | "optional"
 }
 
-#HowItWorks: [Name=string]: close({
+#HowItWorks: [Name=string]: {
 	#Subsection: {
 		title: string
 		body:  string
@@ -144,13 +136,13 @@ _values: {
 	title: string
 	body:  string | null
 	sub_sections?: [#Subsection, ...#Subsection]
-})
+}
 
 #LogEvent: {
 	host?:      string | null
 	message?:   string | null
 	timestamp?: string | null
-	#Any
+	...
 }
 
 #Map: [string]: string
@@ -161,12 +153,12 @@ _values: {
 	namespace?: string
 	tags: [Name=string]: string
 	timestamp?: string
-	close({counter: #MetricEventCounter}) |
-	close({distribution: #MetricEventDistribution}) |
-	close({gauge: #MetricEventGauge}) |
-	close({histogram: #MetricEventHistogram}) |
-	close({set: #MetricEventSet}) |
-	close({summary: #MetricEventSummary})
+	{counter: #MetricEventCounter} |
+	{distribution: #MetricEventDistribution} |
+	{gauge: #MetricEventGauge} |
+	{histogram: #MetricEventHistogram} |
+	{set: #MetricEventSet} |
+	{summary: #MetricEventSummary}
 }
 
 #MetricEventCounter: {
@@ -201,14 +193,14 @@ _values: {
 	sum:   float
 }
 
-#MetricTags: [Name=string]: close({
+#MetricTags: [Name=string]: {
 	name:        Name
 	default?:    string
 	description: string
 	enum?:       #Enum
 	examples?: [string, ...string]
 	required: bool
-})
+}
 
 #MetricType: "counter" | "distribution" | "gauge" | "histogram" | "summary"
 
@@ -351,7 +343,7 @@ _values: {
 	//
 	// For example, the `sinks.http.headers.*` option allows for arbitrary
 	// key/value pairs.
-	close({"array": #TypeArray & {_args: required: Args.required}}) |
+	{"array": #TypeArray & {_args: required: Args.required}} |
 	#TypePrimitive
 }
 
@@ -366,13 +358,13 @@ _values: {
 	//
 	// For example, the `sinks.http.headers.*` option allows for arbitrary
 	// key/value pairs.
-	close({"*": close({})}) |
-	close({"bool": #TypeBool & {_args: required: Args.required}}) |
-	close({"float": #TypeFloat & {_args: required: Args.required}}) |
-	close({"object": #TypeObject & {_args: required: Args.required}}) |
-	close({"string": #TypeString & {_args: required: Args.required}}) |
-	close({"timestamp": #TypeTimestamp & {_args: required: Args.required}}) |
-	close({"uint": #TypeUint & {_args: required: Args.required}})
+	{"*": {}} |
+	{"bool": #TypeBool & {_args: required: Args.required}} |
+	{"float": #TypeFloat & {_args: required: Args.required}} |
+	{"object": #TypeObject & {_args: required: Args.required}} |
+	{"string": #TypeString & {_args: required: Args.required}} |
+	{"timestamp": #TypeTimestamp & {_args: required: Args.required}} |
+	{"uint": #TypeUint & {_args: required: Args.required}}
 }
 
 #TypeArray: {
diff --git a/docs/reference/components.cue b/docs/reference/components.cue
index 7cfbc6854..267cabd5c 100644
--- a/docs/reference/components.cue
+++ b/docs/reference/components.cue
@@ -65,10 +65,11 @@ components: {
 
 		// `examples` demonstrates various ways to use the component using an
 		// input, output, and example configuration.
-		#ExampleConfig: close({
+		#ExampleConfig: {
 			title:    string
 			context?: string
 			"configuration": {
+				...
 				for k, v in configuration {
 					"\( k )"?: _ | *null
 				}
@@ -91,7 +92,7 @@ components: {
 			}
 
 			notes?: string
-		})
+		}
 
 		examples?: [#ExampleConfig, ...#ExampleConfig]
 
@@ -182,14 +183,14 @@ components: {
 
 		if Args.kind == "sink" {
 			// `buffer` describes how the component buffers data.
-			buffer: close({
+			buffer: {
 				enabled: bool | string
-			})
+			}
 
 			// `healtcheck` notes if a component offers a healthcheck on boot.
-			healthcheck: close({
+			healthcheck: {
 				enabled: bool
-			})
+			}
 
 			exposes?: #FeaturesExpose
 			send?:    #FeaturesSend & {_args: Args}
@@ -199,9 +200,9 @@ components: {
 	}
 
 	#FeaturesCollect: {
-		checkpoint: close({
+		checkpoint: {
 			enabled: bool
-		})
+		}
 
 		from?: {
 			service:    #Service
@@ -215,11 +216,11 @@ components: {
 	}
 
 	#FeaturesEnrich: {
-		from: service: close({
+		from: service: {
 			name:     string
 			url:      string
 			versions: string | null
-		})
+		}
 	}
 
 	#FeaturesExpose: {
@@ -244,11 +245,11 @@ components: {
 	}
 
 	#FeaturesParse: {
-		format: close({
+		format: {
 			name:     string
 			url:      string | null
 			versions: string | null
-		})
+		}
 	}
 
 	#FeaturesProgram: {
@@ -288,13 +289,13 @@ components: {
 		if Args.egress_method == "batch" || Args.egress_method == "dynamic" {
 			// `batch` describes how the component batches data. This is only
 			// relevant if a component has an `egress_method` of "batch".
-			batch: close({
+			batch: {
 				enabled:      bool
 				common:       bool
 				max_bytes:    uint | null
 				max_events:   uint | null
 				timeout_secs: uint16 | null
-			})
+			}
 		}
 
 		// `compression` describes how the component compresses data.
@@ -375,11 +376,11 @@ components: {
 		metrics: #MetricInput | null
 	}
 
-	#LogOutput: [Name=string]: close({
+	#LogOutput: [Name=string]: {
 		description: string
 		name:        Name
 		fields:      #Schema
-	})
+	}
 
 	#MetricInput: {
 		counter:      *false | bool
@@ -390,14 +391,14 @@ components: {
 		summary:      *false | bool
 	}
 
-	#MetricOutput: [Name=string]: close({
+	#MetricOutput: [Name=string]: {
 		description:       string
 		relevant_when?:    string
 		tags:              #MetricTags
 		name:              Name
 		type:              #MetricType
 		default_namespace: string
-	})
+	}
 
 	#Output: {
 		logs?:    #LogOutput
diff --git a/docs/reference/installation.cue b/docs/reference/installation.cue
index 96cd87e76..8f15ab620 100644
--- a/docs/reference/installation.cue
+++ b/docs/reference/installation.cue
@@ -1,6 +1,6 @@
 package metadata
 
-installation: close({
+installation: {
 	#Commands: {
 		{[Name=string]: string | null}
 	} & {
@@ -264,4 +264,4 @@ installation: close({
 	package_managers:  #PackageManagers
 	platforms:         #Platforms
 	roles:             #Roles
-})
+}
diff --git a/docs/reference/remap.cue b/docs/reference/remap.cue
index 209307242..0569164b3 100644
--- a/docs/reference/remap.cue
+++ b/docs/reference/remap.cue
@@ -42,9 +42,9 @@ remap: {
 			#RemapExample: {
 				title: string
 				configuration?: [string]: string
-				input:  #Fields
+				input:  #Fields // {...}
 				source: string
-				output: #Fields
+				output: {...}
 			}
 
 			arguments: [...#Argument] // Allow for empty list
diff --git a/docs/reference/remap/parse_syslog.cue b/docs/reference/remap/parse_syslog.cue
index 4d7e4bbac..eada5be1b 100644
--- a/docs/reference/remap/parse_syslog.cue
+++ b/docs/reference/remap/parse_syslog.cue
@@ -1,3 +1,5 @@
+package metadata
+
 remap: functions: parse_syslog: {
 	arguments: [
 		{
diff --git a/docs/reference/remap/to_bool.cue b/docs/reference/remap/to_bool.cue
index c302639d3..c323e97b1 100644
--- a/docs/reference/remap/to_bool.cue
+++ b/docs/reference/remap/to_bool.cue
@@ -1,3 +1,5 @@
+package metadata
+
 remap: functions: to_bool: {
 	arguments: [
 		{
diff --git a/docs/reference/remap/to_float.cue b/docs/reference/remap/to_float.cue
index b40de4ed9..a6bafa702 100644
--- a/docs/reference/remap/to_float.cue
+++ b/docs/reference/remap/to_float.cue
@@ -1,3 +1,5 @@
+package metadata
+
 remap: functions: to_float: {
 	arguments: [
 		{
diff --git a/docs/reference/remap/to_int.cue b/docs/reference/remap/to_int.cue
index 91c5de2c2..112a63181 100644
--- a/docs/reference/remap/to_int.cue
+++ b/docs/reference/remap/to_int.cue
@@ -1,3 +1,5 @@
+package metadata
+
 remap: functions: to_int: {
 	arguments: [
 		{
diff --git a/docs/reference/remap/to_timestamp.cue b/docs/reference/remap/to_timestamp.cue
index 81318589a..313fa722b 100644
--- a/docs/reference/remap/to_timestamp.cue
+++ b/docs/reference/remap/to_timestamp.cue
@@ -1,3 +1,5 @@
+package metadata
+
 remap: functions: to_timestamp: {
 	arguments: [
 		{
```

**Comment by cueckoo** [comment]
_Original reply by @binarylogic in https://github.com/cuelang/cue/issues/633#issuecomment-759572681_

Thank you! We'll apply the patch as soon as `beta.2` comes out.

And appreciate your help with this issue. We've been very happy with Cue across our team!

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/633#issuecomment-759745931_

Glad to be of help and that you are liking CUE.
