### ISSUE TITLE
Invalid memory address panic in tool

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#650]
_Originally opened by @addreas in https://github.com/cuelang/cue/issues/650_

### What version of CUE are you using (`cue version`)?
Bisected from v0.2.2 to master and ended up at bef7b263893bf64368d00aeb6d3e8cf7976dbdf2.

### Does this issue reproduce with the latest release?
Yes

### What did you do?
Defined a tool that I got down to this
```
package kube

import (
	"tool/cli"
	core_v1 "k8s.io/api/core/v1"
)

root: core_v1.#Pod

root: spec: _

command: test: task: test: cli.Print & {
	for _ in root {
		text: "success"
	}
}
```
Wasn't able to get deep enough to get rid of the #Pod dependency, unfortunately.

### What did you expect to see?
Running `cue test` should print `success`

### What did you see instead?
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa517f6]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc000247ec0)
	/home/addem/.go/src/cuelang.org/go/cmd/cue/cmd/root.go:221 +0x95
panic(0xbd9de0, 0x11b5d30)
	/usr/lib/go/src/runtime/panic.go:969 +0x1b9
cuelang.org/go/internal/core/dep.visit.func1(0xc000247848, 0xc0002478c0)
	/home/addem/.go/src/cuelang.org/go/internal/core/dep/dep.go:120 +0xcd
panic(0xbd9de0, 0x11b5d30)
	/usr/lib/go/src/runtime/panic.go:969 +0x1b9
cuelang.org/go/internal/core/dep.visit.func1(0xc0002471a8, 0xc000247220)
	/home/addem/.go/src/cuelang.org/go/internal/core/dep/dep.go:120 +0xcd
panic(0xbd9de0, 0x11b5d30)
	/usr/lib/go/src/runtime/panic.go:969 +0x1b9
cuelang.org/go/tools/flow.(*Controller).findImpliedTask(0xc0002a6410, 0xc000203200, 0x7fd5c4223728, 0xc0000eef80, 0x0, 0xc000445950)
	/home/addem/.go/src/cuelang.org/go/tools/flow/tasks.go:170 +0x176
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies.func1(0xc000203200, 0x7fd5c4223728, 0xc0000eef80, 0xc0000eef00, 0xc000203200, 0x0)
	/home/addem/.go/src/cuelang.org/go/tools/flow/tasks.go:211 +0x65
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0xc0002471a8, 0xc0004445a0, 0x7fd5c4223728, 0xc0000eef80)
	/home/addem/.go/src/cuelang.org/go/internal/core/dep/dep.go:230 +0x203
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc0002471a8, 0xc0004445a0, 0xda4040, 0xc0000eef80)
	/home/addem/.go/src/cuelang.org/go/internal/core/dep/dep.go:150 +0x912
cuelang.org/go/internal/core/dep.visit(0xc0002a6340, 0xc00026fe60, 0xc000383f80, 0xc000240000, 0x0, 0x0)
	/home/addem/.go/src/cuelang.org/go/internal/core/dep/dep.go:125 +0x1a9
cuelang.org/go/internal/core/dep.dynamic(0xc0002a6340, 0xc00026fe60, 0xc000383f80, 0xc0002473a8, 0x0)
	/home/addem/.go/src/cuelang.org/go/internal/core/dep/mixed.go:43 +0x17b
cuelang.org/go/internal/core/dep.dynamic(0xc0002a6340, 0xc00026fcb0, 0xc000383f80, 0xc0002473a8, 0xc000247401)
	/home/addem/.go/src/cuelang.org/go/internal/core/dep/mixed.go:48 +0x1e5
cuelang.org/go/internal/core/dep.VisitFields(0xc0002a6340, 0xc00026fcb0, 0xc000383f80, 0xf2658ed9cf6b9a01, 0xda4040)
	/home/addem/.go/src/cuelang.org/go/internal/core/dep/dep.go:91 +0xed
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies(0xc0002a6410, 0xc00013a620, 0xc00026fcb0)
	/home/addem/.go/src/cuelang.org/go/tools/flow/tasks.go:210 +0x77
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies.func1(0xc00026fcb0, 0x7fd5c4223728, 0xc000617ce0, 0xc000617c01, 0xc00026fcb0, 0x0)
	/home/addem/.go/src/cuelang.org/go/tools/flow/tasks.go:226 +0x1e8
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0xc000247848, 0xc00045aaa0, 0x7fd5c4223728, 0xc000617ce0)
	/home/addem/.go/src/cuelang.org/go/internal/core/dep/dep.go:230 +0x203
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc000247848, 0xc00045aaa0, 0xda4040, 0xc000617ce0)
	/home/addem/.go/src/cuelang.org/go/internal/core/dep/dep.go:150 +0x912
cuelang.org/go/internal/core/dep.(*visitor).markYielder(0xc000247848, 0xc00045aaa0, 0xd9e240, 0xc000588cc0)
	/home/addem/.go/src/cuelang.org/go/internal/core/dep/dep.go:305 +0x8b
cuelang.org/go/internal/core/dep.(*visitor).markDecl(0xc000247848, 0xc00045aaa0, 0xd9e200, 0xc000588cc0)
	/home/addem/.go/src/cuelang.org/go/internal/core/dep/dep.go:290 +0x138
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc000247848, 0xc000444d20, 0xda43c0, 0xc000188460)
	/home/addem/.go/src/cuelang.org/go/internal/core/dep/dep.go:206 +0x69c
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc000247848, 0xc000444d20, 0xda3d00, 0xc000588d20)
	/home/addem/.go/src/cuelang.org/go/internal/core/dep/dep.go:154 +0x8e5
cuelang.org/go/internal/core/dep.visit(0xc0002a6340, 0xc00029e120, 0xc000383f60, 0xc000240100, 0x0, 0x0)
	/home/addem/.go/src/cuelang.org/go/internal/core/dep/dep.go:125 +0x1a9
cuelang.org/go/internal/core/dep.dynamic(0xc0002a6340, 0xc00029e120, 0xc000383f60, 0xc000247988, 0xc000247a01)
	/home/addem/.go/src/cuelang.org/go/internal/core/dep/mixed.go:43 +0x17b
cuelang.org/go/internal/core/dep.VisitFields(0xc0002a6340, 0xc00029e120, 0xc000383f60, 0xc000065be0, 0xc000065be0)
	/home/addem/.go/src/cuelang.org/go/internal/core/dep/dep.go:91 +0xed
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies(0xc0002a6410, 0xc00013a620, 0xc00029e120)
	/home/addem/.go/src/cuelang.org/go/tools/flow/tasks.go:210 +0x77
cuelang.org/go/tools/flow.(*Controller).initTasks(0xc0002a6410)
	/home/addem/.go/src/cuelang.org/go/tools/flow/tasks.go:50 +0xed
cuelang.org/go/tools/flow.New(0xc000247bd0, 0xc000217260, 0xc000099940, 0x0)
	/home/addem/.go/src/cuelang.org/go/tools/flow/flow.go:225 +0x1c5
cuelang.org/go/cmd/cue/cmd.doTasks(0xc00036f8a0, 0xca3d69, 0x7, 0x7ffee46a8924, 0x4, 0xc000217260, 0xc000247ca0, 0xc000247ca0)
	/home/addem/.go/src/cuelang.org/go/cmd/cue/cmd/custom.go:114 +0x12a
cuelang.org/go/cmd/cue/cmd.addCustom.func1(0xc00036f8a0, 0x120c268, 0x0, 0x0, 0x601cc0, 0xc000247c88)
	/home/addem/.go/src/cuelang.org/go/cmd/cue/cmd/custom.go:98 +0x58
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc0003982c0, 0x120c268, 0x0, 0x0, 0x0, 0x0)
	/home/addem/.go/src/cuelang.org/go/cmd/cue/cmd/root.go:46 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc0003982c0, 0x120c268, 0x0, 0x0, 0xc0003982c0, 0x120c268)
	/home/addem/.go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000135080, 0x0, 0x0, 0x0)
	/home/addem/.go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/addem/.go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc00036f8a0, 0xda1cc0, 0xc0000a4030, 0x0, 0x0)
	/home/addem/.go/src/cuelang.org/go/cmd/cue/cmd/root.go:206 +0x65
cuelang.org/go/cmd/cue/cmd.mainErr(0xda1cc0, 0xc0000a4030, 0xc0000ac010, 0x1, 0x1, 0xce4480, 0xc000307f48)
	/home/addem/.go/src/cuelang.org/go/cmd/cue/cmd/root.go:145 +0x8a
cuelang.org/go/cmd/cue/cmd.Main(0xc00008e058)
	/home/addem/.go/src/cuelang.org/go/cmd/cue/cmd/root.go:127 +0x9c
main.main()
	/home/addem/.go/src/cuelang.org/go/cmd/cue/main.go:24 +0x25
```

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cue/issues/650#issuecomment-764553724_

Here's a minimal repro (tested with c58e0ffc)

```
testscript <<'EOD'
exec cue cmd test

-- blah/blah.cue --
package blah

#Pod: {
 spec?: #PodSpec
}

#PodSpec: {
}
-- cue.mod/module.cue --
module: "mod.com"
-- x.cue --
package kube

import (
 "tool/cli"
 "mod.com/blah"
)

root: blah.#Pod

root: spec: _

command: test: task: test: cli.Print & {
 for _ in root {
  text: "success"
 }
}
-- y_tool.cue --
package kube
EOD
```

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cue/issues/650#issuecomment-764613688_

Further analysis

* I've confirmed that the repro also bisects to bef7b26.
* ~The trigger for this appears to be "commands" that are declared in non-`_tool.cue` files, which might be genuine commands (if for example you accidentally put them in a non-`_tool.cue` file) or CUE that happens to look like a command but really isn't.~ **Edit:** see https://github.com/cuelang/cue/issues/650#issuecomment-764677971
 
@addreas I was only able to repro your example by accident before then finding a minimal repro. I accidentally placed the command definition in a non-`_tool.cue` file. If the command itself (in this issue) is in a `_tool.cue` file the problem goes away (although it won't print `"success"`).

It's questionable whether we should be considering commands defined entirely in non-`_tool.cue` files as commands, but we can revisit that once we've found the underlying cause of the panic. I'll raise a separate issue for that discussion.

The fact that bef7b26 bisects as the "cause" of this problem is likely somewhat misleading. Prior to this commit "commands" in non-`_tool.cue` files were being walked/run. All bef7b26 did was cause a panic as part of the evaluation that happens during that walk (because the CL was otherwise entirely unrelated to `tools/flow`). Per @mpvl - this could well be related to the "overlay" that gets created between `_tool.cue` and non-`_tool.cue` files.

**Comment by cueckoo** [comment]
_Original reply by @addreas in https://github.com/cuelang/cue/issues/650#issuecomment-764651877_

Interesting to say the least. Now that you mention it I've noticed commands being found in non-`_tool.cue` files, and I think I was playing around with that when digging into this. Never considered that it might be the cause or related to it, though.

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cue/issues/650#issuecomment-764659786_

It's not the cause of the panic per se. The changes in bef7b26 have (indirectly) shone a light on a more fundamental problem, very likely unrelated to the change that CL was intending. In the process of narrowing down the repro however we identified the walking of non-`_tool.cue` files. I've raised https://github.com/cuelang/cue/issues/654 to continue the discussion there on whether it's right/wrong.

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cue/issues/650#issuecomment-764677971_

Yet more analysis from looking at another repro.

It is not the existence of commands in non-`_tool.cue` files that is the trigger here. Consider:

```
testscript <<'EOD'
exec cue cmd test

-- blah/blah.cue --
package blah

#Pod: {
 spec?: #PodSpec
}

#PodSpec: {
}
-- cue.mod/module.cue --
module: "mod.com"
-- x.cue --
package kube

import "mod.com/blah"

root: blah.#Pod

root: spec: _

-- y_tool.cue --
package kube

import "tool/cli"

command: test: task: test: cli.Print & {
 for _ in root {
  text: "success"
 }
}
EOD
```

In this case the command _is_ defined in a `_tool.cue` file. It is the reference to `root` (and transitively the things that `root` references through its definition) that is therefore the cause.

However, this doesn't really change things. It's still possible for people to have valid CUE in non-`_tool.cue` files that just so happens to look like a `cue cmd` command, where those "commands" have references like the above, and hence trigger this issue.

So, #654 is still relevant, as is tracking down the root cause of this panic.
