### ISSUE TITLE
Nil pointer panic on eval with -O

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#662]
_Originally opened by @sdboyer in https://github.com/cuelang/cue/issues/662_

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.3.0-beta.2 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yep.

### What did you do?

`cue eval -iO uPlot.cue` - original file is in [this gist](https://gist.github.com/sdboyer/5053e745b7c16579f7d59ccc8c340af3#file-uplot-cue).

### What did you expect to see?

Well, not a panic 😉 The appropriate eval'd output.

### What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1254446]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc000213ec0)
	/Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/root.go:221 +0x95
panic(0x17d2300, 0x1daee00)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
cuelang.org/go/cue/ast.Comments(0x0, 0x0, 0x0, 0x0, 0x1)
	/Users/mpvl/Documents/dev/release/cue/cue/ast/comments.go:19 +0x26
cuelang.org/go/cue/ast.(*inspector).Before(0xc000526f00, 0x0, 0x0, 0x1f86108, 0xc000526f00)
	/Users/mpvl/Documents/dev/release/cue/cue/ast/walk.go:228 +0xa7
cuelang.org/go/cue/ast.walk(0x198ed80, 0xc000526f00, 0x0, 0x0)
	/Users/mpvl/Documents/dev/release/cue/cue/ast/walk.go:61 +0x63
cuelang.org/go/cue/ast.Walk(...)
	/Users/mpvl/Documents/dev/release/cue/cue/ast/walk.go:29
cuelang.org/go/internal/core/export.stripRefs(0x0, 0x0, 0xc0000fe900, 0x0)
	/Users/mpvl/Documents/dev/release/cue/internal/core/export/value.go:95 +0xa5
cuelang.org/go/internal/core/export.(*exporter).structComposite(0xc0000e8fc0, 0xc0000d5e60, 0x0, 0x0)
	/Users/mpvl/Documents/dev/release/cue/internal/core/export/value.go:413 +0x6a5
cuelang.org/go/internal/core/export.(*exporter).vertex(0xc0000e8fc0, 0xc0000d5e60, 0xc0000d5e60, 0xc000296088)
	/Users/mpvl/Documents/dev/release/cue/internal/core/export/value.go:48 +0x55f
cuelang.org/go/internal/core/export.(*exporter).structComposite(0xc0000e8fc0, 0xc0000d55f0, 0x0, 0x0)
	/Users/mpvl/Documents/dev/release/cue/internal/core/export/value.go:419 +0x953
cuelang.org/go/internal/core/export.(*exporter).vertex(0xc0000e8fc0, 0xc0000d55f0, 0x19a14c0, 0xc0000d55f0)
	/Users/mpvl/Documents/dev/release/cue/internal/core/export/value.go:48 +0x55f
cuelang.org/go/internal/core/export.(*exporter).value(0xc0000e8fc0, 0x19a14c0, 0xc0000d55f0, 0x0, 0x0, 0x0, 0xc000399f28, 0x6)
	/Users/mpvl/Documents/dev/release/cue/internal/core/export/value.go:153 +0xab7
cuelang.org/go/internal/core/export.(*Profile).Value(0xc000399f20, 0x199cb80, 0xc0000d2c20, 0xc000399f28, 0x6, 0x19a14c0, 0xc0000d55f0, 0x8, 0x189957a, 0x4, ...)
	/Users/mpvl/Documents/dev/release/cue/internal/core/export/export.go:204 +0x1c5
cuelang.org/go/cue.Value.Syntax(0xc0004393d0, 0xc0000d55f0, 0xc000213c18, 0x4, 0x4, 0xc0003a20c0, 0x0)
	/Users/mpvl/Documents/dev/release/cue/cue/types.go:972 +0x205
cuelang.org/go/cmd/cue/cmd.runEval(0xc00036b860, 0xc00036bfe0, 0x1, 0x2, 0x0, 0x0)
	/Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/eval.go:154 +0x687
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc0002b18c0, 0xc00036bfe0, 0x1, 0x2, 0x0, 0x0)
	/Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/root.go:46 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc0002b18c0, 0xc00036bfc0, 0x2, 0x2, 0xc0002b18c0, 0xc00036bfc0)
	/Users/mpvl/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002b1080, 0x0, 0x0, 0x0)
	/Users/mpvl/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/mpvl/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc00036b860, 0x199a280, 0xc0000a6008, 0x0, 0x0)
	/Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/root.go:206 +0x65
cuelang.org/go/cmd/cue/cmd.mainErr(0x199a280, 0xc0000a6008, 0xc0000a4050, 0x3, 0x3, 0x18dc6c0, 0xc0002fdf48)
	/Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/root.go:145 +0x8a
cuelang.org/go/cmd/cue/cmd.Main(0xc00008c058)
	/Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/root.go:127 +0x9c
main.main()
	/Users/mpvl/Documents/dev/release/cue/cmd/cue/main.go:24 +0x25
```

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/662#issuecomment-768271129_

Hey Sam, good to see you here. :) The optional output with eval is indeed a bit shoddy. No excuse for a panic, though, of course.

Background: eval is a bit an unprincipled output. cue def prints schemas and cue export --out cue prints concrete CUE output. eval was originally intended as a sort of in-between, optimized for debugging. The way CUE works, it makes it hard to define what an optional field means in this in-between state. We plan to clean up the semantics and streamline the output modes. Part of that is already done, but eval+optionals hasn't gotten much love. But again, a crash is not okay.

In the mean time, perhaps `cue def` can be of help.

**Comment by cueckoo** [comment]
_Original reply by @sdboyer in https://github.com/cuelang/cue/issues/662#issuecomment-768348772_

Glad to be here! i'm quite excited about what you appear to be aiming for with CUE. If i can figure out how to conform it to our needs, it's plausible that we could start using it for some pretty key in Grafana. Fortunately, the baby steps we need for now don't look terribly challenging :wink:

Totally understood on the intermediate form. Perhaps i'm overdrawing on my own experience areas and assuming they're analogous, but i can imagine attempting to define relations over optional fields could get hairy due to negation ambiguities/3VL-type problems.

No worries on the panic! The notion that, as you say, there exists a relative ordering of concreteness between `def`, `eval` and `export` is super useful, and really lights up something in my mind. As i've been spelunking CUE, i've formed the notion that degrees of concreteness are a foundational piece of both how CUE works, and how one ought to think about it in order to use it effectively. With that in mind, here's a quick attempt at making my lack-of-curse-of-knowledge hopefully useful for you.

i organically found my way to this particular use of `cue eval` just by relatively blindly following the [tutorial](https://cuelang.org/docs/tutorials/tour/intro/), where `cue eval` seemed to be what i was seeing most of the time. As i looked through `cue help`, it wasn't actually clear to me what i ought to use in order to illustrate my desired goal to some other folks - which, basically, is turning most of the declarations in a [file like this](https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/uPlot/config.ts) into something we can generate from CUE files. (i'm now prototyping a very simple generator to do exactly that.) I added the `-O` when i discovered that the optional fields - clearly, almost everything there - were omitted. (i then subsequently ran into #665 when experimenting with attributes in this same file, with the intent of feeding them to my custom generator.)

Again, this relative concreteness thing seems super important. Idk how feasible or valuable this is, but i'll throw it out there: the tutorials might be an opportunity to reflect that importance. While it wouldn't necessarily work well for all of the tutorial steps, i'm imagining that, rather than showing just one output (which seems a tad random as to whether `eval`, or `export` are used?), it could show all three. i'm picturing tabs on the output box akin to when code samples are given for a particular task in various languages, tabbed by language in the same box.
