### ISSUE TITLE
panic on '_a: 2, 1 | _a': assertion failed: invalid state for disjunct

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#755]
_Originally opened by @antong in https://github.com/cuelang/cue/issues/755_

Cue eval and export crash when presented with:
```
_a: 2
1  | _a
``` 

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.3.0-beta.4 windows/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes, 0.3.0-beta.4 is the latest at time of writing.

### What did you do?

```
echo '_a: 2, 1 | _a' | cue eval -
```

### What did you expect to see?
 
```
1 | 2
```

or perhaps
```
_|_ // conflicting values {(1 | _a), _a: 2} and (1 | 2) (mismatched types struct and int)
```

### What did you see instead?

```
panic: assertion failed: invalid state for disjunct
        panic: freeNode: nodeContext out of sync [recovered]
        panic: freeNode: nodeContext out of sync

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc0000cfec0)
        /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/root.go:221 +0x9a
panic(0x109d640, 0x12779e0)
        /usr/local/go/src/runtime/panic.go:969 +0x1c7
cuelang.org/go/internal/core/adt.(*Vertex).freeNode(0xc000400900, 0xc00036a700)
        /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:887 +0x13b
panic(0x109d640, 0xc0004080e0)
        /usr/local/go/src/runtime/panic.go:975 +0x499
cuelang.org/go/internal/core/adt.Assertf(...)
        /Users/mpvl/Documents/dev/release/cue/internal/core/adt/context.go:54
cuelang.org/go/internal/core/adt.clone(0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x1288440, 0x16b7280, 0x0, 0xc000
007d60, ...)
        /Users/mpvl/Documents/dev/release/cue/internal/core/adt/disjunct.go:422 +0x685
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0xc00036ae00, 0xc0004d9a05, 0xc00036a7
00, 0x0, 0xc000406201)
        /Users/mpvl/Documents/dev/release/cue/internal/core/adt/disjunct.go:134 +0x1818
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0xc00036a700, 0xc000400905, 0xc00036a7
00, 0x0, 0x0)
        /Users/mpvl/Documents/dev/release/cue/internal/core/adt/disjunct.go:265 +0x565
cuelang.org/go/internal/core/adt.(*OpContext).Unify(0xc00038cc30, 0xc000400900, 0x5)
        /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:309 +0x3ee
cuelang.org/go/internal/core/adt.(*Vertex).Finalize(...)
        /Users/mpvl/Documents/dev/release/cue/internal/core/adt/composite.go:438
cuelang.org/go/cue.(*Instance).Value(0xc00031e930, 0x6, 0xc000347880)
        /Users/mpvl/Documents/dev/release/cue/cue/instance.go:271 +0x67
cuelang.org/go/cmd/cue/cmd.buildInstances(0xc000347880, 0xc000207e00, 0x1, 0x1, 0xc000408030, 0xc0005b
cd50, 0xc0005bcd40)
        /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/common.go:561 +0x135
cuelang.org/go/cmd/cue/cmd.(*buildPlan).instances(0xc0002da180, 0x0, 0x0)
        /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/common.go:156 +0x5f
cuelang.org/go/cmd/cue/cmd.runEval(0xc000347880, 0xc000303460, 0x1, 0x1, 0x0, 0x0)
        /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/eval.go:113 +0x325
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc00029b8c0, 0xc000303460, 0x1, 0x1, 0x0, 0x0)
        /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/root.go:46 +0x73
github.com/spf13/cobra.(*Command).execute(0xc00029b8c0, 0xc000303450, 0x1, 0x1, 0xc00029b8c0, 0xc00030
3450)
        /Users/mpvl/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00029b080, 0x0, 0x0, 0x0)
        /Users/mpvl/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/mpvl/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc000347880, 0x12992e0, 0xc0000a40a0, 0x0, 0x0)
        /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/root.go:206 +0x6a
cuelang.org/go/cmd/cue/cmd.mainErr(0x12992e0, 0xc0000a40a0, 0xc000090050, 0x2, 0x3, 0x11dc2d0, 0xc0000
cff48)
        /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/root.go:145 +0x8f
cuelang.org/go/cmd/cue/cmd.Main(0xc000096058)
        /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/root.go:127 +0xa5
main.main()
        /Users/mpvl/Documents/dev/release/cue/cmd/cue/main.go:24 +0x29
```

**Comment by cueckoo** [comment]
_Original reply by @antong in https://github.com/cuelang/cue/issues/755#issuecomment-777800881_

Looks like this is fixed by b25147c.
