### ISSUE TITLE
panic with if

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#762]
_Originally opened by @ah-edg in https://github.com/cuelang/cue/issues/762_

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.3.0-beta.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What did you do?

run `cue eval test.cue` on this `test.cue`:

```
#Foo: {
	#bar: string
	{
		#bar: ""
	} | {
		#bar: != ""
	}
	if #bar != "" {}
}

foo: #Foo & {#bar: "x"}
```

### What did you expect to see?

No panic

### What did you see instead?

The panic below. It does not come without either the if or the concrete foo. It might be possible to reduce it further, but it's rather short as it is.
```
panic: assertion failed: invalid state for disjunct [recovered]
        panic: assertion failed: invalid state for disjunct

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc000349ec0)
        /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/root.go:221 +0x95
panic(0xba6480, 0xc00059e980)
        /usr/local/go/src/runtime/panic.go:969 +0x1b9
cuelang.org/go/internal/core/adt.Assertf(...)
        /Users/mpvl/Documents/dev/release/cue/internal/core/adt/context.go:54
cuelang.org/go/internal/core/adt.clone(0xc0000f0750, 0x268, 0x0, 0x1, 0x0, 0x0, 0xd92f80, 0x11c2280, 0x0, 0xc0004b13d0, ...)
        /Users/mpvl/Documents/dev/release/cue/internal/core/adt/disjunct.go:422 +0x665
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0xc0000ef180, 0xc0000f0905, 0xc0000ef180, 0x0, 0xdaad00)
        /Users/mpvl/Documents/dev/release/cue/internal/core/adt/disjunct.go:134 +0x17f8
cuelang.org/go/internal/core/adt.(*OpContext).Unify(0xc00059aea0, 0xc0000f0900, 0xc000348d05)
        /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:309 +0x3ee
cuelang.org/go/internal/core/adt.(*nodeContext).completeArcs(0xc0000eee00, 0x5)
        /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:645 +0x14a
cuelang.org/go/internal/core/adt.(*nodeContext).postDisjunct(0xc0000eee00, 0xbf1c05)
        /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:578 +0x49b
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0xc0000eee00, 0xc0000f0705, 0xc0000eee00, 0x0, 0x203000)
        /Users/mpvl/Documents/dev/release/cue/internal/core/adt/disjunct.go:142 +0x12a8
cuelang.org/go/internal/core/adt.(*OpContext).Unify(0xc00059aea0, 0xc0000f0750, 0x5)
        /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:309 +0x3ee
cuelang.org/go/internal/core/adt.(*Vertex).Finalize(...)
        /Users/mpvl/Documents/dev/release/cue/internal/core/adt/composite.go:438
cuelang.org/go/cue.(*Instance).Value(0xc0002e0540, 0x6, 0xc00030b7e0)
        /Users/mpvl/Documents/dev/release/cue/cue/instance.go:271 +0x65
cuelang.org/go/cmd/cue/cmd.buildInstances(0xc00030b7e0, 0xc0003c3c00, 0x1, 0x1, 0xc00059e830, 0xc0000b0220, 0xc0000b0210)
        /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/common.go:561 +0x131
cuelang.org/go/cmd/cue/cmd.(*buildPlan).instances(0xc000290180, 0x0, 0x0)
        /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/common.go:156 +0x58
cuelang.org/go/cmd/cue/cmd.runEval(0xc00030b7e0, 0xc0002c74f0, 0x1, 0x1, 0x0, 0x0)
        /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/eval.go:113 +0x318
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc0002418c0, 0xc0002c74f0, 0x1, 0x1, 0x0, 0x0)
        /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/root.go:46 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc0002418c0, 0xc0002c74c0, 0x1, 0x1, 0xc0002418c0, 0xc0002c74c0)
        /Users/mpvl/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000241080, 0x0, 0x0, 0x0)
        /Users/mpvl/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/mpvl/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc00030b7e0, 0xda40c0, 0xc0000360a8, 0x0, 0x0)
        /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/root.go:206 +0x65
cuelang.org/go/cmd/cue/cmd.mainErr(0xda40c0, 0xc0000360a8, 0xc0000300a0, 0x2, 0x2, 0xce6a28, 0xc00029bf48)
        /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/root.go:145 +0x8a
cuelang.org/go/cmd/cue/cmd.Main(0xc0000420b8)
        /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/root.go:127 +0x9c
main.main()
        /Users/mpvl/Documents/dev/release/cue/cmd/cue/main.go:24 +0x25
```

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cue/issues/762#issuecomment-778260090_

Like #764, this is fixed at tip (as of b25147c)

Thanks for the repro in any case.
