### ISSUE TITLE
panic on invalid disjunction state

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#764]
_Originally opened by @ah-edg in https://github.com/cuelang/cue/issues/764_

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.3.0-beta.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

yes

### What did you do?

run `cue eval test.cue` on this `test.cue`:
```
#Foo: {
	#bar: string
	{#bar == ""} | {#bar: != ""}
}
```

### What did you expect to see?

It's a mistake, but it should not panic but probably just embed a bool value when #bar is "" or report a warning or an error.

### What did you see instead?

This panic:
```panic: assertion failed: invalid state for disjunct
        panic: freeNode: nodeContext out of sync [recovered]
        panic: freeNode: nodeContext out of sync

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc000421ec0)
        /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/root.go:221 +0x95
panic(0xba6480, 0xd82340)
        /usr/local/go/src/runtime/panic.go:969 +0x1b9
cuelang.org/go/internal/core/adt.(*Vertex).freeNode(0xc0006ae7e0, 0xc0006ad180)
        /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:887 +0x132
panic(0xba6480, 0xc000289e00)
        /usr/local/go/src/runtime/panic.go:975 +0x47a
cuelang.org/go/internal/core/adt.Assertf(...)
        /Users/mpvl/Documents/dev/release/cue/internal/core/adt/context.go:54
cuelang.org/go/internal/core/adt.clone(0xc0006ae6c0, 0x263, 0x0, 0x10001, 0x0, 0x0, 0xd92f80, 0x11c2280, 0x0, 0xc00011f3c0, ...)
        /Users/mpvl/Documents/dev/release/cue/internal/core/adt/disjunct.go:422 +0x665
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0xc0006ad500, 0xc000395305, 0xc0006ad180, 0x0, 0xc000552601)
        /Users/mpvl/Documents/dev/release/cue/internal/core/adt/disjunct.go:134 +0x17f8
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0xc0006ad180, 0xc0006ae705, 0xc0006ad180, 0x0, 0x0)
        /Users/mpvl/Documents/dev/release/cue/internal/core/adt/disjunct.go:265 +0x545
cuelang.org/go/internal/core/adt.(*OpContext).Unify(0xc00055f930, 0xc0006ae7e0, 0xc000420d05)
        /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:309 +0x3ee
cuelang.org/go/internal/core/adt.(*nodeContext).completeArcs(0xc0006ace00, 0x5)
        /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:645 +0x14a
cuelang.org/go/internal/core/adt.(*nodeContext).postDisjunct(0xc0006ace00, 0xbf1c05)
        /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:578 +0x49b
cuelang.org/go/internal/core/adt.(*nodeContext).expandDisjuncts(0xc0006ace00, 0xc0006ae605, 0xc0006ace00, 0x0, 0x203000)
        /Users/mpvl/Documents/dev/release/cue/internal/core/adt/disjunct.go:142 +0x12a8
cuelang.org/go/internal/core/adt.(*OpContext).Unify(0xc00055f930, 0xc0006ae6c0, 0x5)
        /Users/mpvl/Documents/dev/release/cue/internal/core/adt/eval.go:309 +0x3ee
cuelang.org/go/internal/core/adt.(*Vertex).Finalize(...)
        /Users/mpvl/Documents/dev/release/cue/internal/core/adt/composite.go:438
cuelang.org/go/cue.(*Instance).Value(0xc0003bc540, 0x6, 0xc0003e57e0)
        /Users/mpvl/Documents/dev/release/cue/cue/instance.go:271 +0x65
cuelang.org/go/cmd/cue/cmd.buildInstances(0xc0003e57e0, 0xc000499b10, 0x1, 0x1, 0xc000289cf0, 0xc00052c5f0, 0xc00052c5e0)
        /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/common.go:561 +0x131
cuelang.org/go/cmd/cue/cmd.(*buildPlan).instances(0xc000370180, 0x0, 0x0)
        /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/common.go:156 +0x58
cuelang.org/go/cmd/cue/cmd.runEval(0xc0003e57e0, 0xc0003a34e0, 0x1, 0x1, 0x0, 0x0)
        /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/eval.go:113 +0x318
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc00032f8c0, 0xc0003a34e0, 0x1, 0x1, 0x0, 0x0)
        /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/root.go:46 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc00032f8c0, 0xc0003a34b0, 0x1, 0x1, 0xc00032f8c0, 0xc0003a34b0)
        /Users/mpvl/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00032f080, 0x0, 0x0, 0x0)
        /Users/mpvl/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/mpvl/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc0003e57e0, 0xda40c0, 0xc00011a030, 0x0, 0x0)
        /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/root.go:206 +0x65
cuelang.org/go/cmd/cue/cmd.mainErr(0xda40c0, 0xc00011a030, 0xc00010a070, 0x2, 0x2, 0xce6a28, 0xc00037bf48)
        /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/root.go:145 +0x8a
cuelang.org/go/cmd/cue/cmd.Main(0xc000102058)
        /Users/mpvl/Documents/dev/release/cue/cmd/cue/cmd/root.go:127 +0x9c
main.main()
        /Users/mpvl/Documents/dev/release/cue/cmd/cue/main.go:24 +0x25
```

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cue/issues/764#issuecomment-778243773_

This is fixed at tip (as of b25147c31717259f0daec8de3636c1e04968b892)

Thanks for the repro in any case.
