### ISSUE TITLE
panic on cue vet

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#767]
_Originally opened by @ah-edg in https://github.com/cuelang/cue/issues/767_

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.3.0-beta.5 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
yes

### What did you do?
`cue vet test.cue` on this `test.cue` (other commands fail, too)
```
#Foo: {
	let _#bar = {
        value: ""
	}
	let _#volmnts = {
        x: _#baz.value
	}
	let _#baz = {
		_#bar
	}
}
```

### What did you expect to see?

no panic

### What did you see instead?
this panic:
```
panic: expected nil field [recovered]
        panic: expected nil field

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc0003a1ec0)
        /home/runner/work/cue/cue/cmd/cue/cmd/root.go:221 +0x95
panic(0xba9500, 0xd85710)
        /opt/hostedtoolcache/go/1.15.8/x64/src/runtime/panic.go:969 +0x1b9
cuelang.org/go/internal/core/compile.(*compiler).labeledExpr(0xc0004d1930, 0x0, 0xd96380, 0xc0004d3b80, 0xdaf320, 0xc0004d3b30, 0xc00039ff88, 0x71dc25)
        /home/runner/work/cue/cue/internal/core/compile/compile.go:757 +0x266
cuelang.org/go/internal/core/compile.compiler.lookupAlias(0x0, 0x0, 0xca63d4, 0x4, 0xd9c940, 0xc0004cdd80, 0xc0001c2460, 0x3, 0x4, 0x1, ...)
        /home/runner/work/cue/cue/internal/core/compile/compile.go:208 +0x2e6
cuelang.org/go/internal/core/compile.(*compiler).resolve(0xc0004d1860, 0xc0004d3590, 0x28, 0x28)
        /home/runner/work/cue/cue/internal/core/compile/compile.go:415 +0x554
cuelang.org/go/internal/core/compile.(*compiler).expr(0xc0004d1860, 0xdaf020, 0xc0004d3590, 0xc0004d6ab0, 0x18)
        /home/runner/work/cue/cue/internal/core/compile/compile.go:775 +0x827
cuelang.org/go/internal/core/compile.(*compiler).expr(0xc0004d1860, 0xdaf260, 0xc0004d67b0, 0xc088e0, 0x11e0780)
        /home/runner/work/cue/cue/internal/core/compile/compile.go:811 +0x657
cuelang.org/go/internal/core/compile.(*compiler).labeledExpr(0xc0004d1860, 0xc00033b1f0, 0xd96340, 0xc00033b1f0, 0xdaf260, 0xc0004d67b0, 0xbf4a40, 0xc0004d6ab0)
        /home/runner/work/cue/cue/internal/core/compile/compile.go:764 +0x13a
cuelang.org/go/internal/core/compile.(*compiler).decl(0xc0004d1860, 0xdadb80, 0xc00033b1f0, 0x0, 0x0)
        /home/runner/work/cue/cue/internal/core/compile/compile.go:541 +0xf8
cuelang.org/go/internal/core/compile.(*compiler).addDecls(0xc0004d1860, 0xc0004d87e0, 0xc0004af820, 0x1, 0x1)
        /home/runner/work/cue/cue/internal/core/compile/compile.go:482 +0x13f
cuelang.org/go/internal/core/compile.(*compiler).expr(0xc0004d1860, 0xdaf320, 0xc0004d3720, 0xda9b00, 0x41409b)
        /home/runner/work/cue/cue/internal/core/compile/compile.go:780 +0x196d
cuelang.org/go/internal/core/compile.(*compiler).labeledExpr(0xc0004d1860, 0x0, 0xd96380, 0xc0004d3770, 0xdaf320, 0xc0004d3720, 0xda9b00, 0xc0004d8750)
        /home/runner/work/cue/cue/internal/core/compile/compile.go:764 +0x13a
cuelang.org/go/internal/core/compile.(*compiler).addLetDecl(0xc0004d1860, 0xdade20, 0xc0004d3770)
        /home/runner/work/cue/cue/internal/core/compile/compile.go:638 +0x2a5
cuelang.org/go/internal/core/compile.(*compiler).addDecls(0xc0004d1860, 0xc0004d86c0, 0xc0004ceb80, 0x3, 0x4)
        /home/runner/work/cue/cue/internal/core/compile/compile.go:479 +0xda
cuelang.org/go/internal/core/compile.(*compiler).expr(0xc0004d1860, 0xdaf320, 0xc0004d3bd0, 0x0, 0x0)
        /home/runner/work/cue/cue/internal/core/compile/compile.go:780 +0x196d
cuelang.org/go/internal/core/compile.(*compiler).labeledExpr(0xc0004d1860, 0xc00033b030, 0xd96340, 0xc00033b030, 0xdaf320, 0xc0004d3bd0, 0x4, 0x4b)
        /home/runner/work/cue/cue/internal/core/compile/compile.go:764 +0x13a
cuelang.org/go/internal/core/compile.(*compiler).decl(0xc0004d1860, 0xdadb80, 0xc00033b030, 0x0, 0x0)
        /home/runner/work/cue/cue/internal/core/compile/compile.go:541 +0xf8
cuelang.org/go/internal/core/compile.(*compiler).addDecls(0xc0004d1860, 0xc0004d8630, 0xc0004af850, 0x1, 0x1)
        /home/runner/work/cue/cue/internal/core/compile/compile.go:482 +0x13f
cuelang.org/go/internal/core/compile.(*compiler).compileFiles(0xc0004d1860, 0xc000417ae8, 0x1, 0x1, 0x0)
        /home/runner/work/cue/cue/internal/core/compile/compile.go:275 +0x52b
cuelang.org/go/internal/core/compile.Files(0x0, 0xda9c80, 0xc0004cdd80, 0x0, 0x0, 0xc000417ae8, 0x1, 0x1, 0x30, 0xc701a0, ...)
        /home/runner/work/cue/cue/internal/core/compile/compile.go:58 +0x115
cuelang.org/go/internal/core/runtime.(*Runtime).Build(0xc0004cdd80, 0xc00036c500, 0x0, 0x0, 0x0)
        /home/runner/work/cue/cue/internal/core/runtime/build.go:56 +0x211
cuelang.org/go/cue.(*index).loadInstance(0xc0004af8d0, 0xc00036c500, 0x0)
        /home/runner/work/cue/cue/cue/build.go:233 +0x38
cuelang.org/go/cue.(*Runtime).build(0xc0003a1a68, 0xc000417af8, 0x1, 0x1, 0x40d790, 0xc00035bb90, 0xc000417af0, 0x203000, 0xc00036c500)
        /home/runner/work/cue/cue/cue/build.go:177 +0x13f
cuelang.org/go/cue.Build(0xc000417af8, 0x1, 0x1, 0xc000358a40, 0x40, 0x38)
        /home/runner/work/cue/cue/cue/build.go:162 +0x5a
cuelang.org/go/cmd/cue/cmd.buildInstances(0xc00035dd40, 0xc000417af8, 0x1, 0x1, 0xc0003862d0, 0xcadba2, 0xc000307b60)
        /home/runner/work/cue/cue/cmd/cue/cmd/common.go:546 +0x4c
cuelang.org/go/cmd/cue/cmd.(*buildPlan).instances(0xc00012e240, 0x0, 0x0)
        /home/runner/work/cue/cue/cmd/cue/cmd/common.go:156 +0x58
cuelang.org/go/cmd/cue/cmd.doVet(0xc00035dd40, 0xc0001e3cd0, 0x1, 0x1, 0x0, 0x0)
        /home/runner/work/cue/cue/cmd/cue/cmd/vet.go:107 +0xf2
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc00037fb80, 0xc0001e3cd0, 0x1, 0x1, 0x0, 0x0)
        /home/runner/work/cue/cue/cmd/cue/cmd/root.go:46 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc00037fb80, 0xc0001e3ca0, 0x1, 0x1, 0xc00037fb80, 0xc0001e3ca0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001bb080, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc00035dd40, 0xda7400, 0xc0000bc030, 0x0, 0x0)
        /home/runner/work/cue/cue/cmd/cue/cmd/root.go:206 +0x65
cuelang.org/go/cmd/cue/cmd.mainErr(0xda7400, 0xc0000bc030, 0xc0000ac070, 0x2, 0x2, 0xce9a00, 0xc000307f48)
        /home/runner/work/cue/cue/cmd/cue/cmd/root.go:145 +0x8a
cuelang.org/go/cmd/cue/cmd.Main(0xc0000a4058)
        /home/runner/work/cue/cue/cmd/cue/cmd/root.go:127 +0x9c
main.main()
        /home/runner/work/cue/cue/cmd/cue/main.go:24 +0x25
```

**Comment by cueckoo** [comment]
_Original reply by @mpvl in https://github.com/cuelang/cue/issues/767#issuecomment-779255144_

Analysis: this is a compiler bug! Here is a smaller reproducer:
```
let X = { value: Y }
let Y = ""
```
