### ISSUE TITLE
cmd/cue: cmd panics when _tool.cue file contains import with no non-_tool.cue files

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#869]
_Originally opened by @bowsersenior in https://github.com/cuelang/cue/issues/869_

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version 0.3.0-beta.8 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes

### What did you do?

```
# inside cue repo root folder, on latest commit as of April 1, 2021
$ git rev-parse head
2115955add8edcd083bffcea45bbe249415e2354

# go into test folder where issue can be reproduced
$ cd cue/load/testdata/

# create foo_with_import_tool.cue to reproduce the issue
$ cat <<EOF > toolonly/foo_with_import_tool.cue
> package foo_with_import

import (
  "tool/cli"
  "example.org/test/sub"
)

command: foo: task: {
        foo: cli.Print & {
                text: "Hello \(sub.User)!"
        }
}
> EOF

# run the foo cmd
$ cue cmd foo toolonly/foo_with_import_tool.cue 
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
...

# foo_tool.cue is fine since it has no imports
$ cat toolonly/foo_tool.cue 
package foo

import "tool/cli"

command: foo: task: {
	foo: cli.Print & {
		text: "foo"
	}
}
$ cue cmd foo toolonly/foo_tool.cue
foo

# same import of "example.org/test/sub" works in a non-tool file
$ cat test.cue 
package test

import "example.org/test/sub"

out: "Hello \(sub.User)!"
$ cue eval test.cue 
out: "Hello sub!"
```

### What did you expect to see?

```
$ cue cmd foo toolonly/foo_with_import_tool.cue 
Hello sub
```

### What did you see instead?

```
$ cue cmd foo toolonly/foo_with_import_tool.cue 
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x12d1b94]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc00039dec0)
	/home/runner/work/cue/cue/cmd/cue/cmd/root.go:221 +0x95
panic(0x17df160, 0x1dc3e90)
	/opt/hostedtoolcache/go/1.15.10/x64/src/runtime/panic.go:969 +0x1b9
cuelang.org/go/internal/core/dep.visit.func1(0xc00039d788, 0xc00039d800)
	/home/runner/work/cue/cue/internal/core/dep/dep.go:120 +0xcd
panic(0x17df160, 0x1dc3e90)
	/opt/hostedtoolcache/go/1.15.10/x64/src/runtime/panic.go:969 +0x1b9
cuelang.org/go/internal/core/adt.(*OpContext).Resolve(0xc0004c5ba0, 0xc00034f180, 0xa44f240, 0xc0002c70f0, 0xc00039d4c0, 0x100b34a)
	/home/runner/work/cue/cue/internal/core/adt/context.go:411 +0x134
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0xc00039d788, 0xc00034f180, 0xa44f240, 0xc0002c70f0)
	/home/runner/work/cue/cue/internal/core/dep/dep.go:223 +0x1a5
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc00039d788, 0xc00034f180, 0x19aa820, 0xc0002c70f0)
	/home/runner/work/cue/cue/internal/core/dep/dep.go:150 +0x912
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0xc00039d788, 0xc00034f180, 0x19a4b20, 0xc0002f1480)
	/home/runner/work/cue/cue/internal/core/dep/dep.go:254 +0x2d4
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc00039d788, 0xc00034f180, 0x19aaaa0, 0xc0002f1480)
	/home/runner/work/cue/cue/internal/core/dep/dep.go:150 +0x912
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc00039d788, 0xc00034f180, 0x19aa8a0, 0xc000317170)
	/home/runner/work/cue/cue/internal/core/dep/dep.go:161 +0x4f2
cuelang.org/go/internal/core/dep.visit(0xc0004c5ba0, 0xc0003523f0, 0xc000359220, 0xc000390000, 0x0, 0x0)
	/home/runner/work/cue/cue/internal/core/dep/dep.go:125 +0x1a9
cuelang.org/go/internal/core/dep.dynamic(0xc0004c5ba0, 0xc0003523f0, 0xc000359220, 0xc00039d988, 0x0)
	/home/runner/work/cue/cue/internal/core/dep/mixed.go:43 +0x17b
cuelang.org/go/internal/core/dep.dynamic(0xc0004c5ba0, 0xc0003218c0, 0xc000359220, 0xc00039d988, 0xc00039da01)
	/home/runner/work/cue/cue/internal/core/dep/mixed.go:48 +0x1e5
cuelang.org/go/internal/core/dep.VisitFields(0xc0004c5ba0, 0xc0003218c0, 0xc000359220, 0xc0002c7bb0, 0xc0002c7bb0)
	/home/runner/work/cue/cue/internal/core/dep/dep.go:91 +0xed
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies(0xc0004c5c70, 0xc000298460, 0xc0003218c0)
	/home/runner/work/cue/cue/tools/flow/tasks.go:225 +0x77
cuelang.org/go/tools/flow.(*Controller).initTasks(0xc0004c5c70)
	/home/runner/work/cue/cue/tools/flow/tasks.go:50 +0xed
cuelang.org/go/tools/flow.New(0xc00039dbd0, 0xc000310a10, 0xc0002c76d0, 0x0)
	/home/runner/work/cue/cue/tools/flow/flow.go:216 +0x1c5
cuelang.org/go/cmd/cue/cmd.doTasks(0xc000335e60, 0x18a9364, 0x7, 0xc000295e00, 0x3, 0xc000310a10, 0xc00039dca0, 0xc00039dca0)
	/home/runner/work/cue/cue/cmd/cue/cmd/custom.go:134 +0x12a
cuelang.org/go/cmd/cue/cmd.addCustom.func1(0xc000335e60, 0xc0002c76a0, 0x1, 0x1, 0x11fc460, 0xc00039dc88)
	/home/runner/work/cue/cue/cmd/cue/cmd/custom.go:118 +0x58
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc0003642c0, 0xc0002c76a0, 0x1, 0x1, 0x0, 0x0)
	/home/runner/work/cue/cue/cmd/cue/cmd/root.go:46 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc0003642c0, 0xc0002c7670, 0x1, 0x1, 0xc0003642c0, 0xc0002c7670)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00028f080, 0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc000335e60, 0x19a83a0, 0xc000036088, 0x0, 0x0)
	/home/runner/work/cue/cue/cmd/cue/cmd/root.go:206 +0x65
cuelang.org/go/cmd/cue/cmd.mainErr(0x19a83a0, 0xc000036088, 0xc000030090, 0x3, 0x3, 0x18e9860, 0xc0002d7f48)
	/home/runner/work/cue/cue/cmd/cue/cmd/root.go:145 +0x8a
cuelang.org/go/cmd/cue/cmd.Main(0xc0000380b8)
	/home/runner/work/cue/cue/cmd/cue/cmd/root.go:127 +0x9c
main.main()
	/home/runner/work/cue/cue/cmd/cue/main.go:24 +0x25
```

**Comment by cueckoo** [comment]
_Original reply by @bowsersenior in https://github.com/cuelang/cue/issues/869#issuecomment-812186767_

After poking around a bit, the underlying error seems to be the following:

```
command.foo.task.foo.text: invalid string argument: invalid interpolation: "example.org/test/sub".User undefined ("example.org/test/sub" is incomplete):
    ./toolonly/foo_with_import_tool.cue:9:2
    ./toolonly/foo_with_import_tool.cue:10:3
    tool/cli:4:3
```

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cue/issues/869#issuecomment-812427561_

@bowsersenior this actually appears to be more related to whether or not there is a non-`_tool.cue` file:

```
# cue eval with x.cue and x_tool.cue
exec cue eval
cmp stdout cue_eval.golden

# cue cmd foo with x.cue and x_tool.cue
exec cue cmd foo
cmp stdout cue_cmd_foo_both.golden

rm x.cue

# cue cmd foo with ONLY x_tool.cue
exec cue cmd foo
cmp stdout cue_cmd_foo_both.golden

-- cue.mod/module.cue --
module: "example.org/test"
-- sub/sub.cue --
package sub

User: "sub"
-- x.cue --
package x

import "example.org/test/sub"

x: sub.User
-- x_tool.cue --
package x

import (
	"tool/cli"

	"example.org/test/sub"
)

command: foo: cli.Print & {
	text: "test \(sub.User)"
}
-- cue_eval.golden --
x: "sub"
-- cue_cmd_foo_both.golden --
test sub
```

### What did you expect to see?

The above test to pass. A non-`_tool.cue` file should not be required.

### What did you see instead?

The following panic:

```
# cue eval with x.cue and x_tool.cue (0.055s)
# cue cmd foo with x.cue and x_tool.cue (0.052s)
# cue cmd foo with ONLY x_tool.cue (0.046s)
> exec cue cmd foo
[stderr]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x6b2115]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc0003f1ec0)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:221 +0x9d
panic(0xb97b40, 0x1135650)
        /home/myitcv/gos/src/runtime/panic.go:983 +0x25b
cuelang.org/go/internal/core/dep.visit.func1(0xc0003f17d8, 0xc0003f1850)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:120 +0xdb
panic(0xb97b40, 0x1135650)
        /home/myitcv/gos/src/runtime/panic.go:983 +0x25b
cuelang.org/go/internal/core/adt.(*OpContext).Resolve(0xc0007805b0, 0xc000091ef0, 0x7fbcd43671b0, 0xc000229ab0, 0xc0003f1538, 0x40d9ec)
        /home/myitcv/dev/cuelang/cue/internal/core/adt/context.go:411 +0x195
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0xc0003f17d8, 0xc000091ef0, 0x7fbcd43671b0, 0xc000229ab0)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:223 +0xe5
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc0003f17d8, 0xc000091ef0, 0xd629b8, 0xc000229ab0)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:150 +0x5af
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0xc0003f17d8, 0xc000091ef0, 0xd5da78, 0xc0005381e0)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:254 +0x21a
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc0003f17d8, 0xc000091ef0, 0xd62c38, 0xc0005381e0)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:150 +0x5af
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc0003f17d8, 0xc000091ef0, 0xd62a38, 0xc00062d2f0)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:161 +0x645
cuelang.org/go/internal/core/dep.visit(0xc0007805b0, 0xc00007cab0, 0xc000597050, 0xc0003f0000, 0x0, 0x0)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:125 +0x254
cuelang.org/go/internal/core/dep.dynamic(0xc0007805b0, 0xc00007cab0, 0xc000597050, 0xc0003f19a8, 0x0)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/mixed.go:43 +0x1e5
cuelang.org/go/internal/core/dep.dynamic(0xc0007805b0, 0xc00007c000, 0xc000597050, 0xc0003f19a8, 0x1)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/mixed.go:48 +0x259
cuelang.org/go/internal/core/dep.VisitFields(0xc0007805b0, 0xc00007c000, 0xc000597050, 0xc000592480, 0xc000592480)
        /home/myitcv/dev/cuelang/cue/internal/core/dep/dep.go:91 +0xf6
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies(0xc000780680, 0xc0002d4460, 0xc00007c000)
        /home/myitcv/dev/cuelang/cue/tools/flow/tasks.go:225 +0x95
cuelang.org/go/tools/flow.(*Controller).initTasks(0xc000780680)
        /home/myitcv/dev/cuelang/cue/tools/flow/tasks.go:50 +0x149
cuelang.org/go/tools/flow.New(0xc0003f1be0, 0xc000362c40, 0xc0005921c0, 0x0)
        /home/myitcv/dev/cuelang/cue/tools/flow/flow.go:216 +0x233
cuelang.org/go/cmd/cue/cmd.doTasks(0xc00039c120, 0xc6115f, 0x7, 0xc00003b3e7, 0x3, 0xc000362c40, 0xc0003f1cb0, 0xc0003f1cb0)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/custom.go:134 +0x14d
cuelang.org/go/cmd/cue/cmd.addCustom.func1(0xc00039c120, 0x1189dd8, 0x0, 0x0, 0x5dbe80, 0xc0003f1c98)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/custom.go:118 +0x58
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc0003b8580, 0x1189dd8, 0x0, 0x0, 0x0, 0x0)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:46 +0x74
github.com/spf13/cobra.(*Command).execute(0xc0003b8580, 0x1189dd8, 0x0, 0x0, 0xc0003b8580, 0x1189dd8)
        /home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x8dc
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002cd340, 0x0, 0x0, 0x0)
        /home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x525
github.com/spf13/cobra.(*Command).Execute(...)
        /home/myitcv/gostuff/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc00039c120, 0xd606d0, 0xc000124030, 0x0, 0x0)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:206 +0x67
cuelang.org/go/cmd/cue/cmd.mainErr(0xd606d0, 0xc000124030, 0xc00011c070, 0x2, 0x2, 0xc00005a740, 0x467867)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:145 +0x8d
cuelang.org/go/cmd/cue/cmd.Main(0xc00010e058)
        /home/myitcv/dev/cuelang/cue/cmd/cue/cmd/root.go:127 +0x9b
main.main()
        /home/myitcv/dev/cuelang/cue/cmd/cue/main.go:24 +0x25
[exit status 2]
FAIL: /tmp/testscript353063449/repro.txt/script.txt:12: unexpected command failure
```

**Comment by cueckoo** [comment]
_Original reply by @bowsersenior in https://github.com/cuelang/cue/issues/869#issuecomment-812601923_

Thanks for fixing this so quickly. I updated to 0.3.0 and confirm the issue is resolved.
