### ISSUE TITLE
cmd/cmd: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by cueckoo** [cue-lang/cue#871]
_Originally opened by @galo2099 in https://github.com/cuelang/cue/issues/871_

### What version of CUE are you using (`cue version`)?

<pre>
$ cue version
cue version v0.3.0-beta.8 darwin/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What did you do?
Ran a custom cue cmd. I don't have a small repro but the stack trace may be enough to see the error.

### What did you expect to see?

success

### What did you see instead?

<pre>
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x12be87f]

goroutine 1 [running]:
cuelang.org/go/cmd/cue/cmd.recoverError(0xc000b23ec0)
	/Users/robsonaraujo/work/cue/cmd/cue/cmd/root.go:221 +0xa3
panic(0x17bd160, 0x1efebe0)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:969 +0x166
cuelang.org/go/internal/core/dep.visit.func1(0xc000b23788, 0xc000b23800)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:120 +0xcd
panic(0x17bd160, 0x1efebe0)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:969 +0x166
cuelang.org/go/internal/core/dep.visit.func1(0xc000b23260, 0xc000b232d8)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:120 +0xcd
panic(0x17bd160, 0x1efebe0)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:969 +0x166
cuelang.org/go/internal/core/dep.visit.func1(0xc000b22900, 0xc000b22978)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:120 +0xcd
panic(0x17bd160, 0x1efebe0)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:969 +0x166
cuelang.org/go/internal/core/dep.visit.func1(0xc000b223d8, 0xc000b22450)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:120 +0xcd
panic(0x17bd160, 0x1efebe0)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:969 +0x166
cuelang.org/go/internal/core/adt.(*OpContext).Resolve(0xc000b34410, 0xc0001627d0, 0x6382b60, 0xc0002aa670, 0x18592, 0x0)
	/Users/robsonaraujo/work/cue/internal/core/adt/context.go:411 +0x12f
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0xc000b223d8, 0xc0001627d0, 0x6382b60, 0xc0002aa670)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:223 +0x1bd
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc000b223d8, 0xc0001627d0, 0x19ccc20, 0xc0002aa670)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:150 +0x952
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0xc000b223d8, 0xc0001627d0, 0x19c6ca0, 0xc0005a1920)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:254 +0x34e
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc000b223d8, 0xc0001627d0, 0x19ccea0, 0xc0005a1920)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:150 +0x952
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc000b223d8, 0xc0001627d0, 0x19ccaa0, 0xc000494ae0)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:172 +0x3b7
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc000b223d8, 0xc0001627d0, 0x19ccaa0, 0xc000494ab0)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:172 +0x3b7
cuelang.org/go/internal/core/dep.visit(0xc000b34410, 0xc0006c7d40, 0xc000739ce0, 0xc000b20000, 0x0, 0x0)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:125 +0x1b8
cuelang.org/go/internal/core/dep.dynamic(0xc000b34410, 0xc0006c7d40, 0xc000739ce0, 0xc000b225d8, 0x0)
	/Users/robsonaraujo/work/cue/internal/core/dep/mixed.go:43 +0x164
cuelang.org/go/internal/core/dep.dynamic(0xc000b34410, 0xc00054c7e0, 0xc000739ce0, 0xc000b225d8, 0xc000b22601)
	/Users/robsonaraujo/work/cue/internal/core/dep/mixed.go:48 +0x1cc
cuelang.org/go/internal/core/dep.VisitFields(0xc000b34410, 0xc00054c7e0, 0xc000739ce0, 0xbde87af7a42981c4, 0x19ccbe0)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:91 +0xdd
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies(0xc000b344e0, 0xc0000de460, 0xc00054c7e0)
	/Users/robsonaraujo/work/cue/tools/flow/tasks.go:225 +0x77
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies.func1(0xc00054c7e0, 0x63644b0, 0xc000592990, 0xc000592901, 0xc00054c7e0, 0x0)
	/Users/robsonaraujo/work/cue/tools/flow/tasks.go:241 +0x1e1
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0xc000b22900, 0xc0009f6910, 0x63644b0, 0xc000592990)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:230 +0x20f
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc000b22900, 0xc0009f6910, 0x19ccbe0, 0xc000592990)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:150 +0x952
cuelang.org/go/internal/core/dep.visit(0xc000b34410, 0xc000929200, 0xc000739cc0, 0xc000b20100, 0x0, 0x0)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:125 +0x1b8
cuelang.org/go/internal/core/dep.dynamic(0xc000b34410, 0xc000929200, 0xc000739cc0, 0xc000b22a40, 0xc000b22a01)
	/Users/robsonaraujo/work/cue/internal/core/dep/mixed.go:43 +0x164
cuelang.org/go/internal/core/dep.VisitFields(0xc000b34410, 0xc000929200, 0xc000739cc0, 0xed352609db7022bd, 0x19ccbe0)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:91 +0xdd
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies(0xc000b344e0, 0xc0000de460, 0xc000929200)
	/Users/robsonaraujo/work/cue/tools/flow/tasks.go:225 +0x77
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies.func1(0xc000929200, 0x63644b0, 0xc0003bd390, 0xc0003bd301, 0xc000929200, 0x0)
	/Users/robsonaraujo/work/cue/tools/flow/tasks.go:241 +0x1e1
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0xc000b23260, 0xc0009bc140, 0x63644b0, 0xc0003bd390)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:230 +0x20f
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc000b23260, 0xc0009bc140, 0x19ccbe0, 0xc0003bd390)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:150 +0x952
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0xc000b23260, 0xc0009bc140, 0x19c6b60, 0xc0002c12f0)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:250 +0x2ca
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc000b23260, 0xc0009bc140, 0x19ccc60, 0xc0002c12f0)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:150 +0x952
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc000b23260, 0xc0009bc140, 0x19cc8a0, 0xc0002c1320)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:153 +0x8e9
cuelang.org/go/internal/core/dep.(*visitor).markYielder(0xc000b23260, 0xc0009bc140, 0x19c6b20, 0xc0002c1350)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:317 +0x2bf
cuelang.org/go/internal/core/dep.(*visitor).markDecl(0xc000b23260, 0xc0009bc140, 0x6382008, 0xc0002c1350)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:290 +0xbb
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc000b23260, 0xc0009bc0f0, 0x19ccf60, 0xc0001f0870)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:206 +0x6c1
cuelang.org/go/internal/core/dep.(*visitor).markYielder(0xc000b23260, 0xc0009bc0f0, 0x19c6ce0, 0xc0002cb680)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:322 +0x178
cuelang.org/go/internal/core/dep.(*visitor).markYielder(0xc000b23260, 0xc0009f7ef0, 0x19c6ae0, 0xc0002c12c0)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:307 +0xfa
cuelang.org/go/internal/core/dep.(*visitor).markDecl(0xc000b23260, 0xc0009f7ef0, 0x19c6aa0, 0xc0002c12c0)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:290 +0xbb
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc000b23260, 0xc0009f67d0, 0x19ccf60, 0xc0001f07e0)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:206 +0x6c1
cuelang.org/go/internal/core/dep.visit(0xc000b34410, 0xc000929320, 0xc000739c40, 0xc000390100, 0x0, 0x0)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:125 +0x1b8
cuelang.org/go/internal/core/dep.dynamic(0xc000b34410, 0xc000929320, 0xc000739c40, 0xc000b233a0, 0xc000b23401)
	/Users/robsonaraujo/work/cue/internal/core/dep/mixed.go:43 +0x164
cuelang.org/go/internal/core/dep.VisitFields(0xc000b34410, 0xc000929320, 0xc000739c40, 0x45a2dc7416d816e5, 0x0)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:91 +0xdd
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies(0xc000b344e0, 0xc0000de460, 0xc000929320)
	/Users/robsonaraujo/work/cue/tools/flow/tasks.go:225 +0x77
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies.func1(0xc000929320, 0x19c6ca0, 0xc000616f80, 0xc000616f00, 0xc000929320, 0x0)
	/Users/robsonaraujo/work/cue/tools/flow/tasks.go:241 +0x1e1
cuelang.org/go/internal/core/dep.(*visitor).markResolver(0xc000b23788, 0xc000205720, 0x19c6ca0, 0xc000616f80)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:230 +0x20f
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc000b23788, 0xc000205720, 0x19ccea0, 0xc000616f80)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:150 +0x952
cuelang.org/go/internal/core/dep.(*visitor).markExpr(0xc000b23788, 0xc000205720, 0x19ccaa0, 0xc0004b10b0)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:172 +0x3b7
cuelang.org/go/internal/core/dep.visit(0xc000b34410, 0xc0007e3680, 0xc0007a3600, 0xc000b20000, 0x0, 0x0)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:125 +0x1b8
cuelang.org/go/internal/core/dep.dynamic(0xc000b34410, 0xc0007e3680, 0xc0007a3600, 0xc000b23988, 0x0)
	/Users/robsonaraujo/work/cue/internal/core/dep/mixed.go:43 +0x164
cuelang.org/go/internal/core/dep.dynamic(0xc000b34410, 0xc0007e2900, 0xc0007a3600, 0xc000b23988, 0xc000b23a01)
	/Users/robsonaraujo/work/cue/internal/core/dep/mixed.go:48 +0x1cc
cuelang.org/go/internal/core/dep.VisitFields(0xc000b34410, 0xc0007e2900, 0xc0007a3600, 0xc0007d2f90, 0xc0007d2f90)
	/Users/robsonaraujo/work/cue/internal/core/dep/dep.go:91 +0xdd
cuelang.org/go/tools/flow.(*Controller).markTaskDependencies(0xc000b344e0, 0xc0000de460, 0xc0007e2900)
	/Users/robsonaraujo/work/cue/tools/flow/tasks.go:225 +0x77
cuelang.org/go/tools/flow.(*Controller).initTasks(0xc000b344e0)
	/Users/robsonaraujo/work/cue/tools/flow/tasks.go:50 +0xed
cuelang.org/go/tools/flow.New(0xc000b23bd0, 0xc0006a65b0, 0xc000642300, 0x0)
	/Users/robsonaraujo/work/cue/tools/flow/flow.go:216 +0x1b8
cuelang.org/go/cmd/cue/cmd.doTasks(0xc00038f860, 0x188f48f, 0x7, 0x7ffeefbff942, 0xb, 0xc0006a65b0, 0xc000b23ca0, 0xc000b23ca0)
	/Users/robsonaraujo/work/cue/cmd/cue/cmd/custom.go:134 +0x138
cuelang.org/go/cmd/cue/cmd.addCustom.func1(0xc00038f860, 0x1f4e5c0, 0x0, 0x0, 0x11ef2e0, 0xc000b23c88)
	/Users/robsonaraujo/work/cue/cmd/cue/cmd/custom.go:118 +0x58
cuelang.org/go/cmd/cue/cmd.mkRunE.func1(0xc0000d8580, 0x1f4e5c0, 0x0, 0x0, 0x0, 0x0)
	/Users/robsonaraujo/work/cue/cmd/cue/cmd/root.go:46 +0x6c
github.com/spf13/cobra.(*Command).execute(0xc0000d8580, 0x1f4e5c0, 0x0, 0x0, 0xc0000d8580, 0x1f4e5c0)
	/Users/robsonaraujo/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000d9080, 0x0, 0x0, 0x0)
	/Users/robsonaraujo/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/robsonaraujo/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
cuelang.org/go/cmd/cue/cmd.(*Command).Run(0xc00038f860, 0x19ca5e0, 0xc00011c008, 0x0, 0x0)
	/Users/robsonaraujo/work/cue/cmd/cue/cmd/root.go:206 +0x63
cuelang.org/go/cmd/cue/cmd.mainErr(0x19ca5e0, 0xc00011c008, 0xc000126010, 0x1, 0x1, 0x18cee18, 0xc000323f48)
	/Users/robsonaraujo/work/cue/cmd/cue/cmd/root.go:145 +0x88
cuelang.org/go/cmd/cue/cmd.Main(0xc000182058)
	/Users/robsonaraujo/work/cue/cmd/cue/cmd/root.go:127 +0x9c
main.main()
	/Users/robsonaraujo/work/cue/cmd/cue/main.go:24 +0x22</pre>

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cue/issues/871#issuecomment-812404373_

@galo2099 please can you share a repro for this? Unfortunately a stack trace is rarely sufficient to track down the root cause. A non-minimal repro is fine - we can always iterate on that.

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cue/issues/871#issuecomment-812440450_

The top of this stack trace looks very similar to #869. @galo2099 - I wonder if the minimal repro in https://github.com/cuelang/cue/issues/869#issuecomment-812427561 captures your situation too?

**Comment by cueckoo** [comment]
_Original reply by @myitcv in https://github.com/cuelang/cue/issues/871#issuecomment-812495395_

@galo2099 we believe we have fixed this issue per the commit above. But if you are still seeing issues, please raise a new issue with a repro and we'd be very happy to help investigate. Thanks again for opening this issue in the first place.
